In [1]:
import pandas as pd
import numpy as np

<p2>Thiết kế các schema theo mô hình Dimension/Fact Table</p2>

<h2>I. Dimensional Tables</h2>

<p2>Sử dụng các file csv đã được xử lý ở basic-transformation</p2>

In [3]:
#fbref
fbref_matchgoals = pd.read_csv("gs://football_data_etl/football_data_extracted/output-basic/fbref_matchgoals.csv/part-00000-e8501008-4b91-4e70-97fa-f200c5a97ef2-c000.csv")
fbref_matchinfos = pd.read_csv("gs://football_data_etl/football_data_extracted/output-basic/fbref_matchinfos.csv/part-00000-b133a2c9-fee4-4fce-b917-ae96c664aa8e-c000.csv")
#
fbref_matchsquad = pd.read_csv("gs://football_data_etl/football_data_extracted/output-basic/fbref_matchsquad.csv/part-00000-701e4a9b-5a6b-4171-9c82-9857304c7151-c000.csv")
fbref_matchstats = pd.read_csv("gs://football_data_etl/football_data_extracted/output-basic/fbref_matchstats.csv/part-00000-ff109b2d-1c71-4ca4-bc94-12df8a30a86c-c000.csv")
fbref_matchplayerstats = pd.read_csv("gs://football_data_etl/football_data_extracted/output-basic/fbref_matchplayerstats.csv/part-00000-e0143337-4c3d-41e4-9213-a6ffee29f714-c000.csv")

In [6]:
fbref_matchinfos.head(5)

,Match_Id,League,Season,Match_Week,Home_Team,Away_Team,Match_Date,Venue_Day,Venue_Time,Attendance,Stadium,Officials,Link
0,a68e623d,Ligue 1,2018,1,Monaco,Toulouse,2017-08-04,Fri,2024-07-02T20:45:00.000Z,13572.0,Stade Louis II,Clément Turpin,https://fbref.com/en/matches/a68e623d/Monaco-T...
1,37f2c25f,Ligue 1,2018,1,Paris S-G,Amiens,2017-08-05,Sat,2024-07-02T17:15:00.000Z,46898.0,Parc des Princes,Mikael Lesage,https://fbref.com/en/matches/37f2c25f/Paris-Sa...
2,4d28b63b,Ligue 1,2018,1,Lyon,Strasbourg,2017-08-05,Sat,2024-07-02T20:00:00.000Z,1979.0,Groupama Stadium,Ruddy Buquet,https://fbref.com/en/matches/4d28b63b/Lyon-Str...
3,68b9eea2,Ligue 1,2018,1,Saint-Étienne,Nice,2017-08-05,Sat,2024-07-02T20:00:00.000Z,25879.0,Stade Geoffroy-Guichard,François Letexier,https://fbref.com/en/matches/68b9eea2/Saint-Et...
4,7d2eb66d,Ligue 1,2018,1,Metz,Guingamp,2017-08-05,Sat,2024-07-02T20:00:00.000Z,14595.0,Stade Saint-Symphorien,Jérôme Miguelgorry,https://fbref.com/en/matches/7d2eb66d/Metz-Gui...

In [7]:
fbref_matchinfos['Match_Date'] = pd.to_datetime(fbref_matchinfos['Match_Date'])
fbref_matchinfos['Match_Date'] = fbref_matchinfos['Match_Date'].dt.strftime('%Y-%m-%d')
fbref_matchinfos['Venue_Time'] = pd.to_datetime(fbref_matchinfos['Venue_Time'])
fbref_matchinfos['Venue_Time'] = fbref_matchinfos['Venue_Time'].dt.strftime('%Y-%m-%d %H:%M')

In [8]:
#sofifa
sofifa_players_attr = pd.read_csv('gs://football_data_etl/football_data_extracted/output-basic/sofifa_players_attr.csv/part-00000-0474179e-867f-4f31-9d30-40c396f830f5-c000.csv',
                                  on_bad_lines="skip")

<ipython-input-8-8df04426fdee>:2: DtypeWarning: Columns (45) have mixed types. Specify dtype option on import or set low_memory=False.
  sofifa_players_attr = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/fbref/sofifa_players_attr.csv/part-00000-0474179e-867f-4f31-9d30-40c396f830f5-c000.csv',

In [9]:
sofifa_players_attr['Birthday'] = pd.to_datetime(sofifa_players_attr['Birthday'])
sofifa_players_attr['Birthday'] = sofifa_players_attr['Birthday'].dt.strftime('%Y-%m-%d')
sofifa_players_attr['Club_Joined'] = pd.to_datetime(sofifa_players_attr['Club_Joined'])
sofifa_players_attr['Club_Joined'] = sofifa_players_attr['Club_Joined'].dt.strftime('%Y-%m-%d')
sofifa_players_attr['Update_Date'] = pd.to_datetime(sofifa_players_attr['Update_Date'])
sofifa_players_attr['Update_Date'] = sofifa_players_attr['Update_Date'].dt.strftime('%Y-%m-%d')

In [10]:
sofifa_players_attr

,Acceleration,Age,Aggression,Agility,All_Positions,Attacking_Work_Rate,Balance,Ball_Control,Birthday,Body_Type,...,Stamina,Standing_Tackle,Strength,Update_Date,Value,Vision,Volleys,Wage,Weak_Foot,Weight
0,79,27,77,79,RB RWB,High,77,75,1993-04-26,Normal (170-185),...,81.0,77.0,65.0,2020-09-23,€15M,65.0,52.0,€46K,3.0,71.0
1,80,27,48,75,ST LM,High,71,79,1992-09-14,Normal (185+),...,72.0,14.0,76.0,2020-09-23,€15M,65.0,73.0,€65K,4.0,78.0
2,89,24,62,81,LM,High,81,81,1996-03-26,Normal (170-185),...,74.0,37.0,60.0,2020-09-23,€21M,74.0,68.0,€33K,4.0,70.0
3,32,36,83,47,CB,Medium,53,64,1983-12-22,Lean (185+),...,59.0,79.0,82.0,2020-09-23,€2.5M,55.0,34.0,€24K,3.0,81.0
4,30,24,25,32,GK,Medium,29,18,1995-10-31,Normal (185+),...,26.0,10.0,66.0,2020-09-23,€21.5M,42.0,8.0,€20K,2.0,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291042,89,30,63,89,RW,High,91,86,1992-06-15,Unique,...,87.0,43.0,76.0,2023-07-05,€99.5M,84.0,83.0,€260K,3.0,71.0
291043,82,21,87,76,ST,High,74,82,2000-07-21,Unique,...,79.0,53.0,93.0,2023-07-05,€176.5M,74.0,89.0,€240K,3.0,94.0
291044,75,31,75,76,CM CAM,High,78,90,1991-06-28,Unique,...,89.0,66.0,74.0,2023-07-05,€107.5M,94.0,83.0,€350K,5.0,75.0
291045,69,19,51,56,LB,High,58,42,2003-04-04,Normal (170-185),...,59.0,67.0,52.0,2023-06-05,€600K,42.0,31.0,€6K,3.0,73.0
291046,72,20,37,84,RW,Medium,89,65,2002-06-14,Lean (170-),...,41.0,29.0,46.0,2023-06-05,€600K,58.0,53.0,€12K,3.0,59.0

<h3>1. Dim League</h3>

In [11]:
dim_league = pd.DataFrame({'League_Key': [],
                          'League_Name': [],
                          'League_Description': []})

list_league_key = []
list_league_name = fbref_matchinfos['League'].unique().tolist()

for i in range(0,len(list_league_name)):
    list_league_key.append(i+1)

dim_league['League_Key'] = list_league_key
dim_league['League_Name'] = list_league_name

list_league_description = ['Ligue 1,[A] officially known as Ligue 1 Uber Eats for sponsorship reasons,[1][2] is a French professional league for men primary football competition. Administered by the Ligue de Football Professionnel, Ligue 1 is contested by 18 clubs (as of the 2023–24 season) and operates on a system of promotion and relegation from and to Ligue 2.',
                           'The Premier League is the highest level of the English football league system. Contested by 20 clubs, it operates on a system of promotion and relegation',
                           'The Campeonato Nacional de Liga de Primera División, commonly known as the Primera División or LaLiga and officially as LaLiga EA Sports since 2023',
                           'The Bundesliga sometimes referred to as the Fußball-Bundesliga or 1. Bundesliga is a professional association football league in Germany.',
                           'The Serie A officially known as Serie A TIM for sponsorship reasons, is a professional league competition for football clubs located at the top of the']
dim_league['League_Description'] = list_league_description

In [12]:
dim_league

,League_Key,League_Name,League_Description
0,1,Ligue 1,"Ligue 1,[A] officially known as Ligue 1 Uber E..."
1,2,Premier League,The Premier League is the highest level of the...
2,3,La Liga,The Campeonato Nacional de Liga de Primera Div...
3,4,Fußball-Bundesliga,The Bundesliga sometimes referred to as the Fu...
4,5,Serie A,The Serie A officially known as Serie A TIM fo...

<h3>2. Dim Team</h3>

In [13]:
fbref_matchinfos.loc[fbref_matchinfos['Home_Team'] == 'Gladbach', 'Home_Team'] = "M'Gladbach"
fbref_matchinfos.loc[fbref_matchinfos['Away_Team'] == 'Gladbach', 'Away_Team'] = "M'Gladbach"

In [14]:
dim_team = pd.DataFrame({'Team_Key': [],
                          'Team_Name': [],
                          'Team_Description': []})

list_team_key = []
list_team_name = fbref_matchinfos['Home_Team'].unique().tolist()

for i in range(0,len(list_team_name)):
    list_team_key.append(i+1)

dim_team['Team_Key'] = list_team_key
dim_team['Team_Name'] = list_team_name

In [15]:
dim_team

     Team_Key      Team_Name  Team_Description
0           1         Monaco               NaN
1           2      Paris S-G               NaN
2           3           Lyon               NaN
3           4  Saint-Étienne               NaN
4           5           Metz               NaN
..        ...            ...               ...
140       141         Spezia               NaN
141       142        Venezia               NaN
142       143    Salernitana               NaN
143       144          Monza               NaN
144       145      Cremonese               NaN

[145 rows x 3 columns]

<h3>3. Dim Date</h3>

In [ ]:
dates_13_18 = pd.read_csv('gs://football_data_etl/football_data_extracted/output-basic/SampleDateDim_13_18.csv')
dates_19_24 = pd.read_csv('gs://football_data_etl/football_data_extracted/output-basic/SampleDateDim_19_24.csv')

In [17]:
dates = pd.concat([dates_13_18,dates_19_24], ignore_index=True)

In [18]:
dim_date = pd.DataFrame({'Date_Key': [],
                          'Full_Date': [],
                          'Day_Of_Week': [],
                          'Day_Num_In_Month': [],
                          'Day_Name': [],
                          'Month': [],
                          'Month_Name': [],
                          'Quarter': [],
                          'Year': []})

dim_date['Date_Key'] = dates['date key'].to_list()
dim_date['Full_Date'] = dates['full date'].to_list()
dim_date['Day_Of_Week'] = dates['day of week'].to_list()
dim_date['Day_Num_In_Month'] = dates['day num in month'].to_list()
dim_date['Day_Name'] = dates['day name'].to_list()
dim_date['Month'] = dates['month'].to_list()
dim_date['Month_Name'] = dates['month name'].to_list()
dim_date['Quarter'] = dates['quarter'].to_list()
dim_date['Year'] = dates['year'].to_list()

In [19]:
dim_date['Full_Date'] = pd.to_datetime(dim_date['Full_Date'])

In [20]:
dim_date.head(10)

,Date_Key,Full_Date,Day_Of_Week,Day_Num_In_Month,Day_Name,Month,Month_Name,Quarter,Year
0,20130101,2013-01-01,2,1,Tuesday,1,January,1,2013
1,20130102,2013-01-02,3,2,Wednesday,1,January,1,2013
2,20130103,2013-01-03,4,3,Thursday,1,January,1,2013
3,20130104,2013-01-04,5,4,Friday,1,January,1,2013
4,20130105,2013-01-05,6,5,Saturday,1,January,1,2013
5,20130106,2013-01-06,7,6,Sunday,1,January,1,2013
6,20130107,2013-01-07,1,7,Monday,1,January,1,2013
7,20130108,2013-01-08,2,8,Tuesday,1,January,1,2013
8,20130109,2013-01-09,3,9,Wednesday,1,January,1,2013
9,20130110,2013-01-10,4,10,Thursday,1,January,1,2013

<h3>4. Dim Match</h3>

In [21]:
unique_values = fbref_matchinfos.loc[~fbref_matchinfos['Home_Team'].isin(fbref_matchstats['Team']), 'Home_Team'].unique()
unique_values

array([], dtype=object)

In [ ]:
#fbref_matchinfos.loc[fbref_matchinfos['Home_Team'] == 'Gladbach', 'Home_Team'] = "M'Gladbach"
#fbref_matchstats[fbref_matchstats['Team'] == "Gladbach"]

In [22]:
dim_match = pd.DataFrame({'Match_Key': [],
                          'Match_Id': [],
                          'League': [],
                          'Season': [],
                          'Match_Week': [],
                          'Home_Team': [],
                          'Away_Team': [],
                          'Match_Date': [],
                          'Venue_Day': [],
                          'Venue_Time': [],
                          'Attendance': [],
                          'Stadium': [],
                          'Officials': [],
                          'Link': [],
                          'Home_Team_Formation': [],
                          'Away_Team_Formation': [],
                          'Result': []})

#'Home_Team_Manager': [],'Home_Team_Captain': [], Away_Team_Manager': [],'Away_Team_Captain': [],'Away_Team_Formation': []

list_match_key = []
list_match_id = fbref_matchinfos['Match_Id'].to_list()

for i in range(0,len(list_match_id)):
    list_match_key.append(i+1)

dim_match['Match_Key'] = list_match_key
dim_match['Match_Id'] = list_match_id
dim_match['Season'] = fbref_matchinfos['Season'].to_list()
dim_match['Match_Week'] = fbref_matchinfos['Match_Week'].to_list()

dim_match['Venue_Day'] = fbref_matchinfos['Venue_Day'].to_list()
dim_match['Venue_Time'] = fbref_matchinfos['Venue_Time'].to_list()
dim_match['Attendance'] = fbref_matchinfos['Attendance'].to_list()
dim_match['Stadium'] = fbref_matchinfos['Stadium'].to_list()
dim_match['Officials'] = fbref_matchinfos['Officials'].to_list()
dim_match['Link'] = fbref_matchinfos['Link'].to_list()

#
list_home_team_formation = []
list_away_team_formation = []
list_result = []

for i in range(0, len(fbref_matchinfos)):

    team_df = fbref_matchstats[(fbref_matchstats['Match_Id'] == fbref_matchinfos['Match_Id'].iloc[i]) &
                               (fbref_matchstats['Team'] == fbref_matchinfos['Home_Team'].iloc[i])]

    if (len(team_df) > 0):
        list_home_team_formation.append(team_df['Formation'].iloc[0])
        home_score = team_df['Score'].iloc[0]
    else:
        list_home_team_formation.append(np.nan)
        home_score = -1


    team_df = fbref_matchstats[(fbref_matchstats['Match_Id'] == fbref_matchinfos['Match_Id'].iloc[i]) &
                               (fbref_matchstats['Team'] == fbref_matchinfos['Away_Team'].iloc[i])]

    if (len(team_df) > 0):
        list_away_team_formation.append(team_df['Formation'].iloc[0])
        away_score = team_df['Score'].iloc[0]
    else:
        list_away_team_formation.append(np.nan)
        away_score = -1

    if(home_score == -1 or away_score == -1):
        list_result.append(np.nan)
    else:
        if(home_score > away_score):
            list_result.append("Win")
        elif (home_score == away_score):
            list_result.append("Draw")
        else:
            list_result.append("Lose")


dim_match['Home_Team_Formation'] = list_home_team_formation
dim_match['Away_Team_Formation'] = list_away_team_formation

dim_match['Result'] = list_result

#fk
list_league = []
list_home_team = []
list_away_team = []
list_match_date = []

for i in range(0, len(fbref_matchinfos)):
    print(i)

    team_df = dim_league[dim_league['League_Name'] == fbref_matchinfos['League'].iloc[i]]
    list_league.append(team_df['League_Key'].iloc[0])

    team_df = dim_team[dim_team['Team_Name'] == fbref_matchinfos['Home_Team'].iloc[i]]
    list_home_team.append(team_df['Team_Key'].iloc[0])

    team_df = dim_team[dim_team['Team_Name'] == fbref_matchinfos['Away_Team'].iloc[i]]
    list_away_team.append(team_df['Team_Key'].iloc[0])

    team_df = dim_date[dim_date['Full_Date'] == fbref_matchinfos['Match_Date'].iloc[i]]
    list_match_date.append(team_df['Date_Key'].iloc[0])


dim_match['League'] = list_league
dim_match['Home_Team'] = list_home_team
dim_match['Away_Team'] = list_away_team
dim_match['Match_Date'] = list_match_date

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
7708
7709
7710
7711
7712
7713
7714
7715
7716
7717
7718
7719
7720
7721
7722
7723
7724
7725
7726
7727
7728
7729
7730
7731
7732
7733
7734
7735
7736
7737
7738
7739
7740
7741
7742
7743
7744
7745
7746
7747
7748
7749
7750
7751
7752
7753
7754
7755
7756
7757
7758
7759
7760
7761
7762
7763
7764
7765
7766
7767
7768
7769
7770
7771
7772
7773
7774
7775
7776
7777
7778
7779
7780
7781
7782
7783
7784
7785
7786
7787
7788
7789
7790
7791
7792
7793
7794
7795
7796
7797
7798
7799
7800
7801
7802
7803
7804
7805
7806
7807
7808
7809
7810
7811
7812
7813
7814
7815
7816
7817
7818
7819
7820
7821
7822
7823
7824
7825
7826
7827
7828
7829
7830
7831
7832
7833
7834
7835
7836
7837
7838
7839
7840
7841
7842
7843
7844
7845
7846
7847
7848
7849
7850
7851
7852
7853
7854
7855
7856
7857
7858
7859
7860
7861
7862
7863
7864
7865
7866
7867
7868
7869
7870
7871
7872
7873
7874
7875
7876
7877
7878
7879
7880
7881
7882
7883
7884
7885
7886
7887
7888
7889
7890
7891
7892
7893
7894
7895
7896
7897
7898
7899
7900
7901
7902
7903
7904
7905
7906
7907
7908
7909
7910
7911
7912
7913
7914
7915
7916
7917
7918
7919
7920
7921
7922
7923
7924
7925
7926
7927
7928
7929
7930
7931
7932
7933
7934
7935
7936
7937
7938
7939
7940
7941
7942
7943
7944
7945
7946
7947
7948
7949
7950
7951
7952
7953
7954
7955
7956
7957
7958
7959
7960
7961
7962
7963
7964
7965
7966
7967
7968
7969
7970
7971
7972
7973
7974
7975
7976
7977
7978
7979
7980
7981
7982
7983
7984
7985
7986
7987
7988
7989
7990
7991
7992
7993
7994
7995
7996
7997
7998
7999
8000
8001
8002
8003
8004
8005
8006
8007
8008
8009
8010
8011
8012
8013
8014
8015
8016
8017
8018
8019
8020
8021
8022
8023
8024
8025
8026
8027
8028
8029
8030
8031
8032
8033
8034
8035
8036
8037
8038
8039
8040
8041
8042
8043
8044
8045
8046
8047
8048
8049
8050
8051
8052
8053
8054
8055
8056
8057
8058
8059
8060
8061
8062
8063
8064
8065
8066
8067
8068
8069
8070
8071
8072
8073
8074
8075
8076
8077
8078
8079
8080
8081
8082
8083
8084
8085
8086
8087
8088
8089
8090
8091
8092
8093
8094
8095
8096
8097
8098
8099
8100
8101
8102
8103
8104
8105
8106
8107
8108
8109
8110
8111
8112
8113
8114
8115
8116
8117
8118
8119
8120
8121
8122
8123
8124
8125
8126
8127
8128
8129
8130
8131
8132
8133
8134
8135
8136
8137
8138
8139
8140
8141
8142
8143
8144
8145
8146
8147
8148
8149
8150
8151
8152
8153
8154
8155
8156
8157
8158
8159
8160
8161
8162
8163
8164
8165
8166
8167
8168
8169
8170
8171
8172
8173
8174
8175
8176
8177
8178
8179
8180
8181
8182
8183
8184
8185
8186
8187
8188
8189
8190
8191
8192
8193
8194
8195
8196
8197
8198
8199
8200
8201
8202
8203
8204
8205
8206
8207
8208
8209
8210
8211
8212
8213
8214
8215
8216
8217
8218
8219
8220
8221
8222
8223
8224
8225
8226
8227
8228
8229
8230
8231
8232
8233
8234
8235
8236
8237
8238
8239
8240
8241
8242
8243
8244
8245
8246
8247
8248
8249
8250
8251
8252
8253
8254
8255
8256
8257
8258
8259
8260
8261
8262
8263
8264
8265
8266
8267
8268
8269
8270
8271
8272
8273
8274
8275
8276
8277
8278
8279
8280
8281
8282
8283
8284
8285
8286
8287
8288
8289
8290
8291
8292
8293
8294
8295
8296
8297
8298
8299
8300
8301
8302
8303
8304
8305
8306
8307
8308
8309
8310
8311
8312
8313
8314
8315
8316
8317
8318
8319
8320
8321
8322
8323
8324
8325
8326
8327
8328
8329
8330
8331
8332
8333
8334
8335
8336
8337
8338
8339
8340
8341
8342
8343
8344
8345
8346
8347
8348
8349
8350
8351
8352
8353
8354
8355
8356
8357
8358
8359
8360
8361
8362
8363
8364
8365
8366
8367
8368
8369
8370
8371
8372
8373
8374
8375
8376
8377
8378
8379
8380
8381
8382
8383
8384
8385
8386
8387
8388
8389
8390
8391
8392
8393
8394
8395
8396
8397
8398
8399
8400
8401
8402
8403
8404
8405
8406
8407
8408
8409
8410
8411
8412
8413
8414
8415
8416
8417
8418
8419
8420
8421
8422
8423
8424
8425
8426
8427
8428
8429
8430
8431
8432
8433
8434
8435
8436
8437
8438
8439
8440
8441
8442
8443
8444
8445
8446
8447
8448
8449
8450
8451
8452
8453
8454
8455
8456
8457
8458
8459
8460
8461
8462
8463
8464
8465
8466
8467
8468
8469
8470
8471
8472
8473
8474
8475
8476
8477
8478
8479
8480
8481
8482
8483
8484
8485
8486
8487
8488
8489
8490
8491
8492
8493
8494
8495
8496
8497
8498
8499
8500
8501
8502
8503
8504
8505
8506
8507
8508
8509
8510
8511
8512
8513
8514
8515
8516
8517
8518
8519
8520
8521
8522
8523
8524
8525
8526
8527
8528
8529
8530
8531
8532
8533
8534
8535
8536
8537
8538
8539
8540
8541
8542
8543
8544
8545
8546
8547
8548
8549
8550
8551
8552
8553
8554
8555
8556
8557
8558
8559
8560
8561
8562
8563
8564
8565
8566
8567
8568
8569
8570
8571
8572
8573
8574
8575
8576
8577
8578
8579
8580
8581
8582
8583
8584
8585
8586
8587
8588
8589
8590
8591
8592
8593
8594
8595
8596
8597
8598
8599
8600
8601
8602
8603
8604
8605
8606
8607
8608
8609
8610
8611
8612
8613
8614
8615
8616
8617
8618
8619
8620
8621
8622
8623
8624
8625
8626
8627
8628
8629
8630
8631
8632
8633
8634
8635
8636
8637
8638
8639
8640
8641
8642
8643
8644
8645
8646
8647
8648
8649
8650
8651
8652
8653
8654
8655
8656
8657
8658
8659
8660
8661
8662
8663
8664
8665
8666
8667
8668
8669
8670
8671
8672
8673
8674
8675
8676
8677
8678
8679
8680
8681
8682
8683
8684
8685
8686
8687
8688
8689
8690
8691
8692
8693
8694
8695
8696
8697
8698
8699
8700
8701
8702
8703
8704
8705
8706
8707
8708
8709
8710
8711
8712
8713
8714
8715
8716
8717
8718
8719
8720
8721
8722
8723
8724
8725
8726
8727
8728
8729
8730
8731
8732
8733
8734
8735
8736
8737
8738
8739
8740
8741
8742
8743
8744
8745
8746
8747
8748
8749
8750
8751
8752
8753
8754
8755
8756
8757
8758
8759
8760
8761
8762
8763
8764
8765
8766
8767
8768
8769
8770
8771
8772
8773
8774
8775
8776
8777
8778
8779
8780
8781
8782
8783
8784
8785
8786
8787
8788
8789
8790
8791
8792
8793
8794
8795
8796
8797
8798
8799
8800
8801
8802
8803
8804
8805
8806
8807
8808
8809
8810
8811
8812
8813
8814
8815
8816
8817
8818
8819
8820
8821
8822
8823
8824
8825
8826
8827
8828
8829
8830
8831
8832
8833
8834
8835
8836
8837
8838
8839
8840
8841
8842
8843
8844
8845
8846
8847
8848
8849
8850
8851
8852
8853
8854
8855
8856
8857
8858
8859
8860
8861
8862
8863
8864
8865
8866
8867
8868
8869
8870
8871
8872
8873
8874
8875
8876
8877
8878
8879
8880
8881
8882
8883
8884
8885
8886
8887
8888
8889
8890
8891
8892
8893
8894
8895
8896
8897
8898
8899
8900
8901
8902
8903
8904
8905
8906
8907
8908
8909
8910
8911
8912
8913
8914
8915
8916
8917
8918
8919
8920
8921
8922
8923
8924
8925
8926
8927
8928
8929
8930
8931
8932
8933
8934
8935
8936
8937
8938
8939
8940
8941
8942
8943
8944
8945
8946
8947
8948
8949
8950
8951
8952
8953
8954
8955
8956
8957
8958
8959
8960
8961
8962
8963
8964
8965
8966
8967
8968
8969
8970
8971
8972
8973
8974
8975
8976
8977
8978
8979
8980
8981
8982
8983
8984
8985
8986
8987
8988
8989
8990
8991
8992
8993
8994
8995
8996
8997
8998
8999
9000
9001
9002
9003
9004
9005
9006
9007
9008
9009
9010
9011
9012
9013
9014
9015
9016
9017
9018
9019
9020
9021
9022
9023
9024
9025
9026
9027
9028
9029
9030
9031
9032
9033
9034
9035
9036
9037
9038
9039
9040
9041
9042
9043
9044
9045
9046
9047
9048
9049
9050
9051
9052
9053
9054
9055
9056
9057
9058
9059
9060
9061
9062
9063
9064
9065
9066
9067
9068
9069
9070
9071
9072
9073
9074
9075
9076
9077
9078
9079
9080
9081
9082
9083
9084
9085
9086
9087
9088
9089
9090
9091
9092
9093
9094
9095
9096
9097
9098
9099
9100
9101
9102
9103
9104
9105
9106
9107
9108
9109
9110
9111
9112
9113
9114
9115
9116
9117
9118
9119
9120
9121
9122
9123
9124
9125
9126
9127
9128
9129
9130
9131
9132
9133
9134
9135
9136
9137
9138
9139
9140
9141
9142
9143
9144
9145
9146
9147
9148
9149
9150
9151
9152
9153
9154
9155
9156
9157
9158
9159
9160
9161
9162
9163
9164
9165
9166
9167
9168
9169
9170
9171
9172
9173
9174
9175
9176
9177
9178
9179
9180
9181
9182
9183
9184
9185
9186
9187
9188
9189
9190
9191
9192
9193
9194
9195
9196
9197
9198
9199
9200
9201
9202
9203
9204
9205
9206
9207
9208
9209
9210
9211
9212
9213
9214
9215
9216
9217
9218
9219
9220
9221
9222
9223
9224
9225
9226
9227
9228
9229
9230
9231
9232
9233
9234
9235
9236
9237
9238
9239
9240
9241
9242
9243
9244
9245
9246
9247
9248
9249
9250
9251
9252
9253
9254
9255
9256
9257
9258
9259
9260
9261
9262
9263
9264
9265
9266
9267
9268
9269
9270
9271
9272
9273
9274
9275
9276
9277
9278
9279
9280
9281
9282
9283
9284
9285
9286
9287
9288
9289
9290
9291
9292
9293
9294
9295
9296
9297
9298
9299
9300
9301
9302
9303
9304
9305
9306
9307
9308
9309
9310
9311
9312
9313
9314
9315
9316
9317
9318
9319
9320
9321
9322
9323
9324
9325
9326
9327
9328
9329
9330
9331
9332
9333
9334
9335
9336
9337
9338
9339
9340
9341
9342
9343
9344
9345
9346
9347
9348
9349
9350
9351
9352
9353
9354
9355
9356
9357
9358
9359
9360
9361
9362
9363
9364
9365
9366
9367
9368
9369
9370
9371
9372
9373
9374
9375
9376
9377
9378
9379
9380
9381
9382
9383
9384
9385
9386
9387
9388
9389
9390
9391
9392
9393
9394
9395
9396
9397
9398
9399
9400
9401
9402
9403
9404
9405
9406
9407
9408
9409
9410
9411
9412
9413
9414
9415
9416
9417
9418
9419
9420
9421
9422
9423
9424
9425
9426
9427
9428
9429
9430
9431
9432
9433
9434
9435
9436
9437
9438
9439
9440
9441
9442
9443
9444
9445
9446
9447
9448
9449
9450
9451
9452
9453
9454
9455
9456
9457
9458
9459
9460
9461
9462
9463
9464
9465
9466
9467
9468
9469
9470
9471
9472
9473
9474
9475
9476
9477
9478
9479
9480
9481
9482
9483
9484
9485
9486
9487
9488
9489
9490
9491
9492
9493
9494
9495
9496
9497
9498
9499
9500
9501
9502
9503
9504
9505
9506
9507
9508
9509
9510
9511
9512
9513
9514
9515
9516
9517
9518
9519
9520
9521
9522
9523
9524
9525
9526
9527
9528
9529
9530
9531
9532
9533
9534
9535
9536
9537
9538
9539
9540
9541
9542
9543
9544
9545
9546
9547
9548
9549
9550
9551
9552
9553
9554
9555
9556
9557
9558
9559
9560
9561
9562
9563
9564
9565
9566
9567
9568
9569
9570
9571
9572
9573
9574
9575
9576
9577
9578
9579
9580
9581
9582
9583
9584
9585
9586
9587
9588
9589
9590
9591
9592
9593
9594
9595
9596
9597
9598
9599
9600
9601
9602
9603
9604
9605
9606
9607
9608
9609
9610
9611
9612
9613
9614
9615
9616
9617
9618
9619
9620
9621
9622
9623
9624
9625
9626
9627
9628
9629
9630
9631
9632
9633
9634
9635
9636
9637
9638
9639
9640
9641
9642
9643
9644
9645
9646
9647
9648
9649
9650
9651
9652
9653
9654
9655
9656
9657
9658
9659
9660
9661
9662
9663
9664
9665
9666
9667
9668
9669
9670
9671
9672
9673
9674
9675
9676
9677
9678
9679
9680
9681
9682
9683
9684
9685
9686
9687
9688
9689
9690
9691
9692
9693
9694
9695
9696
9697
9698
9699
9700
9701
9702
9703
9704
9705
9706
9707
9708
9709
9710
9711
9712
9713
9714
9715
9716
9717
9718
9719
9720
9721
9722
9723
9724
9725
9726
9727
9728
9729
9730
9731
9732
9733
9734
9735
9736
9737
9738
9739
9740
9741
9742
9743
9744
9745
9746
9747
9748
9749
9750
9751
9752
9753
9754
9755
9756
9757
9758
9759
9760
9761
9762
9763
9764
9765
9766
9767
9768
9769
9770
9771
9772
9773
9774
9775
9776
9777
9778
9779
9780
9781
9782
9783
9784
9785
9786
9787
9788
9789
9790
9791
9792
9793
9794
9795
9796
9797
9798
9799
9800
9801
9802
9803
9804
9805
9806
9807
9808
9809
9810
9811
9812
9813
9814
9815
9816
9817
9818
9819
9820
9821
9822
9823
9824
9825
9826
9827
9828
9829
9830
9831
9832
9833
9834
9835
9836
9837
9838
9839
9840
9841
9842
9843
9844
9845
9846
9847
9848
9849
9850
9851
9852
9853
9854
9855
9856
9857
9858
9859
9860
9861
9862
9863
9864
9865
9866
9867
9868
9869
9870
9871
9872
9873
9874
9875
9876
9877
9878
9879
9880
9881
9882
9883
9884
9885
9886
9887
9888
9889
9890
9891
9892
9893
9894
9895
9896
9897
9898
9899
9900
9901
9902
9903
9904
9905
9906
9907
9908
9909
9910
9911
9912
9913
9914
9915
9916
9917
9918
9919
9920
9921
9922
9923
9924
9925
9926
9927
9928
9929
9930
9931
9932
9933
9934
9935
9936
9937
9938
9939
9940
9941
9942
9943
9944
9945
9946
9947
9948
9949
9950
9951
9952
9953
9954
9955
9956
9957
9958
9959
9960
9961
9962
9963
9964
9965
9966
9967
9968
9969
9970
9971
9972
9973
9974
9975
9976
9977
9978
9979
9980
9981
9982
9983
9984
9985
9986
9987
9988
9989
9990
9991
9992
9993
9994
9995
9996
9997
9998
9999
10000
10001
10002
10003
10004
10005
10006
10007
10008
10009
10010
10011
10012
10013
10014
10015
10016
10017
10018
10019
10020
10021
10022
10023
10024
10025
10026
10027
10028
10029
10030
10031
10032
10033
10034
10035
10036
10037
10038
10039
10040
10041
10042
10043
10044
10045
10046
10047
10048
10049
10050
10051
10052
10053
10054
10055
10056
10057
10058
10059
10060
10061
10062
10063
10064
10065
10066
10067
10068
10069
10070
10071
10072
10073
10074
10075
10076
10077
10078
10079
10080
10081
10082
10083
10084
10085
10086
10087
10088
10089
10090
10091
10092
10093
10094
10095
10096
10097
10098
10099
10100
10101
10102
10103
10104
10105
10106
10107
10108
10109
10110
10111
10112
10113
10114
10115
10116
10117
10118
10119
10120
10121
10122
10123
10124
10125
10126
10127
10128
10129
10130
10131
10132
10133
10134
10135
10136
10137
10138
10139
10140
10141
10142
10143
10144
10145
10146
10147
10148
10149
10150
10151
10152
10153
10154
10155
10156
10157
10158
10159
10160
10161
10162
10163
10164
10165
10166
10167
10168
10169
10170
10171
10172
10173
10174
10175
10176
10177
10178
10179
10180
10181
10182
10183
10184
10185
10186
10187
10188
10189
10190
10191
10192
10193
10194
10195
10196
10197
10198
10199
10200
10201
10202
10203
10204
10205
10206
10207
10208
10209
10210
10211
10212
10213
10214
10215
10216
10217
10218
10219
10220
10221
10222
10223
10224
10225
10226
10227
10228
10229
10230
10231
10232
10233
10234
10235
10236
10237
10238
10239
10240
10241
10242
10243
10244
10245
10246
10247
10248
10249
10250
10251
10252
10253
10254
10255
10256
10257
10258
10259
10260
10261
10262
10263
10264
10265
10266
10267
10268
10269
10270
10271
10272
10273
10274
10275
10276
10277
10278
10279
10280
10281
10282
10283
10284
10285
10286
10287
10288
10289
10290
10291
10292
10293
10294
10295
10296
10297
10298
10299
10300
10301
10302
10303
10304
10305
10306
10307
10308
10309
10310
10311
10312
10313
10314
10315
10316
10317
10318
10319
10320
10321
10322
10323
10324
10325
10326
10327
10328
10329
10330
10331
10332
10333
10334
10335
10336
10337
10338
10339
10340
10341
10342
10343
10344
10345
10346
10347
10348
10349
10350
10351
10352
10353
10354
10355
10356
10357
10358
10359
10360
10361
10362
10363
10364
10365
10366
10367
10368
10369
10370
10371
10372
10373
10374
10375
10376
10377
10378
10379
10380
10381
10382
10383
10384
10385
10386
10387
10388
10389
10390
10391
10392
10393
10394
10395
10396
10397
10398
10399
10400
10401
10402
10403
10404
10405
10406
10407
10408
10409
10410
10411
10412
10413
10414
10415
10416
10417
10418
10419
10420
10421
10422
10423
10424
10425
10426
10427
10428
10429
10430
10431
10432
10433
10434
10435
10436
10437
10438
10439
10440
10441
10442
10443
10444
10445
10446
10447
10448
10449
10450
10451
10452
10453
10454
10455
10456
10457
10458
10459
10460
10461
10462
10463
10464
10465
10466
10467
10468
10469
10470
10471
10472
10473
10474
10475
10476
10477
10478
10479
10480
10481
10482
10483
10484
10485
10486
10487
10488
10489
10490
10491
10492
10493
10494
10495
10496
10497
10498
10499
10500
10501
10502
10503
10504
10505
10506
10507
10508
10509
10510
10511
10512
10513
10514
10515
10516
10517
10518
10519
10520
10521
10522
10523
10524
10525
10526
10527
10528
10529
10530
10531
10532
10533
10534
10535
10536
10537
10538
10539
10540
10541
10542
10543
10544
10545
10546
10547
10548
10549
10550
10551
10552
10553
10554
10555
10556
10557
10558
10559
10560
10561
10562
10563
10564
10565
10566
10567
10568
10569
10570
10571
10572
10573
10574
10575
10576
10577
10578
10579
10580
10581
10582
10583
10584
10585
10586
10587
10588
10589
10590
10591
10592
10593
10594
10595
10596
10597
10598
10599
10600
10601
10602
10603
10604
10605
10606
10607
10608
10609
10610
10611
10612
10613
10614
10615
10616
10617
10618
10619
10620
10621
10622
10623
10624
10625
10626
10627
10628
10629
10630
10631
10632
10633
10634
10635
10636
10637
10638
10639
10640
10641
10642
10643
10644
10645
10646
10647
10648
10649
10650
10651
10652
10653
10654
10655
10656
10657
10658
10659
10660
10661
10662
10663
10664
10665
10666
10667
10668
10669
10670
10671
10672
10673
10674
10675
10676
10677
10678
10679
10680
10681
10682
10683
10684
10685
10686
10687
10688
10689
10690
10691
10692
10693
10694
10695
10696
10697
10698
10699
10700
10701
10702
10703
10704
10705
10706
10707
10708
10709
10710
10711
10712
10713
10714
10715
10716
10717
10718
10719
10720
10721
10722
10723
10724
10725
10726
10727
10728
10729
10730
10731
10732
10733
10734
10735
10736
10737
10738
10739
10740
10741
10742
10743
10744
10745
10746
10747
10748
10749
10750
10751
10752
10753
10754
10755
10756
10757
10758
10759
10760
10761
10762
10763
10764
10765
10766
10767
10768
10769
10770
10771
10772
10773
10774
10775
10776
10777
10778
10779
10780
10781
10782
10783
10784
10785
10786
10787
10788
10789
10790
10791
10792
10793
10794
10795
10796
10797
10798
10799
10800
10801
10802
10803
10804
10805
10806
10807
10808
10809
10810
10811
10812
10813
10814
10815
10816
10817
10818
10819
10820
10821
10822
10823
10824
10825
10826
10827
10828
10829
10830
10831
10832
10833
10834
10835
10836
10837
10838
10839
10840
10841
10842
10843
10844
10845
10846
10847
10848
10849
10850
10851
10852
10853
10854
10855
10856
10857
10858
10859
10860
10861
10862
10863
10864
10865
10866
10867
10868
10869
10870
10871
10872
10873
10874
10875
10876
10877
10878
10879
10880
10881
10882
10883
10884
10885
10886
10887
10888
10889
10890
10891
10892
10893
10894
10895
10896
10897
10898
10899
10900
10901
10902
10903
10904
10905
10906
10907
10908
10909
10910
10911
10912
10913
10914
10915
10916
10917
10918
10919
10920
10921
10922
10923
10924
10925
10926
10927
10928
10929
10930
10931
10932
10933
10934
10935
10936
10937
10938
10939
10940
10941
10942
10943
10944
10945
10946
10947
10948
10949
10950
10951
10952
10953
10954
10955
10956
10957
10958
10959
10960
10961
10962
10963
10964
10965
10966
10967
10968
10969
10970
10971
10972
10973
10974
10975
10976
10977
10978
10979
10980
10981
10982
10983
10984
10985
10986
10987
10988
10989
10990
10991
10992
10993
10994
10995
10996
10997
10998
10999
11000
11001
11002
11003
11004
11005
11006
11007
11008
11009
11010
11011
11012
11013
11014
11015
11016
11017
11018
11019
11020
11021
11022
11023
11024
11025
11026
11027
11028
11029
11030
11031
11032
11033
11034
11035
11036
11037
11038
11039
11040
11041
11042
11043
11044
11045
11046
11047
11048
11049
11050
11051
11052
11053
11054
11055
11056
11057
11058
11059
11060
11061
11062
11063
11064
11065
11066
11067
11068
11069
11070
11071
11072
11073
11074
11075
11076
11077
11078
11079
11080
11081
11082
11083
11084
11085
11086
11087
11088
11089
11090
11091
11092
11093
11094
11095
11096
11097
11098
11099
11100
11101
11102
11103
11104
11105
11106
11107
11108
11109
11110
11111
11112
11113
11114
11115
11116
11117
11118
11119
11120
11121
11122
11123
11124
11125
11126
11127
11128
11129
11130
11131
11132
11133
11134
11135
11136
11137
11138
11139
11140
11141
11142
11143
11144
11145
11146
11147
11148
11149
11150
11151
11152
11153
11154
11155
11156
11157
11158
11159
11160
11161
11162
11163
11164
11165
11166
11167
11168
11169
11170
11171
11172
11173
11174
11175
11176
11177
11178
11179
11180
11181
11182
11183
11184
11185
11186
11187
11188
11189
11190
11191
11192
11193
11194
11195
11196
11197
11198
11199
11200
11201
11202
11203
11204
11205
11206
11207
11208
11209
11210
11211
11212
11213
11214
11215
11216
11217
11218
11219
11220
11221
11222
11223
11224
11225
11226
11227
11228
11229
11230
11231
11232
11233
11234
11235
11236
11237
11238
11239
11240
11241
11242
11243
11244
11245
11246
11247
11248
11249
11250
11251
11252
11253
11254
11255
11256
11257
11258
11259
11260
11261
11262
11263
11264
11265
11266
11267
11268
11269
11270
11271
11272
11273
11274
11275
11276
11277
11278
11279
11280
11281
11282
11283
11284
11285
11286
11287
11288
11289
11290
11291
11292
11293
11294
11295
11296
11297
11298
11299
11300
11301
11302
11303
11304
11305
11306
11307
11308
11309
11310
11311
11312
11313
11314
11315
11316
11317
11318
11319
11320
11321
11322
11323
11324
11325
11326
11327
11328
11329
11330
11331
11332
11333
11334
11335
11336
11337
11338
11339
11340
11341
11342
11343
11344
11345
11346
11347
11348
11349
11350
11351
11352
11353
11354
11355
11356
11357
11358
11359
11360
11361
11362
11363
11364
11365
11366
11367
11368
11369
11370
11371
11372
11373
11374
11375
11376
11377
11378
11379
11380
11381
11382
11383
11384
11385
11386
11387
11388
11389
11390
11391
11392
11393
11394
11395
11396
11397
11398
11399
11400
11401
11402
11403
11404
11405
11406
11407
11408
11409
11410
11411
11412

In [23]:
dim_match

,Match_Key,Match_Id,League,Season,Match_Week,Home_Team,Away_Team,Match_Date,Venue_Day,Venue_Time,Attendance,Stadium,Officials,Link,Home_Team_Formation,Away_Team_Formation,Result
0,1,a68e623d,1,2018,1,1,20,20170804,Fri,2024-07-02 20:45,13572.0,Stade Louis II,Clément Turpin,https://fbref.com/en/matches/a68e623d/Monaco-T...,4/4/2002,4/3/2003,Win
1,2,37f2c25f,1,2018,1,2,13,20170805,Sat,2024-07-02 17:15,46898.0,Parc des Princes,Mikael Lesage,https://fbref.com/en/matches/37f2c25f/Paris-Sa...,4/3/2003,5/4/2001,Win
2,3,4d28b63b,1,2018,1,3,19,20170805,Sat,2024-07-02 20:00,1979.0,Groupama Stadium,Ruddy Buquet,https://fbref.com/en/matches/4d28b63b/Lyon-Str...,4-2-3-1,4-1-4-1,Win
3,4,68b9eea2,1,2018,1,4,14,20170805,Sat,2024-07-02 20:00,25879.0,Stade Geoffroy-Guichard,François Letexier,https://fbref.com/en/matches/68b9eea2/Saint-Et...,4/3/2003,4-2-3-1,Win
4,5,7d2eb66d,1,2018,1,5,17,20170805,Sat,2024-07-02 20:00,14595.0,Stade Saint-Symphorien,Jérôme Miguelgorry,https://fbref.com/en/matches/7d2eb66d/Metz-Gui...,4-2-3-1,4/4/2002,Lose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12703,12704,6635e569,5,2024,9,143,126,20231022,Sun,2024-07-02 15:00,17409.0,Stadio Arechi,Daniele Chiffi,https://fbref.com/en/matches/6635e569/Salernit...,4-3-2-1,4-3-1-2,Draw
12704,12705,045aca2a,5,2024,9,118,130,20231022,Sun,2024-07-02 18:00,14848.0,Gewiss Stadium,Livio Marinelli,https://fbref.com/en/matches/045aca2a/Atalanta...,3/4/2003,3/5/2002,Win
12705,12706,bea57463,5,2024,9,131,116,20231022,Sun,2024-07-02 20:45,75676.0,Stadio Giuseppe Meazza,Maurizio Mariani,https://fbref.com/en/matches/bea57463/Milan-Ju...,4-2-3-1,3/5/2002,Lose
12706,12707,cd802be7,5,2024,9,119,140,20231023,Mon,2024-07-02 18:30,20113.0,Bluenergy Stadium,Paride Tremolada,https://fbref.com/en/matches/cd802be7/Udinese-...,3/5/2002,4/3/2003,Draw
12707,12708,e961a763,5,2024,9,129,136,20231023,Mon,2024-07-02 20:45,43147.0,Stadio Artemio Franchi,Federico Dionisi,https://fbref.com/en/matches/e961a763/Fiorenti...,4-2-3-1,4-3-2-1,Lose

In [24]:
dim_match.isna().sum()

Match_Key                 0
Match_Id                  0
League                    0
Season                    0
Match_Week                0
Home_Team                 0
Away_Team                 0
Match_Date                0
Venue_Day                 0
Venue_Time               73
Attendance             2266
Stadium                   0
Officials               101
Link                      0
Home_Team_Formation     104
Away_Team_Formation     104
Result                  104
dtype: int64

<h3>5. Dim Player</h3>

In [ ]:
dim_player = pd.DataFrame({'Player_Key': [],
                          'Player_Id': [],
                          'Player_Name': [],
                          'Player_Full_Name': [],
                          'Birthdate': []})

list_player_key = []
list_player_id = sofifa_players_attr['Sofifa_Id'].unique().tolist()

for i in range(0,len(list_player_id)):
    list_player_key.append(i+1)

dim_player['Player_Key'] = list_player_key
dim_player['Player_Id'] = list_player_id

list_player_name = []
list_player_full_name = []
list_birthdate = []

for i in range(0, len(list_player_id)):
    print(i)

    temp_df = sofifa_players_attr[sofifa_players_attr['Sofifa_Id'] == list_player_id[i]]

    if (len(temp_df) > 0):
        list_player_name.append(temp_df['Player_Name'].iloc[0])
        list_player_full_name.append(temp_df['Player_Full_Name'].iloc[0])
        list_birthdate.append(temp_df['Birthday'].iloc[0])
    else:
        list_player_name.append(np.nan)
        list_player_full_name.append(np.nan)
        list_birthdate.append(np.nan)

dim_player['Player_Name'] = list_player_name
dim_player['Player_Full_Name'] = list_player_full_name
dim_player['Birthdate'] = list_birthdate

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
4180
4181
4182
4183
4184
4185
4186
4187
4188
4189
4190
4191
4192
4193
4194
4195
4196
4197
4198
4199
4200
4201
4202
4203
4204
4205
4206
4207
4208
4209
4210
4211
4212
4213
4214
4215
4216
4217
4218
4219
4220
4221
4222
4223
4224
4225
4226
4227
4228
4229
4230
4231
4232
4233
4234
4235
4236
4237
4238
4239
4240
4241
4242
4243
4244
4245
4246
4247
4248
4249
4250
4251
4252
4253
4254
4255
4256
4257
4258
4259
4260
4261
4262
4263
4264
4265
4266
4267
4268
4269
4270
4271
4272
4273
4274
4275
4276
4277
4278
4279
4280
4281
4282
4283
4284
4285
4286
4287
4288
4289
4290
4291
4292
4293
4294
4295
4296
4297
4298
4299
4300
4301
4302
4303
4304
4305
4306
4307
4308
4309
4310
4311
4312
4313
4314
4315
4316
4317
4318
4319
4320
4321
4322
4323
4324
4325
4326
4327
4328
4329
4330
4331
4332
4333
4334
4335
4336
4337
4338
4339
4340
4341
4342
4343
4344
4345
4346
4347
4348
4349
4350
4351
4352
4353
4354
4355
4356
4357
4358
4359
4360
4361
4362
4363
4364
4365
4366
4367
4368
4369
4370
4371
4372
4373
4374
4375
4376
4377
4378
4379
4380
4381
4382
4383
4384
4385
4386
4387
4388
4389
4390
4391
4392
4393
4394
4395
4396
4397
4398
4399
4400
4401
4402
4403
4404
4405
4406
4407
4408
4409
4410
4411
4412
4413
4414
4415
4416
4417
4418
4419
4420
4421
4422
4423
4424
4425
4426
4427
4428
4429
4430
4431
4432
4433
4434
4435
4436
4437
4438
4439
4440
4441
4442
4443
4444
4445
4446
4447
4448
4449
4450
4451
4452
4453
4454
4455
4456
4457
4458
4459
4460
4461
4462
4463
4464
4465
4466
4467
4468
4469
4470
4471
4472
4473
4474
4475
4476
4477
4478
4479
4480
4481
4482
4483
4484
4485
4486
4487
4488
4489
4490
4491
4492
4493
4494
4495
4496
4497
4498
4499
4500
4501
4502
4503
4504
4505
4506
4507
4508
4509
4510
4511
4512
4513
4514
4515
4516
4517
4518
4519
4520
4521
4522
4523
4524
4525
4526
4527
4528
4529
4530
4531
4532
4533
4534
4535
4536
4537
4538
4539
4540
4541
4542
4543
4544
4545
4546
4547
4548
4549
4550
4551
4552
4553
4554
4555
4556
4557
4558
4559
4560
4561
4562
4563
4564
4565
4566
4567
4568
4569
4570
4571
4572
4573
4574
4575
4576
4577
4578
4579
4580
4581
4582
4583
4584
4585
4586
4587
4588
4589
4590
4591
4592
4593
4594
4595
4596
4597
4598
4599
4600
4601
4602
4603
4604
4605
4606
4607
4608
4609
4610
4611
4612
4613
4614
4615
4616
4617
4618
4619
4620
4621
4622
4623
4624
4625
4626
4627
4628
4629
4630
4631
4632
4633
4634
4635
4636
4637
4638
4639
4640
4641
4642
4643
4644
4645
4646
4647
4648
4649
4650
4651
4652
4653
4654
4655
4656
4657
4658
4659
4660
4661
4662
4663
4664
4665
4666
4667
4668
4669
4670
4671
4672
4673
4674
4675
4676
4677
4678
4679
4680
4681
4682
4683
4684
4685
4686
4687
4688
4689
4690
4691
4692
4693
4694
4695
4696
4697
4698
4699
4700
4701
4702
4703
4704
4705
4706
4707
4708
4709
4710
4711
4712
4713
4714
4715
4716
4717
4718
4719
4720
4721
4722
4723
4724
4725
4726
4727
4728
4729
4730
4731
4732
4733
4734
4735
4736
4737
4738
4739
4740
4741
4742
4743
4744
4745
4746
4747
4748
4749
4750
4751
4752
4753
4754
4755
4756
4757
4758
4759
4760
4761
4762
4763
4764
4765
4766
4767
4768
4769
4770
4771
4772
4773
4774
4775
4776
4777
4778
4779
4780
4781
4782
4783
4784
4785
4786
4787
4788
4789
4790
4791
4792
4793
4794
4795
4796
4797
4798
4799
4800
4801
4802
4803
4804
4805
4806
4807
4808
4809
4810
4811
4812
4813
4814
4815
4816
4817
4818
4819
4820
4821
4822
4823
4824
4825
4826
4827
4828
4829
4830
4831
4832
4833
4834
4835
4836
4837
4838
4839
4840
4841
4842
4843
4844
4845
4846
4847
4848
4849
4850
4851
4852
4853
4854
4855
4856
4857
4858
4859
4860
4861
4862
4863
4864
4865
4866
4867
4868
4869
4870
4871
4872
4873
4874
4875
4876
4877
4878
4879
4880
4881
4882
4883
4884
4885
4886
4887
4888
4889
4890
4891
4892
4893
4894
4895
4896
4897
4898
4899
4900
4901
4902
4903
4904
4905
4906
4907
4908
4909
4910
4911
4912
4913
4914
4915
4916
4917
4918
4919
4920
4921
4922
4923
4924
4925
4926
4927
4928
4929
4930
4931
4932
4933
4934
4935
4936
4937
4938
4939
4940
4941
4942
4943
4944
4945
4946
4947
4948
4949
4950
4951
4952
4953
4954
4955
4956
4957
4958
4959
4960
4961
4962
4963
4964
4965
4966
4967
4968
4969
4970
4971
4972
4973
4974
4975
4976
4977
4978
4979
4980
4981
4982
4983
4984
4985
4986
4987
4988
4989
4990
4991
4992
4993
4994
4995
4996
4997
4998
4999
5000
5001
5002
5003
5004
5005
5006
5007
5008
5009
5010
5011
5012
5013
5014
5015
5016
5017
5018
5019
5020
5021
5022
5023
5024
5025
5026
5027
5028
5029
5030
5031
5032
5033
5034
5035
5036
5037
5038
5039
5040
5041
5042
5043
5044
5045
5046
5047
5048
5049
5050
5051
5052
5053
5054
5055
5056
5057
5058
5059
5060
5061
5062
5063
5064
5065
5066
5067
5068
5069
5070
5071
5072
5073
5074
5075
5076
5077
5078
5079
5080
5081
5082
5083
5084
5085
5086
5087
5088
5089
5090
5091
5092
5093
5094
5095
5096
5097
5098
5099
5100
5101
5102
5103
5104
5105
5106
5107
5108
5109
5110
5111
5112
5113
5114
5115
5116
5117
5118
5119
5120
5121
5122
5123
5124
5125
5126
5127
5128
5129
5130
5131
5132
5133
5134
5135
5136
5137
5138
5139
5140
5141
5142
5143
5144
5145
5146
5147
5148
5149
5150
5151
5152
5153
5154
5155
5156
5157
5158
5159
5160
5161
5162
5163
5164
5165
5166
5167
5168
5169
5170
5171
5172
5173
5174
5175
5176
5177
5178
5179
5180
5181
5182
5183
5184
5185
5186
5187
5188
5189
5190
5191
5192
5193
5194
5195
5196
5197
5198
5199
5200
5201
5202
5203
5204
5205
5206
5207
5208
5209
5210
5211
5212
5213
5214
5215
5216
5217
5218
5219
5220
5221
5222
5223
5224
5225
5226
5227
5228
5229
5230
5231
5232
5233
5234
5235
5236
5237
5238
5239
5240
5241
5242
5243
5244
5245
5246
5247
5248
5249
5250
5251
5252
5253
5254
5255
5256
5257
5258
5259
5260
5261
5262
5263
5264
5265
5266
5267
5268
5269
5270
5271
5272
5273
5274
5275
5276
5277
5278
5279
5280
5281
5282
5283
5284
5285
5286
5287
5288
5289
5290
5291
5292
5293
5294
5295
5296
5297
5298
5299
5300
5301
5302
5303
5304
5305
5306
5307
5308
5309
5310
5311
5312
5313
5314
5315
5316
5317
5318
5319
5320
5321
5322
5323
5324
5325
5326
5327
5328
5329
5330
5331
5332
5333
5334
5335
5336
5337
5338
5339
5340
5341
5342
5343
5344
5345
5346
5347
5348
5349
5350
5351
5352
5353
5354
5355
5356
5357
5358
5359
5360
5361
5362
5363
5364
5365
5366
5367
5368
5369
5370
5371
5372
5373
5374
5375
5376
5377
5378
5379
5380
5381
5382
5383
5384
5385
5386
5387
5388
5389
5390
5391
5392
5393
5394
5395
5396
5397
5398
5399
5400
5401
5402
5403
5404
5405
5406
5407
5408
5409
5410
5411
5412
5413
5414
5415
5416
5417
5418
5419
5420
5421
5422
5423
5424
5425
5426
5427
5428
5429
5430
5431
5432
5433
5434
5435
5436
5437
5438
5439
5440
5441
5442
5443
5444
5445
5446
5447
5448
5449
5450
5451
5452
5453
5454
5455
5456
5457
5458
5459
5460
5461
5462
5463
5464
5465
5466
5467
5468
5469
5470
5471
5472
5473
5474
5475
5476
5477
5478
5479
5480
5481
5482
5483
5484
5485
5486
5487
5488
5489
5490
5491
5492
5493
5494
5495
5496
5497
5498
5499
5500
5501
5502
5503
5504
5505
5506
5507
5508
5509
5510
5511
5512
5513
5514
5515
5516
5517
5518
5519
5520
5521
5522
5523
5524
5525
5526
5527
5528
5529
5530
5531
5532
5533
5534
5535
5536
5537
5538
5539
5540
5541
5542
5543
5544
5545
5546
5547
5548
5549
5550
5551
5552
5553
5554
5555
5556
5557
5558
5559
5560
5561
5562
5563
5564
5565
5566
5567
5568
5569
5570
5571
5572
5573
5574
5575
5576
5577
5578
5579
5580
5581
5582
5583
5584
5585
5586
5587
5588
5589
5590
5591
5592
5593
5594
5595
5596
5597
5598
5599
5600
5601
5602
5603
5604
5605
5606
5607
5608
5609
5610
5611
5612
5613
5614
5615
5616
5617
5618
5619
5620
5621
5622
5623
5624
5625
5626
5627
5628
5629
5630
5631
5632
5633
5634
5635
5636
5637
5638
5639
5640
5641
5642
5643
5644
5645
5646
5647
5648
5649
5650
5651
5652
5653
5654
5655
5656
5657
5658
5659
5660
5661
5662
5663
5664
5665
5666
5667
5668
5669
5670
5671
5672
5673
5674
5675
5676
5677
5678
5679
5680
5681
5682
5683
5684
5685
5686
5687
5688
5689
5690
5691
5692
5693
5694
5695
5696
5697
5698
5699
5700
5701
5702
5703
5704
5705
5706
5707
5708
5709
5710
5711
5712
5713
5714
5715
5716
5717
5718
5719
5720
5721
5722
5723
5724
5725
5726
5727
5728
5729
5730
5731
5732
5733
5734
5735
5736
5737
5738
5739
5740
5741
5742
5743
5744
5745
5746
5747
5748
5749
5750
5751
5752
5753
5754
5755
5756
5757
5758
5759
5760
5761
5762
5763
5764
5765
5766
5767
5768
5769
5770
5771
5772
5773
5774
5775
5776
5777
5778
5779
5780
5781
5782
5783
5784
5785
5786
5787
5788
5789
5790
5791
5792
5793
5794
5795
5796
5797
5798
5799
5800
5801
5802
5803
5804
5805
5806
5807
5808
5809
5810
5811
5812
5813
5814
5815
5816
5817
5818
5819
5820
5821
5822
5823
5824
5825
5826
5827
5828
5829
5830
5831
5832
5833
5834
5835
5836
5837
5838
5839
5840
5841
5842
5843
5844
5845
5846
5847
5848
5849
5850
5851
5852
5853
5854
5855
5856
5857
5858
5859
5860
5861
5862
5863
5864
5865
5866
5867
5868
5869
5870
5871
5872
5873
5874
5875
5876
5877
5878
5879
5880
5881
5882
5883
5884
5885
5886
5887
5888
5889
5890
5891
5892
5893
5894
5895
5896
5897
5898
5899
5900
5901
5902
5903
5904
5905
5906
5907
5908
5909
5910
5911
5912
5913
5914
5915
5916
5917
5918
5919
5920
5921
5922
5923
5924
5925
5926
5927
5928
5929
5930
5931
5932
5933
5934
5935
5936
5937
5938
5939
5940
5941
5942
5943
5944
5945
5946
5947
5948
5949
5950
5951
5952
5953
5954
5955
5956
5957
5958
5959
5960
5961
5962
5963
5964
5965
5966
5967
5968
5969
5970
5971
5972
5973
5974
5975
5976
5977
5978
5979
5980
5981
5982
5983
5984
5985
5986
5987
5988
5989
5990
5991
5992
5993
5994
5995
5996
5997
5998
5999
6000
6001
6002
6003
6004
6005
6006
6007
6008
6009
6010
6011
6012
6013
6014
6015
6016
6017
6018
6019
6020
6021
6022
6023
6024
6025
6026
6027
6028
6029
6030
6031
6032
6033
6034
6035
6036
6037
6038
6039
6040
6041
6042
6043
6044
6045
6046
6047
6048
6049
6050
6051
6052
6053
6054
6055
6056
6057
6058
6059
6060
6061
6062
6063
6064
6065
6066
6067
6068
6069
6070
6071
6072
6073
6074
6075
6076
6077
6078
6079
6080
6081
6082
6083
6084
6085
6086
6087
6088
6089
6090
6091
6092
6093
6094
6095
6096
6097
6098
6099
6100
6101
6102
6103
6104
6105
6106
6107
6108
6109
6110
6111
6112
6113
6114
6115
6116
6117
6118
6119
6120
6121
6122
6123
6124
6125
6126
6127
6128
6129
6130
6131
6132
6133
6134
6135
6136
6137
6138
6139
6140
6141
6142
6143
6144
6145
6146
6147
6148
6149
6150
6151
6152
6153
6154
6155
6156
6157
6158
6159
6160
6161
6162
6163
6164
6165
6166
6167
6168
6169
6170
6171
6172
6173
6174
6175
6176
6177
6178
6179
6180
6181
6182
6183
6184
6185
6186
6187
6188
6189
6190
6191
6192
6193
6194
6195
6196
6197
6198
6199
6200
6201
6202
6203
6204
6205
6206
6207
6208
6209
6210
6211
6212
6213
6214
6215
6216
6217
6218
6219
6220
6221
6222
6223
6224
6225
6226
6227
6228
6229
6230
6231
6232
6233
6234
6235
6236
6237
6238
6239
6240
6241
6242
6243
6244
6245
6246
6247
6248
6249
6250
6251
6252
6253
6254
6255
6256
6257
6258
6259
6260
6261
6262
6263
6264
6265
6266
6267
6268
6269
6270
6271
6272
6273
6274
6275
6276
6277
6278
6279
6280
6281
6282
6283
6284
6285
6286
6287
6288
6289
6290
6291
6292
6293
6294
6295
6296
6297
6298
6299
6300
6301
6302
6303
6304
6305
6306
6307
6308
6309
6310
6311
6312
6313
6314
6315
6316
6317
6318
6319
6320
6321
6322
6323
6324
6325
6326
6327
6328
6329
6330
6331
6332
6333
6334
6335
6336
6337
6338
6339
6340
6341
6342
6343
6344
6345
6346
6347
6348
6349
6350
6351
6352
6353
6354
6355
6356
6357
6358
6359
6360
6361
6362
6363
6364
6365
6366
6367
6368
6369
6370
6371
6372
6373
6374
6375
6376
6377
6378
6379
6380
6381
6382
6383
6384
6385
6386
6387
6388
6389
6390
6391
6392
6393
6394
6395
6396
6397
6398
6399
6400
6401
6402
6403
6404
6405
6406
6407
6408
6409
6410
6411
6412
6413
6414
6415
6416
6417
6418
6419
6420
6421
6422
6423
6424
6425
6426
6427
6428
6429
6430
6431
6432
6433
6434
6435
6436
6437
6438
6439
6440
6441
6442
6443
6444
6445
6446
6447
6448
6449
6450
6451
6452
6453
6454
6455
6456
6457
6458
6459
6460
6461
6462
6463
6464
6465
6466
6467
6468
6469
6470
6471
6472
6473
6474
6475
6476
6477
6478
6479
6480
6481
6482
6483
6484
6485
6486
6487
6488
6489
6490
6491
6492
6493
6494
6495
6496
6497
6498
6499
6500
6501
6502
6503
6504
6505
6506
6507
6508
6509
6510
6511
6512
6513
6514
6515
6516
6517
6518
6519
6520
6521
6522
6523
6524
6525
6526
6527
6528
6529
6530
6531
6532
6533
6534
6535
6536
6537
6538
6539
6540
6541
6542
6543
6544
6545
6546
6547
6548
6549
6550
6551
6552
6553
6554
6555
6556
6557
6558
6559
6560
6561
6562
6563
6564
6565
6566
6567
6568
6569
6570
6571
6572
6573
6574
6575
6576
6577
6578
6579
6580
6581
6582
6583
6584
6585
6586
6587
6588
6589
6590
6591
6592
6593
6594
6595
6596
6597
6598
6599
6600
6601
6602
6603
6604
6605
6606
6607
6608
6609
6610
6611
6612
6613
6614
6615
6616
6617
6618
6619
6620
6621
6622
6623
6624
6625
6626
6627
6628
6629
6630
6631
6632
6633
6634
6635
6636
6637
6638
6639
6640
6641
6642
6643
6644
6645
6646
6647
6648
6649
6650
6651
6652
6653
6654
6655
6656
6657
6658
6659
6660
6661
6662
6663
6664
6665
6666
6667
6668
6669
6670
6671
6672
6673
6674
6675
6676
6677
6678
6679
6680
6681
6682
6683
6684
6685
6686
6687
6688
6689
6690
6691
6692
6693
6694
6695
6696
6697
6698
6699
6700
6701
6702
6703
6704
6705
6706
6707
6708
6709
6710
6711
6712
6713
6714
6715
6716
6717
6718
6719
6720
6721
6722
6723
6724
6725
6726
6727
6728
6729
6730
6731
6732
6733
6734
6735
6736
6737
6738
6739
6740
6741
6742
6743
6744
6745
6746
6747
6748
6749
6750
6751
6752
6753
6754
6755
6756
6757
6758
6759
6760
6761
6762
6763
6764
6765
6766
6767
6768
6769
6770
6771
6772
6773
6774
6775
6776
6777
6778
6779
6780
6781
6782
6783
6784
6785
6786
6787
6788
6789
6790
6791
6792
6793
6794
6795
6796
6797
6798
6799
6800
6801
6802
6803
6804
6805
6806
6807
6808
6809
6810
6811
6812
6813
6814
6815
6816
6817
6818
6819
6820
6821
6822
6823
6824
6825
6826
6827
6828
6829
6830
6831
6832
6833
6834
6835
6836
6837
6838
6839
6840
6841
6842
6843
6844
6845
6846
6847
6848
6849
6850
6851
6852
6853
6854
6855
6856
6857
6858
6859
6860
6861
6862
6863
6864
6865
6866
6867
6868
6869
6870
6871
6872
6873
6874
6875
6876
6877
6878
6879
6880
6881
6882
6883
6884
6885
6886
6887
6888
6889
6890
6891
6892
6893
6894
6895
6896
6897
6898
6899
6900
6901
6902
6903
6904
6905
6906
6907
6908
6909
6910
6911
6912
6913
6914
6915
6916
6917
6918
6919
6920
6921
6922
6923
6924
6925
6926
6927
6928
6929
6930
6931
6932
6933
6934
6935
6936
6937
6938
6939
6940
6941
6942
6943
6944
6945
6946
6947
6948
6949
6950
6951
6952
6953
6954
6955
6956
6957
6958
6959
6960
6961
6962
6963
6964
6965
6966
6967
6968
6969
6970
6971
6972
6973
6974
6975
6976
6977
6978
6979
6980
6981
6982
6983
6984
6985
6986
6987
6988
6989
6990
6991
6992
6993
6994
6995
6996
6997
6998
6999
7000
7001
7002
7003
7004
7005
7006
7007
7008
7009
7010
7011
7012
7013
7014
7015
7016
7017
7018
7019
7020
7021
7022
7023
7024
7025
7026
7027
7028
7029
7030
7031
7032
7033
7034
7035
7036
7037
7038
7039
7040
7041
7042
7043
7044
7045
7046
7047
7048
7049
7050
7051
7052
7053
7054
7055
7056
7057
7058
7059
7060
7061
7062
7063
7064
7065
7066
7067
7068
7069
7070
7071
7072
7073
7074
7075
7076
7077
7078
7079
7080
7081
7082
7083
7084
7085
7086
7087
7088
7089
7090
7091
7092
7093
7094
7095
7096
7097
7098
7099
7100
7101
7102
7103
7104
7105
7106
7107
7108
7109
7110
7111
7112
7113
7114
7115
7116
7117
7118
7119
7120
7121
7122
7123
7124
7125
7126
7127
7128
7129
7130
7131
7132
7133
7134
7135
7136
7137
7138
7139
7140
7141
7142
7143
7144
7145
7146
7147
7148
7149
7150
7151
7152
7153
7154
7155
7156
7157
7158
7159
7160
7161
7162
7163
7164
7165
7166
7167
7168
7169
7170
7171
7172
7173
7174
7175
7176
7177
7178
7179
7180
7181
7182
7183
7184
7185
7186
7187
7188
7189
7190
7191
7192
7193
7194
7195
7196
7197
7198
7199
7200
7201
7202
7203
7204
7205
7206
7207
7208
7209
7210
7211
7212
7213
7214
7215
7216
7217
7218
7219
7220
7221
7222
7223
7224
7225
7226
7227
7228
7229
7230
7231
7232
7233
7234
7235
7236
7237
7238
7239
7240
7241
7242
7243
7244
7245
7246
7247
7248
7249
7250
7251
7252
7253
7254
7255
7256
7257
7258
7259
7260
7261
7262
7263
7264
7265
7266
7267
7268
7269
7270
7271
7272
7273
7274
7275
7276
7277
7278
7279
7280
7281
7282
7283
7284
7285
7286
7287
7288
7289
7290
7291
7292
7293
7294
7295
7296
7297
7298
7299
7300
7301
7302
7303
7304
7305
7306
7307
7308
7309
7310
7311
7312
7313
7314
7315
7316
7317
7318
7319
7320
7321
7322
7323
7324
7325
7326
7327
7328
7329
7330
7331
7332
7333
7334
7335
7336
7337
7338
7339
7340
7341
7342
7343
7344
7345
7346
7347
7348
7349
7350
7351
7352
7353
7354
7355
7356
7357
7358
7359
7360
7361
7362
7363
7364
7365
7366
7367
7368
7369
7370
7371
7372
7373
7374
7375
7376
7377
7378
7379
7380
7381
7382
7383
7384
7385
7386
7387
7388
7389
7390
7391
7392
7393
7394
7395
7396
7397
7398
7399
7400
7401
7402
7403
7404
7405
7406
7407
7408
7409
7410
7411
7412
7413
7414
7415
7416
7417
7418
7419
7420
7421
7422
7423
7424
7425
7426
7427
7428
7429
7430
7431
7432
7433
7434
7435
7436
7437
7438
7439
7440
7441
7442
7443
7444
7445
7446
7447
7448
7449
7450
7451
7452
7453
7454
7455
7456
7457
7458
7459
7460
7461
7462
7463
7464
7465
7466
7467
7468
7469
7470
7471
7472
7473
7474
7475
7476
7477
7478
7479
7480
7481
7482
7483
7484
7485
7486
7487
7488
7489
7490
7491
7492
7493
7494
7495
7496
7497
7498
7499
7500
7501
7502
7503
7504
7505
7506
7507
7508
7509
7510
7511
7512
7513
7514
7515
7516
7517
7518
7519
7520
7521
7522
7523
7524
7525
7526
7527
7528
7529
7530
7531
7532
7533
7534
7535
7536
7537
7538
7539
7540
7541
7542
7543
7544
7545
7546
7547
7548
7549
7550
7551
7552
7553
7554
7555
7556
7557
7558
7559
7560
7561
7562
7563
7564
7565
7566
7567
7568
7569
7570
7571
7572
7573
7574
7575
7576
7577
7578
7579
7580
7581
7582
7583
7584
7585
7586
7587
7588
7589
7590
7591
7592
7593
7594
7595
7596
7597
7598
7599
7600
7601
7602
7603
7604
7605
7606
7607
7608
7609
7610
7611
7612
7613
7614
7615
7616
7617
7618
7619
7620
7621
7622
7623
7624
7625
7626
7627
7628
7629
7630
7631
7632
7633
7634
7635
7636
7637
7638
7639
7640
7641
7642
7643
7644
7645
7646
7647
7648
7649
7650
7651
7652
7653
7654
7655
7656
7657
7658
7659
7660
7661
7662
7663
7664
7665
7666
7667
7668
7669
7670
7671
7672
7673
7674
7675
7676
7677
7678
7679
7680
7681
7682
7683
7684
7685
7686
7687
7688
7689
7690
7691
7692
7693
7694
7695
7696
7697
7698
7699
7700
7701
7702
7703
7704
7705
7706
7707
7708
7709
7710
7711
7712
7713
7714
7715
7716
7717
7718
7719
7720
7721
7722
7723
7724
7725
7726
7727
7728
7729
7730
7731
7732
7733
7734
7735
7736
7737
7738
7739
7740
7741
7742
7743
7744
7745
7746
7747
7748
7749
7750
7751
7752
7753
7754
7755
7756
7757
7758
7759
7760
7761
7762
7763
7764
7765
7766
7767
7768
7769
7770
7771
7772
7773
7774
7775
7776
7777
7778
7779
7780
7781
7782
7783
7784
7785
7786
7787
7788
7789
7790
7791
7792
7793
7794
7795
7796
7797
7798
7799
7800
7801
7802
7803
7804
7805
7806
7807
7808
7809
7810
7811
7812
7813
7814
7815
7816
7817
7818
7819
7820
7821
7822
7823
7824
7825
7826
7827
7828
7829
7830
7831
7832
7833
7834
7835
7836
7837
7838
7839
7840
7841
7842
7843
7844
7845
7846
7847
7848
7849
7850
7851
7852
7853
7854
7855
7856
7857
7858
7859
7860
7861
7862
7863
7864
7865
7866
7867
7868
7869
7870
7871
7872
7873
7874
7875
7876
7877
7878
7879
7880
7881
7882
7883
7884
7885
7886
7887
7888
7889
7890
7891
7892
7893
7894
7895
7896
7897
7898
7899
7900
7901
7902
7903
7904
7905
7906
7907
7908
7909
7910
7911
7912
7913
7914
7915
7916
7917
7918
7919
7920
7921
7922
7923
7924
7925
7926
7927
7928
7929
7930
7931
7932
7933
7934
7935
7936
7937
7938
7939
7940
7941
7942
7943
7944
7945
7946
7947
7948
7949
7950
7951
7952
7953
7954
7955
7956
7957
7958
7959
7960
7961
7962
7963
7964
7965
7966
7967
7968
7969
7970
7971
7972
7973
7974
7975
7976
7977
7978
7979
7980
7981
7982
7983
7984
7985
7986
7987
7988
7989
7990
7991
7992
7993
7994
7995
7996
7997
7998
7999
8000
8001
8002
8003
8004
8005
8006
8007
8008
8009
8010
8011
8012
8013
8014
8015
8016
8017
8018
8019
8020
8021
8022
8023
8024
8025
8026
8027
8028
8029
8030
8031
8032
8033
8034
8035
8036
8037
8038
8039
8040
8041
8042
8043
8044
8045
8046
8047
8048
8049
8050
8051
8052
8053
8054
8055
8056
8057
8058
8059
8060
8061
8062
8063
8064
8065
8066
8067
8068
8069
8070
8071
8072
8073
8074
8075
8076
8077
8078
8079
8080
8081
8082
8083
8084
8085
8086
8087
8088
8089
8090
8091
8092
8093
8094
8095
8096
8097
8098
8099
8100
8101
8102
8103
8104
8105
8106
8107
8108
8109
8110
8111
8112
8113
8114
8115
8116
8117
8118
8119
8120
8121
8122
8123
8124
8125
8126
8127
8128
8129
8130
8131
8132
8133
8134
8135
8136
8137
8138
8139
8140
8141
8142
8143
8144
8145
8146
8147
8148
8149
8150
8151
8152
8153
8154
8155
8156
8157
8158
8159
8160
8161
8162
8163
8164
8165
8166
8167

In [ ]:
dim_player

,Player_Key,Player_Id,Player_Name,Player_Full_Name,Birthdate
0,1,223597.0,R. Aguilar,Ruben Aguilar,1993-04-26
1,2,224069.0,K. Toko-Ekambi,Karl Brillant Toko Ekambi,1992-09-14
2,3,225085.0,J. Bamba,Jonathan Bamba,1996-03-26
3,4,171791.0,José Fonte,José Miguel da Rocha Fonte,1983-12-22
4,5,241727.0,P. Rajković,Predrag Rajković,1995-10-31
...,...,...,...,...,...
9175,9176,256948.0,C. Tzolis,Christos Tzolis,2002-01-30
9176,9177,236457.0,D. Giannoulis,Dimitris Giannoulis,1995-10-17
9177,9178,223154.0,O. Tufan,Ozan Tufan,1995-03-23
9178,9179,260142.0,R. Alebiosu,Ryan Alebiousu,2001-12-17
9179,9180,252477.0,J. Oluwayemi,Joshua Oluwayemi,2001-03-13

In [ ]:
dim_player.isna().sum()

Player_Key          0
Player_Id           1
Player_Name         1
Player_Full_Name    1
Birthdate           1
dtype: int64

<h3>6. Dim Player Version</h3>

In [ ]:
unique_values = fbref_matchinfos.loc[~fbref_matchinfos['Home_Team'].isin(sofifa_players_attr['Club']), 'Home_Team'].unique()
unique_values

array(['Hamburger SV', 'Düsseldorf', 'Paderborn 07', 'Arminia',
       'Greuther Fürth'], dtype=object)

In [ ]:
len(sofifa_players_attr)

291047

In [ ]:
dim_player_version = pd.DataFrame({'Player_Version_Key': [],
                          'Player': [],
                          'Update_Date': [],
                          'Team_Club': [],
                          'Team_National': [],
                          'Height': [],
                          'Weight': [],
                          'All_Positions': [], 'Attacking_Work_Rate': [], 'Body_Type': [],
                          'Defensive_Work_Rate': [], 'Preferred_Foot': [],
                          'Team_Club_Contract': [], 'Team_Club_Joined': [], 'Team_Club_Kitnum': [],
                          'Team_Club_Loaned_From': [], 'Team_National_Positions': [],
                          'Team_National_Rating': [], 'Specialities': []})

list_player_version_key = []
for i in range(0,len(sofifa_players_attr)):
    list_player_version_key.append(i+1)

dim_player_version['Player_Version_Key'] = list_player_version_key
dim_player_version['Team_National'] = sofifa_players_attr['National_Team'].to_list()
dim_player_version['Height'] = sofifa_players_attr['Height'].to_list()
dim_player_version['Weight'] = sofifa_players_attr['Weight'].to_list()
dim_player_version['All_Positions'] = sofifa_players_attr['All_Positions'].to_list()
dim_player_version['Attacking_Work_Rate'] = sofifa_players_attr['Attacking_Work_Rate'].to_list()
dim_player_version['Body_Type'] = sofifa_players_attr['Body_Type'].to_list()
dim_player_version['Defensive_Work_Rate'] = sofifa_players_attr['Defensive_Work_Rate'].to_list()
dim_player_version['Preferred_Foot'] = sofifa_players_attr['Preferred_Foot'].to_list()
dim_player_version['Team_Club_Contract'] = sofifa_players_attr['Club_Contract'].to_list()
dim_player_version['Team_Club_Joined'] = sofifa_players_attr['Club_Joined'].to_list()
dim_player_version['Team_Club_Kitnum'] = sofifa_players_attr['Club_Kitnum'].to_list()
dim_player_version['Team_Club_Loaned_From'] = sofifa_players_attr['Club_Loaned_From'].to_list()
dim_player_version['Team_National_Positions'] = sofifa_players_attr['National_Team_Position'].to_list()
dim_player_version['Team_National_Rating'] = sofifa_players_attr['National_Team_Rating'].to_list()
dim_player_version['Specialities'] = sofifa_players_attr['Specialities'].to_list()


#fk
list_player = []
list_update_date = []
list_team_club = []

for i in range(0, len(sofifa_players_attr)):

    print(i)

    temp_df = dim_player[dim_player['Player_Id'] == sofifa_players_attr['Sofifa_Id'].iloc[i]]
    if len(temp_df) > 0:
        list_player.append(temp_df['Player_Key'].iloc[0])
    else:
        list_player.append(np.nan)

    temp_df = dim_date[dim_date['Full_Date'] == sofifa_players_attr['Update_Date'].iloc[i]]
    if len(temp_df) > 0:
        list_update_date.append(temp_df['Date_Key'].iloc[0])
    else:
        list_update_date.append(np.nan)


    temp_df = dim_team[dim_team['Team_Name'] == sofifa_players_attr['Club'].iloc[i]]
    if len(temp_df) > 0:
        list_team_club.append(temp_df['Team_Key'].iloc[0])
    else:
        list_team_club.append(np.nan)

dim_player_version['Player'] = list_player
dim_player_version['Update_Date'] = list_update_date
dim_player_version['Team_Club'] = list_team_club

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
286047
286048
286049
286050
286051
286052
286053
286054
286055
286056
286057
286058
286059
286060
286061
286062
286063
286064
286065
286066
286067
286068
286069
286070
286071
286072
286073
286074
286075
286076
286077
286078
286079
286080
286081
286082
286083
286084
286085
286086
286087
286088
286089
286090
286091
286092
286093
286094
286095
286096
286097
286098
286099
286100
286101
286102
286103
286104
286105
286106
286107
286108
286109
286110
286111
286112
286113
286114
286115
286116
286117
286118
286119
286120
286121
286122
286123
286124
286125
286126
286127
286128
286129
286130
286131
286132
286133
286134
286135
286136
286137
286138
286139
286140
286141
286142
286143
286144
286145
286146
286147
286148
286149
286150
286151
286152
286153
286154
286155
286156
286157
286158
286159
286160
286161
286162
286163
286164
286165
286166
286167
286168
286169
286170
286171
286172
286173
286174
286175
286176
286177
286178
286179
286180
286181
286182
286183
286184
286185
286186
286187
286188
286189
286190
286191
286192
286193
286194
286195
286196
286197
286198
286199
286200
286201
286202
286203
286204
286205
286206
286207
286208
286209
286210
286211
286212
286213
286214
286215
286216
286217
286218
286219
286220
286221
286222
286223
286224
286225
286226
286227
286228
286229
286230
286231
286232
286233
286234
286235
286236
286237
286238
286239
286240
286241
286242
286243
286244
286245
286246
286247
286248
286249
286250
286251
286252
286253
286254
286255
286256
286257
286258
286259
286260
286261
286262
286263
286264
286265
286266
286267
286268
286269
286270
286271
286272
286273
286274
286275
286276
286277
286278
286279
286280
286281
286282
286283
286284
286285
286286
286287
286288
286289
286290
286291
286292
286293
286294
286295
286296
286297
286298
286299
286300
286301
286302
286303
286304
286305
286306
286307
286308
286309
286310
286311
286312
286313
286314
286315
286316
286317
286318
286319
286320
286321
286322
286323
286324
286325
286326
286327
286328
286329
286330
286331
286332
286333
286334
286335
286336
286337
286338
286339
286340
286341
286342
286343
286344
286345
286346
286347
286348
286349
286350
286351
286352
286353
286354
286355
286356
286357
286358
286359
286360
286361
286362
286363
286364
286365
286366
286367
286368
286369
286370
286371
286372
286373
286374
286375
286376
286377
286378
286379
286380
286381
286382
286383
286384
286385
286386
286387
286388
286389
286390
286391
286392
286393
286394
286395
286396
286397
286398
286399
286400
286401
286402
286403
286404
286405
286406
286407
286408
286409
286410
286411
286412
286413
286414
286415
286416
286417
286418
286419
286420
286421
286422
286423
286424
286425
286426
286427
286428
286429
286430
286431
286432
286433
286434
286435
286436
286437
286438
286439
286440
286441
286442
286443
286444
286445
286446
286447
286448
286449
286450
286451
286452
286453
286454
286455
286456
286457
286458
286459
286460
286461
286462
286463
286464
286465
286466
286467
286468
286469
286470
286471
286472
286473
286474
286475
286476
286477
286478
286479
286480
286481
286482
286483
286484
286485
286486
286487
286488
286489
286490
286491
286492
286493
286494
286495
286496
286497
286498
286499
286500
286501
286502
286503
286504
286505
286506
286507
286508
286509
286510
286511
286512
286513
286514
286515
286516
286517
286518
286519
286520
286521
286522
286523
286524
286525
286526
286527
286528
286529
286530
286531
286532
286533
286534
286535
286536
286537
286538
286539
286540
286541
286542
286543
286544
286545
286546
286547
286548
286549
286550
286551
286552
286553
286554
286555
286556
286557
286558
286559
286560
286561
286562
286563
286564
286565
286566
286567
286568
286569
286570
286571
286572
286573
286574
286575
286576
286577
286578
286579
286580
286581
286582
286583
286584
286585
286586
286587
286588
286589
286590
286591
286592
286593
286594
286595
286596
286597
286598
286599
286600
286601
286602
286603
286604
286605
286606
286607
286608
286609
286610
286611
286612
286613
286614
286615
286616
286617
286618
286619
286620
286621
286622
286623
286624
286625
286626
286627
286628
286629
286630
286631
286632
286633
286634
286635
286636
286637
286638
286639
286640
286641
286642
286643
286644
286645
286646
286647
286648
286649
286650
286651
286652
286653
286654
286655
286656
286657
286658
286659
286660
286661
286662
286663
286664
286665
286666
286667
286668
286669
286670
286671
286672
286673
286674
286675
286676
286677
286678
286679
286680
286681
286682
286683
286684
286685
286686
286687
286688
286689
286690
286691
286692
286693
286694
286695
286696
286697
286698
286699
286700
286701
286702
286703
286704
286705
286706
286707
286708
286709
286710
286711
286712
286713
286714
286715
286716
286717
286718
286719
286720
286721
286722
286723
286724
286725
286726
286727
286728
286729
286730
286731
286732
286733
286734
286735
286736
286737
286738
286739
286740
286741
286742
286743
286744
286745
286746
286747
286748
286749
286750
286751
286752
286753
286754
286755
286756
286757
286758
286759
286760
286761
286762
286763
286764
286765
286766
286767
286768
286769
286770
286771
286772
286773
286774
286775
286776
286777
286778
286779
286780
286781
286782
286783
286784
286785
286786
286787
286788
286789
286790
286791
286792
286793
286794
286795
286796
286797
286798
286799
286800
286801
286802
286803
286804
286805
286806
286807
286808
286809
286810
286811
286812
286813
286814
286815
286816
286817
286818
286819
286820
286821
286822
286823
286824
286825
286826
286827
286828
286829
286830
286831
286832
286833
286834
286835
286836
286837
286838
286839
286840
286841
286842
286843
286844
286845
286846
286847
286848
286849
286850
286851
286852
286853
286854
286855
286856
286857
286858
286859
286860
286861
286862
286863
286864
286865
286866
286867
286868
286869
286870
286871
286872
286873
286874
286875
286876
286877
286878
286879
286880
286881
286882
286883
286884
286885
286886
286887
286888
286889
286890
286891
286892
286893
286894
286895
286896
286897
286898
286899
286900
286901
286902
286903
286904
286905
286906
286907
286908
286909
286910
286911
286912
286913
286914
286915
286916
286917
286918
286919
286920
286921
286922
286923
286924
286925
286926
286927
286928
286929
286930
286931
286932
286933
286934
286935
286936
286937
286938
286939
286940
286941
286942
286943
286944
286945
286946
286947
286948
286949
286950
286951
286952
286953
286954
286955
286956
286957
286958
286959
286960
286961
286962
286963
286964
286965
286966
286967
286968
286969
286970
286971
286972
286973
286974
286975
286976
286977
286978
286979
286980
286981
286982
286983
286984
286985
286986
286987
286988
286989
286990
286991
286992
286993
286994
286995
286996
286997
286998
286999
287000
287001
287002
287003
287004
287005
287006
287007
287008
287009
287010
287011
287012
287013
287014
287015
287016
287017
287018
287019
287020
287021
287022
287023
287024
287025
287026
287027
287028
287029
287030
287031
287032
287033
287034
287035
287036
287037
287038
287039
287040
287041
287042
287043
287044
287045
287046
287047
287048
287049
287050
287051
287052
287053
287054
287055
287056
287057
287058
287059
287060
287061
287062
287063
287064
287065
287066
287067
287068
287069
287070
287071
287072
287073
287074
287075
287076
287077
287078
287079
287080
287081
287082
287083
287084
287085
287086
287087
287088
287089
287090
287091
287092
287093
287094
287095
287096
287097
287098
287099
287100
287101
287102
287103
287104
287105
287106
287107
287108
287109
287110
287111
287112
287113
287114
287115
287116
287117
287118
287119
287120
287121
287122
287123
287124
287125
287126
287127
287128
287129
287130
287131
287132
287133
287134
287135
287136
287137
287138
287139
287140
287141
287142
287143
287144
287145
287146
287147
287148
287149
287150
287151
287152
287153
287154
287155
287156
287157
287158
287159
287160
287161
287162
287163
287164
287165
287166
287167
287168
287169
287170
287171
287172
287173
287174
287175
287176
287177
287178
287179
287180
287181
287182
287183
287184
287185
287186
287187
287188
287189
287190
287191
287192
287193
287194
287195
287196
287197
287198
287199
287200
287201
287202
287203
287204
287205
287206
287207
287208
287209
287210
287211
287212
287213
287214
287215
287216
287217
287218
287219
287220
287221
287222
287223
287224
287225
287226
287227
287228
287229
287230
287231
287232
287233
287234
287235
287236
287237
287238
287239
287240
287241
287242
287243
287244
287245
287246
287247
287248
287249
287250
287251
287252
287253
287254
287255
287256
287257
287258
287259
287260
287261
287262
287263
287264
287265
287266
287267
287268
287269
287270
287271
287272
287273
287274
287275
287276
287277
287278
287279
287280
287281
287282
287283
287284
287285
287286
287287
287288
287289
287290
287291
287292
287293
287294
287295
287296
287297
287298
287299
287300
287301
287302
287303
287304
287305
287306
287307
287308
287309
287310
287311
287312
287313
287314
287315
287316
287317
287318
287319
287320
287321
287322
287323
287324
287325
287326
287327
287328
287329
287330
287331
287332
287333
287334
287335
287336
287337
287338
287339
287340
287341
287342
287343
287344
287345
287346
287347
287348
287349
287350
287351
287352
287353
287354
287355
287356
287357
287358
287359
287360
287361
287362
287363
287364
287365
287366
287367
287368
287369
287370
287371
287372
287373
287374
287375
287376
287377
287378
287379
287380
287381
287382
287383
287384
287385
287386
287387
287388
287389
287390
287391
287392
287393
287394
287395
287396
287397
287398
287399
287400
287401
287402
287403
287404
287405
287406
287407
287408
287409
287410
287411
287412
287413
287414
287415
287416
287417
287418
287419
287420
287421
287422
287423
287424
287425
287426
287427
287428
287429
287430
287431
287432
287433
287434
287435
287436
287437
287438
287439
287440
287441
287442
287443
287444
287445
287446
287447
287448
287449
287450
287451
287452
287453
287454
287455
287456
287457
287458
287459
287460
287461
287462
287463
287464
287465
287466
287467
287468
287469
287470
287471
287472
287473
287474
287475
287476
287477
287478
287479
287480
287481
287482
287483
287484
287485
287486
287487
287488
287489
287490
287491
287492
287493
287494
287495
287496
287497
287498
287499
287500
287501
287502
287503
287504
287505
287506
287507
287508
287509
287510
287511
287512
287513
287514
287515
287516
287517
287518
287519
287520
287521
287522
287523
287524
287525
287526
287527
287528
287529
287530
287531
287532
287533
287534
287535
287536
287537
287538
287539
287540
287541
287542
287543
287544
287545
287546
287547
287548
287549
287550
287551
287552
287553
287554
287555
287556
287557
287558
287559
287560
287561
287562
287563
287564
287565
287566
287567
287568
287569
287570
287571
287572
287573
287574
287575
287576
287577
287578
287579
287580
287581
287582
287583
287584
287585
287586
287587
287588
287589
287590
287591
287592
287593
287594
287595
287596
287597
287598
287599
287600
287601
287602
287603
287604
287605
287606
287607
287608
287609
287610
287611
287612
287613
287614
287615
287616
287617
287618
287619
287620
287621
287622
287623
287624
287625
287626
287627
287628
287629
287630
287631
287632
287633
287634
287635
287636
287637
287638
287639
287640
287641
287642
287643
287644
287645
287646
287647
287648
287649
287650
287651
287652
287653
287654
287655
287656
287657
287658
287659
287660
287661
287662
287663
287664
287665
287666
287667
287668
287669
287670
287671
287672
287673
287674
287675
287676
287677
287678
287679
287680
287681
287682
287683
287684
287685
287686
287687
287688
287689
287690
287691
287692
287693
287694
287695
287696
287697
287698
287699
287700
287701
287702
287703
287704
287705
287706
287707
287708
287709
287710
287711
287712
287713
287714
287715
287716
287717
287718
287719
287720
287721
287722
287723
287724
287725
287726
287727
287728
287729
287730
287731
287732
287733
287734
287735
287736
287737
287738
287739
287740
287741
287742
287743
287744
287745
287746
287747
287748
287749
287750
287751
287752
287753
287754
287755
287756
287757
287758
287759
287760
287761
287762
287763
287764
287765
287766
287767
287768
287769
287770
287771
287772
287773
287774
287775
287776
287777
287778
287779
287780
287781
287782
287783
287784
287785
287786
287787
287788
287789
287790
287791
287792
287793
287794
287795
287796
287797
287798
287799
287800
287801
287802
287803
287804
287805
287806
287807
287808
287809
287810
287811
287812
287813
287814
287815
287816
287817
287818
287819
287820
287821
287822
287823
287824
287825
287826
287827
287828
287829
287830
287831
287832
287833
287834
287835
287836
287837
287838
287839
287840
287841
287842
287843
287844
287845
287846
287847
287848
287849
287850
287851
287852
287853
287854
287855
287856
287857
287858
287859
287860
287861
287862
287863
287864
287865
287866
287867
287868
287869
287870
287871
287872
287873
287874
287875
287876
287877
287878
287879
287880
287881
287882
287883
287884
287885
287886
287887
287888
287889
287890
287891
287892
287893
287894
287895
287896
287897
287898
287899
287900
287901
287902
287903
287904
287905
287906
287907
287908
287909
287910
287911
287912
287913
287914
287915
287916
287917
287918
287919
287920
287921
287922
287923
287924
287925
287926
287927
287928
287929
287930
287931
287932
287933
287934
287935
287936
287937
287938
287939
287940
287941
287942
287943
287944
287945
287946
287947
287948
287949
287950
287951
287952
287953
287954
287955
287956
287957
287958
287959
287960
287961
287962
287963
287964
287965
287966
287967
287968
287969
287970
287971
287972
287973
287974
287975
287976
287977
287978
287979
287980
287981
287982
287983
287984
287985
287986
287987
287988
287989
287990
287991
287992
287993
287994
287995
287996
287997
287998
287999
288000
288001
288002
288003
288004
288005
288006
288007
288008
288009
288010
288011
288012
288013
288014
288015
288016
288017
288018
288019
288020
288021
288022
288023
288024
288025
288026
288027
288028
288029
288030
288031
288032
288033
288034
288035
288036
288037
288038
288039
288040
288041
288042
288043
288044
288045
288046
288047
288048
288049
288050
288051
288052
288053
288054
288055
288056
288057
288058
288059
288060
288061
288062
288063
288064
288065
288066
288067
288068
288069
288070
288071
288072
288073
288074
288075
288076
288077
288078
288079
288080
288081
288082
288083
288084
288085
288086
288087
288088
288089
288090
288091
288092
288093
288094
288095
288096
288097
288098
288099
288100
288101
288102
288103
288104
288105
288106
288107
288108
288109
288110
288111
288112
288113
288114
288115
288116
288117
288118
288119
288120
288121
288122
288123
288124
288125
288126
288127
288128
288129
288130
288131
288132
288133
288134
288135
288136
288137
288138
288139
288140
288141
288142
288143
288144
288145
288146
288147
288148
288149
288150
288151
288152
288153
288154
288155
288156
288157
288158
288159
288160
288161
288162
288163
288164
288165
288166
288167
288168
288169
288170
288171
288172
288173
288174
288175
288176
288177
288178
288179
288180
288181
288182
288183
288184
288185
288186
288187
288188
288189
288190
288191
288192
288193
288194
288195
288196
288197
288198
288199
288200
288201
288202
288203
288204
288205
288206
288207
288208
288209
288210
288211
288212
288213
288214
288215
288216
288217
288218
288219
288220
288221
288222
288223
288224
288225
288226
288227
288228
288229
288230
288231
288232
288233
288234
288235
288236
288237
288238
288239
288240
288241
288242
288243
288244
288245
288246
288247
288248
288249
288250
288251
288252
288253
288254
288255
288256
288257
288258
288259
288260
288261
288262
288263
288264
288265
288266
288267
288268
288269
288270
288271
288272
288273
288274
288275
288276
288277
288278
288279
288280
288281
288282
288283
288284
288285
288286
288287
288288
288289
288290
288291
288292
288293
288294
288295
288296
288297
288298
288299
288300
288301
288302
288303
288304
288305
288306
288307
288308
288309
288310
288311
288312
288313
288314
288315
288316
288317
288318
288319
288320
288321
288322
288323
288324
288325
288326
288327
288328
288329
288330
288331
288332
288333
288334
288335
288336
288337
288338
288339
288340
288341
288342
288343
288344
288345
288346
288347
288348
288349
288350
288351
288352
288353
288354
288355
288356
288357
288358
288359
288360
288361
288362
288363
288364
288365
288366
288367
288368
288369
288370
288371
288372
288373
288374
288375
288376
288377
288378
288379
288380
288381
288382
288383
288384
288385
288386
288387
288388
288389
288390
288391
288392
288393
288394
288395
288396
288397
288398
288399
288400
288401
288402
288403
288404
288405
288406
288407
288408
288409
288410
288411
288412
288413
288414
288415
288416
288417
288418
288419
288420
288421
288422
288423
288424
288425
288426
288427
288428
288429
288430
288431
288432
288433
288434
288435
288436
288437
288438
288439
288440
288441
288442
288443
288444
288445
288446
288447
288448
288449
288450
288451
288452
288453
288454
288455
288456
288457
288458
288459
288460
288461
288462
288463
288464
288465
288466
288467
288468
288469
288470
288471
288472
288473
288474
288475
288476
288477
288478
288479
288480
288481
288482
288483
288484
288485
288486
288487
288488
288489
288490
288491
288492
288493
288494
288495
288496
288497
288498
288499
288500
288501
288502
288503
288504
288505
288506
288507
288508
288509
288510
288511
288512
288513
288514
288515
288516
288517
288518
288519
288520
288521
288522
288523
288524
288525
288526
288527
288528
288529
288530
288531
288532
288533
288534
288535
288536
288537
288538
288539
288540
288541
288542
288543
288544
288545
288546
288547
288548
288549
288550
288551
288552
288553
288554
288555
288556
288557
288558
288559
288560
288561
288562
288563
288564
288565
288566
288567
288568
288569
288570
288571
288572
288573
288574
288575
288576
288577
288578
288579
288580
288581
288582
288583
288584
288585
288586
288587
288588
288589
288590
288591
288592
288593
288594
288595
288596
288597
288598
288599
288600
288601
288602
288603
288604
288605
288606
288607
288608
288609
288610
288611
288612
288613
288614
288615
288616
288617
288618
288619
288620
288621
288622
288623
288624
288625
288626
288627
288628
288629
288630
288631
288632
288633
288634
288635
288636
288637
288638
288639
288640
288641
288642
288643
288644
288645
288646
288647
288648
288649
288650
288651
288652
288653
288654
288655
288656
288657
288658
288659
288660
288661
288662
288663
288664
288665
288666
288667
288668
288669
288670
288671
288672
288673
288674
288675
288676
288677
288678
288679
288680
288681
288682
288683
288684
288685
288686
288687
288688
288689
288690
288691
288692
288693
288694
288695
288696
288697
288698
288699
288700
288701
288702
288703
288704
288705
288706
288707
288708
288709
288710
288711
288712
288713
288714
288715
288716
288717
288718
288719
288720
288721
288722
288723
288724
288725
288726
288727
288728
288729
288730
288731
288732
288733
288734
288735
288736
288737
288738
288739
288740
288741
288742
288743
288744
288745
288746
288747
288748
288749
288750
288751
288752
288753
288754
288755
288756
288757
288758
288759
288760
288761
288762
288763
288764
288765
288766
288767
288768
288769
288770
288771
288772
288773
288774
288775
288776
288777
288778
288779
288780
288781
288782
288783
288784
288785
288786
288787
288788
288789
288790
288791
288792
288793
288794
288795
288796
288797
288798
288799
288800
288801
288802
288803
288804
288805
288806
288807
288808
288809
288810
288811
288812
288813
288814
288815
288816
288817
288818
288819
288820
288821
288822
288823
288824
288825
288826
288827
288828
288829
288830
288831
288832
288833
288834
288835
288836
288837
288838
288839
288840
288841
288842
288843
288844
288845
288846
288847
288848
288849
288850
288851
288852
288853
288854
288855
288856
288857
288858
288859
288860
288861
288862
288863
288864
288865
288866
288867
288868
288869
288870
288871
288872
288873
288874
288875
288876
288877
288878
288879
288880
288881
288882
288883
288884
288885
288886
288887
288888
288889
288890
288891
288892
288893
288894
288895

In [ ]:
dim_player_version

,Player_Version_Key,Player,Update_Date,Team_Club,Team_National,Height,Weight,All_Positions,Attacking_Work_Rate,Body_Type,Defensive_Work_Rate,Preferred_Foot,Team_Club_Contract,Team_Club_Joined,Team_Club_Kitnum,Team_Club_Loaned_From,Team_National_Positions,Team_National_Rating,Specialities
0,1,1.0,20200923.0,1.0,NaN,172,71.0,RB RWB,High,Normal (170-185),Medium,Right,2024,2019-08-06,26,NaN,NaN,NaN,NaN
1,2,2.0,20200923.0,3.0,Cameroon,185,78.0,ST LM,High,Normal (185+),Medium,Right,2024,2020-06-08,21,NaN,SUB,75.0,NaN
2,3,3.0,20200923.0,8.0,NaN,175,70.0,LM,High,Normal (170-185),High,Right,2023,2018-07-02,14,NaN,NaN,NaN,NaN
3,4,4.0,20200923.0,8.0,Portugal,191,81.0,CB,Medium,Lean (185+),High,Right,2021,2018-07-15,6,NaN,SUB,83.0,NaN
4,5,5.0,20200923.0,21.0,NaN,191,85.0,GK,Medium,Normal (185+),Medium,Right,2023,2019-06-21,1,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291042,291043,5025.0,20230705.0,38.0,NaN,175,71.0,RW,High,Unique,Medium,Left,2025,2017-07-01,11,NaN,NaN,NaN,#Dribbler#Acrobat#Clinical finisher#Complete f...
291043,291044,5018.0,20230705.0,48.0,Norway,195,94.0,ST,High,Unique,Medium,Left,2027,2022-07-01,9,NaN,ST,76.0,#Aerial threat#Distance shooter#Strength#Clini...
291044,291045,5031.0,20230705.0,48.0,Belgium,181,75.0,CM CAM,High,Unique,Medium,Right,2025,2015-08-30,17,NaN,RF,80.0,#Dribbler#Playmaker #Distance shooter#Crosser#...
291045,291046,6798.0,20230605.0,38.0,NaN,178,73.0,LB,High,Normal (170-185),Medium,Left,2024,2021-08-30,77,NaN,NaN,NaN,NaN
291046,291047,6273.0,20230605.0,48.0,NaN,170,59.0,RW,Medium,Lean (170-),Medium,Left,2025,2019-06-14,96,NaN,NaN,NaN,NaN

In [ ]:
dim_player_version.isna().sum()

Player_Version_Key              0
Player                         19
Update_Date                    19
Team_Club                    3730
Team_National              247723
Height                          0
Weight                         19
All_Positions                   0
Attacking_Work_Rate             0
Body_Type                       0
Defensive_Work_Rate             0
Preferred_Foot                 19
Team_Club_Contract              0
Team_Club_Joined            22924
Team_Club_Kitnum                0
Team_Club_Loaned_From      268123
Team_National_Positions    247723
Team_National_Rating       247723
Specialities               246361
dtype: int64

<h3>7. Dim MatchSquad</h3>

In [ ]:
#sofifa
sofifa_players = pd.read_csv('gs://football_data_etl/football_data_extracted/output-basic/sofifa_players_attr.csv/part-00000-0474179e-867f-4f31-9d30-40c396f830f5-c000.csv',
                                  on_bad_lines="skip")
sofifa_players['Birthday'] = pd.to_datetime(sofifa_players['Birthday'])
sofifa_players['Birthday'] = sofifa_players['Birthday'].dt.strftime('%Y-%m-%d')
sofifa_players['Club_Joined'] = pd.to_datetime(sofifa_players['Club_Joined'])
sofifa_players['Club_Joined'] = sofifa_players['Club_Joined'].dt.strftime('%Y-%m-%d')
sofifa_players['Update_Date'] = pd.to_datetime(sofifa_players['Update_Date'])
sofifa_players['Update_Date'] = sofifa_players['Update_Date'].dt.strftime('%Y-%m-%d')

/tmp/ipykernel_270595/3872846029.py:2: DtypeWarning: Columns (45) have mixed types. Specify dtype option on import or set low_memory=False.
  sofifa_players = pd.read_csv('gs://football-data-etl/football-data-extracted/output-basic/sofifa_players_attr.csv/part-00000-c052c0ee-65cd-4820-8e09-1e44e809dcc5-c000.csv',

In [ ]:
different_team = set(fbref_matchsquad['Team']) - set(sofifa_players['Club'])
different_team

{'Arminia',
 'Cardiff City',
 'Düsseldorf',
 'Greuther Fürth',
 'Hamburger SV',
 'Hannover 96',
 'Huddersfield',
 'Norwich City',
 'Nürnberg',
 'Paderborn 07',
 'Stoke City',
 'Swansea City',
 'Watford',
 'West Brom'}

Merge

In [ ]:
fbref_matchsquad_new = pd.merge(fbref_matchsquad, fbref_matchinfos, on='Match_Id')
fbref_matchsquad_new = fbref_matchsquad_new.loc[:,['Match_Id', 'Match_Date', 'Team',
                                                             'Player_Name', 'Player_Kitnum', 'Is_Sub', 'Season']]
fbref_matchsquad_new.head(10)

,Match_Id,Match_Date,Team,Player_Name,Player_Kitnum,Is_Sub,Season
0,39b738ac,2017-11-24,Saint-Étienne,Stéphane Ruffier,16,No,2018
1,39b738ac,2017-11-24,Saint-Étienne,Kévin Théophile-Catherine,2,No,2018
2,39b738ac,2017-11-24,Saint-Étienne,Vincent Pajot,5,No,2018
3,39b738ac,2017-11-24,Saint-Étienne,Assane Dioussé,8,No,2018
4,39b738ac,2017-11-24,Saint-Étienne,Jonathan Bamba,14,No,2018
5,39b738ac,2017-11-24,Saint-Étienne,Florentin Pogba,19,No,2018
6,39b738ac,2017-11-24,Saint-Étienne,Hernani,20,No,2018
7,39b738ac,2017-11-24,Saint-Étienne,Kévin Monnet-Paquet,22,No,2018
8,39b738ac,2017-11-24,Saint-Étienne,Alexander Søderlund,23,No,2018
9,39b738ac,2017-11-24,Saint-Étienne,Loïc Perrin,24,No,2018

In [ ]:
#remove season 2017-2018
fbref_matchsquad_new = fbref_matchsquad_new[fbref_matchsquad_new['Season'] != 2018]
fbref_matchsquad_new = fbref_matchsquad_new.drop('Season', axis=1)
fbref_matchsquad_new.count()

Match_Id         428843
Match_Date       428843
Team             428843
Player_Name      428843
Player_Kitnum    428843
Is_Sub           428843
dtype: int64

Sắp xếp Sofifa_playes theo ngày cập nhật Update_Date giảm dần và tăng dần

In [ ]:
sofifa_players_desc_update_date = sofifa_players.sort_values(by = 'Update_Date', ascending=False)
sofifa_players_asc_update_date = sofifa_players.sort_values(by = 'Update_Date', ascending=True)

* function() ClosestUpdateDate: trả về ngày Update_Date gần nhất cho Match_Date (ngày diễn ra match)
* function() SofifaPlayersEqualUpdateDate: trả về dataframe tất cả các sofifa player với 1 Update_Date

In [ ]:
#return closest Update_Date: date-time
def ClosestUpdateDate(sofifa_players_desc_update_date, match_date):
    closest_update_date = sofifa_players_desc_update_date[sofifa_players_desc_update_date['Update_Date']
                                                        <= match_date]['Update_Date'].iloc[0]
    return closest_update_date

#return dataframe
def SofifaPlayersEqualUpdateDate(sofifa_players_desc_update_date, closest_update_date):
    sofia_players_one_update_version = sofifa_players_desc_update_date[sofifa_players_desc_update_date['Update_Date']
                                                                    == closest_update_date]
    return sofia_players_one_update_version

* function() SofifaPlayer: trả về player với id, position và overall rating ứng với mỗi match
* function() SofifaPlayer_ByName: trả về player theo name

In [ ]:
#return dataframe:
def SofifaPlayer(sofifa_update_version, team_fbref, player_kitnum_fbref):
    player = sofifa_update_version[(sofifa_update_version['Club'] == team_fbref) &
                                   (sofifa_update_version['Club_Kitnum'] == player_kitnum_fbref)][['Sofifa_Id', 'All_Positions',
                                                                                                   'Overall_Rating', 'Update_Date']]
    return player

#return dataframe:
def SofifaPlayer_ByName(sofifa_update_version, player_name):
    player = sofifa_update_version[sofifa_update_version['Player_Name']
                                            == player_name][['Sofifa_Id',
                                                             'All_Positions',
                                                             'Overall_Rating',
                                                             'Update_Date']]
    return player

- function() PLayerNotFound: kiểm tra trường hợp player trong match không có trong phiên bản sofifa gần nhất

In [ ]:
#return player_id: integer
def PLayerNotFound(sofifa_players_asc_update_date,closest_update_date, player_name):

    player = pd.DataFrame()

    dates_last = sofifa_players_asc_update_date[sofifa_players_asc_update_date['Update_Date']
                                                            > closest_update_date]['Update_Date'].unique()
    if(len(dates_last)>0):
        for k in range(0,len(dates_last)):
            sofia_players_more_update_date = sofifa_players_asc_update_date[sofifa_players_asc_update_date['Update_Date']
                                                                        == dates_last[k]]

            player = SofifaPlayer_ByName(sofia_players_more_update_date, player_name)

            if not player.empty:
                break

    return player

Cập nhật thêm cho MatchSquad với sofifa_id player, vị trí, overall rating và phiên bản player

In [ ]:
new_attrs = pd.DataFrame({'Sofifa_Id': [],
                          'Player_Position': [],
                          'Player_Overall_Rating': [],
                          'Player_Update_Date': []})
list_sofifa_id = []
list_player_position = []
list_player_overall_rating = []
list_update_date = []

Xác định ứng với mỗi match, tại thời điểm Update_Date của player gần nhất, với mỗi Team - đội bóng và Player_Kitnum - số áo player trong đội ta có thể tìm được player tương ứng trong Sofifa

In [ ]:
for i in range(0, len(fbref_matchsquad_new)):
    print(i)
    #
    match_date_i = fbref_matchsquad_new.iloc[i, fbref_matchsquad_new.columns.get_loc('Match_Date')]

    closest_update_date_i = ClosestUpdateDate(sofifa_players_desc_update_date, match_date_i)

    # Sofifa_Id attribute
    # ** team **
    team_fbref_i = fbref_matchsquad_new.iloc[i, fbref_matchsquad_new.columns.get_loc('Team')]
    # ** player_kit_num **
    player_kitnum_fbref_i = fbref_matchsquad_new.iloc[i, fbref_matchsquad_new.columns.get_loc('Player_Kitnum')]

    sofia_players_this_update_version = SofifaPlayersEqualUpdateDate(sofifa_players_desc_update_date, closest_update_date_i)

    player = SofifaPlayer(sofia_players_this_update_version, team_fbref_i, player_kitnum_fbref_i)

    player_id = np.nan
    player_position = np.nan
    player_overall_rating = np.nan
    player_update_date = np.nan

    #if player.empty:
        #player = PLayerNotFound(sofifa_players_asc_update_date,closest_update_date_i, team_fbref_i, player_kitnum_fbref_i)

    if not player.empty:
        player_id = player['Sofifa_Id'].iloc[0]
        player_position = player['All_Positions'].iloc[0]#.split(' ')[0]
        player_overall_rating = player['Overall_Rating'].iloc[0]
        player_update_date = player['Update_Date'].iloc[0]


    list_sofifa_id.append(player_id)

    #Player_Position attribute
    list_player_position.append(player_position)

    #Player_Overall_Rating attribute
    list_player_overall_rating.append(player_overall_rating)

    #Player_Update_Date attribute
    list_update_date.append(player_update_date)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860

1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2246
2247
2248
2249
2250
2251
2252
2253
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
2265
2266
2267
2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2392
2393
2394
2395
2396
2397
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
2413
2414
2415
2416
2417
2418
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2470
2471
2472
2473
2474
2475
2476
2477
2478
2479
2480
2481
2482
2483
2484
2485
2486
2487
2488
2489
2490
2491
2492
2493
2494
2495
2496
2497
2498
2499
2500
2501
2502
2503
2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2519
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551
2552
2553
2554
2555
2556
2557
2558
2559
2560
2561
2562
2563
2564
2565
2566
2567
2568
2569
2570
2571
2572
2573
2574
2575
2576
2577
2578
2579
2580
2581
2582
2583
2584
2585
2586
2587
2588
2589
2590
2591
2592
2593
2594
2595
2596
2597
2598
2599
2600
2601
2602
2603
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2625
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
2636
2637
2638
2639
2640
2641
2642
2643
2644
2645
2646
2647
2648
2649
2650
2651
2652
2653
2654
2655
2656
2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2673
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
2686
2687
2688
2689
2690
2691
2692
2693
2694
2695
2696
2697
2698
2699
2700
2701
2702
2703
2704
2705
2706
2707
2708
2709
2710
2711
2712
2713
2714
2715
2716
2717
2718
2719
2720
2721
2722
2723
2724
2725
2726
2727
2728
2729
2730
2731
2732
2733
2734
2735
2736
2737
2738
2739
2740
2741
2742
2743
2744
2745
2746
2747
2748
2749
2750
2751
2752
2753
2754
2755
2756
2757
2758
2759
2760
2761
2762
2763
2764
2765
2766
2767
2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2782
2783
2784
2785
2786
2787
2788
2789
2790
2791
2792
2793
2794
2795
2796
2797
2798
2799
2800
2801
2802
2803
2804
2805
2806
2807
2808
2809
2810
2811
2812
2813
2814
2815
2816
2817
2818
2819
2820
2821
2822
2823
2824
2825
2826
2827
2828
2829
2830
2831
2832
2833
2834
2835
2836
2837
2838
2839
2840
2841
2842
2843
2844
2845
2846
2847
2848
2849
2850
2851
2852
2853
2854
2855
2856
2857
2858
2859
2860
2861
2862
2863
2864
2865
2866
2867
2868
2869
2870
2871
2872
2873
2874
2875
2876
2877
2878
2879
2880
2881
2882
2883
2884
2885
2886
2887
2888
2889
2890
2891
2892
2893
2894
2895
2896
2897
2898
2899
2900
2901
2902
2903
2904
2905
2906
2907
2908
2909
2910
2911
2912
2913
2914
2915
2916
2917
2918
2919
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963
2964
2965
2966
2967
2968
2969
2970
2971
2972
2973
2974
2975
2976
2977
2978
2979
2980
2981
2982
2983
2984
2985
2986
2987
2988
2989
2990
2991
2992
2993
2994
2995
2996
2997
2998
2999
3000
3001
3002
3003
3004
3005
3006
3007
3008
3009
3010
3011
3012
3013
3014
3015
3016
3017
3018
3019
3020
3021
3022
3023
3024
3025
3026
3027
3028
3029
3030
3031
3032
3033
3034
3035
3036
3037
3038
3039
3040
3041
3042
3043
3044
3045
3046
3047
3048
3049
3050
3051
3052
3053
3054
3055
3056
3057
3058
3059
3060
3061
3062
3063
3064
3065
3066
3067
3068
3069
3070
3071
3072
3073
3074
3075
3076
3077
3078
3079
3080
3081
3082
3083
3084
3085
3086
3087
3088
3089
3090
3091
3092
3093
3094
3095
3096
3097
3098
3099
3100
3101
3102
3103
3104
3105
3106
3107
3108
3109
3110
3111
3112
3113
3114
3115
3116
3117
3118
3119
3120
3121
3122
3123
3124
3125
3126
3127
3128
3129
3130
3131
3132
3133
3134
3135
3136
3137
3138
3139
3140
3141
3142
3143
3144
3145
3146
3147
3148
3149
3150
3151
3152
3153
3154
3155
3156
3157
3158
3159
3160
3161
3162
3163
3164
3165
3166
3167
3168
3169
3170
3171
3172
3173
3174
3175
3176
3177
3178
3179
3180
3181
3182
3183
3184
3185
3186
3187
3188
3189
3190
3191
3192
3193
3194
3195
3196
3197
3198
3199
3200
3201
3202
3203
3204
3205
3206
3207
3208
3209
3210
3211
3212
3213
3214
3215
3216
3217
3218
3219
3220
3221
3222
3223
3224
3225
3226
3227
3228
3229
3230
3231
3232
3233
3234
3235
3236
3237
3238
3239
3240
3241
3242
3243
3244
3245
3246
3247
3248
3249
3250
3251
3252
3253
3254
3255
3256
3257
3258
3259
3260
3261
3262
3263
3264
3265
3266
3267
3268
3269
3270
3271
3272
3273
3274
3275
3276
3277
3278
3279
3280
3281
3282
3283
3284
3285
3286
3287
3288
3289
3290
3291
3292
3293
3294
3295
3296
3297
3298
3299
3300
3301
3302
3303
3304
3305
3306
3307
3308
3309
3310
3311
3312
3313
3314
3315
3316
3317
3318
3319
3320
3321
3322
3323
3324
3325
3326
3327
3328
3329
3330
3331
3332
3333
3334
3335
3336
3337
3338
3339
3340
3341
3342
3343
3344
3345
3346
3347
3348
3349
3350
3351
3352
3353
3354
3355
3356
3357
3358
3359
3360
3361
3362
3363
3364
3365
3366
3367
3368
3369
3370
3371
3372
3373
3374
3375
3376
3377
3378
3379
3380
3381
3382
3383
3384
3385
3386
3387
3388
3389
3390
3391
3392
3393
3394
3395
3396
3397
3398
3399
3400
3401
3402
3403
3404
3405
3406
3407
3408
3409
3410
3411
3412
3413
3414
3415
3416
3417
3418
3419
3420
3421
3422
3423
3424
3425
3426
3427
3428
3429
3430
3431
3432
3433
3434
3435
3436
3437
3438
3439
3440
3441
3442
3443
3444
3445
3446
3447
3448
3449
3450
3451
3452
3453
3454
3455
3456
3457
3458
3459
3460
3461
3462
3463
3464
3465
3466
3467
3468
3469
3470
3471
3472
3473
3474
3475
3476
3477
3478
3479
3480
3481
3482
3483
3484
3485
3486
3487
3488
3489
3490
3491
3492
3493
3494
3495
3496
3497
3498
3499
3500
3501

3502
3503
3504
3505
3506
3507
3508
3509
3510
3511
3512
3513
3514
3515
3516
3517
3518
3519
3520
3521
3522
3523
3524
3525
3526
3527
3528
3529
3530
3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
3724
3725
3726
3727
3728
3729
3730
3731
3732
3733
3734
3735
3736
3737
3738
3739
3740
3741
3742
3743
3744
3745
3746
3747
3748
3749
3750
3751
3752
3753
3754
3755
3756
3757
3758
3759
3760
3761
3762
3763
3764
3765
3766
3767
3768
3769
3770
3771
3772
3773
3774
3775
3776
3777
3778
3779
3780
3781
3782
3783
3784
3785
3786
3787
3788
3789
3790
3791
3792
3793
3794
3795
3796
3797
3798
3799
3800
3801
3802
3803
3804
3805
3806
3807
3808
3809
3810
3811
3812
3813
3814
3815
3816
3817
3818
3819
3820
3821
3822
3823
3824
3825
3826
3827
3828
3829
3830
3831
3832
3833
3834
3835
3836
3837
3838
3839
3840
3841
3842
3843
3844
3845
3846
3847
3848
3849
3850
3851
3852
3853
3854
3855
3856
3857
3858
3859
3860
3861
3862
3863
3864
3865
3866
3867
3868
3869
3870
3871
3872
3873
3874
3875
3876
3877
3878
3879
3880
3881
3882
3883
3884
3885
3886
3887
3888
3889
3890
3891
3892
3893
3894
3895
3896
3897
3898
3899
3900
3901
3902
3903
3904
3905
3906
3907
3908
3909
3910
3911
3912
3913
3914
3915
3916
3917
3918
3919
3920
3921
3922
3923
3924
3925
3926
3927
3928
3929
3930
3931
3932
3933
3934
3935
3936
3937
3938
3939
3940
3941
3942
3943
3944
3945
3946
3947
3948
3949
3950
3951
3952
3953
3954
3955
3956
3957
3958
3959
3960
3961
3962
3963
3964
3965
3966
3967
3968
3969
3970
3971
3972
3973
3974
3975
3976
3977
3978
3979
3980
3981
3982
3983
3984
3985
3986
3987
3988
3989
3990
3991
3992
3993
3994
3995
3996
3997
3998
3999
4000
4001
4002
4003
4004
4005
4006
4007
4008
4009
4010
4011
4012
4013
4014
4015
4016
4017
4018
4019
4020
4021
4022
4023
4024
4025
4026
4027
4028
4029
4030
4031
4032
4033
4034
4035
4036
4037
4038
4039
4040
4041
4042
4043
4044
4045
4046
4047
4048
4049
4050
4051
4052
4053
4054
4055
4056
4057
4058
4059
4060
4061
4062
4063
4064
4065
4066
4067
4068
4069
4070
4071
4072
4073
4074
4075
4076
4077
4078
4079
4080
4081
4082
4083
4084
4085
4086
4087
4088
4089
4090
4091
4092
4093
4094
4095
4096
4097
4098
4099
4100
4101
4102
4103
4104
4105
4106
4107
4108
4109
4110
4111
4112
4113
4114
4115
4116
4117
4118
4119
4120
4121
4122
4123
4124
4125
4126
4127
4128
4129
4130
4131
4132
4133
4134
4135
4136
4137
4138
4139
4140
4141
4142
4143
4144
4145
4146
4147
4148
4149
4150
4151
4152
4153
4154
4155
4156
4157
4158
4159
4160
4161
4162
4163
4164
4165
4166
4167
4168
4169
4170
4171
4172
4173
4174
4175
4176
4177
4178
4179
4180
4181
4182
4183
4184
4185
4186
4187
4188
4189
4190
4191
4192
4193
4194
4195
4196
4197
4198
4199
4200
4201
4202
4203
4204
4205
4206
4207
4208
4209
4210
4211
4212
4213
4214
4215
4216
4217
4218
4219
4220
4221
4222
4223
4224
4225
4226
4227
4228
4229
4230
4231
4232
4233
4234
4235
4236
4237
4238
4239
4240
4241
4242
4243
4244
4245
4246
4247
4248
4249
4250
4251
4252
4253
4254
4255
4256
4257
4258
4259
4260
4261
4262
4263
4264
4265
4266
4267
4268
4269
4270
4271
4272
4273
4274
4275
4276
4277
4278
4279
4280
4281
4282
4283
4284
4285
4286
4287
4288
4289
4290
4291
4292
4293
4294
4295
4296
4297
4298
4299
4300
4301
4302
4303
4304
4305
4306
4307
4308
4309
4310
4311
4312
4313
4314
4315
4316
4317
4318
4319
4320
4321
4322
4323
4324
4325
4326
4327
4328
4329
4330
4331
4332
4333
4334
4335
4336
4337
4338
4339
4340
4341
4342
4343
4344
4345
4346
4347
4348
4349
4350
4351
4352
4353
4354
4355
4356
4357
4358
4359
4360
4361
4362
4363
4364
4365
4366
4367
4368
4369
4370
4371
4372
4373
4374
4375
4376
4377
4378
4379
4380
4381
4382
4383
4384
4385
4386
4387
4388
4389
4390
4391
4392
4393
4394
4395
4396
4397
4398
4399
4400
4401
4402
4403
4404
4405
4406
4407
4408
4409
4410
4411
4412
4413
4414
4415
4416
4417
4418
4419
4420
4421
4422
4423
4424
4425
4426
4427
4428
4429
4430
4431
4432
4433
4434
4435
4436
4437
4438
4439
4440
4441
4442
4443
4444
4445
4446
4447
4448
4449
4450
4451
4452
4453
4454
4455
4456
4457
4458
4459
4460
4461
4462
4463
4464
4465
4466
4467
4468
4469
4470
4471
4472
4473
4474
4475
4476
4477
4478
4479
4480
4481
4482
4483
4484
4485
4486
4487
4488
4489
4490
4491
4492
4493
4494
4495
4496
4497
4498
4499
4500
4501
4502
4503
4504
4505
4506
4507
4508
4509
4510
4511
4512
4513
4514
4515
4516
4517
4518
4519
4520
4521
4522
4523
4524
4525
4526
4527
4528
4529
4530
4531
4532
4533
4534
4535
4536
4537
4538
4539
4540
4541
4542
4543
4544
4545
4546
4547
4548
4549
4550
4551
4552
4553
4554
4555
4556
4557
4558
4559
4560
4561
4562
4563
4564
4565
4566
4567
4568
4569
4570
4571
4572
4573
4574
4575
4576
4577
4578
4579
4580
4581
4582
4583
4584
4585
4586
4587
4588
4589
4590
4591
4592
4593
4594
4595
4596
4597
4598
4599
4600
4601
4602
4603
4604
4605
4606
4607
4608
4609
4610
4611
4612
4613
4614
4615
4616
4617
4618
4619
4620
4621
4622
4623
4624
4625
4626
4627
4628
4629
4630
4631
4632
4633
4634
4635
4636
4637
4638
4639
4640
4641
4642
4643
4644
4645
4646
4647
4648
4649
4650
4651
4652
4653
4654
4655
4656
4657
4658
4659
4660
4661
4662
4663
4664
4665
4666
4667
4668
4669
4670
4671
4672
4673
4674
4675
4676
4677
4678
4679
4680
4681
4682
4683
4684
4685
4686
4687
4688
4689
4690
4691
4692
4693
4694
4695
4696
4697
4698
4699
4700
4701
4702
4703
4704
4705
4706
4707
4708
4709
4710
4711
4712
4713
4714
4715
4716
4717
4718
4719
4720
4721
4722
4723
4724
4725
4726
4727
4728
4729
4730
4731
4732
4733
4734
4735
4736
4737
4738
4739
4740
4741
4742
4743
4744
4745
4746
4747
4748
4749
4750
4751
4752
4753
4754
4755
4756
4757
4758
4759
4760
4761
4762
4763
4764
4765
4766
4767
4768
4769
4770
4771
4772
4773
4774
4775
4776
4777
4778
4779
4780
4781
4782
4783
4784
4785
4786
4787
4788
4789
4790
4791
4792
4793
4794
4795
4796
4797
4798
4799
4800
4801
4802
4803
4804
4805
4806
4807
4808
4809
4810
4811
4812
4813
4814
4815
4816
4817
4818
4819
4820
4821
4822
4823
4824
4825
4826
4827
4828
4829
4830
4831
4832
4833
4834
4835
4836
4837
4838
4839
4840
4841
4842
4843
4844
4845
4846
4847
4848
4849
4850
4851
4852
4853
4854
4855
4856
4857
4858
4859
4860
4861
4862
4863
4864
4865
4866
4867
4868
4869
4870
4871
4872
4873
4874
4875
4876
4877
4878
4879
4880
4881
4882
4883
4884
4885
4886
4887
4888
4889
4890
4891
4892
4893
4894
4895
4896
4897
4898
4899
4900
4901
4902
4903
4904
4905
4906
4907
4908
4909
4910
4911
4912
4913
4914
4915
4916
4917
4918
4919
4920
4921
4922
4923
4924
4925
4926
4927
4928
4929
4930
4931
4932
4933
4934
4935
4936
4937
4938
4939
4940
4941
4942
4943
4944
4945
4946
4947
4948
4949
4950
4951
4952
4953
4954
4955
4956
4957
4958
4959
4960
4961
4962
4963
4964
4965
4966
4967
4968
4969
4970
4971
4972
4973
4974
4975
4976
4977
4978
4979
4980
4981
4982
4983
4984
4985
4986
4987
4988
4989
4990
4991
4992
4993
4994
4995
4996
4997
4998
4999
5000
5001
5002
5003
5004
5005
5006
5007
5008
5009
5010
5011
5012
5013
5014
5015
5016
5017
5018
5019
5020
5021
5022
5023
5024
5025
5026
5027
5028
5029
5030
5031
5032
5033
5034
5035
5036
5037
5038
5039
5040
5041
5042
5043
5044
5045
5046
5047
5048
5049
5050
5051
5052
5053
5054
5055
5056
5057
5058
5059
5060
5061
5062
5063
5064
5065
5066
5067
5068
5069
5070
5071
5072
5073
5074
5075
5076
5077
5078
5079
5080
5081
5082
5083
5084
5085
5086
5087
5088
5089
5090
5091
5092
5093
5094
5095
5096
5097
5098
5099
5100
5101
5102
5103
5104
5105
5106
5107
5108
5109
5110
5111
5112
5113
5114
5115
5116
5117
5118
5119
5120
5121
5122
5123
5124
5125
5126
5127
5128
5129
5130
5131
5132
5133
5134
5135
5136
5137
5138
5139
5140
5141
5142

5143
5144
5145
5146
5147
5148
5149
5150
5151
5152
5153
5154
5155
5156
5157
5158
5159
5160
5161
5162
5163
5164
5165
5166
5167
5168
5169
5170
5171
5172
5173
5174
5175
5176
5177
5178
5179
5180
5181
5182
5183
5184
5185
5186
5187
5188
5189
5190
5191
5192
5193
5194
5195
5196
5197
5198
5199
5200
5201
5202
5203
5204
5205
5206
5207
5208
5209
5210
5211
5212
5213
5214
5215
5216
5217
5218
5219
5220
5221
5222
5223
5224
5225
5226
5227
5228
5229
5230
5231
5232
5233
5234
5235
5236
5237
5238
5239
5240
5241
5242
5243
5244
5245
5246
5247
5248
5249
5250
5251
5252
5253
5254
5255
5256
5257
5258
5259
5260
5261
5262
5263
5264
5265
5266
5267
5268
5269
5270
5271
5272
5273
5274
5275
5276
5277
5278
5279
5280
5281
5282
5283
5284
5285
5286
5287
5288
5289
5290
5291
5292
5293
5294
5295
5296
5297
5298
5299
5300
5301
5302
5303
5304
5305
5306
5307
5308
5309
5310
5311
5312
5313
5314
5315
5316
5317
5318
5319
5320
5321
5322
5323
5324
5325
5326
5327
5328
5329
5330
5331
5332
5333
5334
5335
5336
5337
5338
5339
5340
5341
5342
5343
5344
5345
5346
5347
5348
5349
5350
5351
5352
5353
5354
5355
5356
5357
5358
5359
5360
5361
5362
5363
5364
5365
5366
5367
5368
5369
5370
5371
5372
5373
5374
5375
5376
5377
5378
5379
5380
5381
5382
5383
5384
5385
5386
5387
5388
5389
5390
5391
5392
5393
5394
5395
5396
5397
5398
5399
5400
5401
5402
5403
5404
5405
5406
5407
5408
5409
5410
5411
5412
5413
5414
5415
5416
5417
5418
5419
5420
5421
5422
5423
5424
5425
5426
5427
5428
5429
5430
5431
5432
5433
5434
5435
5436
5437
5438
5439
5440
5441
5442
5443
5444
5445
5446
5447
5448
5449
5450
5451
5452
5453
5454
5455
5456
5457
5458
5459
5460
5461
5462
5463
5464
5465
5466
5467
5468
5469
5470
5471
5472
5473
5474
5475
5476
5477
5478
5479
5480
5481
5482
5483
5484
5485
5486
5487
5488
5489
5490
5491
5492
5493
5494
5495
5496
5497
5498
5499
5500
5501
5502
5503
5504
5505
5506
5507
5508
5509
5510
5511
5512
5513
5514
5515
5516
5517
5518
5519
5520
5521
5522
5523
5524
5525
5526
5527
5528
5529
5530
5531
5532
5533
5534
5535
5536
5537
5538
5539
5540
5541
5542
5543
5544
5545
5546
5547
5548
5549
5550
5551
5552
5553
5554
5555
5556
5557
5558
5559
5560
5561
5562
5563
5564
5565
5566
5567
5568
5569
5570
5571
5572
5573
5574
5575
5576
5577
5578
5579
5580
5581
5582
5583
5584
5585
5586
5587
5588
5589
5590
5591
5592
5593
5594
5595
5596
5597
5598
5599
5600
5601
5602
5603
5604
5605
5606
5607
5608
5609
5610
5611
5612
5613
5614
5615
5616
5617
5618
5619
5620
5621
5622
5623
5624
5625
5626
5627
5628
5629
5630
5631
5632
5633
5634
5635
5636
5637
5638
5639
5640
5641
5642
5643
5644
5645
5646
5647
5648
5649
5650
5651
5652
5653
5654
5655
5656
5657
5658
5659
5660
5661
5662
5663
5664
5665
5666
5667
5668
5669
5670
5671
5672
5673
5674
5675
5676
5677
5678
5679
5680
5681
5682
5683
5684
5685
5686
5687
5688
5689
5690
5691
5692
5693
5694
5695
5696
5697
5698
5699
5700
5701
5702
5703
5704
5705
5706
5707
5708
5709
5710
5711
5712
5713
5714
5715
5716
5717
5718
5719
5720
5721
5722
5723
5724
5725
5726
5727
5728
5729
5730
5731
5732
5733
5734
5735
5736
5737
5738
5739
5740
5741
5742
5743
5744
5745
5746
5747
5748
5749
5750
5751
5752
5753
5754
5755
5756
5757
5758
5759
5760
5761
5762
5763
5764
5765
5766
5767
5768
5769
5770
5771
5772
5773
5774
5775
5776
5777
5778
5779
5780
5781
5782
5783
5784
5785
5786
5787
5788
5789
5790
5791
5792
5793
5794
5795
5796
5797
5798
5799
5800
5801
5802
5803
5804
5805
5806
5807
5808
5809
5810
5811
5812
5813
5814
5815
5816
5817
5818
5819
5820
5821
5822
5823
5824
5825
5826
5827
5828
5829
5830
5831
5832
5833
5834
5835
5836
5837
5838
5839
5840
5841
5842
5843
5844
5845
5846
5847
5848
5849
5850
5851
5852
5853
5854
5855
5856
5857
5858
5859
5860
5861
5862
5863
5864
5865
5866
5867
5868
5869
5870
5871
5872
5873
5874
5875
5876
5877
5878
5879
5880
5881
5882
5883
5884
5885
5886
5887
5888
5889
5890
5891
5892
5893
5894
5895
5896
5897
5898
5899
5900
5901
5902
5903
5904
5905
5906
5907
5908
5909
5910
5911
5912
5913
5914
5915
5916
5917
5918
5919
5920
5921
5922
5923
5924
5925
5926
5927
5928
5929
5930
5931
5932
5933
5934
5935
5936
5937
5938
5939
5940
5941
5942
5943
5944
5945
5946
5947
5948
5949
5950
5951
5952
5953
5954
5955
5956
5957
5958
5959
5960
5961
5962
5963
5964
5965
5966
5967
5968
5969
5970
5971
5972
5973
5974
5975
5976
5977
5978
5979
5980
5981
5982
5983
5984
5985
5986
5987
5988
5989
5990
5991
5992
5993
5994
5995
5996
5997
5998
5999
6000
6001
6002
6003
6004
6005
6006
6007
6008
6009
6010
6011
6012
6013
6014
6015
6016
6017
6018
6019
6020
6021
6022
6023
6024
6025
6026
6027
6028
6029
6030
6031
6032
6033
6034
6035
6036
6037
6038
6039
6040
6041
6042
6043
6044
6045
6046
6047
6048
6049
6050
6051
6052
6053
6054
6055
6056
6057
6058
6059
6060
6061
6062
6063
6064
6065
6066
6067
6068
6069
6070
6071
6072
6073
6074
6075
6076
6077
6078
6079
6080
6081
6082
6083
6084
6085
6086
6087
6088
6089
6090
6091
6092
6093
6094
6095
6096
6097
6098
6099
6100
6101
6102
6103
6104
6105
6106
6107
6108
6109
6110
6111
6112
6113
6114
6115
6116
6117
6118
6119
6120
6121
6122
6123
6124
6125
6126
6127
6128
6129
6130
6131
6132
6133
6134
6135
6136
6137
6138
6139
6140
6141
6142
6143
6144
6145
6146
6147
6148
6149
6150
6151
6152
6153
6154
6155
6156
6157
6158
6159
6160
6161
6162
6163
6164
6165
6166
6167
6168
6169
6170
6171
6172
6173
6174
6175
6176
6177
6178
6179
6180
6181
6182
6183
6184
6185
6186
6187
6188
6189
6190
6191
6192
6193
6194
6195
6196
6197
6198
6199
6200
6201
6202
6203
6204
6205
6206
6207
6208
6209
6210
6211
6212
6213
6214
6215
6216
6217
6218
6219
6220
6221
6222
6223
6224
6225
6226
6227
6228
6229
6230
6231
6232
6233
6234
6235
6236
6237
6238
6239
6240
6241
6242
6243
6244
6245
6246
6247
6248
6249
6250
6251
6252
6253
6254
6255
6256
6257
6258
6259
6260
6261
6262
6263
6264
6265
6266
6267
6268
6269
6270
6271
6272
6273
6274
6275
6276
6277
6278
6279
6280
6281
6282
6283
6284
6285
6286
6287
6288
6289
6290
6291
6292
6293
6294
6295
6296
6297
6298
6299
6300
6301
6302
6303
6304
6305
6306
6307
6308
6309
6310
6311
6312
6313
6314
6315
6316
6317
6318
6319
6320
6321
6322
6323
6324
6325
6326
6327
6328
6329
6330
6331
6332
6333
6334
6335
6336
6337
6338
6339
6340
6341
6342
6343
6344
6345
6346
6347
6348
6349
6350
6351
6352
6353
6354
6355
6356
6357
6358
6359
6360
6361
6362
6363
6364
6365
6366
6367
6368
6369
6370
6371
6372
6373
6374
6375
6376
6377
6378
6379
6380
6381
6382
6383
6384
6385
6386
6387
6388
6389
6390
6391
6392
6393
6394
6395
6396
6397
6398
6399
6400
6401
6402
6403
6404
6405
6406
6407
6408
6409
6410
6411
6412
6413
6414
6415
6416
6417
6418
6419
6420
6421
6422
6423
6424
6425
6426
6427
6428
6429
6430
6431
6432
6433
6434
6435
6436
6437
6438
6439
6440
6441
6442
6443
6444
6445
6446
6447
6448
6449
6450
6451
6452
6453
6454
6455
6456
6457
6458
6459
6460
6461
6462
6463
6464
6465
6466
6467
6468
6469
6470
6471
6472
6473
6474
6475
6476
6477
6478
6479
6480
6481
6482
6483
6484
6485
6486
6487
6488
6489
6490
6491
6492
6493
6494
6495
6496
6497
6498
6499
6500
6501
6502
6503
6504
6505
6506
6507
6508
6509
6510
6511
6512
6513
6514
6515
6516
6517
6518
6519
6520
6521
6522
6523
6524
6525
6526
6527
6528
6529
6530
6531
6532
6533
6534
6535
6536
6537
6538
6539
6540
6541
6542
6543
6544
6545
6546
6547
6548
6549
6550
6551
6552
6553
6554
6555
6556
6557
6558
6559
6560
6561
6562
6563
6564
6565
6566
6567
6568
6569
6570
6571
6572
6573
6574
6575
6576
6577
6578
6579
6580
6581
6582
6583
6584
6585
6586
6587
6588
6589
6590
6591
6592
6593
6594
6595
6596
6597
6598
6599
6600
6601
6602
6603
6604
6605
6606
6607
6608
6609
6610
6611
6612
6613
6614
6615
6616
6617
6618
6619
6620
6621
6622
6623
6624
6625
6626
6627
6628
6629
6630
6631
6632
6633
6634
6635
6636
6637
6638
6639
6640
6641
6642
6643
6644
6645
6646
6647
6648
6649
6650
6651
6652
6653
6654
6655
6656
6657
6658
6659
6660
6661
6662
6663
6664
6665
6666
6667
6668
6669
6670
6671
6672
6673
6674
6675
6676
6677
6678
6679
6680
6681
6682
6683
6684
6685
6686
6687
6688
6689
6690
6691
6692
6693
6694
6695
6696
6697
6698
6699
6700
6701
6702
6703
6704
6705
6706
6707
6708
6709
6710
6711
6712
6713
6714
6715
6716
6717
6718
6719
6720
6721
6722
6723
6724
6725
6726
6727
6728
6729
6730
6731
6732
6733
6734
6735
6736
6737
6738
6739
6740
6741
6742
6743
6744
6745
6746
6747
6748
6749
6750
6751
6752
6753
6754
6755
6756
6757
6758
6759
6760
6761
6762
6763
6764
6765
6766
6767
6768
6769
6770
6771
6772
6773
6774
6775
6776
6777
6778
6779
6780
6781
6782
6783

6784
6785
6786
6787
6788
6789
6790
6791
6792
6793
6794
6795
6796
6797
6798
6799
6800
6801
6802
6803
6804
6805
6806
6807
6808
6809
6810
6811
6812
6813
6814
6815
6816
6817
6818
6819
6820
6821
6822
6823
6824
6825
6826
6827
6828
6829
6830
6831
6832
6833
6834
6835
6836
6837
6838
6839
6840
6841
6842
6843
6844
6845
6846
6847
6848
6849
6850
6851
6852
6853
6854
6855
6856
6857
6858
6859
6860
6861
6862
6863
6864
6865
6866
6867
6868
6869
6870
6871
6872
6873
6874
6875
6876
6877
6878
6879
6880
6881
6882
6883
6884
6885
6886
6887
6888
6889
6890
6891
6892
6893
6894
6895
6896
6897
6898
6899
6900
6901
6902
6903
6904
6905
6906
6907
6908
6909
6910
6911
6912
6913
6914
6915
6916
6917
6918
6919
6920
6921
6922
6923
6924
6925
6926
6927
6928
6929
6930
6931
6932
6933
6934
6935
6936
6937
6938
6939
6940
6941
6942
6943
6944
6945
6946
6947
6948
6949
6950
6951
6952
6953
6954
6955
6956
6957
6958
6959
6960
6961
6962
6963
6964
6965
6966
6967
6968
6969
6970
6971
6972
6973
6974
6975
6976
6977
6978
6979
6980
6981
6982
6983
6984
6985
6986
6987
6988
6989
6990
6991
6992
6993
6994
6995
6996
6997
6998
6999
7000
7001
7002
7003
7004
7005
7006
7007
7008
7009
7010
7011
7012
7013
7014
7015
7016
7017
7018
7019
7020
7021
7022
7023
7024
7025
7026
7027
7028
7029
7030
7031
7032
7033
7034
7035
7036
7037
7038
7039
7040
7041
7042
7043
7044
7045
7046
7047
7048
7049
7050
7051
7052
7053
7054
7055
7056
7057
7058
7059
7060
7061
7062
7063
7064
7065
7066
7067
7068
7069
7070
7071
7072
7073
7074
7075
7076
7077
7078
7079
7080
7081
7082
7083
7084
7085
7086
7087
7088
7089
7090
7091
7092
7093
7094
7095
7096
7097
7098
7099
7100
7101
7102
7103
7104
7105
7106
7107
7108
7109
7110
7111
7112
7113
7114
7115
7116
7117
7118
7119
7120
7121
7122
7123
7124
7125
7126
7127
7128
7129
7130
7131
7132
7133
7134
7135
7136
7137
7138
7139
7140
7141
7142
7143
7144
7145
7146
7147
7148
7149
7150
7151
7152
7153
7154
7155
7156
7157
7158
7159
7160
7161
7162
7163
7164
7165
7166
7167
7168
7169
7170
7171
7172
7173
7174
7175
7176
7177
7178
7179
7180
7181
7182
7183
7184
7185
7186
7187
7188
7189
7190
7191
7192
7193
7194
7195
7196
7197
7198
7199
7200
7201
7202
7203
7204
7205
7206
7207
7208
7209
7210
7211
7212
7213
7214
7215
7216
7217
7218
7219
7220
7221
7222
7223
7224
7225
7226
7227
7228
7229
7230
7231
7232
7233
7234
7235
7236
7237
7238
7239
7240
7241
7242
7243
7244
7245
7246
7247
7248
7249
7250
7251
7252
7253
7254
7255
7256
7257
7258
7259
7260
7261
7262
7263
7264
7265
7266
7267
7268
7269
7270
7271
7272
7273
7274
7275
7276
7277
7278
7279
7280
7281
7282
7283
7284
7285
7286
7287
7288
7289
7290
7291
7292
7293
7294
7295
7296
7297
7298
7299
7300
7301
7302
7303
7304
7305
7306
7307
7308
7309
7310
7311
7312
7313
7314
7315
7316
7317
7318
7319
7320
7321
7322
7323
7324
7325
7326
7327
7328
7329
7330
7331
7332
7333
7334
7335
7336
7337
7338
7339
7340
7341
7342
7343
7344
7345
7346
7347
7348
7349
7350
7351
7352
7353
7354
7355
7356
7357
7358
7359
7360
7361
7362
7363
7364
7365
7366
7367
7368
7369
7370
7371
7372
7373
7374
7375
7376
7377
7378
7379
7380
7381
7382
7383
7384
7385
7386
7387
7388
7389
7390
7391
7392
7393
7394
7395
7396
7397
7398
7399
7400
7401
7402
7403
7404
7405
7406
7407
7408
7409
7410
7411
7412
7413
7414
7415
7416
7417
7418
7419
7420
7421
7422
7423
7424
7425
7426
7427
7428
7429
7430
7431
7432
7433
7434
7435
7436
7437
7438
7439
7440
7441
7442
7443
7444
7445
7446
7447
7448
7449
7450
7451
7452
7453
7454
7455
7456
7457
7458
7459
7460
7461
7462
7463
7464
7465
7466
7467
7468
7469
7470
7471
7472
7473
7474
7475
7476
7477
7478
7479
7480
7481
7482
7483
7484
7485
7486
7487
7488
7489
7490
7491
7492
7493
7494
7495
7496
7497
7498
7499
7500
7501
7502
7503
7504
7505
7506
7507
7508
7509
7510
7511
7512
7513
7514
7515
7516
7517
7518
7519
7520
7521
7522
7523
7524
7525
7526
7527
7528
7529
7530
7531
7532
7533
7534
7535
7536
7537
7538
7539
7540
7541
7542
7543
7544
7545
7546
7547
7548
7549
7550
7551
7552
7553
7554
7555
7556
7557
7558
7559
7560
7561
7562
7563
7564
7565
7566
7567
7568
7569
7570
7571
7572
7573
7574
7575
7576
7577
7578
7579
7580
7581
7582
7583
7584
7585
7586
7587
7588
7589
7590
7591
7592
7593
7594
7595
7596
7597
7598
7599
7600
7601
7602
7603
7604
7605
7606
7607
7608
7609
7610
7611
7612
7613
7614
7615
7616
7617
7618
7619
7620
7621
7622
7623
7624
7625
7626
7627
7628
7629
7630
7631
7632
7633
7634
7635
7636
7637
7638
7639
7640
7641
7642
7643
7644
7645
7646
7647
7648
7649
7650
7651
7652
7653
7654
7655
7656
7657
7658
7659
7660
7661
7662
7663
7664
7665
7666
7667
7668
7669
7670
7671
7672
7673
7674
7675
7676
7677
7678
7679
7680
7681
7682
7683
7684
7685
7686
7687
7688
7689
7690
7691
7692
7693
7694
7695
7696
7697
7698
7699
7700
7701
7702
7703
7704
7705
7706
7707
7708
7709
7710
7711
7712
7713
7714
7715
7716
7717
7718
7719
7720
7721
7722
7723
7724
7725
7726
7727
7728
7729
7730
7731
7732
7733
7734
7735
7736
7737
7738
7739
7740
7741
7742
7743
7744
7745
7746
7747
7748
7749
7750
7751
7752
7753
7754
7755
7756
7757
7758
7759
7760
7761
7762
7763
7764
7765
7766
7767
7768
7769
7770
7771
7772
7773
7774
7775
7776
7777
7778
7779
7780
7781
7782
7783
7784
7785
7786
7787
7788
7789
7790
7791
7792
7793
7794
7795
7796
7797
7798
7799
7800
7801
7802
7803
7804
7805
7806
7807
7808
7809
7810
7811
7812
7813
7814
7815
7816
7817
7818
7819
7820
7821
7822
7823
7824
7825
7826
7827
7828
7829
7830
7831
7832
7833
7834
7835
7836
7837
7838
7839
7840
7841
7842
7843
7844
7845
7846
7847
7848
7849
7850
7851
7852
7853
7854
7855
7856
7857
7858
7859
7860
7861
7862
7863
7864
7865
7866
7867
7868
7869
7870
7871
7872
7873
7874
7875
7876
7877
7878
7879
7880
7881
7882
7883
7884
7885
7886
7887
7888
7889
7890
7891
7892
7893
7894
7895
7896
7897
7898
7899
7900
7901
7902
7903
7904
7905
7906
7907
7908
7909
7910
7911
7912
7913
7914
7915
7916
7917
7918
7919
7920
7921
7922
7923
7924
7925
7926
7927
7928
7929
7930
7931
7932
7933
7934
7935
7936
7937
7938
7939
7940
7941
7942
7943
7944
7945
7946
7947
7948
7949
7950
7951
7952
7953
7954
7955
7956
7957
7958
7959
7960
7961
7962
7963
7964
7965
7966
7967
7968
7969
7970
7971
7972
7973
7974
7975
7976
7977
7978
7979
7980
7981
7982
7983
7984
7985
7986
7987
7988
7989
7990
7991
7992
7993
7994
7995
7996
7997
7998
7999
8000
8001
8002
8003
8004
8005
8006
8007
8008
8009
8010
8011
8012
8013
8014
8015
8016
8017
8018
8019
8020
8021
8022
8023
8024
8025
8026
8027
8028
8029
8030
8031
8032
8033
8034
8035
8036
8037
8038
8039
8040
8041
8042
8043
8044
8045
8046
8047
8048
8049
8050
8051
8052
8053
8054
8055
8056
8057
8058
8059
8060
8061
8062
8063
8064
8065
8066
8067
8068
8069
8070
8071
8072
8073
8074
8075
8076
8077
8078
8079
8080
8081
8082
8083
8084
8085
8086
8087
8088
8089
8090
8091
8092
8093
8094
8095
8096
8097
8098
8099
8100
8101
8102
8103
8104
8105
8106
8107
8108
8109
8110
8111
8112
8113
8114
8115
8116
8117
8118
8119
8120
8121
8122
8123
8124
8125
8126
8127
8128
8129
8130
8131
8132
8133
8134
8135
8136
8137
8138
8139
8140
8141
8142
8143
8144
8145
8146
8147
8148
8149
8150
8151
8152
8153
8154
8155
8156
8157
8158
8159
8160
8161
8162
8163
8164
8165
8166
8167
8168
8169
8170
8171
8172
8173
8174
8175
8176
8177
8178
8179
8180
8181
8182
8183
8184
8185
8186
8187
8188
8189
8190
8191
8192
8193
8194
8195
8196
8197
8198
8199
8200
8201
8202
8203
8204
8205
8206
8207
8208
8209
8210
8211
8212
8213
8214
8215
8216
8217
8218
8219
8220
8221
8222
8223
8224
8225
8226
8227
8228
8229
8230
8231
8232
8233
8234
8235
8236
8237
8238
8239
8240
8241
8242
8243
8244
8245
8246
8247
8248
8249
8250
8251
8252
8253
8254
8255
8256
8257
8258
8259
8260
8261
8262
8263
8264
8265
8266
8267
8268
8269
8270
8271
8272
8273
8274
8275
8276
8277
8278
8279
8280
8281
8282
8283
8284
8285
8286
8287
8288
8289
8290
8291
8292
8293
8294
8295
8296
8297
8298
8299
8300
8301
8302
8303
8304
8305
8306
8307
8308
8309
8310
8311
8312
8313
8314
8315
8316
8317
8318
8319
8320
8321
8322
8323
8324
8325
8326
8327
8328
8329
8330
8331
8332
8333
8334
8335
8336
8337
8338
8339
8340
8341
8342
8343
8344
8345
8346
8347
8348
8349
8350
8351
8352
8353
8354
8355
8356
8357
8358
8359
8360
8361
8362
8363
8364
8365
8366
8367
8368
8369
8370
8371
8372
8373
8374
8375
8376
8377
8378
8379
8380
8381
8382
8383
8384
8385
8386
8387
8388
8389
8390
8391
8392
8393
8394
8395
8396
8397
8398
8399
8400
8401
8402
8403
8404
8405
8406
8407
8408
8409
8410
8411
8412
8413
8414
8415
8416
8417
8418
8419
8420
8421
8422
8423
8424
8425

8426
8427
8428
8429
8430
8431
8432
8433
8434
8435
8436
8437
8438
8439
8440
8441
8442
8443
8444
8445
8446
8447
8448
8449
8450
8451
8452
8453
8454
8455
8456
8457
8458
8459
8460
8461
8462
8463
8464
8465
8466
8467
8468
8469
8470
8471
8472
8473
8474
8475
8476
8477
8478
8479
8480
8481
8482
8483
8484
8485
8486
8487
8488
8489
8490
8491
8492
8493
8494
8495
8496
8497
8498
8499
8500
8501
8502
8503
8504
8505
8506
8507
8508
8509
8510
8511
8512
8513
8514
8515
8516
8517
8518
8519
8520
8521
8522
8523
8524
8525
8526
8527
8528
8529
8530
8531
8532
8533
8534
8535
8536
8537
8538
8539
8540
8541
8542
8543
8544
8545
8546
8547
8548
8549
8550
8551
8552
8553
8554
8555
8556
8557
8558
8559
8560
8561
8562
8563
8564
8565
8566
8567
8568
8569
8570
8571
8572
8573
8574
8575
8576
8577
8578
8579
8580
8581
8582
8583
8584
8585
8586
8587
8588
8589
8590
8591
8592
8593
8594
8595
8596
8597
8598
8599
8600
8601
8602
8603
8604
8605
8606
8607
8608
8609
8610
8611
8612
8613
8614
8615
8616
8617
8618
8619
8620
8621
8622
8623
8624
8625
8626
8627
8628
8629
8630
8631
8632
8633
8634
8635
8636
8637
8638
8639
8640
8641
8642
8643
8644
8645
8646
8647
8648
8649
8650
8651
8652
8653
8654
8655
8656
8657
8658
8659
8660
8661
8662
8663
8664
8665
8666
8667
8668
8669
8670
8671
8672
8673
8674
8675
8676
8677
8678
8679
8680
8681
8682
8683
8684
8685
8686
8687
8688
8689
8690
8691
8692
8693
8694
8695
8696
8697
8698
8699
8700
8701
8702
8703
8704
8705
8706
8707
8708
8709
8710
8711
8712
8713
8714
8715
8716
8717
8718
8719
8720
8721
8722
8723
8724
8725
8726
8727
8728
8729
8730
8731
8732
8733
8734
8735
8736
8737
8738
8739
8740
8741
8742
8743
8744
8745
8746
8747
8748
8749
8750
8751
8752
8753
8754
8755
8756
8757
8758
8759
8760
8761
8762
8763
8764
8765
8766
8767
8768
8769
8770
8771
8772
8773
8774
8775
8776
8777
8778
8779
8780
8781
8782
8783
8784
8785
8786
8787
8788
8789
8790
8791
8792
8793
8794
8795
8796
8797
8798
8799
8800
8801
8802
8803
8804
8805
8806
8807
8808
8809
8810
8811
8812
8813
8814
8815
8816
8817
8818
8819
8820
8821
8822
8823
8824
8825
8826
8827
8828
8829
8830
8831
8832
8833
8834
8835
8836
8837
8838
8839
8840
8841
8842
8843
8844
8845
8846
8847
8848
8849
8850
8851
8852
8853
8854
8855
8856
8857
8858
8859
8860
8861
8862
8863
8864
8865
8866
8867
8868
8869
8870
8871
8872
8873
8874
8875
8876
8877
8878
8879
8880
8881
8882
8883
8884
8885
8886
8887
8888
8889
8890
8891
8892
8893
8894
8895
8896
8897
8898
8899
8900
8901
8902
8903
8904
8905
8906
8907
8908
8909
8910
8911
8912
8913
8914
8915
8916
8917
8918
8919
8920
8921
8922
8923
8924
8925
8926
8927
8928
8929
8930
8931
8932
8933
8934
8935
8936
8937
8938
8939
8940
8941
8942
8943
8944
8945
8946
8947
8948
8949
8950
8951
8952
8953
8954
8955
8956
8957
8958
8959
8960
8961
8962
8963
8964
8965
8966
8967
8968
8969
8970
8971
8972
8973
8974
8975
8976
8977
8978
8979
8980
8981
8982
8983
8984
8985
8986
8987
8988
8989
8990
8991
8992
8993
8994
8995
8996
8997
8998
8999
9000
9001
9002
9003
9004
9005
9006
9007
9008
9009
9010
9011
9012
9013
9014
9015
9016
9017
9018
9019
9020
9021
9022
9023
9024
9025
9026
9027
9028
9029
9030
9031
9032
9033
9034
9035
9036
9037
9038
9039
9040
9041
9042
9043
9044
9045
9046
9047
9048
9049
9050
9051
9052
9053
9054
9055
9056
9057
9058
9059
9060
9061
9062
9063
9064
9065
9066
9067
9068
9069
9070
9071
9072
9073
9074
9075
9076
9077
9078
9079
9080
9081
9082
9083
9084
9085
9086
9087
9088
9089
9090
9091
9092
9093
9094
9095
9096
9097
9098
9099
9100
9101
9102
9103
9104
9105
9106
9107
9108
9109
9110
9111
9112
9113
9114
9115
9116
9117
9118
9119
9120
9121
9122
9123
9124
9125
9126
9127
9128
9129
9130
9131
9132
9133
9134
9135
9136
9137
9138
9139
9140
9141
9142
9143
9144
9145
9146
9147
9148
9149
9150
9151
9152
9153
9154
9155
9156
9157
9158
9159
9160
9161
9162
9163
9164
9165
9166
9167
9168
9169
9170
9171
9172
9173
9174
9175
9176
9177
9178
9179
9180
9181
9182
9183
9184
9185
9186
9187
9188
9189
9190
9191
9192
9193
9194
9195
9196
9197
9198
9199
9200
9201
9202
9203
9204
9205
9206
9207
9208
9209
9210
9211
9212
9213
9214
9215
9216
9217
9218
9219
9220
9221
9222
9223
9224
9225
9226
9227
9228
9229
9230
9231
9232
9233
9234
9235
9236
9237
9238
9239
9240
9241
9242
9243
9244
9245
9246
9247
9248
9249
9250
9251
9252
9253
9254
9255
9256
9257
9258
9259
9260
9261
9262
9263
9264
9265
9266
9267
9268
9269
9270
9271
9272
9273
9274
9275
9276
9277
9278
9279
9280
9281
9282
9283
9284
9285
9286
9287
9288
9289
9290
9291
9292
9293
9294
9295
9296
9297
9298
9299
9300
9301
9302
9303
9304
9305
9306
9307
9308
9309
9310
9311
9312
9313
9314
9315
9316
9317
9318
9319
9320
9321
9322
9323
9324
9325
9326
9327
9328
9329
9330
9331
9332
9333
9334
9335
9336
9337
9338
9339
9340
9341
9342
9343
9344
9345
9346
9347
9348
9349
9350
9351
9352
9353
9354
9355
9356
9357
9358
9359
9360
9361
9362
9363
9364
9365
9366
9367
9368
9369
9370
9371
9372
9373
9374
9375
9376
9377
9378
9379
9380
9381
9382
9383
9384
9385
9386
9387
9388
9389
9390
9391
9392
9393
9394
9395
9396
9397
9398
9399
9400
9401
9402
9403
9404
9405
9406
9407
9408
9409
9410
9411
9412
9413
9414
9415
9416
9417
9418
9419
9420
9421
9422
9423
9424
9425
9426
9427
9428
9429
9430
9431
9432
9433
9434
9435
9436
9437
9438
9439
9440
9441
9442
9443
9444
9445
9446
9447
9448
9449
9450
9451
9452
9453
9454
9455
9456
9457
9458
9459
9460
9461
9462
9463
9464
9465
9466
9467
9468
9469
9470
9471
9472
9473
9474
9475
9476
9477
9478
9479
9480
9481
9482
9483
9484
9485
9486
9487
9488
9489
9490
9491
9492
9493
9494
9495
9496
9497
9498
9499
9500
9501
9502
9503
9504
9505
9506
9507
9508
9509
9510
9511
9512
9513
9514
9515
9516
9517
9518
9519
9520
9521
9522
9523
9524
9525
9526
9527
9528
9529
9530
9531
9532
9533
9534
9535
9536
9537
9538
9539
9540
9541
9542
9543
9544
9545
9546
9547
9548
9549
9550
9551
9552
9553
9554
9555
9556
9557
9558
9559
9560
9561
9562
9563
9564
9565
9566
9567
9568
9569
9570
9571
9572
9573
9574
9575
9576
9577
9578
9579
9580
9581
9582
9583
9584
9585
9586
9587
9588
9589
9590
9591
9592
9593
9594
9595
9596
9597
9598
9599
9600
9601
9602
9603
9604
9605
9606
9607
9608
9609
9610
9611
9612
9613
9614
9615
9616
9617
9618
9619
9620
9621
9622
9623
9624
9625
9626
9627
9628
9629
9630
9631
9632
9633
9634
9635
9636
9637
9638
9639
9640
9641
9642
9643
9644
9645
9646
9647
9648
9649
9650
9651
9652
9653
9654
9655
9656
9657
9658
9659
9660
9661
9662
9663
9664
9665
9666
9667
9668
9669
9670
9671
9672
9673
9674
9675
9676
9677
9678
9679
9680
9681
9682
9683
9684
9685
9686
9687
9688
9689
9690
9691
9692
9693
9694
9695
9696
9697
9698
9699
9700
9701
9702
9703
9704
9705
9706
9707
9708
9709
9710
9711
9712
9713
9714
9715
9716
9717
9718
9719
9720
9721
9722
9723
9724
9725
9726
9727
9728
9729
9730
9731
9732
9733
9734
9735
9736
9737
9738
9739
9740
9741
9742
9743
9744
9745
9746
9747
9748
9749
9750
9751
9752
9753
9754
9755
9756
9757
9758
9759
9760
9761
9762
9763
9764
9765
9766
9767
9768
9769
9770
9771
9772
9773
9774
9775
9776
9777
9778
9779
9780
9781
9782
9783
9784
9785
9786
9787
9788
9789
9790
9791
9792
9793
9794
9795
9796
9797
9798
9799
9800
9801
9802
9803
9804
9805
9806
9807
9808
9809
9810
9811
9812
9813
9814
9815
9816
9817
9818
9819
9820
9821
9822
9823
9824
9825
9826
9827
9828
9829
9830
9831
9832
9833
9834
9835
9836
9837
9838
9839
9840
9841
9842
9843
9844
9845
9846
9847
9848
9849
9850
9851
9852
9853
9854
9855
9856
9857
9858
9859
9860
9861
9862
9863
9864
9865
9866
9867
9868
9869
9870
9871
9872
9873
9874
9875
9876
9877
9878
9879
9880
9881
9882
9883
9884
9885
9886
9887
9888
9889
9890
9891
9892
9893
9894
9895
9896
9897
9898
9899
9900
9901
9902
9903
9904
9905
9906
9907
9908
9909
9910
9911
9912
9913
9914
9915
9916
9917
9918
9919
9920
9921
9922
9923
9924
9925
9926
9927
9928
9929
9930
9931
9932
9933
9934
9935
9936
9937
9938
9939
9940
9941
9942
9943
9944
9945
9946
9947
9948
9949
9950
9951
9952
9953
9954
9955
9956
9957
9958
9959
9960
9961
9962
9963
9964
9965
9966
9967
9968
9969
9970
9971
9972
9973
9974
9975
9976
9977
9978
9979
9980
9981
9982
9983
9984
9985
9986
9987
9988
9989
9990
9991
9992
9993
9994
9995
9996
9997
9998
9999
10000
10001
10002
10003
10004
10005
10006
10007
10008
10009
10010
10011
10012
10013
10014
10015
10016
10017
10018
10019
10020
10021
10022
10023
10024
10025
10026
10027
10028
10029
10030
10031
10032
10033
10034
10035
10036
10037
10038
10039
10040
10041
10042
10043
10044
10045
10046
10047
10048
10049
10050
10051
10052
10053

10054
10055
10056
10057
10058
10059
10060
10061
10062
10063
10064
10065
10066
10067
10068
10069
10070
10071
10072
10073
10074
10075
10076
10077
10078
10079
10080
10081
10082
10083
10084
10085
10086
10087
10088
10089
10090
10091
10092
10093
10094
10095
10096
10097
10098
10099
10100
10101
10102
10103
10104
10105
10106
10107
10108
10109
10110
10111
10112
10113
10114
10115
10116
10117
10118
10119
10120
10121
10122
10123
10124
10125
10126
10127
10128
10129
10130
10131
10132
10133
10134
10135
10136
10137
10138
10139
10140
10141
10142
10143
10144
10145
10146
10147
10148
10149
10150
10151
10152
10153
10154
10155
10156
10157
10158
10159
10160
10161
10162
10163
10164
10165
10166
10167
10168
10169
10170
10171
10172
10173
10174
10175
10176
10177
10178
10179
10180
10181
10182
10183
10184
10185
10186
10187
10188
10189
10190
10191
10192
10193
10194
10195
10196
10197
10198
10199
10200
10201
10202
10203
10204
10205
10206
10207
10208
10209
10210
10211
10212
10213
10214
10215
10216
10217
10218
10219
10220
10221
10222
10223
10224
10225
10226
10227
10228
10229
10230
10231
10232
10233
10234
10235
10236
10237
10238
10239
10240
10241
10242
10243
10244
10245
10246
10247
10248
10249
10250
10251
10252
10253
10254
10255
10256
10257
10258
10259
10260
10261
10262
10263
10264
10265
10266
10267
10268
10269
10270
10271
10272
10273
10274
10275
10276
10277
10278
10279
10280
10281
10282
10283
10284
10285
10286
10287
10288
10289
10290
10291
10292
10293
10294
10295
10296
10297
10298
10299
10300
10301
10302
10303
10304
10305
10306
10307
10308
10309
10310
10311
10312
10313
10314
10315
10316
10317
10318
10319
10320
10321
10322
10323
10324
10325
10326
10327
10328
10329
10330
10331
10332
10333
10334
10335
10336
10337
10338
10339
10340
10341
10342
10343
10344
10345
10346
10347
10348
10349
10350
10351
10352
10353
10354
10355
10356
10357
10358
10359
10360
10361
10362
10363
10364
10365
10366
10367
10368
10369
10370
10371
10372
10373
10374
10375
10376
10377
10378
10379
10380
10381
10382
10383
10384
10385
10386
10387
10388
10389
10390
10391
10392
10393
10394
10395
10396
10397
10398
10399
10400
10401
10402
10403
10404
10405
10406
10407
10408
10409
10410
10411
10412
10413
10414
10415
10416
10417
10418
10419
10420
10421
10422
10423
10424
10425
10426
10427
10428
10429
10430
10431
10432
10433
10434
10435
10436
10437
10438
10439
10440
10441
10442
10443
10444
10445
10446
10447
10448
10449
10450
10451
10452
10453
10454
10455
10456
10457
10458
10459
10460
10461
10462
10463
10464
10465
10466
10467
10468
10469
10470
10471
10472
10473
10474
10475
10476
10477
10478
10479
10480
10481
10482
10483
10484
10485
10486
10487
10488
10489
10490
10491
10492
10493
10494
10495
10496
10497
10498
10499
10500
10501
10502
10503
10504
10505
10506
10507
10508
10509
10510
10511
10512
10513
10514
10515
10516
10517
10518
10519
10520
10521
10522
10523
10524
10525
10526
10527
10528
10529
10530
10531
10532
10533
10534
10535
10536
10537
10538
10539
10540
10541
10542
10543
10544
10545
10546
10547
10548
10549
10550
10551
10552
10553
10554
10555
10556
10557
10558
10559
10560
10561
10562
10563
10564
10565
10566
10567
10568
10569
10570
10571
10572
10573
10574
10575
10576
10577
10578
10579
10580
10581
10582
10583
10584
10585
10586
10587
10588
10589
10590
10591
10592
10593
10594
10595
10596
10597
10598
10599
10600
10601
10602
10603
10604
10605
10606
10607
10608
10609
10610
10611
10612
10613
10614
10615
10616
10617
10618
10619
10620
10621
10622
10623
10624
10625
10626
10627
10628
10629
10630
10631
10632
10633
10634
10635
10636
10637
10638
10639
10640
10641
10642
10643
10644
10645
10646
10647
10648
10649
10650
10651
10652
10653
10654
10655
10656
10657
10658
10659
10660
10661
10662
10663
10664
10665
10666
10667
10668
10669
10670
10671
10672
10673
10674
10675
10676
10677
10678
10679
10680
10681
10682
10683
10684
10685
10686
10687
10688
10689
10690
10691
10692
10693
10694
10695
10696
10697
10698
10699
10700
10701
10702
10703
10704
10705
10706
10707
10708
10709
10710
10711
10712
10713
10714
10715
10716
10717
10718
10719
10720
10721
10722
10723
10724
10725
10726
10727
10728
10729
10730
10731
10732
10733
10734
10735
10736
10737
10738
10739
10740
10741
10742
10743
10744
10745
10746
10747
10748
10749
10750
10751
10752
10753
10754
10755
10756
10757
10758
10759
10760
10761
10762
10763
10764
10765
10766
10767
10768
10769
10770
10771
10772
10773
10774
10775
10776
10777
10778
10779
10780
10781
10782
10783
10784
10785
10786
10787
10788
10789
10790
10791
10792
10793
10794
10795
10796
10797
10798
10799
10800
10801
10802
10803
10804
10805
10806
10807
10808
10809
10810
10811
10812
10813
10814
10815
10816
10817
10818
10819
10820
10821
10822
10823
10824
10825
10826
10827
10828
10829
10830
10831
10832
10833
10834
10835
10836
10837
10838
10839
10840
10841
10842
10843
10844
10845
10846
10847
10848
10849
10850
10851
10852
10853
10854
10855
10856
10857
10858
10859
10860
10861
10862
10863
10864
10865
10866
10867
10868
10869
10870
10871
10872
10873
10874
10875
10876
10877
10878
10879
10880
10881
10882
10883
10884
10885
10886
10887
10888
10889
10890
10891
10892
10893
10894
10895
10896
10897
10898
10899
10900
10901
10902
10903
10904
10905
10906
10907
10908
10909
10910
10911
10912
10913
10914
10915
10916
10917
10918
10919
10920
10921
10922
10923
10924
10925
10926
10927
10928
10929
10930
10931
10932
10933
10934
10935
10936
10937
10938
10939
10940
10941
10942
10943
10944
10945
10946
10947
10948
10949
10950
10951
10952
10953
10954
10955
10956
10957
10958
10959
10960
10961
10962
10963
10964
10965
10966
10967
10968
10969
10970
10971
10972
10973
10974
10975
10976
10977
10978
10979
10980
10981
10982
10983
10984
10985
10986
10987
10988
10989
10990
10991
10992
10993
10994
10995
10996
10997
10998
10999
11000
11001
11002
11003
11004
11005
11006
11007
11008
11009
11010
11011
11012
11013
11014
11015
11016
11017
11018
11019
11020
11021
11022
11023
11024
11025
11026
11027
11028
11029
11030
11031
11032
11033
11034
11035
11036
11037
11038
11039
11040
11041
11042
11043
11044
11045
11046
11047
11048
11049
11050
11051
11052
11053
11054
11055
11056
11057
11058
11059
11060
11061
11062
11063
11064
11065
11066
11067
11068
11069
11070
11071
11072
11073
11074
11075
11076
11077
11078
11079
11080
11081
11082
11083
11084
11085
11086
11087
11088
11089
11090
11091
11092
11093
11094
11095
11096
11097
11098
11099
11100
11101
11102
11103
11104
11105
11106
11107
11108
11109
11110
11111
11112
11113
11114
11115
11116
11117
11118
11119
11120
11121
11122
11123
11124
11125
11126
11127
11128
11129
11130
11131
11132
11133
11134
11135
11136
11137
11138
11139
11140
11141
11142
11143
11144
11145
11146
11147
11148
11149
11150
11151
11152
11153
11154
11155
11156
11157
11158
11159
11160
11161
11162
11163
11164
11165
11166
11167
11168
11169
11170
11171
11172
11173
11174
11175
11176
11177
11178
11179
11180
11181
11182
11183
11184
11185
11186
11187
11188
11189
11190
11191
11192
11193
11194
11195
11196
11197
11198
11199
11200
11201
11202
11203
11204
11205
11206
11207
11208
11209
11210
11211
11212
11213
11214
11215
11216
11217
11218
11219
11220
11221
11222
11223
11224
11225
11226
11227
11228
11229
11230
11231
11232
11233
11234
11235
11236
11237
11238
11239
11240
11241
11242
11243
11244
11245
11246
11247
11248
11249
11250
11251
11252
11253
11254
11255
11256
11257
11258
11259
11260
11261
11262
11263
11264
11265
11266
11267
11268
11269
11270
11271
11272
11273
11274
11275
11276
11277
11278
11279
11280
11281
11282
11283
11284
11285
11286
11287
11288
11289
11290
11291
11292
11293
11294
11295
11296
11297
11298
11299
11300
11301
11302
11303
11304
11305
11306
11307
11308
11309
11310
11311
11312
11313
11314
11315
11316
11317
11318
11319
11320
11321
11322
11323
11324
11325
11326
11327
11328
11329
11330
11331
11332
11333
11334
11335
11336
11337
11338
11339
11340
11341
11342
11343
11344
11345
11346
11347
11348
11349
11350
11351
11352
11353
11354
11355
11356
11357
11358
11359
11360
11361
11362
11363
11364
11365
11366
11367
11368
11369
11370
11371
11372
11373
11374
11375
11376
11377
11378
11379
11380
11381
11382
11383
11384
11385
11386
11387
11388
11389
11390
11391
11392
11393
11394
11395
11396
11397
11398
11399
11400
11401
11402
11403
11404
11405
11406
11407
11408
11409
11410
11411
11412
11413
11414
11415
11416
11417
11418
11419
11420
11421

11422
11423
11424
11425
11426
11427
11428
11429
11430
11431
11432
11433
11434
11435
11436
11437
11438
11439
11440
11441
11442
11443
11444
11445
11446
11447
11448
11449
11450
11451
11452
11453
11454
11455
11456
11457
11458
11459
11460
11461
11462
11463
11464
11465
11466
11467
11468
11469
11470
11471
11472
11473
11474
11475
11476
11477
11478
11479
11480
11481
11482
11483
11484
11485
11486
11487
11488
11489
11490
11491
11492
11493
11494
11495
11496
11497
11498
11499
11500
11501
11502
11503
11504
11505
11506
11507
11508
11509
11510
11511
11512
11513
11514
11515
11516
11517
11518
11519
11520
11521
11522
11523
11524
11525
11526
11527
11528
11529
11530
11531
11532
11533
11534
11535
11536
11537
11538
11539
11540
11541
11542
11543
11544
11545
11546
11547
11548
11549
11550
11551
11552
11553
11554
11555
11556
11557
11558
11559
11560
11561
11562
11563
11564
11565
11566
11567
11568
11569
11570
11571
11572
11573
11574
11575
11576
11577
11578
11579
11580
11581
11582
11583
11584
11585
11586
11587
11588
11589
11590
11591
11592
11593
11594
11595
11596
11597
11598
11599
11600
11601
11602
11603
11604
11605
11606
11607
11608
11609
11610
11611
11612
11613
11614
11615
11616
11617
11618
11619
11620
11621
11622
11623
11624
11625
11626
11627
11628
11629
11630
11631
11632
11633
11634
11635
11636
11637
11638
11639
11640
11641
11642
11643
11644
11645
11646
11647
11648
11649
11650
11651
11652
11653
11654
11655
11656
11657
11658
11659
11660
11661
11662
11663
11664
11665
11666
11667
11668
11669
11670
11671
11672
11673
11674
11675
11676
11677
11678
11679
11680
11681
11682
11683
11684
11685
11686
11687
11688
11689
11690
11691
11692
11693
11694
11695
11696
11697
11698
11699
11700
11701
11702
11703
11704
11705
11706
11707
11708
11709
11710
11711
11712
11713
11714
11715
11716
11717
11718
11719
11720
11721
11722
11723
11724
11725
11726
11727
11728
11729
11730
11731
11732
11733
11734
11735
11736
11737
11738
11739
11740
11741
11742
11743
11744
11745
11746
11747
11748
11749
11750
11751
11752
11753
11754
11755
11756
11757
11758
11759
11760
11761
11762
11763
11764
11765
11766
11767
11768
11769
11770
11771
11772
11773
11774
11775
11776
11777
11778
11779
11780
11781
11782
11783
11784
11785
11786
11787
11788
11789
11790
11791
11792
11793
11794
11795
11796
11797
11798
11799
11800
11801
11802
11803
11804
11805
11806
11807
11808
11809
11810
11811
11812
11813
11814
11815
11816
11817
11818
11819
11820
11821
11822
11823
11824
11825
11826
11827
11828
11829
11830
11831
11832
11833
11834
11835
11836
11837
11838
11839
11840
11841
11842
11843
11844
11845
11846
11847
11848
11849
11850
11851
11852
11853
11854
11855
11856
11857
11858
11859
11860
11861
11862
11863
11864
11865
11866
11867
11868
11869
11870
11871
11872
11873
11874
11875
11876
11877
11878
11879
11880
11881
11882
11883
11884
11885
11886
11887
11888
11889
11890
11891
11892
11893
11894
11895
11896
11897
11898
11899
11900
11901
11902
11903
11904
11905
11906
11907
11908
11909
11910
11911
11912
11913
11914
11915
11916
11917
11918
11919
11920
11921
11922
11923
11924
11925
11926
11927
11928
11929
11930
11931
11932
11933
11934
11935
11936
11937
11938
11939
11940
11941
11942
11943
11944
11945
11946
11947
11948
11949
11950
11951
11952
11953
11954
11955
11956
11957
11958
11959
11960
11961
11962
11963
11964
11965
11966
11967
11968
11969
11970
11971
11972
11973
11974
11975
11976
11977
11978
11979
11980
11981
11982
11983
11984
11985
11986
11987
11988
11989
11990
11991
11992
11993
11994
11995
11996
11997
11998
11999
12000
12001
12002
12003
12004
12005
12006
12007
12008
12009
12010
12011
12012
12013
12014
12015
12016
12017
12018
12019
12020
12021
12022
12023
12024
12025
12026
12027
12028
12029
12030
12031
12032
12033
12034
12035
12036
12037
12038
12039
12040
12041
12042
12043
12044
12045
12046
12047
12048
12049
12050
12051
12052
12053
12054
12055
12056
12057
12058
12059
12060
12061
12062
12063
12064
12065
12066
12067
12068
12069
12070
12071
12072
12073
12074
12075
12076
12077
12078
12079
12080
12081
12082
12083
12084
12085
12086
12087
12088
12089
12090
12091
12092
12093
12094
12095
12096
12097
12098
12099
12100
12101
12102
12103
12104
12105
12106
12107
12108
12109
12110
12111
12112
12113
12114
12115
12116
12117
12118
12119
12120
12121
12122
12123
12124
12125
12126
12127
12128
12129
12130
12131
12132
12133
12134
12135
12136
12137
12138
12139
12140
12141
12142
12143
12144
12145
12146
12147
12148
12149
12150
12151
12152
12153
12154
12155
12156
12157
12158
12159
12160
12161
12162
12163
12164
12165
12166
12167
12168
12169
12170
12171
12172
12173
12174
12175
12176
12177
12178
12179
12180
12181
12182
12183
12184
12185
12186
12187
12188
12189
12190
12191
12192
12193
12194
12195
12196
12197
12198
12199
12200
12201
12202
12203
12204
12205
12206
12207
12208
12209
12210
12211
12212
12213
12214
12215
12216
12217
12218
12219
12220
12221
12222
12223
12224
12225
12226
12227
12228
12229
12230
12231
12232
12233
12234
12235
12236
12237
12238
12239
12240
12241
12242
12243
12244
12245
12246
12247
12248
12249
12250
12251
12252
12253
12254
12255
12256
12257
12258
12259
12260
12261
12262
12263
12264
12265
12266
12267
12268
12269
12270
12271
12272
12273
12274
12275
12276
12277
12278
12279
12280
12281
12282
12283
12284
12285
12286
12287
12288
12289
12290
12291
12292
12293
12294
12295
12296
12297
12298
12299
12300
12301
12302
12303
12304
12305
12306
12307
12308
12309
12310
12311
12312
12313
12314
12315
12316
12317
12318
12319
12320
12321
12322
12323
12324
12325
12326
12327
12328
12329
12330
12331
12332
12333
12334
12335
12336
12337
12338
12339
12340
12341
12342
12343
12344
12345
12346
12347
12348
12349
12350
12351
12352
12353
12354
12355
12356
12357
12358
12359
12360
12361
12362
12363
12364
12365
12366
12367
12368
12369
12370
12371
12372
12373
12374
12375
12376
12377
12378
12379
12380
12381
12382
12383
12384
12385
12386
12387
12388
12389
12390
12391
12392
12393
12394
12395
12396
12397
12398
12399
12400
12401
12402
12403
12404
12405
12406
12407
12408
12409
12410
12411
12412
12413
12414
12415
12416
12417
12418
12419
12420
12421
12422
12423
12424
12425
12426
12427
12428
12429
12430
12431
12432
12433
12434
12435
12436
12437
12438
12439
12440
12441
12442
12443
12444
12445
12446
12447
12448
12449
12450
12451
12452
12453
12454
12455
12456
12457
12458
12459
12460
12461
12462
12463
12464
12465
12466
12467
12468
12469
12470
12471
12472
12473
12474
12475
12476
12477
12478
12479
12480
12481
12482
12483
12484
12485
12486
12487
12488
12489
12490
12491
12492
12493
12494
12495
12496
12497
12498
12499
12500
12501
12502
12503
12504
12505
12506
12507
12508
12509
12510
12511
12512
12513
12514
12515
12516
12517
12518
12519
12520
12521
12522
12523
12524
12525
12526
12527
12528
12529
12530
12531
12532
12533
12534
12535
12536
12537
12538
12539
12540
12541
12542
12543
12544
12545
12546
12547
12548
12549
12550
12551
12552
12553
12554
12555
12556
12557
12558
12559
12560
12561
12562
12563
12564
12565
12566
12567
12568
12569
12570
12571
12572
12573
12574
12575
12576
12577
12578
12579
12580
12581
12582
12583
12584
12585
12586
12587
12588
12589
12590
12591
12592
12593
12594
12595
12596
12597
12598
12599
12600
12601
12602
12603
12604
12605
12606
12607
12608
12609
12610
12611
12612
12613
12614
12615
12616
12617
12618
12619
12620
12621
12622
12623
12624
12625
12626
12627
12628
12629
12630
12631
12632
12633
12634
12635
12636
12637
12638
12639
12640
12641
12642
12643
12644
12645
12646
12647
12648
12649
12650
12651
12652
12653
12654
12655
12656
12657
12658
12659
12660
12661
12662
12663
12664
12665
12666
12667
12668
12669
12670
12671
12672
12673
12674
12675
12676
12677
12678
12679
12680
12681
12682
12683
12684
12685
12686
12687
12688
12689
12690
12691
12692
12693
12694
12695
12696
12697
12698
12699
12700
12701
12702
12703
12704
12705
12706
12707
12708
12709
12710
12711
12712
12713
12714
12715
12716
12717
12718
12719
12720
12721
12722
12723
12724
12725
12726
12727
12728
12729
12730
12731
12732
12733
12734
12735
12736
12737
12738
12739
12740
12741
12742
12743
12744
12745
12746
12747
12748
12749
12750
12751
12752
12753
12754
12755
12756
12757
12758
12759
12760
12761
12762
12763
12764
12765
12766
12767
12768
12769
12770
12771
12772
12773
12774
12775
12776
12777
12778
12779
12780
12781
12782
12783
12784
12785
12786
12787

12788
12789
12790
12791
12792
12793
12794
12795
12796
12797
12798
12799
12800
12801
12802
12803
12804
12805
12806
12807
12808
12809
12810
12811
12812
12813
12814
12815
12816
12817
12818
12819
12820
12821
12822
12823
12824
12825
12826
12827
12828
12829
12830
12831
12832
12833
12834
12835
12836
12837
12838
12839
12840
12841
12842
12843
12844
12845
12846
12847
12848
12849
12850
12851
12852
12853
12854
12855
12856
12857
12858
12859
12860
12861
12862
12863
12864
12865
12866
12867
12868
12869
12870
12871
12872
12873
12874
12875
12876
12877
12878
12879
12880
12881
12882
12883
12884
12885
12886
12887
12888
12889
12890
12891
12892
12893
12894
12895
12896
12897
12898
12899
12900
12901
12902
12903
12904
12905
12906
12907
12908
12909
12910
12911
12912
12913
12914
12915
12916
12917
12918
12919
12920
12921
12922
12923
12924
12925
12926
12927
12928
12929
12930
12931
12932
12933
12934
12935
12936
12937
12938
12939
12940
12941
12942
12943
12944
12945
12946
12947
12948
12949
12950
12951
12952
12953
12954
12955
12956
12957
12958
12959
12960
12961
12962
12963
12964
12965
12966
12967
12968
12969
12970
12971
12972
12973
12974
12975
12976
12977
12978
12979
12980
12981
12982
12983
12984
12985
12986
12987
12988
12989
12990
12991
12992
12993
12994
12995
12996
12997
12998
12999
13000
13001
13002
13003
13004
13005
13006
13007
13008
13009
13010
13011
13012
13013
13014
13015
13016
13017
13018
13019
13020
13021
13022
13023
13024
13025
13026
13027
13028
13029
13030
13031
13032
13033
13034
13035
13036
13037
13038
13039
13040
13041
13042
13043
13044
13045
13046
13047
13048
13049
13050
13051
13052
13053
13054
13055
13056
13057
13058
13059
13060
13061
13062
13063
13064
13065
13066
13067
13068
13069
13070
13071
13072
13073
13074
13075
13076
13077
13078
13079
13080
13081
13082
13083
13084
13085
13086
13087
13088
13089
13090
13091
13092
13093
13094
13095
13096
13097
13098
13099
13100
13101
13102
13103
13104
13105
13106
13107
13108
13109
13110
13111
13112
13113
13114
13115
13116
13117
13118
13119
13120
13121
13122
13123
13124
13125
13126
13127
13128
13129
13130
13131
13132
13133
13134
13135
13136
13137
13138
13139
13140
13141
13142
13143
13144
13145
13146
13147
13148
13149
13150
13151
13152
13153
13154
13155
13156
13157
13158
13159
13160
13161
13162
13163
13164
13165
13166
13167
13168
13169
13170
13171
13172
13173
13174
13175
13176
13177
13178
13179
13180
13181
13182
13183
13184
13185
13186
13187
13188
13189
13190
13191
13192
13193
13194
13195
13196
13197
13198
13199
13200
13201
13202
13203
13204
13205
13206
13207
13208
13209
13210
13211
13212
13213
13214
13215
13216
13217
13218
13219
13220
13221
13222
13223
13224
13225
13226
13227
13228
13229
13230
13231
13232
13233
13234
13235
13236
13237
13238
13239
13240
13241
13242
13243
13244
13245
13246
13247
13248
13249
13250
13251
13252
13253
13254
13255
13256
13257
13258
13259
13260
13261
13262
13263
13264
13265
13266
13267
13268
13269
13270
13271
13272
13273
13274
13275
13276
13277
13278
13279
13280
13281
13282
13283
13284
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
13443
13444
13445
13446
13447
13448
13449
13450
13451
13452
13453
13454
13455
13456
13457
13458
13459
13460
13461
13462
13463
13464
13465
13466
13467
13468
13469
13470
13471
13472
13473
13474
13475
13476
13477
13478
13479
13480
13481
13482
13483
13484
13485
13486
13487
13488
13489
13490
13491
13492
13493
13494
13495
13496
13497
13498
13499
13500
13501
13502
13503
13504
13505
13506
13507
13508
13509
13510
13511
13512
13513
13514
13515
13516
13517
13518
13519
13520
13521
13522
13523
13524
13525
13526
13527
13528
13529
13530
13531
13532
13533
13534
13535
13536
13537
13538
13539
13540
13541
13542
13543
13544
13545
13546
13547
13548
13549
13550
13551
13552
13553
13554
13555
13556
13557
13558
13559
13560
13561
13562
13563
13564
13565
13566
13567
13568
13569
13570
13571
13572
13573
13574
13575
13576
13577
13578
13579
13580
13581
13582
13583
13584
13585
13586
13587
13588
13589
13590
13591
13592
13593
13594
13595
13596
13597
13598
13599
13600
13601
13602
13603
13604
13605
13606
13607
13608
13609
13610
13611
13612
13613
13614
13615
13616
13617
13618
13619
13620
13621
13622
13623
13624
13625
13626
13627
13628
13629
13630
13631
13632
13633
13634
13635
13636
13637
13638
13639
13640
13641
13642
13643
13644
13645
13646
13647
13648
13649
13650
13651
13652
13653
13654
13655
13656
13657
13658
13659
13660
13661
13662
13663
13664
13665
13666
13667
13668
13669
13670
13671
13672
13673
13674
13675
13676
13677
13678
13679
13680
13681
13682
13683
13684
13685
13686
13687
13688
13689
13690
13691
13692
13693
13694
13695
13696
13697
13698
13699
13700
13701
13702
13703
13704
13705
13706
13707
13708
13709
13710
13711
13712
13713
13714
13715
13716
13717
13718
13719
13720
13721
13722
13723
13724
13725
13726
13727
13728
13729
13730
13731
13732
13733
13734
13735
13736
13737
13738
13739
13740
13741
13742
13743
13744
13745
13746
13747
13748
13749
13750
13751
13752
13753
13754
13755
13756
13757
13758
13759
13760
13761
13762
13763
13764
13765
13766
13767
13768
13769
13770
13771
13772
13773
13774
13775
13776
13777
13778
13779
13780
13781
13782
13783
13784
13785
13786
13787
13788
13789
13790
13791
13792
13793
13794
13795
13796
13797
13798
13799
13800
13801
13802
13803
13804
13805
13806
13807
13808
13809
13810
13811
13812
13813
13814
13815
13816
13817
13818
13819
13820
13821
13822
13823
13824
13825
13826
13827
13828
13829
13830
13831
13832
13833
13834
13835
13836
13837
13838
13839
13840
13841
13842
13843
13844
13845
13846
13847
13848
13849
13850
13851
13852
13853
13854
13855
13856
13857
13858
13859
13860
13861
13862
13863
13864
13865
13866
13867
13868
13869
13870
13871
13872
13873
13874
13875
13876
13877
13878
13879
13880
13881
13882
13883
13884
13885
13886
13887
13888
13889
13890
13891
13892
13893
13894
13895
13896
13897
13898
13899
13900
13901
13902
13903
13904
13905
13906
13907
13908
13909
13910
13911
13912
13913
13914
13915
13916
13917
13918
13919
13920
13921
13922
13923
13924
13925
13926
13927
13928
13929
13930
13931
13932
13933
13934
13935
13936
13937
13938
13939
13940
13941
13942
13943
13944
13945
13946
13947
13948
13949
13950
13951
13952
13953
13954
13955
13956
13957
13958
13959
13960
13961
13962
13963
13964
13965
13966
13967
13968
13969
13970
13971
13972
13973
13974
13975
13976
13977
13978
13979
13980
13981
13982
13983
13984
13985
13986
13987
13988
13989
13990
13991
13992
13993
13994
13995
13996
13997
13998
13999
14000
14001
14002
14003
14004
14005
14006
14007
14008
14009
14010
14011
14012
14013
14014
14015
14016
14017
14018
14019
14020
14021
14022
14023
14024
14025
14026
14027
14028
14029
14030
14031
14032
14033
14034
14035
14036
14037
14038
14039
14040
14041
14042
14043
14044
14045
14046
14047
14048
14049
14050
14051
14052
14053
14054
14055
14056
14057
14058
14059
14060
14061
14062
14063
14064
14065
14066
14067
14068
14069
14070
14071
14072
14073
14074
14075
14076
14077
14078
14079
14080
14081
14082
14083
14084
14085
14086
14087
14088
14089
14090
14091
14092
14093
14094
14095
14096
14097
14098
14099
14100
14101
14102
14103
14104
14105
14106
14107
14108
14109
14110
14111
14112
14113
14114
14115
14116
14117
14118
14119
14120
14121
14122
14123
14124
14125
14126
14127
14128
14129
14130
14131
14132
14133
14134
14135
14136
14137
14138
14139
14140
14141
14142
14143
14144
14145
14146
14147
14148
14149
14150
14151
14152
14153
14154

14155
14156
14157
14158
14159
14160
14161
14162
14163
14164
14165
14166
14167
14168
14169
14170
14171
14172
14173
14174
14175
14176
14177
14178
14179
14180
14181
14182
14183
14184
14185
14186
14187
14188
14189
14190
14191
14192
14193
14194
14195
14196
14197
14198
14199
14200
14201
14202
14203
14204
14205
14206
14207
14208
14209
14210
14211
14212
14213
14214
14215
14216
14217
14218
14219
14220
14221
14222
14223
14224
14225
14226
14227
14228
14229
14230
14231
14232
14233
14234
14235
14236
14237
14238
14239
14240
14241
14242
14243
14244
14245
14246
14247
14248
14249
14250
14251
14252
14253
14254
14255
14256
14257
14258
14259
14260
14261
14262
14263
14264
14265
14266
14267
14268
14269
14270
14271
14272
14273
14274
14275
14276
14277
14278
14279
14280
14281
14282
14283
14284
14285
14286
14287
14288
14289
14290
14291
14292
14293
14294
14295
14296
14297
14298
14299
14300
14301
14302
14303
14304
14305
14306
14307
14308
14309
14310
14311
14312
14313
14314
14315
14316
14317
14318
14319
14320
14321
14322
14323
14324
14325
14326
14327
14328
14329
14330
14331
14332
14333
14334
14335
14336
14337
14338
14339
14340
14341
14342
14343
14344
14345
14346
14347
14348
14349
14350
14351
14352
14353
14354
14355
14356
14357
14358
14359
14360
14361
14362
14363
14364
14365
14366
14367
14368
14369
14370
14371
14372
14373
14374
14375
14376
14377
14378
14379
14380
14381
14382
14383
14384
14385
14386
14387
14388
14389
14390
14391
14392
14393
14394
14395
14396
14397
14398
14399
14400
14401
14402
14403
14404
14405
14406
14407
14408
14409
14410
14411
14412
14413
14414
14415
14416
14417
14418
14419
14420
14421
14422
14423
14424
14425
14426
14427
14428
14429
14430
14431
14432
14433
14434
14435
14436
14437
14438
14439
14440
14441
14442
14443
14444
14445
14446
14447
14448
14449
14450
14451
14452
14453
14454
14455
14456
14457
14458
14459
14460
14461
14462
14463
14464
14465
14466
14467
14468
14469
14470
14471
14472
14473
14474
14475
14476
14477
14478
14479
14480
14481
14482
14483
14484
14485
14486
14487
14488
14489
14490
14491
14492
14493
14494
14495
14496
14497
14498
14499
14500
14501
14502
14503
14504
14505
14506
14507
14508
14509
14510
14511
14512
14513
14514
14515
14516
14517
14518
14519
14520
14521
14522
14523
14524
14525
14526
14527
14528
14529
14530
14531
14532
14533
14534
14535
14536
14537
14538
14539
14540
14541
14542
14543
14544
14545
14546
14547
14548
14549
14550
14551
14552
14553
14554
14555
14556
14557
14558
14559
14560
14561
14562
14563
14564
14565
14566
14567
14568
14569
14570
14571
14572
14573
14574
14575
14576
14577
14578
14579
14580
14581
14582
14583
14584
14585
14586
14587
14588
14589
14590
14591
14592
14593
14594
14595
14596
14597
14598
14599
14600
14601
14602
14603
14604
14605
14606
14607
14608
14609
14610
14611
14612
14613
14614
14615
14616
14617
14618
14619
14620
14621
14622
14623
14624
14625
14626
14627
14628
14629
14630
14631
14632
14633
14634
14635
14636
14637
14638
14639
14640
14641
14642
14643
14644
14645
14646
14647
14648
14649
14650
14651
14652
14653
14654
14655
14656
14657
14658
14659
14660
14661
14662
14663
14664
14665
14666
14667
14668
14669
14670
14671
14672
14673
14674
14675
14676
14677
14678
14679
14680
14681
14682
14683
14684
14685
14686
14687
14688
14689
14690
14691
14692
14693
14694
14695
14696
14697
14698
14699
14700
14701
14702
14703
14704
14705
14706
14707
14708
14709
14710
14711
14712
14713
14714
14715
14716
14717
14718
14719
14720
14721
14722
14723
14724
14725
14726
14727
14728
14729
14730
14731
14732
14733
14734
14735
14736
14737
14738
14739
14740
14741
14742
14743
14744
14745
14746
14747
14748
14749
14750
14751
14752
14753
14754
14755
14756
14757
14758
14759
14760
14761
14762
14763
14764
14765
14766
14767
14768
14769
14770
14771
14772
14773
14774
14775
14776
14777
14778
14779
14780
14781
14782
14783
14784
14785
14786
14787
14788
14789
14790
14791
14792
14793
14794
14795
14796
14797
14798
14799
14800
14801
14802
14803
14804
14805
14806
14807
14808
14809
14810
14811
14812
14813
14814
14815
14816
14817
14818
14819
14820
14821
14822
14823
14824
14825
14826
14827
14828
14829
14830
14831
14832
14833
14834
14835
14836
14837
14838
14839
14840
14841
14842
14843
14844
14845
14846
14847
14848
14849
14850
14851
14852
14853
14854
14855
14856
14857
14858
14859
14860
14861
14862
14863
14864
14865
14866
14867
14868
14869
14870
14871
14872
14873
14874
14875
14876
14877
14878
14879
14880
14881
14882
14883
14884
14885
14886
14887
14888
14889
14890
14891
14892
14893
14894
14895
14896
14897
14898
14899
14900
14901
14902
14903
14904
14905
14906
14907
14908
14909
14910
14911
14912
14913
14914
14915
14916
14917
14918
14919
14920
14921
14922
14923
14924
14925
14926
14927
14928
14929
14930
14931
14932
14933
14934
14935
14936
14937
14938
14939
14940
14941
14942
14943
14944
14945
14946
14947
14948
14949
14950
14951
14952
14953
14954
14955
14956
14957
14958
14959
14960
14961
14962
14963
14964
14965
14966
14967
14968
14969
14970
14971
14972
14973
14974
14975
14976
14977
14978
14979
14980
14981
14982
14983
14984
14985
14986
14987
14988
14989
14990
14991
14992
14993
14994
14995
14996
14997
14998
14999
15000
15001
15002
15003
15004
15005
15006
15007
15008
15009
15010
15011
15012
15013
15014
15015
15016
15017
15018
15019
15020
15021
15022
15023
15024
15025
15026
15027
15028
15029
15030
15031
15032
15033
15034
15035
15036
15037
15038
15039
15040
15041
15042
15043
15044
15045
15046
15047
15048
15049
15050
15051
15052
15053
15054
15055
15056
15057
15058
15059
15060
15061
15062
15063
15064
15065
15066
15067
15068
15069
15070
15071
15072
15073
15074
15075
15076
15077
15078
15079
15080
15081
15082
15083
15084
15085
15086
15087
15088
15089
15090
15091
15092
15093
15094
15095
15096
15097
15098
15099
15100
15101
15102
15103
15104
15105
15106
15107
15108
15109
15110
15111
15112
15113
15114
15115
15116
15117
15118
15119
15120
15121
15122
15123
15124
15125
15126
15127
15128
15129
15130
15131
15132
15133
15134
15135
15136
15137
15138
15139
15140
15141
15142
15143
15144
15145
15146
15147
15148
15149
15150
15151
15152
15153
15154
15155
15156
15157
15158
15159
15160
15161
15162
15163
15164
15165
15166
15167
15168
15169
15170
15171
15172
15173
15174
15175
15176
15177
15178
15179
15180
15181
15182
15183
15184
15185
15186
15187
15188
15189
15190
15191
15192
15193
15194
15195
15196
15197
15198
15199
15200
15201
15202
15203
15204
15205
15206
15207
15208
15209
15210
15211
15212
15213
15214
15215
15216
15217
15218
15219
15220
15221
15222
15223
15224
15225
15226
15227
15228
15229
15230
15231
15232
15233
15234
15235
15236
15237
15238
15239
15240
15241
15242
15243
15244
15245
15246
15247
15248
15249
15250
15251
15252
15253
15254
15255
15256
15257
15258
15259
15260
15261
15262
15263
15264
15265
15266
15267
15268
15269
15270
15271
15272
15273
15274
15275
15276
15277
15278
15279
15280
15281
15282
15283
15284
15285
15286
15287
15288
15289
15290
15291
15292
15293
15294
15295
15296
15297
15298
15299
15300
15301
15302
15303
15304
15305
15306
15307
15308
15309
15310
15311
15312
15313
15314
15315
15316
15317
15318
15319
15320
15321
15322
15323
15324
15325
15326
15327
15328
15329
15330
15331
15332
15333
15334
15335
15336
15337
15338
15339
15340
15341
15342
15343
15344
15345
15346
15347
15348
15349
15350
15351
15352
15353
15354
15355
15356
15357
15358
15359
15360
15361
15362
15363
15364
15365
15366
15367
15368
15369
15370
15371
15372
15373
15374
15375
15376
15377
15378
15379
15380
15381
15382
15383
15384
15385
15386
15387
15388
15389
15390
15391
15392
15393
15394
15395
15396
15397
15398
15399
15400
15401
15402
15403
15404
15405
15406
15407
15408
15409
15410
15411
15412
15413
15414
15415
15416
15417
15418
15419
15420
15421
15422
15423
15424
15425
15426
15427
15428
15429
15430
15431
15432
15433
15434
15435
15436
15437
15438
15439
15440
15441
15442
15443
15444
15445
15446
15447
15448
15449
15450
15451
15452
15453
15454
15455
15456
15457
15458
15459
15460
15461
15462
15463
15464
15465
15466
15467
15468
15469
15470
15471
15472
15473
15474
15475
15476
15477
15478
15479
15480
15481
15482
15483
15484
15485
15486
15487
15488
15489
15490
15491
15492
15493
15494
15495
15496
15497
15498
15499
15500
15501
15502
15503
15504
15505
15506
15507
15508
15509
15510
15511
15512
15513
15514
15515
15516
15517
15518
15519
15520
15521

15522
15523
15524
15525
15526
15527
15528
15529
15530
15531
15532
15533
15534
15535
15536
15537
15538
15539
15540
15541
15542
15543
15544
15545
15546
15547
15548
15549
15550
15551
15552
15553
15554
15555
15556
15557
15558
15559
15560
15561
15562
15563
15564
15565
15566
15567
15568
15569
15570
15571
15572
15573
15574
15575
15576
15577
15578
15579
15580
15581
15582
15583
15584
15585
15586
15587
15588
15589
15590
15591
15592
15593
15594
15595
15596
15597
15598
15599
15600
15601
15602
15603
15604
15605
15606
15607
15608
15609
15610
15611
15612
15613
15614
15615
15616
15617
15618
15619
15620
15621
15622
15623
15624
15625
15626
15627
15628
15629
15630
15631
15632
15633
15634
15635
15636
15637
15638
15639
15640
15641
15642
15643
15644
15645
15646
15647
15648
15649
15650
15651
15652
15653
15654
15655
15656
15657
15658
15659
15660
15661
15662
15663
15664
15665
15666
15667
15668
15669
15670
15671
15672
15673
15674
15675
15676
15677
15678
15679
15680
15681
15682
15683
15684
15685
15686
15687
15688
15689
15690
15691
15692
15693
15694
15695
15696
15697
15698
15699
15700
15701
15702
15703
15704
15705
15706
15707
15708
15709
15710
15711
15712
15713
15714
15715
15716
15717
15718
15719
15720
15721
15722
15723
15724
15725
15726
15727
15728
15729
15730
15731
15732
15733
15734
15735
15736
15737
15738
15739
15740
15741
15742
15743
15744
15745
15746
15747
15748
15749
15750
15751
15752
15753
15754
15755
15756
15757
15758
15759
15760
15761
15762
15763
15764
15765
15766
15767
15768
15769
15770
15771
15772
15773
15774
15775
15776
15777
15778
15779
15780
15781
15782
15783
15784
15785
15786
15787
15788
15789
15790
15791
15792
15793
15794
15795
15796
15797
15798
15799
15800
15801
15802
15803
15804
15805
15806
15807
15808
15809
15810
15811
15812
15813
15814
15815
15816
15817
15818
15819
15820
15821
15822
15823
15824
15825
15826
15827
15828
15829
15830
15831
15832
15833
15834
15835
15836
15837
15838
15839
15840
15841
15842
15843
15844
15845
15846
15847
15848
15849
15850
15851
15852
15853
15854
15855
15856
15857
15858
15859
15860
15861
15862
15863
15864
15865
15866
15867
15868
15869
15870
15871
15872
15873
15874
15875
15876
15877
15878
15879
15880
15881
15882
15883
15884
15885
15886
15887
15888
15889
15890
15891
15892
15893
15894
15895
15896
15897
15898
15899
15900
15901
15902
15903
15904
15905
15906
15907
15908
15909
15910
15911
15912
15913
15914
15915
15916
15917
15918
15919
15920
15921
15922
15923
15924
15925
15926
15927
15928
15929
15930
15931
15932
15933
15934
15935
15936
15937
15938
15939
15940
15941
15942
15943
15944
15945
15946
15947
15948
15949
15950
15951
15952
15953
15954
15955
15956
15957
15958
15959
15960
15961
15962
15963
15964
15965
15966
15967
15968
15969
15970
15971
15972
15973
15974
15975
15976
15977
15978
15979
15980
15981
15982
15983
15984
15985
15986
15987
15988
15989
15990
15991
15992
15993
15994
15995
15996
15997
15998
15999
16000
16001
16002
16003
16004
16005
16006
16007
16008
16009
16010
16011
16012
16013
16014
16015
16016
16017
16018
16019
16020
16021
16022
16023
16024
16025
16026
16027
16028
16029
16030
16031
16032
16033
16034
16035
16036
16037
16038
16039
16040
16041
16042
16043
16044
16045
16046
16047
16048
16049
16050
16051
16052
16053
16054
16055
16056
16057
16058
16059
16060
16061
16062
16063
16064
16065
16066
16067
16068
16069
16070
16071
16072
16073
16074
16075
16076
16077
16078
16079
16080
16081
16082
16083
16084
16085
16086
16087
16088
16089
16090
16091
16092
16093
16094
16095
16096
16097
16098
16099
16100
16101
16102
16103
16104
16105
16106
16107
16108
16109
16110
16111
16112
16113
16114
16115
16116
16117
16118
16119
16120
16121
16122
16123
16124
16125
16126
16127
16128
16129
16130
16131
16132
16133
16134
16135
16136
16137
16138
16139
16140
16141
16142
16143
16144
16145
16146
16147
16148
16149
16150
16151
16152
16153
16154
16155
16156
16157
16158
16159
16160
16161
16162
16163
16164
16165
16166
16167
16168
16169
16170
16171
16172
16173
16174
16175
16176
16177
16178
16179
16180
16181
16182
16183
16184
16185
16186
16187
16188
16189
16190
16191
16192
16193
16194
16195
16196
16197
16198
16199
16200
16201
16202
16203
16204
16205
16206
16207
16208
16209
16210
16211
16212
16213
16214
16215
16216
16217
16218
16219
16220
16221
16222
16223
16224
16225
16226
16227
16228
16229
16230
16231
16232
16233
16234
16235
16236
16237
16238
16239
16240
16241
16242
16243
16244
16245
16246
16247
16248
16249
16250
16251
16252
16253
16254
16255
16256
16257
16258
16259
16260
16261
16262
16263
16264
16265
16266
16267
16268
16269
16270
16271
16272
16273
16274
16275
16276
16277
16278
16279
16280
16281
16282
16283
16284
16285
16286
16287
16288
16289
16290
16291
16292
16293
16294
16295
16296
16297
16298
16299
16300
16301
16302
16303
16304
16305
16306
16307
16308
16309
16310
16311
16312
16313
16314
16315
16316
16317
16318
16319
16320
16321
16322
16323
16324
16325
16326
16327
16328
16329
16330
16331
16332
16333
16334
16335
16336
16337
16338
16339
16340
16341
16342
16343
16344
16345
16346
16347
16348
16349
16350
16351
16352
16353
16354
16355
16356
16357
16358
16359
16360
16361
16362
16363
16364
16365
16366
16367
16368
16369
16370
16371
16372
16373
16374
16375
16376
16377
16378
16379
16380
16381
16382
16383
16384
16385
16386
16387
16388
16389
16390
16391
16392
16393
16394
16395
16396
16397
16398
16399
16400
16401
16402
16403
16404
16405
16406
16407
16408
16409
16410
16411
16412
16413
16414
16415
16416
16417
16418
16419
16420
16421
16422
16423
16424
16425
16426
16427
16428
16429
16430
16431
16432
16433
16434
16435
16436
16437
16438
16439
16440
16441
16442
16443
16444
16445
16446
16447
16448
16449
16450
16451
16452
16453
16454
16455
16456
16457
16458
16459
16460
16461
16462
16463
16464
16465
16466
16467
16468
16469
16470
16471
16472
16473
16474
16475
16476
16477
16478
16479
16480
16481
16482
16483
16484
16485
16486
16487
16488
16489
16490
16491
16492
16493
16494
16495
16496
16497
16498
16499
16500
16501
16502
16503
16504
16505
16506
16507
16508
16509
16510
16511
16512
16513
16514
16515
16516
16517
16518
16519
16520
16521
16522
16523
16524
16525
16526
16527
16528
16529
16530
16531
16532
16533
16534
16535
16536
16537
16538
16539
16540
16541
16542
16543
16544
16545
16546
16547
16548
16549
16550
16551
16552
16553
16554
16555
16556
16557
16558
16559
16560
16561
16562
16563
16564
16565
16566
16567
16568
16569
16570
16571
16572
16573
16574
16575
16576
16577
16578
16579
16580
16581
16582
16583
16584
16585
16586
16587
16588
16589
16590
16591
16592
16593
16594
16595
16596
16597
16598
16599
16600
16601
16602
16603
16604
16605
16606
16607
16608
16609
16610
16611
16612
16613
16614
16615
16616
16617
16618
16619
16620
16621
16622
16623
16624
16625
16626
16627
16628
16629
16630
16631
16632
16633
16634
16635
16636
16637
16638
16639
16640
16641
16642
16643
16644
16645
16646
16647
16648
16649
16650
16651
16652
16653
16654
16655
16656
16657
16658
16659
16660
16661
16662
16663
16664
16665
16666
16667
16668
16669
16670
16671
16672
16673
16674
16675
16676
16677
16678
16679
16680
16681
16682
16683
16684
16685
16686
16687
16688
16689
16690
16691
16692
16693
16694
16695
16696
16697
16698
16699
16700
16701
16702
16703
16704
16705
16706
16707
16708
16709
16710
16711
16712
16713
16714
16715
16716
16717
16718
16719
16720
16721
16722
16723
16724
16725
16726
16727
16728
16729
16730
16731
16732
16733
16734
16735
16736
16737
16738
16739
16740
16741
16742
16743
16744
16745
16746
16747
16748
16749
16750
16751
16752
16753
16754
16755
16756
16757
16758
16759
16760
16761
16762
16763
16764
16765
16766
16767
16768
16769
16770
16771
16772
16773
16774
16775
16776
16777
16778
16779
16780
16781
16782
16783
16784
16785
16786
16787
16788
16789
16790
16791
16792
16793
16794
16795
16796
16797
16798
16799
16800
16801
16802
16803
16804
16805
16806
16807
16808
16809
16810
16811
16812
16813
16814
16815
16816
16817
16818
16819
16820
16821
16822
16823
16824
16825
16826
16827
16828
16829
16830
16831
16832
16833
16834
16835
16836
16837
16838
16839
16840
16841
16842
16843
16844
16845
16846
16847
16848
16849
16850
16851
16852
16853
16854
16855
16856
16857
16858
16859
16860
16861
16862
16863
16864
16865
16866
16867
16868
16869
16870
16871
16872
16873
16874
16875
16876
16877
16878
16879
16880
16881
16882
16883
16884
16885
16886
16887
16888

16889
16890
16891
16892
16893
16894
16895
16896
16897
16898
16899
16900
16901
16902
16903
16904
16905
16906
16907
16908
16909
16910
16911
16912
16913
16914
16915
16916
16917
16918
16919
16920
16921
16922
16923
16924
16925
16926
16927
16928
16929
16930
16931
16932
16933
16934
16935
16936
16937
16938
16939
16940
16941
16942
16943
16944
16945
16946
16947
16948
16949
16950
16951
16952
16953
16954
16955
16956
16957
16958
16959
16960
16961
16962
16963
16964
16965
16966
16967
16968
16969
16970
16971
16972
16973
16974
16975
16976
16977
16978
16979
16980
16981
16982
16983
16984
16985
16986
16987
16988
16989
16990
16991
16992
16993
16994
16995
16996
16997
16998
16999
17000
17001
17002
17003
17004
17005
17006
17007
17008
17009
17010
17011
17012
17013
17014
17015
17016
17017
17018
17019
17020
17021
17022
17023
17024
17025
17026
17027
17028
17029
17030
17031
17032
17033
17034
17035
17036
17037
17038
17039
17040
17041
17042
17043
17044
17045
17046
17047
17048
17049
17050
17051
17052
17053
17054
17055
17056
17057
17058
17059
17060
17061
17062
17063
17064
17065
17066
17067
17068
17069
17070
17071
17072
17073
17074
17075
17076
17077
17078
17079
17080
17081
17082
17083
17084
17085
17086
17087
17088
17089
17090
17091
17092
17093
17094
17095
17096
17097
17098
17099
17100
17101
17102
17103
17104
17105
17106
17107
17108
17109
17110
17111
17112
17113
17114
17115
17116
17117
17118
17119
17120
17121
17122
17123
17124
17125
17126
17127
17128
17129
17130
17131
17132
17133
17134
17135
17136
17137
17138
17139
17140
17141
17142
17143
17144
17145
17146
17147
17148
17149
17150
17151
17152
17153
17154
17155
17156
17157
17158
17159
17160
17161
17162
17163
17164
17165
17166
17167
17168
17169
17170
17171
17172
17173
17174
17175
17176
17177
17178
17179
17180
17181
17182
17183
17184
17185
17186
17187
17188
17189
17190
17191
17192
17193
17194
17195
17196
17197
17198
17199
17200
17201
17202
17203
17204
17205
17206
17207
17208
17209
17210
17211
17212
17213
17214
17215
17216
17217
17218
17219
17220
17221
17222
17223
17224
17225
17226
17227
17228
17229
17230
17231
17232
17233
17234
17235
17236
17237
17238
17239
17240
17241
17242
17243
17244
17245
17246
17247
17248
17249
17250
17251
17252
17253
17254
17255
17256
17257
17258
17259
17260
17261
17262
17263
17264
17265
17266
17267
17268
17269
17270
17271
17272
17273
17274
17275
17276
17277
17278
17279
17280
17281
17282
17283
17284
17285
17286
17287
17288
17289
17290
17291
17292
17293
17294
17295
17296
17297
17298
17299
17300
17301
17302
17303
17304
17305
17306
17307
17308
17309
17310
17311
17312
17313
17314
17315
17316
17317
17318
17319
17320
17321
17322
17323
17324
17325
17326
17327
17328
17329
17330
17331
17332
17333
17334
17335
17336
17337
17338
17339
17340
17341
17342
17343
17344
17345
17346
17347
17348
17349
17350
17351
17352
17353
17354
17355
17356
17357
17358
17359
17360
17361
17362
17363
17364
17365
17366
17367
17368
17369
17370
17371
17372
17373
17374
17375
17376
17377
17378
17379
17380
17381
17382
17383
17384
17385
17386
17387
17388
17389
17390
17391
17392
17393
17394
17395
17396
17397
17398
17399
17400
17401
17402
17403
17404
17405
17406
17407
17408
17409
17410
17411
17412
17413
17414
17415
17416
17417
17418
17419
17420
17421
17422
17423
17424
17425
17426
17427
17428
17429
17430
17431
17432
17433
17434
17435
17436
17437
17438
17439
17440
17441
17442
17443
17444
17445
17446
17447
17448
17449
17450
17451
17452
17453
17454
17455
17456
17457
17458
17459
17460
17461
17462
17463
17464
17465
17466
17467
17468
17469
17470
17471
17472
17473
17474
17475
17476
17477
17478
17479
17480
17481
17482
17483
17484
17485
17486
17487
17488
17489
17490
17491
17492
17493
17494
17495
17496
17497
17498
17499
17500
17501
17502
17503
17504
17505
17506
17507
17508
17509
17510
17511
17512
17513
17514
17515
17516
17517
17518
17519
17520
17521
17522
17523
17524
17525
17526
17527
17528
17529
17530
17531
17532
17533
17534
17535
17536
17537
17538
17539
17540
17541
17542
17543
17544
17545
17546
17547
17548
17549
17550
17551
17552
17553
17554
17555
17556
17557
17558
17559
17560
17561
17562
17563
17564
17565
17566
17567
17568
17569
17570
17571
17572
17573
17574
17575
17576
17577
17578
17579
17580
17581
17582
17583
17584
17585
17586
17587
17588
17589
17590
17591
17592
17593
17594
17595
17596
17597
17598
17599
17600
17601
17602
17603
17604
17605
17606
17607
17608
17609
17610
17611
17612
17613
17614
17615
17616
17617
17618
17619
17620
17621
17622
17623
17624
17625
17626
17627
17628
17629
17630
17631
17632
17633
17634
17635
17636
17637
17638
17639
17640
17641
17642
17643
17644
17645
17646
17647
17648
17649
17650
17651
17652
17653
17654
17655
17656
17657
17658
17659
17660
17661
17662
17663
17664
17665
17666
17667
17668
17669
17670
17671
17672
17673
17674
17675
17676
17677
17678
17679
17680
17681
17682
17683
17684
17685
17686
17687
17688
17689
17690
17691
17692
17693
17694
17695
17696
17697
17698
17699
17700
17701
17702
17703
17704
17705
17706
17707
17708
17709
17710
17711
17712
17713
17714
17715
17716
17717
17718
17719
17720
17721
17722
17723
17724
17725
17726
17727
17728
17729
17730
17731
17732
17733
17734
17735
17736
17737
17738
17739
17740
17741
17742
17743
17744
17745
17746
17747
17748
17749
17750
17751
17752
17753
17754
17755
17756
17757
17758
17759
17760
17761
17762
17763
17764
17765
17766
17767
17768
17769
17770
17771
17772
17773
17774
17775
17776
17777
17778
17779
17780
17781
17782
17783
17784
17785
17786
17787
17788
17789
17790
17791
17792
17793
17794
17795
17796
17797
17798
17799
17800
17801
17802
17803
17804
17805
17806
17807
17808
17809
17810
17811
17812
17813
17814
17815
17816
17817
17818
17819
17820
17821
17822
17823
17824
17825
17826
17827
17828
17829
17830
17831
17832
17833
17834
17835
17836
17837
17838
17839
17840
17841
17842
17843
17844
17845
17846
17847
17848
17849
17850
17851
17852
17853
17854
17855
17856
17857
17858
17859
17860
17861
17862
17863
17864
17865
17866
17867
17868
17869
17870
17871
17872
17873
17874
17875
17876
17877
17878
17879
17880
17881
17882
17883
17884
17885
17886
17887
17888
17889
17890
17891
17892
17893
17894
17895
17896
17897
17898
17899
17900
17901
17902
17903
17904
17905
17906
17907
17908
17909
17910
17911
17912
17913
17914
17915
17916
17917
17918
17919
17920
17921
17922
17923
17924
17925
17926
17927
17928
17929
17930
17931
17932
17933
17934
17935
17936
17937
17938
17939
17940
17941
17942
17943
17944
17945
17946
17947
17948
17949
17950
17951
17952
17953
17954
17955
17956
17957
17958
17959
17960
17961
17962
17963
17964
17965
17966
17967
17968
17969
17970
17971
17972
17973
17974
17975
17976
17977
17978
17979
17980
17981
17982
17983
17984
17985
17986
17987
17988
17989
17990
17991
17992
17993
17994
17995
17996
17997
17998
17999
18000
18001
18002
18003
18004
18005
18006
18007
18008
18009
18010
18011
18012
18013
18014
18015
18016
18017
18018
18019
18020
18021
18022
18023
18024
18025
18026
18027
18028
18029
18030
18031
18032
18033
18034
18035
18036
18037
18038
18039
18040
18041
18042
18043
18044
18045
18046
18047
18048
18049
18050
18051
18052
18053
18054
18055
18056
18057
18058
18059
18060
18061
18062
18063
18064
18065
18066
18067
18068
18069
18070
18071
18072
18073
18074
18075
18076
18077
18078
18079
18080
18081
18082
18083
18084
18085
18086
18087
18088
18089
18090
18091
18092
18093
18094
18095
18096
18097
18098
18099
18100
18101
18102
18103
18104
18105
18106
18107
18108
18109
18110
18111
18112
18113
18114
18115
18116
18117
18118
18119
18120
18121
18122
18123
18124
18125
18126
18127
18128
18129
18130
18131
18132
18133
18134
18135
18136
18137
18138
18139
18140
18141
18142
18143
18144
18145
18146
18147
18148
18149
18150
18151
18152
18153
18154
18155
18156
18157
18158
18159
18160
18161
18162
18163
18164
18165
18166
18167
18168
18169
18170
18171
18172
18173
18174
18175
18176
18177
18178
18179
18180
18181
18182
18183
18184
18185
18186
18187
18188
18189
18190
18191
18192
18193
18194
18195
18196
18197
18198
18199
18200
18201
18202
18203
18204
18205
18206
18207
18208
18209
18210
18211
18212
18213
18214
18215
18216
18217
18218
18219
18220
18221
18222
18223
18224
18225
18226
18227
18228
18229
18230
18231
18232
18233
18234
18235
18236
18237
18238
18239
18240
18241
18242
18243
18244
18245
18246
18247
18248
18249
18250
18251
18252
18253
18254
18255

18256
18257
18258
18259
18260
18261
18262
18263
18264
18265
18266
18267
18268
18269
18270
18271
18272
18273
18274
18275
18276
18277
18278
18279
18280
18281
18282
18283
18284
18285
18286
18287
18288
18289
18290
18291
18292
18293
18294
18295
18296
18297
18298
18299
18300
18301
18302
18303
18304
18305
18306
18307
18308
18309
18310
18311
18312
18313
18314
18315
18316
18317
18318
18319
18320
18321
18322
18323
18324
18325
18326
18327
18328
18329
18330
18331
18332
18333
18334
18335
18336
18337
18338
18339
18340
18341
18342
18343
18344
18345
18346
18347
18348
18349
18350
18351
18352
18353
18354
18355
18356
18357
18358
18359
18360
18361
18362
18363
18364

In [ ]:
new_attrs['Sofifa_Id'] = list_sofifa_id
new_attrs['Player_Position'] = list_player_position
new_attrs['Player_Overall_Rating'] = list_player_overall_rating
new_attrs['Player_Update_Date'] = list_update_date

In [ ]:
fbref_matchsquad_new1.reset_index(drop=True, inplace=True)
new_attrs.reset_index(drop=True, inplace=True)

matchsquad_players = pd.concat([fbref_matchsquad_new1, new_attrs], axis=1)

Existing files

In [ ]:
#sofifa
matchsquad_bundesliga = pd.read_csv('gs://football_data_etl/football_data_extracted/output-basic/matchsquad_players/matchsquad_players_bundesliga.csv')
matchsquad_laliga = pd.read_csv('gs://football_data_etl/football_data_extracted/output-basic/matchsquad_players/matchsquad_players_laliga.csv')
matchsquad_ligue1 = pd.read_csv('gs://football_data_etl/football_data_extracted/output-basic/matchsquad_players/matchsquad_players_ligue1.csv')
matchsquad_premierleague = pd.read_csv('gs://football_data_etl/football_data_extracted/output-basic/matchsquad_players/matchsquad_players_premier_league_new.csv')
matchsquad_seriea = pd.read_csv('gs://football_data_etl/football_data_extracted/output-basic/matchsquad_players/matchsquad_players_serie_a.csv')

In [26]:
merge = pd.concat([matchsquad_bundesliga, matchsquad_laliga,
                   matchsquad_ligue1, matchsquad_premierleague, matchsquad_seriea], axis=0)
merge['Match_Date'] = pd.to_datetime(merge['Match_Date'])
merge['Player_Update_Date'] = pd.to_datetime(merge['Player_Update_Date'])

In [27]:
merge

,Match_Id,Match_Date,Team,Player_Name,Player_Kitnum,Is_Sub,Sofifa_Id,Player_Position,Player_Overall_Rating,Player_Update_Date
0,3adcdef9,2018-09-26,M'Gladbach,Yann Sommer,1,No,177683.0,GK,82.0,2018-09-20
1,3adcdef9,2018-09-26,M'Gladbach,Christoph Kramer,6,No,204024.0,CDM CM,81.0,2018-09-20
2,3adcdef9,2018-09-26,M'Gladbach,Patrick Herrmann,7,No,198077.0,RM,77.0,2018-09-20
3,3adcdef9,2018-09-26,M'Gladbach,Thorgan Hazard,10,No,203486.0,LM RM CF,81.0,2018-09-20
4,3adcdef9,2018-09-26,M'Gladbach,Alassane Pléa,14,No,206467.0,ST RW,80.0,2018-09-20
...,...,...,...,...,...,...,...,...,...,...
103038,f6279636,2024-05-12,Empoli,Alberto Cerri,17,Yes,213829.0,ST,68.0,2024-04-09
103039,f6279636,2024-05-12,Empoli,Jacopo Fazzini,21,Yes,266596.0,CM CAM,67.0,2024-04-09
103040,f6279636,2024-05-12,Empoli,Mattia Destro,23,Yes,193338.0,ST,70.0,2024-04-09
103041,f6279636,2024-05-12,Empoli,Szymon Żurkowski,27,Yes,239732.0,CM CAM CF,72.0,2024-04-09
103042,f6279636,2024-05-12,Empoli,Nicolò Cambiaghi,28,Yes,268703.0,RW ST CF,73.0,2024-04-09

In [28]:
different_team = set(dim_team['Team_Name']) - set(merge['Team'])
different_team

{'Hamburger SV', 'La Coruña', 'Málaga', 'Stoke City', 'Swansea City'}

Dim Match Squad

In [ ]:
dim_match_squad = pd.DataFrame({'Match_Squad_Key': [],
                                'Match': [],
                                'Team': [],
                                'Player_Version': [],
                                'Sub': []})

list_match_squad_key = []
list_match = []
list_team = []
list_player_version = []

list_position = []
list_age = []

for i in range(0,len(merge)):
    print(i)
    list_match_squad_key.append(i+1)

    temp_df = dim_match[dim_match['Match_Id'] == merge['Match_Id'].iloc[i]]

    if (len(temp_df) > 0):
        list_match.append(temp_df['Match_Key'].iloc[0])
    else:
        list_match.append(np.nan)

    temp_df = dim_team[dim_team['Team_Name'] == merge['Team'].iloc[i]]
    if (len(temp_df) > 0):
        list_team.append(temp_df['Team_Key'].iloc[0])
    else:
        list_team.append(np.nan)

    if(~np.isnan(merge['Sofifa_Id'].iloc[i])):



        player_df = dim_player[dim_player['Player_Id'] == merge['Sofifa_Id'].iloc[i]]
        update_date_df = dim_date[dim_date['Full_Date'] == merge['Player_Update_Date'].iloc[i]]

        if (len(player_df) > 0):
            player_key = player_df['Player_Key'].iloc[0]
        else:
            player_key = np.nan

        if (len(update_date_df) > 0):
            update_date_key = update_date_df['Date_Key'].iloc[0]
        else:
            update_date_key = np.nan


        temp_df = dim_player_version[(dim_player_version['Player'] == player_key) &
                                 (dim_player_version['Update_Date'] == update_date_key)]

        if (len(temp_df) > 0):
            list_player_version.append(temp_df['Player_Version_Key'].iloc[0])
        else:
            list_player_version.append(np.nan)

    else:
        list_player_version.append(np.nan)

dim_match_squad['Match_Squad_Key'] = list_match_squad_key
dim_match_squad['Match'] = list_match
dim_match_squad['Team'] = list_team
dim_match_squad['Player_Version'] = list_player_version
dim_match_squad['Sub'] = merge['Is_Sub'].to_list()

#continue

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754

ERROR:gcsfs:_request out of retries on exception: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x78c4b758ba00>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 128, in refresh
    self._retrieve_info(request)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 101, in _retrieve_info
    info = _metadata.get_service_account_info(
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 323, in get_service_account_info
    return get(request, path, params={"recursive": "true"})
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 248, in get
    raise exceptions.TransportError(
google.auth.exceptions.TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x78c4b758ba00>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/retry.py", line 114, in retry_request
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/core.py", line 414, in _request
    headers=self._get_headers(headers),
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/core.py", line 393, in _get_headers
    self.credentials.apply(out)
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/credentials.py", line 187, in apply
    self.maybe_refresh()
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/credentials.py", line 182, in maybe_refresh
    self.credentials.refresh(req)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 134, in refresh
    raise new_exc from caught_exc
google.auth.exceptions.RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x78c4b758ba00>)

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
433993
433994
433995
433996
433997
433998
433999
434000
434001
434002
434003
434004
434005
434006
434007
434008
434009
434010
434011
434012
434013
434014
434015
434016
434017
434018
434019
434020
434021
434022
434023
434024
434025
434026
434027
434028
434029
434030
434031
434032
434033
434034
434035
434036
434037
434038
434039
434040
434041
434042
434043
434044
434045
434046
434047
434048
434049
434050
434051
434052
434053
434054
434055
434056
434057
434058
434059
434060
434061
434062
434063
434064
434065
434066
434067
434068
434069
434070
434071
434072
434073
434074
434075
434076
434077
434078
434079
434080
434081
434082
434083
434084
434085
434086
434087
434088
434089
434090
434091
434092
434093
434094
434095
434096
434097
434098
434099
434100
434101
434102
434103
434104
434105
434106
434107
434108
434109
434110
434111
434112
434113
434114
434115
434116
434117
434118
434119
434120
434121
434122
434123
434124
434125
434126
434127
434128
434129
434130
434131
434132
434133
434134
434135
434136
434137
434138
434139
434140
434141
434142
434143
434144
434145
434146
434147
434148
434149
434150
434151
434152
434153
434154
434155
434156
434157
434158
434159
434160
434161
434162
434163
434164
434165
434166
434167
434168
434169
434170
434171
434172
434173
434174
434175
434176
434177
434178
434179
434180
434181
434182
434183
434184
434185
434186
434187
434188
434189
434190
434191
434192
434193
434194
434195
434196
434197
434198
434199
434200
434201
434202
434203
434204
434205
434206
434207
434208
434209
434210
434211
434212
434213
434214
434215
434216
434217
434218
434219
434220
434221
434222
434223
434224
434225
434226
434227
434228
434229
434230
434231
434232
434233
434234
434235
434236
434237
434238
434239
434240
434241
434242
434243
434244
434245
434246
434247
434248
434249
434250
434251
434252
434253
434254
434255
434256
434257
434258
434259
434260
434261
434262
434263
434264
434265
434266
434267
434268
434269
434270
434271
434272
434273
434274
434275
434276
434277
434278
434279
434280
434281
434282
434283
434284
434285
434286
434287
434288
434289
434290
434291
434292
434293
434294
434295
434296
434297
434298
434299
434300
434301
434302
434303
434304
434305
434306
434307
434308
434309
434310
434311
434312
434313
434314
434315
434316
434317
434318
434319
434320
434321
434322
434323
434324
434325
434326
434327
434328
434329
434330
434331
434332
434333
434334
434335
434336
434337
434338
434339
434340
434341
434342
434343
434344
434345
434346
434347
434348
434349
434350
434351
434352
434353
434354
434355
434356
434357
434358
434359
434360
434361
434362
434363
434364
434365
434366
434367
434368
434369
434370
434371
434372
434373
434374
434375
434376
434377
434378
434379
434380
434381
434382
434383
434384
434385
434386
434387
434388
434389
434390
434391
434392
434393
434394
434395
434396
434397
434398
434399
434400
434401
434402
434403
434404
434405
434406
434407
434408
434409
434410
434411
434412
434413
434414
434415
434416
434417
434418
434419
434420
434421
434422
434423
434424
434425
434426
434427
434428
434429
434430
434431
434432
434433
434434
434435
434436
434437
434438
434439
434440
434441
434442
434443
434444
434445
434446
434447
434448
434449
434450
434451
434452
434453
434454
434455
434456
434457
434458
434459
434460
434461
434462
434463
434464
434465
434466
434467
434468
434469
434470
434471
434472
434473
434474
434475
434476
434477
434478
434479
434480
434481
434482
434483
434484
434485
434486
434487
434488
434489
434490
434491
434492
434493
434494
434495
434496
434497
434498
434499
434500
434501
434502
434503
434504
434505
434506
434507
434508
434509
434510
434511
434512
434513
434514
434515
434516
434517
434518
434519
434520
434521
434522
434523
434524
434525
434526
434527
434528
434529
434530
434531
434532
434533
434534
434535
434536
434537
434538
434539
434540
434541
434542
434543
434544
434545
434546
434547
434548
434549
434550
434551
434552
434553
434554
434555
434556
434557
434558
434559
434560
434561
434562
434563
434564
434565
434566
434567
434568
434569
434570
434571
434572
434573
434574
434575
434576
434577
434578
434579
434580
434581
434582
434583
434584
434585
434586
434587
434588
434589
434590
434591
434592
434593
434594
434595
434596
434597
434598
434599
434600
434601
434602
434603
434604
434605
434606
434607
434608
434609
434610
434611
434612
434613
434614
434615
434616
434617
434618
434619
434620
434621
434622
434623
434624
434625
434626
434627
434628
434629
434630
434631
434632
434633
434634
434635
434636
434637
434638
434639
434640
434641
434642
434643
434644
434645
434646
434647
434648
434649
434650
434651
434652
434653
434654
434655
434656
434657
434658
434659
434660
434661
434662
434663
434664
434665
434666
434667
434668
434669
434670
434671
434672
434673
434674
434675
434676
434677
434678
434679
434680
434681
434682
434683
434684
434685
434686
434687
434688
434689
434690
434691
434692
434693
434694
434695
434696
434697
434698
434699
434700
434701
434702
434703
434704
434705
434706
434707
434708
434709
434710
434711
434712
434713
434714
434715
434716
434717
434718
434719
434720
434721
434722
434723
434724
434725
434726
434727
434728
434729
434730
434731
434732
434733
434734
434735
434736
434737
434738
434739
434740
434741
434742
434743
434744
434745
434746
434747
434748
434749
434750
434751
434752
434753
434754
434755
434756
434757
434758
434759
434760
434761
434762
434763
434764
434765
434766
434767
434768
434769
434770
434771
434772
434773
434774
434775
434776
434777
434778
434779
434780
434781
434782
434783
434784
434785
434786
434787
434788
434789
434790
434791
434792
434793
434794
434795
434796
434797
434798
434799
434800
434801
434802
434803
434804
434805
434806
434807
434808
434809
434810
434811
434812
434813
434814
434815
434816
434817
434818
434819
434820
434821
434822
434823
434824
434825
434826
434827
434828
434829
434830
434831
434832
434833
434834
434835
434836
434837
434838
434839
434840
434841
434842
434843
434844
434845
434846
434847
434848
434849
434850
434851
434852
434853
434854
434855
434856
434857
434858
434859
434860
434861
434862
434863
434864
434865
434866
434867
434868
434869
434870
434871
434872
434873
434874
434875
434876
434877
434878
434879
434880
434881
434882
434883
434884
434885
434886
434887
434888
434889
434890
434891
434892
434893
434894
434895
434896
434897
434898
434899
434900
434901
434902
434903
434904
434905
434906
434907
434908
434909
434910
434911
434912
434913
434914
434915
434916
434917
434918
434919
434920
434921
434922
434923
434924
434925
434926
434927
434928
434929
434930
434931
434932
434933
434934
434935
434936
434937
434938
434939
434940
434941
434942
434943
434944
434945
434946
434947
434948
434949
434950
434951
434952
434953
434954
434955
434956
434957
434958
434959
434960
434961
434962
434963
434964
434965
434966
434967
434968
434969
434970
434971
434972
434973
434974
434975
434976
434977
434978
434979
434980
434981
434982
434983
434984
434985
434986
434987
434988
434989
434990
434991
434992
434993
434994
434995
434996
434997
434998
434999
435000
435001
435002
435003
435004
435005
435006
435007
435008
435009
435010
435011
435012
435013
435014
435015
435016
435017
435018
435019
435020
435021
435022
435023
435024
435025
435026
435027
435028
435029
435030
435031
435032
435033
435034
435035
435036
435037
435038
435039
435040
435041
435042
435043
435044
435045
435046
435047
435048
435049
435050
435051
435052
435053
435054
435055
435056
435057
435058
435059
435060
435061
435062
435063
435064
435065
435066
435067
435068
435069
435070
435071
435072
435073
435074
435075
435076
435077
435078
435079
435080
435081
435082
435083
435084
435085
435086
435087
435088
435089
435090
435091
435092
435093
435094
435095
435096
435097
435098
435099
435100
435101
435102
435103
435104
435105
435106
435107
435108
435109
435110
435111
435112
435113
435114
435115
435116
435117
435118
435119
435120
435121
435122
435123
435124
435125
435126
435127
435128
435129
435130
435131
435132
435133
435134
435135
435136
435137
435138
435139
435140
435141
435142
435143
435144
435145
435146
435147
435148
435149
435150
435151
435152
435153
435154
435155
435156
435157
435158
435159
435160
435161
435162
435163
435164
435165
435166
435167
435168
435169
435170
435171
435172
435173
435174
435175
435176
435177
435178
435179
435180
435181
435182
435183
435184
435185
435186
435187
435188
435189
435190
435191
435192
435193
435194
435195
435196
435197
435198
435199
435200
435201
435202
435203
435204
435205
435206
435207
435208
435209
435210
435211
435212
435213
435214
435215
435216
435217
435218
435219
435220
435221
435222
435223
435224
435225
435226
435227
435228
435229
435230
435231
435232
435233
435234
435235
435236
435237
435238
435239
435240
435241
435242
435243
435244
435245
435246
435247
435248
435249
435250
435251
435252
435253
435254
435255
435256
435257
435258
435259
435260
435261
435262
435263
435264
435265
435266
435267
435268
435269
435270
435271
435272
435273
435274
435275
435276
435277
435278
435279
435280
435281
435282
435283
435284
435285
435286
435287
435288
435289
435290
435291
435292
435293
435294
435295
435296
435297
435298
435299
435300
435301
435302
435303
435304
435305
435306
435307
435308
435309
435310
435311
435312
435313
435314
435315
435316
435317
435318
435319
435320
435321
435322
435323
435324
435325
435326
435327
435328
435329
435330
435331
435332
435333
435334
435335
435336
435337
435338
435339
435340
435341
435342
435343
435344
435345
435346
435347
435348
435349
435350
435351
435352
435353
435354
435355
435356
435357
435358
435359
435360
435361
435362
435363
435364
435365
435366
435367
435368
435369
435370
435371
435372
435373
435374
435375
435376
435377
435378
435379
435380
435381
435382
435383
435384
435385
435386
435387
435388
435389
435390
435391
435392
435393
435394
435395
435396
435397
435398
435399
435400
435401
435402
435403
435404
435405
435406
435407
435408
435409
435410
435411
435412
435413
435414
435415
435416
435417
435418
435419
435420
435421
435422
435423
435424
435425
435426
435427
435428
435429
435430
435431
435432
435433
435434
435435
435436
435437
435438
435439
435440
435441
435442
435443
435444
435445
435446
435447
435448
435449
435450
435451
435452
435453
435454
435455
435456
435457
435458
435459
435460
435461
435462
435463
435464
435465
435466
435467
435468
435469
435470
435471
435472
435473
435474
435475
435476
435477
435478
435479
435480
435481
435482
435483
435484
435485
435486
435487
435488
435489
435490
435491
435492
435493
435494
435495
435496
435497
435498
435499
435500
435501
435502
435503
435504
435505
435506
435507
435508
435509
435510
435511
435512
435513
435514
435515
435516
435517
435518
435519
435520
435521
435522
435523
435524
435525
435526
435527
435528
435529
435530
435531
435532
435533
435534
435535
435536
435537
435538
435539
435540
435541
435542
435543
435544
435545
435546
435547
435548
435549
435550
435551
435552
435553
435554
435555
435556
435557
435558
435559
435560
435561
435562
435563
435564
435565
435566
435567
435568
435569
435570
435571
435572
435573
435574
435575
435576
435577
435578
435579
435580
435581
435582
435583
435584
435585
435586
435587
435588
435589
435590
435591
435592
435593
435594
435595
435596
435597
435598
435599
435600
435601
435602
435603
435604
435605
435606
435607
435608
435609
435610
435611
435612
435613
435614
435615
435616
435617
435618
435619
435620
435621
435622
435623
435624
435625
435626
435627
435628
435629
435630
435631
435632
435633
435634
435635
435636
435637
435638
435639
435640
435641
435642
435643
435644
435645
435646
435647
435648
435649
435650
435651
435652
435653
435654
435655
435656
435657
435658
435659
435660
435661
435662
435663
435664
435665
435666
435667
435668
435669
435670
435671
435672
435673
435674
435675
435676
435677
435678
435679
435680
435681
435682
435683
435684
435685
435686
435687
435688
435689
435690
435691
435692
435693
435694
435695
435696
435697
435698
435699
435700
435701
435702
435703
435704
435705
435706
435707
435708
435709
435710
435711
435712
435713
435714
435715
435716
435717
435718
435719
435720
435721
435722
435723
435724
435725
435726
435727
435728
435729
435730
435731
435732
435733
435734
435735
435736
435737
435738
435739
435740
435741
435742
435743
435744
435745
435746
435747
435748
435749
435750
435751
435752
435753
435754
435755
435756
435757
435758
435759
435760
435761
435762
435763
435764
435765
435766
435767
435768
435769
435770
435771
435772
435773
435774
435775
435776
435777
435778
435779
435780
435781
435782
435783
435784
435785
435786
435787
435788
435789
435790
435791
435792
435793
435794
435795
435796
435797
435798
435799
435800
435801
435802
435803
435804
435805
435806
435807
435808
435809
435810
435811
435812
435813
435814
435815
435816
435817
435818
435819
435820
435821
435822
435823
435824
435825
435826
435827
435828
435829
435830
435831
435832
435833
435834
435835
435836
435837
435838
435839
435840
435841
435842
435843
435844
435845
435846
435847
435848
435849
435850
435851
435852
435853
435854
435855
435856
435857
435858
435859
435860
435861
435862
435863
435864
435865
435866
435867
435868
435869
435870
435871
435872
435873
435874
435875
435876
435877
435878
435879
435880
435881
435882
435883
435884
435885
435886
435887
435888
435889
435890
435891
435892
435893
435894
435895
435896
435897
435898
435899
435900
435901
435902
435903
435904
435905
435906
435907
435908
435909
435910
435911
435912
435913
435914
435915
435916
435917
435918
435919
435920
435921
435922
435923
435924
435925
435926
435927
435928
435929
435930
435931
435932
435933
435934
435935
435936
435937
435938
435939
435940
435941
435942
435943
435944
435945
435946
435947
435948
435949
435950
435951
435952
435953
435954
435955
435956
435957
435958
435959
435960
435961
435962
435963
435964
435965
435966
435967
435968
435969
435970
435971
435972
435973
435974
435975
435976
435977
435978
435979
435980
435981
435982
435983
435984
435985
435986
435987
435988
435989
435990
435991
435992
435993
435994
435995
435996
435997
435998
435999
436000
436001
436002
436003
436004
436005
436006
436007
436008
436009
436010
436011
436012
436013
436014
436015
436016
436017
436018
436019
436020
436021
436022
436023
436024
436025
436026
436027
436028
436029
436030
436031
436032
436033
436034
436035
436036
436037
436038
436039
436040
436041
436042
436043
436044
436045
436046
436047
436048
436049
436050
436051
436052
436053
436054
436055
436056
436057
436058
436059
436060
436061
436062
436063
436064
436065
436066
436067
436068
436069
436070
436071
436072
436073
436074
436075
436076
436077
436078
436079
436080
436081
436082
436083
436084
436085
436086
436087
436088
436089
436090
436091
436092
436093
436094
436095
436096
436097
436098
436099
436100
436101
436102
436103
436104
436105
436106
436107
436108
436109
436110
436111
436112
436113
436114
436115
436116
436117
436118
436119
436120
436121
436122
436123
436124
436125
436126
436127
436128
436129
436130
436131
436132
436133
436134
436135
436136
436137
436138
436139
436140
436141
436142
436143
436144
436145
436146
436147
436148
436149
436150
436151
436152
436153
436154
436155
436156
436157
436158
436159
436160
436161
436162
436163
436164
436165
436166
436167
436168
436169
436170
436171
436172
436173
436174
436175
436176
436177
436178
436179
436180
436181
436182
436183
436184
436185
436186
436187
436188
436189
436190
436191
436192
436193
436194
436195
436196
436197
436198
436199
436200
436201
436202
436203
436204
436205
436206
436207
436208
436209
436210
436211
436212
436213
436214
436215
436216
436217
436218
436219
436220
436221
436222
436223
436224
436225
436226
436227
436228
436229
436230
436231
436232
436233
436234
436235
436236
436237
436238
436239
436240
436241
436242
436243
436244
436245
436246
436247
436248
436249
436250
436251
436252
436253
436254
436255
436256
436257
436258
436259
436260
436261
436262
436263
436264
436265
436266
436267
436268
436269
436270
436271
436272
436273
436274
436275
436276
436277
436278
436279
436280
436281
436282
436283
436284
436285
436286
436287
436288
436289
436290
436291
436292
436293
436294
436295
436296
436297
436298
436299
436300
436301
436302
436303
436304
436305
436306
436307
436308
436309
436310
436311
436312
436313
436314
436315
436316
436317
436318
436319
436320
436321
436322
436323
436324
436325
436326
436327
436328
436329
436330
436331
436332
436333
436334
436335
436336
436337
436338
436339
436340
436341
436342
436343
436344
436345
436346
436347
436348
436349
436350
436351
436352
436353
436354
436355
436356
436357
436358
436359
436360
436361
436362
436363
436364
436365
436366
436367
436368
436369
436370
436371
436372
436373
436374
436375
436376
436377
436378
436379
436380
436381
436382
436383
436384
436385
436386
436387
436388
436389
436390
436391
436392
436393
436394
436395
436396
436397
436398
436399
436400
436401
436402
436403
436404
436405
436406
436407
436408
436409
436410
436411
436412
436413
436414
436415
436416
436417
436418
436419
436420
436421
436422
436423
436424
436425
436426
436427
436428
436429
436430
436431
436432
436433
436434
436435
436436
436437
436438
436439
436440
436441
436442
436443
436444
436445
436446
436447
436448
436449
436450
436451
436452
436453
436454
436455
436456
436457
436458
436459
436460
436461
436462
436463
436464
436465
436466
436467
436468
436469
436470
436471
436472
436473
436474
436475
436476
436477
436478
436479
436480
436481
436482
436483
436484
436485
436486
436487
436488
436489
436490
436491
436492
436493
436494
436495
436496
436497
436498
436499
436500
436501
436502
436503
436504
436505
436506
436507
436508
436509
436510
436511
436512
436513
436514
436515
436516
436517
436518
436519
436520
436521
436522
436523
436524
436525
436526
436527
436528
436529
436530
436531
436532
436533
436534
436535
436536
436537
436538
436539
436540
436541
436542
436543
436544
436545
436546
436547
436548
436549
436550
436551
436552
436553
436554
436555
436556
436557
436558
436559
436560
436561
436562
436563
436564
436565
436566
436567
436568
436569
436570
436571
436572
436573
436574
436575
436576
436577
436578
436579
436580
436581
436582
436583
436584
436585
436586
436587
436588
436589
436590
436591
436592
436593
436594
436595
436596
436597
436598
436599
436600
436601
436602
436603
436604
436605
436606
436607
436608
436609
436610
436611
436612
436613
436614
436615
436616
436617
436618
436619
436620
436621
436622
436623
436624
436625
436626
436627
436628
436629
436630
436631
436632
436633
436634
436635
436636
436637
436638
436639
436640
436641
436642
436643
436644
436645
436646
436647
436648
436649
436650
436651
436652
436653
436654
436655
436656
436657
436658
436659
436660
436661
436662
436663
436664
436665
436666
436667
436668
436669
436670
436671
436672
436673
436674
436675
436676
436677
436678
436679
436680
436681
436682
436683
436684
436685
436686
436687
436688
436689
436690
436691
436692
436693
436694
436695
436696
436697
436698
436699
436700
436701
436702
436703
436704
436705
436706
436707
436708
436709
436710
436711
436712
436713
436714
436715
436716
436717
436718
436719
436720
436721
436722
436723
436724
436725
436726
436727
436728
436729
436730
436731
436732
436733
436734
436735
436736
436737
436738
436739
436740
436741
436742
436743
436744
436745
436746
436747
436748
436749
436750
436751
436752
436753
436754
436755
436756
436757
436758
436759
436760
436761
436762
436763
436764
436765
436766
436767
436768
436769
436770
436771
436772
436773
436774
436775
436776
436777
436778
436779
436780
436781
436782
436783
436784
436785
436786
436787
436788
436789
436790
436791
436792
436793
436794
436795
436796
436797
436798
436799
436800
436801
436802
436803
436804
436805
436806
436807
436808
436809
436810
436811
436812
436813
436814
436815
436816
436817
436818
436819
436820
436821
436822
436823
436824
436825
436826
436827
436828
436829
436830
436831
436832
436833
436834
436835
436836
436837
436838
436839
436840
436841

In [ ]:
dim_match_squad

        Match_Squad_Key  Match  Team  Player_Version  Sub
0                     1   8479    97        233074.0   No
1                     2   8479    97        233111.0   No
2                     3   8479    97        233150.0   No
3                     4   8479    97        233110.0   No
4                     5   8479    97        233096.0   No
...                 ...    ...   ...             ...  ...
438988           438989  12622   136         51506.0  Yes
438989           438990  12622   136         51352.0  Yes
438990           438991  12622   136         51385.0  Yes
438991           438992  12622   136         51400.0  Yes
438992           438993  12622   136         43875.0  Yes

[438993 rows x 5 columns]

In [ ]:
dim_match_squad.isna().sum()

Match_Squad_Key         0
Match                   0
Team                    0
Player_Version     150831
Sub                     0
dtype: int64

<h3>8. Dim MatchGoals</h3>

In [ ]:
fbref_matchgoals_new = fbref_matchgoals

In [ ]:
fbref_matchgoals_new

,Match_Id,Team,Minute,Player_Name,Type_Of_Goal,Is_Home_Team
0,39b738ac,Saint-Étienne,10,Unknown,Unknown,Yes
1,39b738ac,Strasbourg,32,Unknown,Unknown,No
2,39b738ac,Saint-Étienne,41,Hernani,Normal,Yes
3,39b738ac,Saint-Étienne,43,Unknown,Unknown,Yes
4,39b738ac,Strasbourg,44,Jean-Eudes Aholou,Normal,No
...,...,...,...,...,...,...
182193,f6279636,Empoli,77,Unknown,Unknown,No
182194,f6279636,Lazio,85,Unknown,Unknown,Yes
182195,f6279636,Lazio,88,Unknown,Unknown,Yes
182196,f6279636,Lazio,89,Matías Vecino,Normal,Yes
182197,f6279636,Lazio,90+5,Unknown,Unknown,Yes

In [ ]:
fbref_matchgoals_new.count()

Match_Id        182198
Team            182198
Minute          182198
Player_Name     182198
Type_Of_Goal    182198
Is_Home_Team    182198
dtype: int64

In [ ]:
different_team = set(dim_team['Team_Name']) - set(fbref_matchgoals_new['Team'])
different_team

set()

In [ ]:
dim_match_goals = pd.DataFrame({'Match_Goal_Key': [],
                                'Match': [],
                                'Team': [],
                                'Player_Name': [],
                                'Minute': [],
                                'Type_Of_Goal': []})

list_match_goals_key = []
list_match = []
list_team = []
#list_player_name = []

for i in range(0,len(fbref_matchgoals_new)):
    print(i)
    list_match_goals_key.append(i+1)

    temp_df = dim_match[dim_match['Match_Id'] == fbref_matchgoals_new['Match_Id'].iloc[i]]
    if (len(temp_df) > 0):
        list_match.append(temp_df['Match_Key'].iloc[0])
    else:
        list_match.append(np.nan)

    temp_df = dim_team[dim_team['Team_Name'] == fbref_matchgoals_new['Team'].iloc[i]]
    if (len(temp_df) > 0):
        list_team.append(temp_df['Team_Key'].iloc[0])
    else:
        list_team.append(np.nan)

    #sofifa_df = merge[(merge['Match_Id'] == fbref_matchgoals_new['Match_Id'].iloc[i]) &
    #                  (merge['Team'] == fbref_matchgoals_new['Team'].iloc[i]) &
    #                  (merge['Player_Name'] == fbref_matchgoals_new['Player_Name'].iloc[i])]

    #if (len(sofifa_df) > 0):
    #    sofifa_id = sofifa_df['Sofifa_Id'].iloc[0]
    #else:
    #    sofifa_id = np.nan

    #if (~np.isnan(sofifa_id)):

    #    temp_df = dim_player[dim_player['Player_Id'] == sofifa_id]
    #    if (len(temp_df) > 0):
    #        list_player_name.append(temp_df['Player_Key'].iloc[0])
    #    else:
    #        list_player_name.append(np.nan)
    #else:
    #    list_player.append(np.nan)

dim_match_goals['Match_Goal_Key'] = list_match_goals_key
dim_match_goals['Match'] = list_match
dim_match_goals['Team'] = list_team
dim_match_goals['Player_Name'] = fbref_matchgoals_new['Player_Name'].to_list()
dim_match_goals['Minute'] = fbref_matchgoals_new['Minute'].to_list()
dim_match_goals['Type_Of_Goal'] = fbref_matchgoals_new['Type_Of_Goal'].to_list()

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
177198
177199
177200
177201
177202
177203
177204
177205
177206
177207
177208
177209
177210
177211
177212
177213
177214
177215
177216
177217
177218
177219
177220
177221
177222
177223
177224
177225
177226
177227
177228
177229
177230
177231
177232
177233
177234
177235
177236
177237
177238
177239
177240
177241
177242
177243
177244
177245
177246
177247
177248
177249
177250
177251
177252
177253
177254
177255
177256
177257
177258
177259
177260
177261
177262
177263
177264
177265
177266
177267
177268
177269
177270
177271
177272
177273
177274
177275
177276
177277
177278
177279
177280
177281
177282
177283
177284
177285
177286
177287
177288
177289
177290
177291
177292
177293
177294
177295
177296
177297
177298
177299
177300
177301
177302
177303
177304
177305
177306
177307
177308
177309
177310
177311
177312
177313
177314
177315
177316
177317
177318
177319
177320
177321
177322
177323
177324
177325
177326
177327
177328
177329
177330
177331
177332
177333
177334
177335
177336
177337
177338
177339
177340
177341
177342
177343
177344
177345
177346
177347
177348
177349
177350
177351
177352
177353
177354
177355
177356
177357
177358
177359
177360
177361
177362
177363
177364
177365
177366
177367
177368
177369
177370
177371
177372
177373
177374
177375
177376
177377
177378
177379
177380
177381
177382
177383
177384
177385
177386
177387
177388
177389
177390
177391
177392
177393
177394
177395
177396
177397
177398
177399
177400
177401
177402
177403
177404
177405
177406
177407
177408
177409
177410
177411
177412
177413
177414
177415
177416
177417
177418
177419
177420
177421
177422
177423
177424
177425
177426
177427
177428
177429
177430
177431
177432
177433
177434
177435
177436
177437
177438
177439
177440
177441
177442
177443
177444
177445
177446
177447
177448
177449
177450
177451
177452
177453
177454
177455
177456
177457
177458
177459
177460
177461
177462
177463
177464
177465
177466
177467
177468
177469
177470
177471
177472
177473
177474
177475
177476
177477
177478
177479
177480
177481
177482
177483
177484
177485
177486
177487
177488
177489
177490
177491
177492
177493
177494
177495
177496
177497
177498
177499
177500
177501
177502
177503
177504
177505
177506
177507
177508
177509
177510
177511
177512
177513
177514
177515
177516
177517
177518
177519
177520
177521
177522
177523
177524
177525
177526
177527
177528
177529
177530
177531
177532
177533
177534
177535
177536
177537
177538
177539
177540
177541
177542
177543
177544
177545
177546
177547
177548
177549
177550
177551
177552
177553
177554
177555
177556
177557
177558
177559
177560
177561
177562
177563
177564
177565
177566
177567
177568
177569
177570
177571
177572
177573
177574
177575
177576
177577
177578
177579
177580
177581
177582
177583
177584
177585
177586
177587
177588
177589
177590
177591
177592
177593
177594
177595
177596
177597
177598
177599
177600
177601
177602
177603
177604
177605
177606
177607
177608
177609
177610
177611
177612
177613
177614
177615
177616
177617
177618
177619
177620
177621
177622
177623
177624
177625
177626
177627
177628
177629
177630
177631
177632
177633
177634
177635
177636
177637
177638
177639
177640
177641
177642
177643
177644
177645
177646
177647
177648
177649
177650
177651
177652
177653
177654
177655
177656
177657
177658
177659
177660
177661
177662
177663
177664
177665
177666
177667
177668
177669
177670
177671
177672
177673
177674
177675
177676
177677
177678
177679
177680
177681
177682
177683
177684
177685
177686
177687
177688
177689
177690
177691
177692
177693
177694
177695
177696
177697
177698
177699
177700
177701
177702
177703
177704
177705
177706
177707
177708
177709
177710
177711
177712
177713
177714
177715
177716
177717
177718
177719
177720
177721
177722
177723
177724
177725
177726
177727
177728
177729
177730
177731
177732
177733
177734
177735
177736
177737
177738
177739
177740
177741
177742
177743
177744
177745
177746
177747
177748
177749
177750
177751
177752
177753
177754
177755
177756
177757
177758
177759
177760
177761
177762
177763
177764
177765
177766
177767
177768
177769
177770
177771
177772
177773
177774
177775
177776
177777
177778
177779
177780
177781
177782
177783
177784
177785
177786
177787
177788
177789
177790
177791
177792
177793
177794
177795
177796
177797
177798
177799
177800
177801
177802
177803
177804
177805
177806
177807
177808
177809
177810
177811
177812
177813
177814
177815
177816
177817
177818
177819
177820
177821
177822
177823
177824
177825
177826
177827
177828
177829
177830
177831
177832
177833
177834
177835
177836
177837
177838
177839
177840
177841
177842
177843
177844
177845
177846
177847
177848
177849
177850
177851
177852
177853
177854
177855
177856
177857
177858
177859
177860
177861
177862
177863
177864
177865
177866
177867
177868
177869
177870
177871
177872
177873
177874
177875
177876
177877
177878
177879
177880
177881
177882
177883
177884
177885
177886
177887
177888
177889
177890
177891
177892
177893
177894
177895
177896
177897
177898
177899
177900
177901
177902
177903
177904
177905
177906
177907
177908
177909
177910
177911
177912
177913
177914
177915
177916
177917
177918
177919
177920
177921
177922
177923
177924
177925
177926
177927
177928
177929
177930
177931
177932
177933
177934
177935
177936
177937
177938
177939
177940
177941
177942
177943
177944
177945
177946
177947
177948
177949
177950
177951
177952
177953
177954
177955
177956
177957
177958
177959
177960
177961
177962
177963
177964
177965
177966
177967
177968
177969
177970
177971
177972
177973
177974
177975
177976
177977
177978
177979
177980
177981
177982
177983
177984
177985
177986
177987
177988
177989
177990
177991
177992
177993
177994
177995
177996
177997
177998
177999
178000
178001
178002
178003
178004
178005
178006
178007
178008
178009
178010
178011
178012
178013
178014
178015
178016
178017
178018
178019
178020
178021
178022
178023
178024
178025
178026
178027
178028
178029
178030
178031
178032
178033
178034
178035
178036
178037
178038
178039
178040
178041
178042
178043
178044
178045
178046
178047
178048
178049
178050
178051
178052
178053
178054
178055
178056
178057
178058
178059
178060
178061
178062
178063
178064
178065
178066
178067
178068
178069
178070
178071
178072
178073
178074
178075
178076
178077
178078
178079
178080
178081
178082
178083
178084
178085
178086
178087
178088
178089
178090
178091
178092
178093
178094
178095
178096
178097
178098
178099
178100
178101
178102
178103
178104
178105
178106
178107
178108
178109
178110
178111
178112
178113
178114
178115
178116
178117
178118
178119
178120
178121
178122
178123
178124
178125
178126
178127
178128
178129
178130
178131
178132
178133
178134
178135
178136
178137
178138
178139
178140
178141
178142
178143
178144
178145
178146
178147
178148
178149
178150
178151
178152
178153
178154
178155
178156
178157
178158
178159
178160
178161
178162
178163
178164
178165
178166
178167
178168
178169
178170
178171
178172
178173
178174
178175
178176
178177
178178
178179
178180
178181
178182
178183
178184
178185
178186
178187
178188
178189
178190
178191
178192
178193
178194
178195
178196
178197
178198
178199
178200
178201
178202
178203
178204
178205
178206
178207
178208
178209
178210
178211
178212
178213
178214
178215
178216
178217
178218
178219
178220
178221
178222
178223
178224
178225
178226
178227
178228
178229
178230
178231
178232
178233
178234
178235
178236
178237
178238
178239
178240
178241
178242
178243
178244
178245
178246
178247
178248
178249
178250
178251
178252
178253
178254
178255
178256
178257
178258
178259
178260
178261
178262
178263
178264
178265
178266
178267
178268
178269
178270
178271
178272
178273
178274
178275
178276
178277
178278
178279
178280
178281
178282
178283
178284
178285
178286
178287
178288
178289
178290
178291
178292
178293
178294
178295
178296
178297
178298
178299
178300
178301
178302
178303
178304
178305
178306
178307
178308
178309
178310
178311
178312
178313
178314
178315
178316
178317
178318
178319
178320
178321
178322
178323
178324
178325
178326
178327
178328
178329
178330
178331
178332
178333
178334
178335
178336
178337
178338
178339
178340
178341
178342
178343
178344
178345
178346
178347
178348
178349
178350
178351
178352
178353
178354
178355
178356
178357
178358
178359
178360
178361
178362
178363
178364
178365
178366
178367
178368
178369
178370
178371
178372
178373
178374
178375
178376
178377
178378
178379
178380
178381
178382
178383
178384
178385
178386
178387
178388
178389
178390
178391
178392
178393
178394
178395
178396
178397
178398
178399
178400
178401
178402
178403
178404
178405
178406
178407
178408
178409
178410
178411
178412
178413
178414
178415
178416
178417
178418
178419
178420
178421
178422
178423
178424
178425
178426
178427
178428
178429
178430
178431
178432
178433
178434
178435
178436
178437
178438
178439
178440
178441
178442
178443
178444
178445
178446
178447
178448
178449
178450
178451
178452
178453
178454
178455
178456
178457
178458
178459
178460
178461
178462
178463
178464
178465
178466
178467
178468
178469
178470
178471
178472
178473
178474
178475
178476
178477
178478
178479
178480
178481
178482
178483
178484
178485
178486
178487
178488
178489
178490
178491
178492
178493
178494
178495
178496
178497
178498
178499
178500
178501
178502
178503
178504
178505
178506
178507
178508
178509
178510
178511
178512
178513
178514
178515
178516
178517
178518
178519
178520
178521
178522
178523
178524
178525
178526
178527
178528
178529
178530
178531
178532
178533
178534
178535
178536
178537
178538
178539
178540
178541
178542
178543
178544
178545
178546
178547
178548
178549
178550
178551
178552
178553
178554
178555
178556
178557
178558
178559
178560
178561
178562
178563
178564
178565
178566
178567
178568
178569
178570
178571
178572
178573
178574
178575
178576
178577
178578
178579
178580
178581
178582
178583
178584
178585
178586
178587
178588
178589
178590
178591
178592
178593
178594
178595
178596
178597
178598
178599
178600
178601
178602
178603
178604
178605
178606
178607
178608
178609
178610
178611
178612
178613
178614
178615
178616
178617
178618
178619
178620
178621
178622
178623
178624
178625
178626
178627
178628
178629
178630
178631
178632
178633
178634
178635
178636
178637
178638
178639
178640
178641
178642
178643
178644
178645
178646
178647
178648
178649
178650
178651
178652
178653
178654
178655
178656
178657
178658
178659
178660
178661
178662
178663
178664
178665
178666
178667
178668
178669
178670
178671
178672
178673
178674
178675
178676
178677
178678
178679
178680
178681
178682
178683
178684
178685
178686
178687
178688
178689
178690
178691
178692
178693
178694
178695
178696
178697
178698
178699
178700
178701
178702
178703
178704
178705
178706
178707
178708
178709
178710
178711
178712
178713
178714
178715
178716
178717
178718
178719
178720
178721
178722
178723
178724
178725
178726
178727
178728
178729
178730
178731
178732
178733
178734
178735
178736
178737
178738
178739
178740
178741
178742
178743
178744
178745
178746
178747
178748
178749
178750
178751
178752
178753
178754
178755
178756
178757
178758
178759
178760
178761
178762
178763
178764
178765
178766
178767
178768
178769
178770
178771
178772
178773
178774
178775
178776
178777
178778
178779
178780
178781
178782
178783
178784
178785
178786
178787
178788
178789
178790
178791
178792
178793
178794
178795
178796
178797
178798
178799
178800
178801
178802
178803
178804
178805
178806
178807
178808
178809
178810
178811
178812
178813
178814
178815
178816
178817
178818
178819
178820
178821
178822
178823
178824
178825
178826
178827
178828
178829
178830
178831
178832
178833
178834
178835
178836
178837
178838
178839
178840
178841
178842
178843
178844
178845
178846
178847
178848
178849
178850
178851
178852
178853
178854
178855
178856
178857
178858
178859
178860
178861
178862
178863
178864
178865
178866
178867
178868
178869
178870
178871
178872
178873
178874
178875
178876
178877
178878
178879
178880
178881
178882
178883
178884
178885
178886
178887
178888
178889
178890
178891
178892
178893
178894
178895
178896
178897
178898
178899
178900
178901
178902
178903
178904
178905
178906
178907
178908
178909
178910
178911
178912
178913
178914
178915
178916
178917
178918
178919
178920
178921
178922
178923
178924
178925
178926
178927
178928
178929
178930
178931
178932
178933
178934
178935
178936
178937
178938
178939
178940
178941
178942
178943
178944
178945
178946
178947
178948
178949
178950
178951
178952
178953
178954
178955
178956
178957
178958
178959
178960
178961
178962
178963
178964
178965
178966
178967
178968
178969
178970
178971
178972
178973
178974
178975
178976
178977
178978
178979
178980
178981
178982
178983
178984
178985
178986
178987
178988
178989
178990
178991
178992
178993
178994
178995
178996
178997
178998
178999
179000
179001
179002
179003
179004
179005
179006
179007
179008
179009
179010
179011
179012
179013
179014
179015
179016
179017
179018
179019
179020
179021
179022
179023
179024
179025
179026
179027
179028
179029
179030
179031
179032
179033
179034
179035
179036
179037
179038
179039
179040
179041
179042
179043
179044
179045
179046
179047
179048
179049
179050
179051
179052
179053
179054
179055
179056
179057
179058
179059
179060
179061
179062
179063
179064
179065
179066
179067
179068
179069
179070
179071
179072
179073
179074
179075
179076
179077
179078
179079
179080
179081
179082
179083
179084
179085
179086
179087
179088
179089
179090
179091
179092
179093
179094
179095
179096
179097
179098
179099
179100
179101
179102
179103
179104
179105
179106
179107
179108
179109
179110
179111
179112
179113
179114
179115
179116
179117
179118
179119
179120
179121
179122
179123
179124
179125
179126
179127
179128
179129
179130
179131
179132
179133
179134
179135
179136
179137
179138
179139
179140
179141
179142
179143
179144
179145
179146
179147
179148
179149
179150
179151
179152
179153
179154
179155
179156
179157
179158
179159
179160
179161
179162
179163
179164
179165
179166
179167
179168
179169
179170
179171
179172
179173
179174
179175
179176
179177
179178
179179
179180
179181
179182
179183
179184
179185
179186
179187
179188
179189
179190
179191
179192
179193
179194
179195
179196
179197
179198
179199
179200
179201
179202
179203
179204
179205
179206
179207
179208
179209
179210
179211
179212
179213
179214
179215
179216
179217
179218
179219
179220
179221
179222
179223
179224
179225
179226
179227
179228
179229
179230
179231
179232
179233
179234
179235
179236
179237
179238
179239
179240
179241
179242
179243
179244
179245
179246
179247
179248
179249
179250
179251
179252
179253
179254
179255
179256
179257
179258
179259
179260
179261
179262
179263
179264
179265
179266
179267
179268
179269
179270
179271
179272
179273
179274
179275
179276
179277
179278
179279
179280
179281
179282
179283
179284
179285
179286
179287
179288
179289
179290
179291
179292
179293
179294
179295
179296
179297
179298
179299
179300
179301
179302
179303
179304
179305
179306
179307
179308
179309
179310
179311
179312
179313
179314
179315
179316
179317
179318
179319
179320
179321
179322
179323
179324
179325
179326
179327
179328
179329
179330
179331
179332
179333
179334
179335
179336
179337
179338
179339
179340
179341
179342
179343
179344
179345
179346
179347
179348
179349
179350
179351
179352
179353
179354
179355
179356
179357
179358
179359
179360
179361
179362
179363
179364
179365
179366
179367
179368
179369
179370
179371
179372
179373
179374
179375
179376
179377
179378
179379
179380
179381
179382
179383
179384
179385
179386
179387
179388
179389
179390
179391
179392
179393
179394
179395
179396
179397
179398
179399
179400
179401
179402
179403
179404
179405
179406
179407
179408
179409
179410
179411
179412
179413
179414
179415
179416
179417
179418
179419
179420
179421
179422
179423
179424
179425
179426
179427
179428
179429
179430
179431
179432
179433
179434
179435
179436
179437
179438
179439
179440
179441
179442
179443
179444
179445
179446
179447
179448
179449
179450
179451
179452
179453
179454
179455
179456
179457
179458
179459
179460
179461
179462
179463
179464
179465
179466
179467
179468
179469
179470
179471
179472
179473
179474
179475
179476
179477
179478
179479
179480
179481
179482
179483
179484
179485
179486
179487
179488
179489
179490
179491
179492
179493
179494
179495
179496
179497
179498
179499
179500
179501
179502
179503
179504
179505
179506
179507
179508
179509
179510
179511
179512
179513
179514
179515
179516
179517
179518
179519
179520
179521
179522
179523
179524
179525
179526
179527
179528
179529
179530
179531
179532
179533
179534
179535
179536
179537
179538
179539
179540
179541
179542
179543
179544
179545
179546
179547
179548
179549
179550
179551
179552
179553
179554
179555
179556
179557
179558
179559
179560
179561
179562
179563
179564
179565
179566
179567
179568
179569
179570
179571
179572
179573
179574
179575
179576
179577
179578
179579
179580
179581
179582
179583
179584
179585
179586
179587
179588
179589
179590
179591
179592
179593
179594
179595
179596
179597
179598
179599
179600
179601
179602
179603
179604
179605
179606
179607
179608
179609
179610
179611
179612
179613
179614
179615
179616
179617
179618
179619
179620
179621
179622
179623
179624
179625
179626
179627
179628
179629
179630
179631
179632
179633
179634
179635
179636
179637
179638
179639
179640
179641
179642
179643
179644
179645
179646
179647
179648
179649
179650
179651
179652
179653
179654
179655
179656
179657
179658
179659
179660
179661
179662
179663
179664
179665
179666
179667
179668
179669
179670
179671
179672
179673
179674
179675
179676
179677
179678
179679
179680
179681
179682
179683
179684
179685
179686
179687
179688
179689
179690
179691
179692
179693
179694
179695
179696
179697
179698
179699
179700
179701
179702
179703
179704
179705
179706
179707
179708
179709
179710
179711
179712
179713
179714
179715
179716
179717
179718
179719
179720
179721
179722
179723
179724
179725
179726
179727
179728
179729
179730
179731
179732
179733
179734
179735
179736
179737
179738
179739
179740
179741
179742
179743
179744
179745
179746
179747
179748
179749
179750
179751
179752
179753
179754
179755
179756
179757
179758
179759
179760
179761
179762
179763
179764
179765
179766
179767
179768
179769
179770
179771
179772
179773
179774
179775
179776
179777
179778
179779
179780
179781
179782
179783
179784
179785
179786
179787
179788
179789
179790
179791
179792
179793
179794
179795
179796
179797
179798
179799
179800
179801
179802
179803
179804
179805
179806
179807
179808
179809
179810
179811
179812
179813
179814
179815
179816
179817
179818
179819
179820
179821
179822
179823
179824
179825
179826
179827
179828
179829
179830
179831
179832
179833
179834
179835
179836
179837
179838
179839
179840
179841
179842
179843
179844
179845
179846
179847
179848
179849
179850
179851
179852
179853
179854
179855
179856
179857
179858
179859
179860
179861
179862
179863
179864
179865
179866
179867
179868
179869
179870
179871
179872
179873
179874
179875
179876
179877
179878
179879
179880
179881
179882
179883
179884
179885
179886
179887
179888
179889
179890
179891
179892
179893
179894
179895
179896
179897
179898
179899
179900
179901
179902
179903
179904
179905
179906
179907
179908
179909
179910
179911
179912
179913
179914
179915
179916
179917
179918
179919
179920
179921
179922
179923
179924
179925
179926
179927
179928
179929
179930
179931
179932
179933
179934
179935
179936
179937
179938
179939
179940
179941
179942
179943
179944
179945
179946
179947
179948
179949
179950
179951
179952
179953
179954
179955
179956
179957
179958
179959
179960
179961
179962
179963
179964
179965
179966
179967
179968
179969
179970
179971
179972
179973
179974
179975
179976
179977
179978
179979
179980
179981
179982
179983
179984
179985
179986
179987
179988
179989
179990
179991
179992
179993
179994
179995
179996
179997
179998
179999
180000
180001
180002
180003
180004
180005
180006
180007
180008
180009
180010
180011
180012
180013
180014
180015
180016
180017
180018
180019
180020
180021
180022
180023
180024
180025
180026
180027
180028
180029
180030
180031
180032
180033
180034
180035
180036
180037
180038
180039
180040
180041
180042
180043
180044
180045
180046

In [ ]:
dim_match_goals

        Match_Goal_Key  Match  Team        Player_Name Minute Type_Of_Goal
0                    1     51     4            Unknown     10      Unknown
1                    2     51    19            Unknown     32      Unknown
2                    3     51     4            Hernani     41       Normal
3                    4     51     4            Unknown     43      Unknown
4                    5     51    19  Jean-Eudes Aholou     44       Normal
...                ...    ...   ...                ...    ...          ...
182193          182194  12622   136            Unknown     77      Unknown
182194          182195  12622   124            Unknown     85      Unknown
182195          182196  12622   124            Unknown     88      Unknown
182196          182197  12622   124      Matías Vecino     89       Normal
182197          182198  12622   124            Unknown   90+5      Unknown

[182198 rows x 6 columns]

In [ ]:
dim_match_goals = dim_match_goals[dim_match_goals['Type_Of_Goal'] != 'Unknown']

In [ ]:
dim_match_goals

        Match_Goal_Key  Match  Team          Player_Name Minute Type_Of_Goal
2                    3     51     4              Hernani     41       Normal
4                    5     51    19    Jean-Eudes Aholou     44       Normal
5                    6     51     4  Kévin Monnet-Paquet     56       Normal
7                    8     51    19         Jonas Martin     63      Penalty
16                  17    287     8          Luiz Araújo     13       Normal
...                ...    ...   ...                  ...    ...          ...
182165          182166  12621   131          Rafael Leão     83       Normal
182167          182168  12621   131    Christian Pulisic     86       Normal
182169          182170  12633   138       Walid Cheddira      9       Normal
182182          182183  12622   124               Patric   45+3       Normal
182196          182197  12622   124        Matías Vecino     89       Normal

[36070 rows x 6 columns]

In [ ]:
dim_match_goals.isna().sum()

Match_Goal_Key    0
Match             0
Team              0
Player_Name       0
Minute            0
Type_Of_Goal      0
dtype: int64

<h2>II. Fact Tables</h2>

<h3>1. Fact Player Attributes</h3>

In [ ]:
#sofifa
sofifa_players = pd.read_csv('gs://football_data_etl/football_data_extracted/output-basic/sofifa_players_attr.csv/part-00000-0474179e-867f-4f31-9d30-40c396f830f5-c000.csv',
                                  on_bad_lines="skip")

sofifa_players['Birthday'] = pd.to_datetime(sofifa_players['Birthday'])
sofifa_players['Birthday'] = sofifa_players['Birthday'].dt.strftime('%Y-%m-%d')
sofifa_players['Club_Joined'] = pd.to_datetime(sofifa_players['Club_Joined'])
sofifa_players['Club_Joined'] = sofifa_players['Club_Joined'].dt.strftime('%Y-%m-%d')
sofifa_players['Update_Date'] = pd.to_datetime(sofifa_players['Update_Date'])
sofifa_players['Update_Date'] = sofifa_players['Update_Date'].dt.strftime('%Y-%m-%d')

<ipython-input-78-9b6878256552>:2: DtypeWarning: Columns (45) have mixed types. Specify dtype option on import or set low_memory=False.
  sofifa_players = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/fbref/sofifa_players_attr.csv/part-00000-0474179e-867f-4f31-9d30-40c396f830f5-c000.csv',

In [ ]:
fact_player_attributes = pd.DataFrame({'Player_Version': [],
                                'Acceleration': [], 'Aggression': [], 'Agility': [],
                                'Balance': [], 'Ball_Control': [], 'Composure': [],
                                'Crossing': [], 'Curve': [], 'Dribbling': [],
                                'Finishing': [], 'Fk_Accuracy': [], 'Gk_Diving': [],
                                'Gk_Handling': [], 'Gk_Kicking': [], 'Gk_Positioning': [],
                                'Gk_Reflexes': [], 'Heading_Accuracy': [], 'Height': [],
                                'Interceptions': [], 'Jumping': [], 'Long_Passing': [],
                                'Long_Shots': [], 'Overall_Rating': [], 'Penalties': [],
                                'Positioning': [], 'Potential': [], 'Reactions': [],
                                'Reputation': [], 'Short_Passing': [], 'Shot_Power': [],
                                'Skill_Moves': [], 'Sliding_Tackle': [], 'Sprint_Speed': [],
                                'Stamina': [], 'Standing_Tackle': [], 'Strength': [], 'Value': [],
                                'Vision': [], 'Volleys': [], 'Wage': [],
                                'Weak_Foot': [], 'Weight': []})

list_player_version = []


for i in range(0,len(sofifa_players)):

    print(i)

    player_df = dim_player[dim_player['Player_Id'] == sofifa_players['Sofifa_Id'].iloc[i]]

    if (len(player_df) > 0):
        player_key = player_df['Player_Key'].iloc[0]
    else:
        player_key = np.nan

    temp_df = dim_player_version[dim_player_version['Player'] == player_key]
    if (len(temp_df) > 0):
        list_player_version.append(temp_df['Player_Version_Key'].iloc[0])
    else:
        list_player_version.append(np.nan)

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
286047
286048
286049
286050
286051
286052
286053
286054
286055
286056
286057
286058
286059
286060
286061
286062
286063
286064
286065
286066
286067
286068
286069
286070
286071
286072
286073
286074
286075
286076
286077
286078
286079
286080
286081
286082
286083
286084
286085
286086
286087
286088
286089
286090
286091
286092
286093
286094
286095
286096
286097
286098
286099
286100
286101
286102
286103
286104
286105
286106
286107
286108
286109
286110
286111
286112
286113
286114
286115
286116
286117
286118
286119
286120
286121
286122
286123
286124
286125
286126
286127
286128
286129
286130
286131
286132
286133
286134
286135
286136
286137
286138
286139
286140
286141
286142
286143
286144
286145
286146
286147
286148
286149
286150
286151
286152
286153
286154
286155
286156
286157
286158
286159
286160
286161
286162
286163
286164
286165
286166
286167
286168
286169
286170
286171
286172
286173
286174
286175
286176
286177
286178
286179
286180
286181
286182
286183
286184
286185
286186
286187
286188
286189
286190
286191
286192
286193
286194
286195
286196
286197
286198
286199
286200
286201
286202
286203
286204
286205
286206
286207
286208
286209
286210
286211
286212
286213
286214
286215
286216
286217
286218
286219
286220
286221
286222
286223
286224
286225
286226
286227
286228
286229
286230
286231
286232
286233
286234
286235
286236
286237
286238
286239
286240
286241
286242
286243
286244
286245
286246
286247
286248
286249
286250
286251
286252
286253
286254
286255
286256
286257
286258
286259
286260
286261
286262
286263
286264
286265
286266
286267
286268
286269
286270
286271
286272
286273
286274
286275
286276
286277
286278
286279
286280
286281
286282
286283
286284
286285
286286
286287
286288
286289
286290
286291
286292
286293
286294
286295
286296
286297
286298
286299
286300
286301
286302
286303
286304
286305
286306
286307
286308
286309
286310
286311
286312
286313
286314
286315
286316
286317
286318
286319
286320
286321
286322
286323
286324
286325
286326
286327
286328
286329
286330
286331
286332
286333
286334
286335
286336
286337
286338
286339
286340
286341
286342
286343
286344
286345
286346
286347
286348
286349
286350
286351
286352
286353
286354
286355
286356
286357
286358
286359
286360
286361
286362
286363
286364
286365
286366
286367
286368
286369
286370
286371
286372
286373
286374
286375
286376
286377
286378
286379
286380
286381
286382
286383
286384
286385
286386
286387
286388
286389
286390
286391
286392
286393
286394
286395
286396
286397
286398
286399
286400
286401
286402
286403
286404
286405
286406
286407
286408
286409
286410
286411
286412
286413
286414
286415
286416
286417
286418
286419
286420
286421
286422
286423
286424
286425
286426
286427
286428
286429
286430
286431
286432
286433
286434
286435
286436
286437
286438
286439
286440
286441
286442
286443
286444
286445
286446
286447
286448
286449
286450
286451
286452
286453
286454
286455
286456
286457
286458
286459
286460
286461
286462
286463
286464
286465
286466
286467
286468
286469
286470
286471
286472
286473
286474
286475
286476
286477
286478
286479
286480
286481
286482
286483
286484
286485
286486
286487
286488
286489
286490
286491
286492
286493
286494
286495
286496
286497
286498
286499
286500
286501
286502
286503
286504
286505
286506
286507
286508
286509
286510
286511
286512
286513
286514
286515
286516
286517
286518
286519
286520
286521
286522
286523
286524
286525
286526
286527
286528
286529
286530
286531
286532
286533
286534
286535
286536
286537
286538
286539
286540
286541
286542
286543
286544
286545
286546
286547
286548
286549
286550
286551
286552
286553
286554
286555
286556
286557
286558
286559
286560
286561
286562
286563
286564
286565
286566
286567
286568
286569
286570
286571
286572
286573
286574
286575
286576
286577
286578
286579
286580
286581
286582
286583
286584
286585
286586
286587
286588
286589
286590
286591
286592
286593
286594
286595
286596
286597
286598
286599
286600
286601
286602
286603
286604
286605
286606
286607
286608
286609
286610
286611
286612
286613
286614
286615
286616
286617
286618
286619
286620
286621
286622
286623
286624
286625
286626
286627
286628
286629
286630
286631
286632
286633
286634
286635
286636
286637
286638
286639
286640
286641
286642
286643
286644
286645
286646
286647
286648
286649
286650
286651
286652
286653
286654
286655
286656
286657
286658
286659
286660
286661
286662
286663
286664
286665
286666
286667
286668
286669
286670
286671
286672
286673
286674
286675
286676
286677
286678
286679
286680
286681
286682
286683
286684
286685
286686
286687
286688
286689
286690
286691
286692
286693
286694
286695
286696
286697
286698
286699
286700
286701
286702
286703
286704
286705
286706
286707
286708
286709
286710
286711
286712
286713
286714
286715
286716
286717
286718
286719
286720
286721
286722
286723
286724
286725
286726
286727
286728
286729
286730
286731
286732
286733
286734
286735
286736
286737
286738
286739
286740
286741
286742
286743
286744
286745
286746
286747
286748
286749
286750
286751
286752
286753
286754
286755
286756
286757
286758
286759
286760
286761
286762
286763
286764
286765
286766
286767
286768
286769
286770
286771
286772
286773
286774
286775
286776
286777
286778
286779
286780
286781
286782
286783
286784
286785
286786
286787
286788
286789
286790
286791
286792
286793
286794
286795
286796
286797
286798
286799
286800
286801
286802
286803
286804
286805
286806
286807
286808
286809
286810
286811
286812
286813
286814
286815
286816
286817
286818
286819
286820
286821
286822
286823
286824
286825
286826
286827
286828
286829
286830
286831
286832
286833
286834
286835
286836
286837
286838
286839
286840
286841
286842
286843
286844
286845
286846
286847
286848
286849
286850
286851
286852
286853
286854
286855
286856
286857
286858
286859
286860
286861
286862
286863
286864
286865
286866
286867
286868
286869
286870
286871
286872
286873
286874
286875
286876
286877
286878
286879
286880
286881
286882
286883
286884
286885
286886
286887
286888
286889
286890
286891
286892
286893
286894
286895
286896
286897
286898
286899
286900
286901
286902
286903
286904
286905
286906
286907
286908
286909
286910
286911
286912
286913
286914
286915
286916
286917
286918
286919
286920
286921
286922
286923
286924
286925
286926
286927
286928
286929
286930
286931
286932
286933
286934
286935
286936
286937
286938
286939
286940
286941
286942
286943
286944
286945
286946
286947
286948
286949
286950
286951
286952
286953
286954
286955
286956
286957
286958
286959
286960
286961
286962
286963
286964
286965
286966
286967
286968
286969
286970
286971
286972
286973
286974
286975
286976
286977
286978
286979
286980
286981
286982
286983
286984
286985
286986
286987
286988
286989
286990
286991
286992
286993
286994
286995
286996
286997
286998
286999
287000
287001
287002
287003
287004
287005
287006
287007
287008
287009
287010
287011
287012
287013
287014
287015
287016
287017
287018
287019
287020
287021
287022
287023
287024
287025
287026
287027
287028
287029
287030
287031
287032
287033
287034
287035
287036
287037
287038
287039
287040
287041
287042
287043
287044
287045
287046
287047
287048
287049
287050
287051
287052
287053
287054
287055
287056
287057
287058
287059
287060
287061
287062
287063
287064
287065
287066
287067
287068
287069
287070
287071
287072
287073
287074
287075
287076
287077
287078
287079
287080
287081
287082
287083
287084
287085
287086
287087
287088
287089
287090
287091
287092
287093
287094
287095
287096
287097
287098
287099
287100
287101
287102
287103
287104
287105
287106
287107
287108
287109
287110
287111
287112
287113
287114
287115
287116
287117
287118
287119
287120
287121
287122
287123
287124
287125
287126
287127
287128
287129
287130
287131
287132
287133
287134
287135
287136
287137
287138
287139
287140
287141
287142
287143
287144
287145
287146
287147
287148
287149
287150
287151
287152
287153
287154
287155
287156
287157
287158
287159
287160
287161
287162
287163
287164
287165
287166
287167
287168
287169
287170
287171
287172
287173
287174
287175
287176
287177
287178
287179
287180
287181
287182
287183
287184
287185
287186
287187
287188
287189
287190
287191
287192
287193
287194
287195
287196
287197
287198
287199
287200
287201
287202
287203
287204
287205
287206
287207
287208
287209
287210
287211
287212
287213
287214
287215
287216
287217
287218
287219
287220
287221
287222
287223
287224
287225
287226
287227
287228
287229
287230
287231
287232
287233
287234
287235
287236
287237
287238
287239
287240
287241
287242
287243
287244
287245
287246
287247
287248
287249
287250
287251
287252
287253
287254
287255
287256
287257
287258
287259
287260
287261
287262
287263
287264
287265
287266
287267
287268
287269
287270
287271
287272
287273
287274
287275
287276
287277
287278
287279
287280
287281
287282
287283
287284
287285
287286
287287
287288
287289
287290
287291
287292
287293
287294
287295
287296
287297
287298
287299
287300
287301
287302
287303
287304
287305
287306
287307
287308
287309
287310
287311
287312
287313
287314
287315
287316
287317
287318
287319
287320
287321
287322
287323
287324
287325
287326
287327
287328
287329
287330
287331
287332
287333
287334
287335
287336
287337
287338
287339
287340
287341
287342
287343
287344
287345
287346
287347
287348
287349
287350
287351
287352
287353
287354
287355
287356
287357
287358
287359
287360
287361
287362
287363
287364
287365
287366
287367
287368
287369
287370
287371
287372
287373
287374
287375
287376
287377
287378
287379
287380
287381
287382
287383
287384
287385
287386
287387
287388
287389
287390
287391
287392
287393
287394
287395
287396
287397
287398
287399
287400
287401
287402
287403
287404
287405
287406
287407
287408
287409
287410
287411
287412
287413
287414
287415
287416
287417
287418
287419
287420
287421
287422
287423
287424
287425
287426
287427
287428
287429
287430
287431
287432
287433
287434
287435
287436
287437
287438
287439
287440
287441
287442
287443
287444
287445
287446
287447
287448
287449
287450
287451
287452
287453
287454
287455
287456
287457
287458
287459
287460
287461
287462
287463
287464
287465
287466
287467
287468
287469
287470
287471
287472
287473
287474
287475
287476
287477
287478
287479
287480
287481
287482
287483
287484
287485
287486
287487
287488
287489
287490
287491
287492
287493
287494
287495
287496
287497
287498
287499
287500
287501
287502
287503
287504
287505
287506
287507
287508
287509
287510
287511
287512
287513
287514
287515
287516
287517
287518
287519
287520
287521
287522
287523
287524
287525
287526
287527
287528
287529
287530
287531
287532
287533
287534
287535
287536
287537
287538
287539
287540
287541
287542
287543
287544
287545
287546
287547
287548
287549
287550
287551
287552
287553
287554
287555
287556
287557
287558
287559
287560
287561
287562
287563
287564
287565
287566
287567
287568
287569
287570
287571
287572
287573
287574
287575
287576
287577
287578
287579
287580
287581
287582
287583
287584
287585
287586
287587
287588
287589
287590
287591
287592
287593
287594
287595
287596
287597
287598
287599
287600
287601
287602
287603
287604
287605
287606
287607
287608
287609
287610
287611
287612
287613
287614
287615
287616
287617
287618
287619
287620
287621
287622
287623
287624
287625
287626
287627
287628
287629
287630
287631
287632
287633
287634
287635
287636
287637
287638
287639
287640
287641
287642
287643
287644
287645
287646
287647
287648
287649
287650
287651
287652
287653
287654
287655
287656
287657
287658
287659
287660
287661
287662
287663
287664
287665
287666
287667
287668
287669
287670
287671
287672
287673
287674
287675
287676
287677
287678
287679
287680
287681
287682
287683
287684
287685
287686
287687
287688
287689
287690
287691
287692
287693
287694
287695
287696
287697
287698
287699
287700
287701
287702
287703
287704
287705
287706
287707
287708
287709
287710
287711
287712
287713
287714
287715
287716
287717
287718
287719
287720
287721
287722
287723
287724
287725
287726
287727
287728
287729
287730
287731
287732
287733
287734
287735
287736
287737
287738
287739
287740
287741
287742
287743
287744
287745
287746
287747
287748
287749
287750
287751
287752
287753
287754
287755
287756
287757
287758
287759
287760
287761
287762
287763
287764
287765
287766
287767
287768
287769
287770
287771
287772
287773
287774
287775
287776
287777
287778
287779
287780
287781
287782
287783
287784
287785
287786
287787
287788
287789
287790
287791
287792
287793
287794
287795
287796
287797
287798
287799
287800
287801
287802
287803
287804
287805
287806
287807
287808
287809
287810
287811
287812
287813
287814
287815
287816
287817
287818
287819
287820
287821
287822
287823
287824
287825
287826
287827
287828
287829
287830
287831
287832
287833
287834
287835
287836
287837
287838
287839
287840
287841
287842
287843
287844
287845
287846
287847
287848
287849
287850
287851
287852
287853
287854
287855
287856
287857
287858
287859
287860
287861
287862
287863
287864
287865
287866
287867
287868
287869
287870
287871
287872
287873
287874
287875
287876
287877
287878
287879
287880
287881
287882
287883
287884
287885
287886
287887
287888
287889
287890
287891
287892
287893
287894
287895
287896
287897
287898
287899
287900
287901
287902
287903
287904
287905
287906
287907
287908
287909
287910
287911
287912
287913
287914
287915
287916
287917
287918
287919
287920
287921
287922
287923
287924
287925
287926
287927
287928
287929
287930
287931
287932
287933
287934
287935
287936
287937
287938
287939
287940
287941
287942
287943
287944
287945
287946
287947
287948
287949
287950
287951
287952
287953
287954
287955
287956
287957
287958
287959
287960
287961
287962
287963
287964
287965
287966
287967
287968
287969
287970
287971
287972
287973
287974
287975
287976
287977
287978
287979
287980
287981
287982
287983
287984
287985
287986
287987
287988
287989
287990
287991
287992
287993
287994
287995
287996
287997
287998
287999
288000
288001
288002
288003
288004
288005
288006
288007
288008
288009
288010
288011
288012
288013
288014
288015
288016
288017
288018
288019
288020
288021
288022
288023
288024
288025
288026
288027
288028
288029
288030
288031
288032
288033
288034
288035
288036
288037
288038
288039
288040
288041
288042
288043
288044
288045
288046
288047
288048
288049
288050
288051
288052
288053
288054
288055
288056
288057
288058
288059
288060
288061
288062
288063
288064
288065
288066
288067
288068
288069
288070
288071
288072
288073
288074
288075
288076
288077
288078
288079
288080
288081
288082
288083
288084
288085
288086
288087
288088
288089
288090
288091
288092
288093
288094
288095
288096
288097
288098
288099
288100
288101
288102
288103
288104
288105
288106
288107
288108
288109
288110
288111
288112
288113
288114
288115
288116
288117
288118
288119
288120
288121
288122
288123
288124
288125
288126
288127
288128
288129
288130
288131
288132
288133
288134
288135
288136
288137
288138
288139
288140
288141
288142
288143
288144
288145
288146
288147
288148
288149
288150
288151
288152
288153
288154
288155
288156
288157
288158
288159
288160
288161
288162
288163
288164
288165
288166
288167
288168
288169
288170
288171
288172
288173
288174
288175
288176
288177
288178
288179
288180
288181
288182
288183
288184
288185
288186
288187
288188
288189
288190
288191
288192
288193
288194
288195
288196
288197
288198
288199
288200
288201
288202
288203
288204
288205
288206
288207
288208
288209
288210
288211
288212
288213
288214
288215
288216
288217
288218
288219
288220
288221
288222
288223
288224
288225
288226
288227
288228
288229
288230
288231
288232
288233
288234
288235
288236
288237
288238
288239
288240
288241
288242
288243
288244
288245
288246
288247
288248
288249
288250
288251
288252
288253
288254
288255
288256
288257
288258
288259
288260
288261
288262
288263
288264
288265
288266
288267
288268
288269
288270
288271
288272
288273
288274
288275
288276
288277
288278
288279
288280
288281
288282
288283
288284
288285
288286
288287
288288
288289
288290
288291
288292
288293
288294
288295
288296
288297
288298
288299
288300
288301
288302
288303
288304
288305
288306
288307
288308
288309
288310
288311
288312
288313
288314
288315
288316
288317
288318
288319
288320
288321
288322
288323
288324
288325
288326
288327
288328
288329
288330
288331
288332
288333
288334
288335
288336
288337
288338
288339
288340
288341
288342
288343
288344
288345
288346
288347
288348
288349
288350
288351
288352
288353
288354
288355
288356
288357
288358
288359
288360
288361
288362
288363
288364
288365
288366
288367
288368
288369
288370
288371
288372
288373
288374
288375
288376
288377
288378
288379
288380
288381
288382
288383
288384
288385
288386
288387
288388
288389
288390
288391
288392
288393
288394
288395
288396
288397
288398
288399
288400
288401
288402
288403
288404
288405
288406
288407
288408
288409
288410
288411
288412
288413
288414
288415
288416
288417
288418
288419
288420
288421
288422
288423
288424
288425
288426
288427
288428
288429
288430
288431
288432
288433
288434
288435
288436
288437
288438
288439
288440
288441
288442
288443
288444
288445
288446
288447
288448
288449
288450
288451
288452
288453
288454
288455
288456
288457
288458
288459
288460
288461
288462
288463
288464
288465
288466
288467
288468
288469
288470
288471
288472
288473
288474
288475
288476
288477
288478
288479
288480
288481
288482
288483
288484
288485
288486
288487
288488
288489
288490
288491
288492
288493
288494
288495
288496
288497
288498
288499
288500
288501
288502
288503
288504
288505
288506
288507
288508
288509
288510
288511
288512
288513
288514
288515
288516
288517
288518
288519
288520
288521
288522
288523
288524
288525
288526
288527
288528
288529
288530
288531
288532
288533
288534
288535
288536
288537
288538
288539
288540
288541
288542
288543
288544
288545
288546
288547
288548
288549
288550
288551
288552
288553
288554
288555
288556
288557
288558
288559
288560
288561
288562
288563
288564
288565
288566
288567
288568
288569
288570
288571
288572
288573
288574
288575
288576
288577
288578
288579
288580
288581
288582
288583
288584
288585
288586
288587
288588
288589
288590
288591
288592
288593
288594
288595
288596
288597
288598
288599
288600
288601
288602
288603
288604
288605
288606
288607
288608
288609
288610
288611
288612
288613
288614
288615
288616
288617
288618
288619
288620
288621
288622
288623
288624
288625
288626
288627
288628
288629
288630
288631
288632
288633
288634
288635
288636
288637
288638
288639
288640
288641
288642
288643
288644
288645
288646
288647
288648
288649
288650
288651
288652
288653
288654
288655
288656
288657
288658
288659
288660
288661
288662
288663
288664
288665
288666
288667
288668
288669
288670
288671
288672
288673
288674
288675
288676
288677
288678
288679
288680
288681
288682
288683
288684
288685
288686
288687
288688
288689
288690
288691
288692
288693
288694
288695
288696
288697
288698
288699
288700
288701
288702
288703
288704
288705
288706
288707
288708
288709
288710
288711
288712
288713
288714
288715
288716
288717
288718
288719
288720
288721
288722
288723
288724
288725
288726
288727
288728
288729
288730
288731
288732
288733
288734
288735
288736
288737
288738
288739
288740
288741
288742
288743
288744
288745
288746
288747
288748
288749
288750
288751
288752
288753
288754
288755
288756
288757
288758
288759
288760
288761
288762
288763
288764
288765
288766
288767
288768
288769
288770
288771
288772
288773
288774
288775
288776
288777
288778
288779
288780
288781
288782
288783
288784
288785
288786
288787
288788
288789
288790
288791
288792
288793
288794
288795
288796
288797
288798
288799
288800
288801
288802
288803
288804
288805
288806
288807
288808
288809
288810
288811
288812
288813
288814
288815
288816
288817
288818
288819
288820
288821
288822
288823
288824
288825
288826
288827
288828
288829
288830
288831
288832
288833
288834
288835
288836
288837
288838
288839
288840
288841
288842
288843
288844
288845
288846
288847
288848
288849
288850
288851
288852
288853
288854
288855
288856
288857
288858
288859
288860
288861
288862
288863
288864
288865
288866
288867
288868
288869
288870
288871
288872
288873
288874
288875
288876
288877
288878
288879
288880
288881
288882
288883
288884
288885
288886
288887
288888
288889
288890
288891
288892
288893
288894
288895

In [ ]:
fact_player_attributes['Player_Version'] = list_player_version
fact_player_attributes['Acceleration'] = sofifa_players['Acceleration']
fact_player_attributes['Aggression'] = sofifa_players['Aggression']
fact_player_attributes['Agility'] = sofifa_players['Agility']
fact_player_attributes['Balance'] = sofifa_players['Balance']
fact_player_attributes['Ball_Control'] = sofifa_players['Ball_Control']
fact_player_attributes['Composure'] = sofifa_players['Composure']
fact_player_attributes['Crossing'] = sofifa_players['Crossing']
fact_player_attributes['Curve'] = sofifa_players['Curve']
fact_player_attributes['Dribbling'] = sofifa_players['Dribbling']
fact_player_attributes['Finishing'] = sofifa_players['Finishing']
fact_player_attributes['Fk_Accuracy'] = sofifa_players['Fk_Accuracy']
fact_player_attributes['Gk_Diving'] = sofifa_players['Gk_Diving']
fact_player_attributes['Gk_Handling'] = sofifa_players['Gk_Handling']
fact_player_attributes['Gk_Kicking'] = sofifa_players['Gk_Kicking']
fact_player_attributes['Gk_Positioning'] = sofifa_players['Gk_Positioning']
fact_player_attributes['Gk_Reflexes'] = sofifa_players['Gk_Reflexes']

fact_player_attributes['Heading_Accuracy'] = sofifa_players['Heading_Accuracy']
fact_player_attributes['Height'] = sofifa_players['Height']
fact_player_attributes['Interceptions'] = sofifa_players['Interceptions']
fact_player_attributes['Jumping'] = sofifa_players['Jumping']
fact_player_attributes['Long_Passing'] = sofifa_players['Long_Passing']
fact_player_attributes['Long_Shots'] = sofifa_players['Long_Shots']
fact_player_attributes['Overall_Rating'] = sofifa_players['Overall_Rating']
fact_player_attributes['Penalties'] = sofifa_players['Penalties']
fact_player_attributes['Positioning'] = sofifa_players['Positioning']
fact_player_attributes['Potential'] = sofifa_players['Potential']
fact_player_attributes['Reactions'] = sofifa_players['Reactions']
fact_player_attributes['Reputation'] = sofifa_players['Reputation']
fact_player_attributes['Short_Passing'] = sofifa_players['Short_Passing']
fact_player_attributes['Shot_Power'] = sofifa_players['Shot_Power']

fact_player_attributes['Skill_Moves'] = sofifa_players['Skill_Moves']
fact_player_attributes['Sliding_Tackle'] = sofifa_players['Sliding_Tackle']
fact_player_attributes['Sprint_Speed'] = sofifa_players['Sprint_Speed']
fact_player_attributes['Stamina'] = sofifa_players['Stamina']
fact_player_attributes['Standing_Tackle'] = sofifa_players['Standing_Tackle']
fact_player_attributes['Strength'] = sofifa_players['Strength']
fact_player_attributes['Value'] = sofifa_players['Value']
fact_player_attributes['Vision'] = sofifa_players['Vision']
fact_player_attributes['Volleys'] = sofifa_players['Volleys']
fact_player_attributes['Wage'] = sofifa_players['Wage']
fact_player_attributes['Weak_Foot'] = sofifa_players['Weak_Foot']
fact_player_attributes['Weight'] = sofifa_players['Weight']

<h3>2. Fact Match Statistics</h3>

Thêm thông số Attack, Midfield, Defense dựa vào Player_Position và Player_Overall_Rating cho mỗi match

In [29]:
match_dataset_model = pd.read_csv("gs://football_data_etl/football_data_extracted/output-basic/match_dataset_model.csv",
                                  encoding='latin1')

In [30]:
match_dataset_model['Home_Team'].unique()

array(['Saint-\x90tienne', 'Lille', 'Nice', 'Guingamp', 'Caen', 'Nantes',
       'Strasbourg', 'Bordeaux', 'Lyon', 'Toulouse', 'Paris S-G', 'Metz',
       'Monaco', 'Montpellier', 'Troyes', 'Rennes', 'Angers', 'Marseille',
       'Dijon', 'Amiens', 'N\x8cmes', 'Reims', 'Brest', 'Lorient', 'Lens',
       'Clermont Foot', 'Auxerre', 'Ajaccio', 'Le Havre', 'West Ham',
       'Everton', 'Chelsea', 'Southampton', 'Crystal Palace',
       'Cardiff City', 'Liverpool', 'Huddersfield', 'Fulham', 'Burnley',
       'Brighton', 'Manchester City', 'Arsenal', 'Tottenham', 'Wolves',
       'Leicester City', 'Bournemouth', 'Newcastle Utd', 'Watford',
       'Manchester Utd', 'Norwich City', 'Aston Villa', 'Sheffield Utd',
       'Leeds United', 'West Brom', 'Brentford', "Nott'ham Forest",
       'Luton Town', 'Swansea City', 'Stoke City', 'La Coru¤a',
       'Athletic Club', 'Villarreal', 'Real Sociedad', 'Valencia',
       'Las Palmas', 'Atl\x82tico Madrid', 'Barcelona', 'Eibar',
       'Real Madrid', 'Espanyol', 'M\xa0laga', 'Celta Vigo', 'Alav\x82s',
       'Getafe', 'Betis', 'Levante', 'Legan\x82s', 'Sevilla', 'Girona',
       'Valladolid', 'Huesca', 'Rayo Vallecano', 'Osasuna', 'Granada',
       'Mallorca', 'Elche', 'C\xa0diz', 'Almer¡a', "M'Gladbach",
       'Dortmund', 'Bayern Munich', 'Hamburger SV', 'Mainz 05',
       'Stuttgart', 'Werder Bremen', 'Hannover 96', 'Freiburg',
       'Wolfsburg', 'Augsburg', 'K\x94ln', 'RB Leipzig', 'Leverkusen',
       'Hertha BSC', 'Schalke 04', 'Hoffenheim', 'Eint Frankfurt',
       'D\x81sseldorf', 'N\x81rnberg', 'Gladbach', 'Union Berlin',
       'Paderborn 07', 'Arminia', 'Bochum', 'Greuther F\x81rth',
       'Darmstadt 98', 'Heidenheim', 'Atalanta', 'SPAL', 'Chievo',
       'Sampdoria', 'Milan', 'Roma', 'Hellas Verona', 'Torino',
       'Sassuolo', 'Lazio', 'Bologna', 'Benevento', 'Genoa', 'Napoli',
       'Cagliari', 'Crotone', 'Inter', 'Juventus', 'Fiorentina',
       'Udinese', 'Frosinone', 'Parma', 'Empoli', 'Brescia', 'Lecce',
       'Spezia', 'Salernitana', 'Venezia', 'Cremonese', 'Monza'],
      dtype=object)

In [31]:
match_dataset_model.loc[match_dataset_model['Home_Team'] == 'Saint-\x90tienne', 'Home_Team'] = 'Saint-Étienne'
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'Saint-\x90tienne', 'Away_Team'] = 'Saint-Étienne'

match_dataset_model.loc[match_dataset_model['Home_Team'] == 'N\x8cmes', 'Home_Team'] = 'Nîmes'
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'N\x8cmes', 'Away_Team'] = 'Nîmes'

match_dataset_model.loc[match_dataset_model['Home_Team'] == 'La Coru¤a', 'Home_Team'] = 'La Coruña'
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'La Coru¤a', 'Away_Team'] = 'La Coruña'

match_dataset_model.loc[match_dataset_model['Home_Team'] == 'Atl\x82tico Madrid', 'Home_Team'] = 'Atlético Madrid'
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'Atl\x82tico Madrid', 'Away_Team'] = 'Atlético Madrid'

match_dataset_model.loc[match_dataset_model['Home_Team'] == 'M\xa0laga', 'Home_Team'] = 'Málaga'
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'M\xa0laga', 'Away_Team'] = 'Málaga'

match_dataset_model.loc[match_dataset_model['Home_Team'] == 'Almer¡a', 'Home_Team'] = 'Almería'
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'Almer¡a', 'Away_Team'] = 'Almería'

match_dataset_model.loc[match_dataset_model['Home_Team'] == 'Alav\x82s', 'Home_Team'] = 'Alavés'
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'Alav\x82s', 'Away_Team'] = 'Alavés'

match_dataset_model.loc[match_dataset_model['Home_Team'] == 'Legan\x82s', 'Home_Team'] = 'Leganés'
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'Legan\x82s', 'Away_Team'] = 'Leganés'

match_dataset_model.loc[match_dataset_model['Home_Team'] == 'C\xa0diz', 'Home_Team'] = 'Cádiz'
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'C\xa0diz', 'Away_Team'] = 'Cádiz'

match_dataset_model.loc[match_dataset_model['Home_Team'] == 'K\x94ln', 'Home_Team'] = 'Köln'
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'K\x94ln', 'Away_Team'] = 'Köln'

match_dataset_model.loc[match_dataset_model['Home_Team'] == 'D\x81sseldorf', 'Home_Team'] = 'Düsseldorf'
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'D\x81sseldorf', 'Away_Team'] = 'Düsseldorf'

match_dataset_model.loc[match_dataset_model['Home_Team'] == 'N\x81rnberg', 'Home_Team'] = 'Nürnberg'
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'N\x81rnberg', 'Away_Team'] = 'Nürnberg'

match_dataset_model.loc[match_dataset_model['Home_Team'] == 'Greuther F\x81rth', 'Home_Team'] = 'Greuther Fürth'
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'Greuther F\x81rth', 'Away_Team'] = 'Greuther Fürth'

In [32]:
match_dataset_model

,Match_Id,Match_Date,Home_Team,Home_Manager,Home_Captain,Home_Formation,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,...,Away_Cmp_Passes,Away_Att_Passes,Away_Cmp_percent_Passes,Away_PrgP_Passes,Away_Carries_Carries,Away_PrgC_Carries,Away_Att_Take_Ons,Away_Succ_Take_Ons,Home_Score,Away_Score
0,39b738ac,11/24/2017,Saint-Étienne,Unknown,Unknown,4-2-3-1,59,14,7,33,...,293,410,71.5,23,297,18,12,9,2,2
1,ed0f2e13,4/28/2018,Lille,Unknown,Unknown,4-2-3-1,50,11,3,12,...,378,511,74.0,38,338,15,23,12,3,1
2,de5b03fe,2/3/2018,Nice,Unknown,Unknown,4/3/2003,75,14,11,34,...,204,279,73.1,26,246,17,21,13,0,1
3,43ebed63,12/20/2017,Guingamp,Unknown,Unknown,4-2-3-1,80,13,10,47,...,90,179,50.3,11,73,5,7,3,2,1
4,1aef5397,8/12/2017,Caen,Unknown,Unknown,4/3/2003,47,12,8,32,...,340,454,74.9,32,260,16,16,10,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12599,9492fa68,5/25/2024,Milan,Unknown,Unknown,4-2-3-1,66,6,13,27,...,234,300,78.0,24,158,17,9,2,3,3
12600,d63c561d,5/18/2024,Lecce,Unknown,Unknown,4/4/2002,44,7,2,15,...,509,593,85.8,50,379,19,13,7,0,2
12601,dec7c7ae,5/11/2024,Milan,Unknown,Unknown,4-2-3-1,66,11,6,15,...,275,350,78.6,21,230,15,17,6,5,1
12602,ab8f65b4,5/19/2024,Monza,Unknown,Unknown,4-2-3-1,70,14,3,23,...,197,278,70.9,25,152,20,17,9,0,1
12603,f6279636,5/12/2024,Lazio,Unknown,Unknown,3/4/2003,59,18,7,17,...,266,362,73.5,22,234,18,20,8,2,0

In [33]:
match_dataset_model = pd.merge(match_dataset_model, fbref_matchinfos[['Match_Id','Season']], on="Match_Id")

In [34]:
match_dataset_model = match_dataset_model[match_dataset_model['Season'] != 2018]
match_dataset_model = match_dataset_model.drop('Season', axis=1)

Xóa các Match với không tìm thấy Sofifa_Id nào của một Team

In [35]:
sofifa_id_counts = merge.groupby(['Match_Id', 'Team'])['Sofifa_Id'].count()
sofifa_id_counts

Match_Id  Team
00023357  Hoffenheim          2
          Leverkusen          4
0006415c  Atalanta           19
          Udinese            23
0012462a  Atlético Madrid    21
                             ..
ffeee70d  Nantes             18
fffbcb62  Monaco             18
          Saint-Étienne      17
fffdfc41  Bochum             16
          Eint Frankfurt     14
Name: Sofifa_Id, Length: 21562, dtype: int64

In [36]:
sofifa_id_counts = sofifa_id_counts.reset_index()

In [37]:
ids_team_with_zero_count = sofifa_id_counts[(sofifa_id_counts['Sofifa_Id'] == 0)][['Match_Id', 'Team']]

In [38]:
merge_filtered = pd.merge(merge, ids_team_with_zero_count, on=['Match_Id', 'Team'], how='outer', indicator=True)
merge_filtered = merge_filtered[merge_filtered['_merge'] != 'both']

In [39]:
len(merge)

438993

In [40]:
len(merge_filtered)

404471

In [41]:
len(merge['Match_Id'].unique())

10781

In [42]:
len(merge_filtered['Match_Id'].unique())

10213

In [43]:
merge_filtered['Team'].unique()

array(["M'Gladbach", 'Eint Frankfurt', 'Hertha BSC', 'Wolfsburg',
       'Leverkusen', 'Dortmund', 'Werder Bremen', 'Freiburg',
       'Bayern Munich', 'Hoffenheim', 'Hannover 96', 'Stuttgart',
       'Schalke 04', 'Nürnberg', 'RB Leipzig', 'Mainz 05', 'Augsburg',
       'Köln', 'Union Berlin', 'Bochum', 'Heidenheim', 'Darmstadt 98',
       'Atlético Madrid', 'Getafe', 'Villarreal', 'Real Sociedad',
       'Valladolid', 'Real Madrid', 'Betis', 'Alavés', 'Girona',
       'Levante', 'Leganés', 'Athletic Club', 'Espanyol', 'Eibar',
       'Barcelona', 'Sevilla', 'Celta Vigo', 'Valencia', 'Huesca',
       'Rayo Vallecano', 'Granada', 'Osasuna', 'Mallorca', 'Elche',
       'Cádiz', 'Almería', 'Las Palmas', 'Nîmes', 'Nantes', 'Dijon',
       'Marseille', 'Saint-Étienne', 'Bordeaux', 'Strasbourg', 'Caen',
       'Lille', 'Paris S-G', 'Toulouse', 'Lyon', 'Montpellier', 'Angers',
       'Amiens', 'Monaco', 'Nice', 'Rennes', 'Guingamp', 'Reims', 'Metz',
       'Brest', 'Lorient', 'Lens', 'Troyes', 'Clermont Foot', 'Auxerre',
       'Ajaccio', 'Le Havre', 'West Ham', 'Manchester Utd', 'Everton',
       'Watford', 'Chelsea', 'Brighton', 'Southampton', 'Burnley',
       'Crystal Palace', 'Arsenal', 'Cardiff City', 'Liverpool', 'Wolves',
       'Huddersfield', 'Fulham', 'Leicester City', 'Bournemouth',
       'Manchester City', 'Tottenham', 'Newcastle Utd', 'Norwich City',
       'Sheffield Utd', 'Aston Villa', 'Leeds United', 'West Brom',
       'Brentford', "Nott'ham Forest", 'Luton Town', 'Milan', 'Lazio',
       'Torino', 'Parma', 'Atalanta', 'Sampdoria', 'Udinese', 'Sassuolo',
       'Frosinone', 'Empoli', 'SPAL', 'Juventus', 'Napoli', 'Cagliari',
       'Genoa', 'Fiorentina', 'Inter', 'Bologna', 'Roma', 'Chievo',
       'Brescia', 'Hellas Verona', 'Lecce', 'Benevento', 'Crotone',
       'Spezia', 'Venezia', 'Salernitana', 'Cremonese', 'Monza'],
      dtype=object)

In [44]:
merge_filtered[~merge_filtered['Team'].isin(match_dataset_model['Home_Team'])]['Team']

Series([], Name: Team, dtype: object)

Qui định các các Position ứng với 3 Lines: Attack, Midfield, Defense

In [45]:
attack_line = ["LS", "ST", "RS","LW", "LF", "CF", "RF", "RW"]
midfield_line = ["LAM", "CAM", "RAM","LM", "LCM", "CM", "RCM", "RM","LDM", "CDM", "RDM"]
defense_line = ["LB", "LCB", "CB", "RCB", "RB","LWB","RWB"]

In [46]:
new_attrs = pd.DataFrame({'Match_Id': [],
                        'Home_Attack': [],
                        'Home_Midfield': [],
                        'Home_Defense': [],
                        'Away_Attack': [],
                        'Away_Midfield': [],
                        'Away_Defense': []})
atr_match_id = []
atr_home_attack = []
atr_home_midfield = []
atr_home_defense = []
atr_away_attack = []
atr_away_midfield = []
atr_away_defense = []

In [47]:
for i in range(0, len(match_dataset_model)):

    match_id = match_dataset_model.iloc[i, match_dataset_model.columns.get_loc('Match_Id')]

    home_team = match_dataset_model.iloc[i, match_dataset_model.columns.get_loc('Home_Team')]
    away_team = match_dataset_model.iloc[i, match_dataset_model.columns.get_loc('Away_Team')]

    #
    current_match_df = merge_filtered[merge_filtered['Match_Id'] == match_id]

    print(i, match_id, home_team, away_team, len(current_match_df))

    if (len(current_match_df) > 0):

      list_home_attack = []
      list_home_midfield = []
      list_home_defense = []
      list_away_attack = []
      list_away_midfield = []
      list_away_defense = []

      for player in current_match_df.itertuples(index=False):

          if not np.isnan(player.Sofifa_Id):
              player_positions = player.Player_Position.split(' ')
              overall_rating = player.Player_Overall_Rating

          #home_team
          if (player.Team == home_team) and not np.isnan(player.Sofifa_Id):

              for position in player_positions:
                  if (position in attack_line):
                      list_home_attack.append(overall_rating)
                  if (position in midfield_line):
                      list_home_midfield.append(overall_rating)
                  if (position in defense_line):
                      list_home_defense.append(overall_rating)
          #away_team
          if (player.Team == away_team) and not np.isnan(player.Sofifa_Id):

              for position in player_positions:
                  if (position in attack_line):
                      list_away_attack.append(overall_rating)
                  if (position in midfield_line):
                      list_away_midfield.append(overall_rating)
                  if (position in defense_line):
                      list_away_defense.append(overall_rating)

      atr_match_id.append(match_id)

      if (len(list_home_attack) > 0):
        atr_home_attack.append(sum(list_home_attack) / len(list_home_attack))
      else:
        atr_home_attack.append(0)
      if (len(list_home_midfield) > 0):
        atr_home_midfield.append(sum(list_home_midfield) / len(list_home_midfield))
      else:
        atr_home_midfield.append(0)
      if (len(list_home_defense) > 0):
        atr_home_defense.append(sum(list_home_defense) / len(list_home_defense))
      else:
        atr_home_defense.append(0)

      if (len(list_away_attack) > 0):
        atr_away_attack.append(sum(list_away_attack) / len(list_away_attack))
      else:
        atr_away_attack.append(0)
      if (len(list_away_midfield) > 0):
        atr_away_midfield.append(sum(list_away_midfield) / len(list_away_midfield))
      else:
        atr_away_midfield.append(0)
      if (len(list_away_defense) > 0):
        atr_away_defense.append(sum(list_away_defense) / len(list_away_defense))
      else:
        atr_away_defense.append(0)


    else:
      atr_match_id.append(match_id)
      atr_home_attack.append(0)
      atr_home_midfield.append(0)
      atr_home_defense.append(0)
      atr_away_attack.append(0)
      atr_away_midfield.append(0)
      atr_away_defense.append(0)

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
5683 5bbb6e37 Alavés Real Sociedad 42
5684 99b54d59 Villarreal Sevilla 44
5685 20c84d6e Atlético Madrid Getafe 41
5686 368c0ef5 Valencia Barcelona 44
5687 20c47249 Real Sociedad Getafe 45
5688 a7352bb8 Granada Valencia 41
5689 170e5383 Sevilla Osasuna 46
5690 f8700700 Athletic Club Mallorca 22
5691 3334afc1 Valencia Alavés 44
5692 140f4110 Valencia Real Madrid 44
5693 6d1df89a Elche Celta Vigo 45
5694 2b813dce Granada Betis 46
5695 bc4e66b1 Elche Betis 46
5696 ed5b7ecb Sevilla Real Sociedad 45
5697 59a8ec39 Celta Vigo Barcelona 42
5698 43ebabcc Elche Espanyol 46
5699 b3946deb Espanyol Cádiz 46
5700 ce97f705 Villarreal Espanyol 45
5701 777c8d55 Athletic Club Real Sociedad 43
5702 557b4f21 Osasuna Atlético Madrid 42
5703 cdc92553 Villarreal Osasuna 46
5704 43a5cb2e Villarreal Cádiz 46
5705 8bb438aa Athletic Club Osasuna 44
5706 e4557ea7 Real Madrid Cádiz 44
5707 ca6be7cc Levante Espanyol 46
5708 ac93ead3 Atlético Madrid Villarreal 44
5709 415aadfb Real Sociedad Espanyol 45
5710 e206a428 Barcelona Cádiz 45
5711 7d192eac Barcelona Athletic Club 46
5712 7a816de3 Celta Vigo Levante 46
5713 c9f9fbfb Rayo Vallecano Real Madrid 43
5714 7b559a06 Granada Rayo Vallecano 40
5715 aafa2121 Granada Mallorca 45
5716 7710201e Barcelona Sevilla 45
5717 1542d512 Real Madrid Getafe 41
5718 cff883cc Betis Atlético Madrid 39
5719 2a3e67f6 Barcelona Valencia 45
5720 7967e862 Athletic Club Getafe 44
5721 d2c094db Real Madrid Villarreal 43
5722 1587e2a3 Mallorca Levante 46
5723 8108aa10 Getafe Barcelona 43
5724 10ad43d5 Rayo Vallecano Sevilla 42
5725 29f073b6 Real Madrid Alavés 46
5726 41d76b6c Villarreal Atlético Madrid 42
5727 3f2a81eb Osasuna Rayo Vallecano 46
5728 91dbe823 Levante Betis 45
5729 be333306 Rayo Vallecano Barcelona 44
5730 6bb68301 Rayo Vallecano Granada 45
5731 26e9e3f4 Alavés Betis 46
5732 eb0ba7e9 Getafe Espanyol 43
5733 9ceae486 Celta Vigo Villarreal 40
5734 aaf3e992 Villarreal Celta Vigo 41
5735 328d7561 Levante Osasuna 46
5736 fea8bbc8 Granada Villarreal 44
5737 fbed1810 Atlético Madrid Real Madrid 40
5738 7af1aac6 Espanyol Real Madrid 41
5739 baafc274 Espanyol Atlético Madrid 21
5740 6e15b9eb Granada Alavés 44
5741 5bd64929 Levante Elche 46
5742 4dd4d3da Sevilla Atlético Madrid 43
5743 457fefd4 Real Sociedad Valencia 44
5744 632ec926 Celta Vigo Osasuna 45
5745 260fb527 Betis Cádiz 46
5746 eba0e42c Granada Osasuna 46
5747 4aab63b0 Valencia Elche 46
5748 506f69b0 Mallorca Atlético Madrid 42
5749 b9745c66 Rayo Vallecano Alavés 44
5750 d071d7bb Real Sociedad Rayo Vallecano 43
5751 ddec11bd Levante Mallorca 46
5752 4654a354 Sevilla Levante 46
5753 c668317c Sevilla Espanyol 46
5754 472cd4cf Getafe Osasuna 42
5755 3cddce8c Osasuna Real Sociedad 44
5756 611e1be5 Barcelona Elche 45
5757 8eecfe5a Real Sociedad Villarreal 44
5758 c6e013a8 Real Sociedad Celta Vigo 44
5759 a135e5a3 Osasuna Granada 44
5760 8b28af73 Getafe Sevilla 46
5761 865a5861 Granada Celta Vigo 43
5762 0511a8eb Cádiz Villarreal 44
5763 96d2a74b Alavés Levante 45
5764 48c210c0 Rayo Vallecano Getafe 23
5765 07873dc8 Villarreal Real Madrid 45
5766 85e81054 Levante Granada 41
5767 4cbde2ca Espanyol Real Sociedad 45
5768 6109e9c9 Alavés Espanyol 46
5769 e268343f Espanyol Athletic Club 44
5770 621fe105 Espanyol Elche 45
5771 80604449 Atlético Madrid Elche 43
5772 edd7cbf9 Real Sociedad Elche 44
5773 8473b085 Real Sociedad Mallorca 44
5774 bd2f6fb5 Atlético Madrid Betis 42
5775 9c4e7a3d Betis Mallorca 46
5776 8401e8f0 Atlético Madrid Espanyol 44
5777 a651a98b Villarreal Mallorca 44
5778 72bd4a17 Valencia Espanyol 46
5779 a4c4a359 Osasuna Valencia 46
5780 413a7fda Real Madrid Osasuna 45
5781 7b7dbd26 Betis Valencia 45
5782 34a45878 Celta Vigo Rayo Vallecano 43
5783 5ed758ee Valencia Rayo Vallecano 43
5784 d33c8bbd Real Sociedad Atlético Madrid 41
5785 2cbbddbd Valencia Celta Vigo 42
5786 7ebd3ee2 Getafe Betis 43
5787 b0c74874 Levante Athletic Club 46
5788 fdc88091 Cádiz Real Sociedad 43
5789 681341da Real Sociedad Athletic Club 43
5790 c3462444 Atlético Madrid Valencia 41
5791 268dc2a6 Barcelona Betis 46
5792 5a71490e Valencia Atlético Madrid 41
5793 8015b853 Athletic Club Celta Vigo 43
5794 6000c89e Sevilla Real Madrid 43
5795 428cdc1d Real Sociedad Real Madrid 45
5796 5225b8b5 Barcelona Real Madrid 46
5797 2fad4a55 Villarreal Real Sociedad 44
5798 ce7d90a0 Osasuna Sevilla 45
5799 f43933c7 Mallorca Sevilla 46
5800 0f4fb26d Espanyol Mallorca 46
5801 3ba60869 Espanyol Levante 45
5802 5b6bf193 Valencia Betis 45
5803 5d00f4ef Mallorca Real Madrid 46
5804 965b998e Sevilla Valencia 45
5805 7232f74e Celta Vigo Betis 39
5806 73394b42 Real Sociedad Sevilla 44
5807 99bb8435 Cádiz Osasuna 46
5808 6b443d2c Real Sociedad Cádiz 46
5809 f8108665 Getafe Elche 46
5810 abb1da57 Barcelona Espanyol 46
5811 60fda0b2 Elche Levante 44
5812 953c7040 Villarreal Granada 43
5813 bcdf22b5 Getafe Villarreal 45
5814 d3b2056d Valencia Real Sociedad 46
5815 9ed4f8dd Getafe Granada 46
5816 c910f5b5 Villarreal Valencia 46
5817 a7a6c37f Alavés Cádiz 46
5818 ac9afdba Athletic Club Real Madrid 41
5819 ee4158be Real Madrid Atlético Madrid 43
5820 88123170 Betis Espanyol 23
5821 c2818e17 Barcelona Getafe 44
5822 cbe4e465 Mallorca Celta Vigo 45
5823 910de8b3 Elche Real Sociedad 46
5824 1728411b Sevilla Getafe 44
5825 ebd1fe82 Villarreal Betis 43
5826 69b0c7f3 Elche Mallorca 45
5827 67476a1c Betis Getafe 44
5828 3f9697f7 Mallorca Real Sociedad 46
5829 800b362a Mallorca Barcelona 44
5830 a5489f75 Granada Real Sociedad 45
5831 53121ac1 Espanyol Sevilla 46
5832 c1065902 Celta Vigo Atlético Madrid 39
5833 4ea03cad Alavés Villarreal 43
5834 14d38d9d Granada Real Madrid 45
5835 33e27dc0 Villarreal Barcelona 46
5836 f2250af1 Rayo Vallecano Levante 44
5837 d639b847 Sevilla Cádiz 46
5838 769d70ff Real Madrid Elche 43
5839 e9568e81 Mallorca Alavés 46
5840 eafd9715 Barcelona Levante 41
5841 fc0ee51a Osasuna Espanyol 23
5842 0bd211ca Barcelona Granada 43
5843 5678d0a8 Atlético Madrid Barcelona 42
5844 e4d7234c Osasuna Villarreal 45
5845 2358f8c4 Betis Alavés 44
5846 12967dc8 Real Madrid Espanyol 44
5847 102335b0 Athletic Club Barcelona 44
5848 98f9512c Real Madrid Mallorca 23
5849 55b23c59 Sevilla Barcelona 46
5850 c2369d86 Barcelona Mallorca 44
5851 8878cd31 Granada Athletic Club 41
5852 cf46eea6 Alavés Sevilla 46
5853 e52a32d1 Celta Vigo Cádiz 43
5854 daab4bf0 Levante Barcelona 44
5855 eca6f082 Villarreal Athletic Club 44
5856 43922a84 Getafe Athletic Club 43
5857 f6fab33c Getafe Real Madrid 43
5858 b811b679 Barcelona Celta Vigo 42
5859 10bdbdae Real Sociedad Levante 43
5860 5f99a85d Celta Vigo Sevilla 42
5861 ad6c38fa Granada Sevilla 45
5862 44ac4530 Mallorca Villarreal 21
5863 3f649419 Osasuna Mallorca 46
5864 5d51fa0c Mallorca Girona 45
5865 53d34361 Mallorca Celta Vigo 46
5866 d4c4e1d2 Valladolid Athletic Club 41
5867 a3f2e116 Sevilla Valencia 46
5868 ebaebf9c Elche Girona 42
5869 05060e6f Valladolid Getafe 45
5870 b3373b5a Atlético Madrid Real Sociedad 42
5871 2af3934b Barcelona Espanyol 45
5872 0913c358 Espanyol Osasuna 39
5873 ab058eb9 Athletic Club Mallorca 44
5874 acef62b2 Getafe Barcelona 43
5875 f24d40c6 Sevilla Real Sociedad 45
5876 d1648255 Elche Valladolid 44
5877 22adf5a4 Almería Valencia 46
5878 5eba4386 Villarreal Athletic Club 43
5879 9c491e2b Athletic Club Espanyol 43
5880 8d4f770b Getafe Rayo Vallecano 46
5881 d30035ab Rayo Vallecano Cádiz 46
5882 0839f02f Elche Real Sociedad 46
5883 b8d72170 Mallorca Cádiz 46
5884 19c1fbec Atlético Madrid Espanyol 44
5885 37d55da6 Girona Mallorca 45
5886 c159b9d8 Rayo Vallecano Valencia 46
5887 a33d24ff Real Madrid Celta Vigo 43
5888 05df662a Girona Barcelona 44
5889 d76a9b5c Real Sociedad Cádiz 46
5890 3fd34920 Mallorca Athletic Club 44
5891 bb7701fa Espanyol Villarreal 45
5892 84529801 Betis Getafe 45
5893 9993b01a Getafe Atlético Madrid 45
5894 52679876 Real Sociedad Getafe 46
5895 495ec163 Barcelona Girona 44
5896 6cf98669 Real Madrid Mallorca 44
5897 7f84388c Real Madrid Betis 44
5898 65797851 Valencia Getafe 45
5899 17268fc9 Villarreal Getafe 43
5900 bb2cc8e7 Mallorca Osasuna 41
5901 dd04c982 Athletic Club Rayo Vallecano 44
5902 184db424 Osasuna Betis 42
5903 2cc94405 Cádiz Real Madrid 43
5904 61f4e6c3 Valladolid Rayo Vallecano 46
5905 c399c435 Mallorca Valencia 46
5906 ef9a3cb4 Almería Sevilla 23
5907 db2d843c Celta Vigo Rayo Vallecano 45
5908 5fd47c38 Almería Rayo Vallecano 46
5909 fcff5859 Rayo Vallecano Real Madrid 44
5910 cddeb6bb Atlético Madrid Cádiz 43
5911 50a0b6b9 Cádiz Barcelona 46
5912 aa81febc Real Madrid Elche 43
5913 4bfe0504 Rayo Vallecano Espanyol 46
5914 3dc648e6 Barcelona Valencia 42
5915 aeab8412 Espanyol Athletic Club 45
5916 0ed472a5 Celta Vigo Valencia 46
5917 cb41f210 Villarreal Celta Vigo 43
5918 9a5e0f15 Real Sociedad Barcelona 46
5919 315c78f1 Valladolid Osasuna 41
5920 514a45ae Cádiz Osasuna 42
5921 d98b5875 Atlético Madrid Getafe 46
5922 3db205b4 Elche Valencia 44
5923 c3d888f5 Sevilla Almería 43
5924 2fb55ba0 Barcelona Athletic Club 45
5925 5f2fdd0a Betis Valencia 46
5926 834124a1 Getafe Villarreal 45
5927 14214742 Mallorca Elche 44
5928 3169fc9b Atlético Madrid Barcelona 45
5929 2705dc41 Espanyol Sevilla 45
5930 8aae24d6 Valladolid Real Sociedad 45
5931 9a689249 Mallorca Real Sociedad 46
5932 4d7b545b Cádiz Valencia 45
5933 43237dc2 Cádiz Elche 42
5934 d3913703 Valladolid Barcelona 42
5935 5b5947df Cádiz Getafe 46
5936 f80c04f0 Cádiz Mallorca 44
5937 2532526d Getafe Betis 45
5938 069f9f40 Sevilla Atlético Madrid 45
5939 fbf241b4 Barcelona Real Madrid 44
5940 841d1e2c Espanyol Valencia 44
5941 e4f7474b Almería Mallorca 46
5942 ab2a8ab6 Elche Athletic Club 45
5943 6b820d45 Mallorca Valladolid 45
5944 1c460149 Villarreal Elche 44
5945 db09f5b6 Valladolid Elche 44
5946 7ca28cbe Valladolid Valencia 41
5947 1edcbf7a Osasuna Sevilla 46
5948 971ff4d2 Betis Real Madrid 44
5949 e9486908 Espanyol Cádiz 46
5950 01037ff0 Osasuna Espanyol 43
5951 d2c509a2 Almería Athletic Club 43
5952 678b0d64 Osasuna Elche 43
5953 249029a4 Almería Elche 46
5954 287c6564 Betis Villarreal 43
5955 82851200 Osasuna Valladolid 43
5956 10b27265 Almería Real Sociedad 45
5957 28bef8bc Almería Getafe 45
5958 a34eae3f Celta Vigo Atlético Madrid 45
5959 6bb56f15 Almería Betis 44
5960 348f39ff Betis Athletic Club 45
5961 0681349c Villarreal Rayo Vallecano 46
5962 54d6b3fc Athletic Club Almería 45
5963 446b1577 Espanyol Mallorca 44
5964 3f1977ac Espanyol Valladolid 40
5965 7952eab7 Sevilla Barcelona 46
5966 cb6bce1d Betis Girona 42
5967 9abb9c34 Valencia Barcelona 44
5968 c3d1d09b Barcelona Cádiz 41
5969 6f46c31d Osasuna Almería 46
5970 e75285fb Real Madrid Real Sociedad 40
5971 7b74b970 Osasuna Atlético Madrid 42
5972 87fea3c7 Espanyol Girona 43
5973 c1875f22 Real Madrid Barcelona 44
5974 fb47fe18 Sevilla Girona 43
5975 796943ab Athletic Club Celta Vigo 45
5976 1a5972e4 Girona Real Madrid 41
5977 0e195cca Valencia Espanyol 46
5978 6c96832f Celta Vigo Sevilla 44
5979 d3056cab Elche Mallorca 46
5980 7564c64e Valladolid Sevilla 43
5981 6a46394b Sevilla Villarreal 42
5982 ef71bc61 Osasuna Rayo Vallecano 45
5983 b9cc54ac Barcelona Almería 45
5984 5ca44582 Atlético Madrid Valencia 43
5985 7cc3bea8 Rayo Vallecano Valladolid 46
5986 a0914b2e Mallorca Real Madrid 42
5987 6facd787 Osasuna Celta Vigo 45
5988 ec90c2fe Valladolid Cádiz 46
5989 fde185f9 Villarreal Cádiz 45
5990 36d21a47 Espanyol Real Madrid 42
5991 377ddbd2 Espanyol Betis 45
5992 cb92acb9 Espanyol Rayo Vallecano 43
5993 0691278f Girona Elche 44
5994 7ed0a343 Espanyol Real Sociedad 44
5995 c0f06039 Valencia Rayo Vallecano 46
5996 058c86cf Real Sociedad Villarreal 45
5997 62d82c5a Atlético Madrid Osasuna 39
5998 a2d45f55 Valladolid Real Madrid 45
5999 36fa46ed Girona Betis 44
6000 012ba4f0 Real Sociedad Girona 43
6001 bbd97201 Elche Villarreal 42
6002 abe1a0be Mallorca Villarreal 44
6003 83cef2e5 Osasuna Villarreal 41
6004 8b6c5b79 Real Sociedad Elche 42
6005 41878242 Osasuna Real Madrid 40
6006 2f696974 Cádiz Almería 42
6007 1ccc0d2c Barcelona Sevilla 42
6008 58fd6a94 Almería Valladolid 46
6009 ebb32848 Atlético Madrid Villarreal 43
6010 7fbde755 Cádiz Real Sociedad 45
6011 e0851269 Athletic Club Getafe 45
6012 a10d32b8 Sevilla Celta Vigo 45
6013 c518c3b1 Atlético Madrid Almería 42
6014 02eab739 Villarreal Betis 44
6015 edcc3e7a Barcelona Elche 46
6016 3cce40a3 Girona Celta Vigo 23
6017 5b51dc48 Valencia Celta Vigo 43
6018 99d51f3f Atlético Madrid Rayo Vallecano 43
6019 3da68242 Barcelona Betis 44
6020 f4bca33a Real Madrid Rayo Vallecano 46
6021 6d421caf Villarreal Real Sociedad 43
6022 87353d2b Atlético Madrid Girona 44
6023 e0ef2dea Barcelona Real Sociedad 42
6024 d233dd60 Getafe Sevilla 42
6025 8b8d6b96 Atlético Madrid Valladolid 42
6026 65ccc663 Celta Vigo Real Madrid 44
6027 e8a7ea12 Mallorca Rayo Vallecano 46
6028 f4163c1c Valladolid Espanyol 42
6029 11efb749 Athletic Club Barcelona 40
6030 1eecb0cd Osasuna Barcelona 44
6031 f06f275b Mallorca Betis 40
6032 484db82d Athletic Club Girona 43
6033 fda8965c Villarreal Almería 44
6034 1d0024c6 Valencia Villarreal 43
6035 6510e441 Betis Almería 46
6036 bf5f27cd Rayo Vallecano Sevilla 43
6037 26d50111 Valencia Athletic Club 44
6038 9a77cbfa Espanyol Almería 46
6039 b5b65432 Betis Valladolid 44
6040 a5ce019a Mallorca Getafe 46
6041 a8988680 Betis Sevilla 45
6042 1019503c Mallorca Sevilla 45
6043 c13e375b Espanyol Celta Vigo 44
6044 37eaac0c Valencia Real Madrid 45
6045 60393b8c Real Sociedad Mallorca 46
6046 8257d737 Celta Vigo Villarreal 42
6047 0665a24f Real Madrid Osasuna 44
6048 78e99c13 Rayo Vallecano Osasuna 43
6049 338e2ca8 Osasuna Real Sociedad 44
6050 3e3f4235 Getafe Real Madrid 44
6051 f5d9346d Getafe Almería 46
6052 49912abe Almería Girona 45
6053 4c9c43b6 Athletic Club Villarreal 44
6054 8bf7a09f Barcelona Osasuna 43
6055 3d760d7b Celta Vigo Mallorca 45
6056 49ebcc28 Rayo Vallecano Almería 46
6057 f3666d93 Villarreal Girona 43
6058 8413c8fa Real Madrid Cádiz 45
6059 ee927bcc Valencia Cádiz 44
6060 610230c8 Villarreal Mallorca 45
6061 21b1f2fd Rayo Vallecano Mallorca 45
6062 73b529f2 Celta Vigo Espanyol 44
6063 1fc0e34e Barcelona Villarreal 42
6064 cf8461b9 Elche Atlético Madrid 43
6065 cd2e3313 Osasuna Mallorca 44
6066 8fd8c270 Almería Celta Vigo 42
6067 f2034421 Sevilla Betis 45
6068 fbc9070c Girona Athletic Club 45
6069 e4dabca8 Almería Cádiz 45
6070 2cbcebd9 Celta Vigo Almería 45
6071 5272c289 Rayo Vallecano Villarreal 45
6072 1778d9c6 Girona Villarreal 43
6073 d13590ac Elche Betis 43
6074 86ebf3d1 Real Sociedad Valencia 45
6075 cbe0a303 Barcelona Rayo Vallecano 46
6076 daafdb0b Athletic Club Valladolid 43
6077 bfedb115 Barcelona Mallorca 43
6078 7bfcaa51 Atlético Madrid Sevilla 40
6079 b51377f8 Real Madrid Atlético Madrid 41
6080 5391ec20 Espanyol Atlético Madrid 43
6081 9943b036 Athletic Club Betis 45
6082 1c37a941 Espanyol Barcelona 45
6083 bb7eb70e Sevilla Elche 44
6084 8cccf9d8 Elche Real Madrid 45
6085 80851b68 Rayo Vallecano Celta Vigo 45
6086 2dc7ac7e Rayo Vallecano Girona 44
6087 92aae030 Barcelona Atlético Madrid 40
6088 09f36184 Getafe Valladolid 43
6089 2d3fc14f Getafe Valencia 46
6090 1826e512 Betis Barcelona 45
6091 f1fddbae Girona Rayo Vallecano 46
6092 28815113 Villarreal Sevilla 44
6093 6b5ac953 Rayo Vallecano Real Sociedad 46
6094 007c5123 Getafe Elche 46
6095 f62862aa Atlético Madrid Mallorca 43
6096 aa565872 Valladolid Celta Vigo 42
6097 b57113f8 Cádiz Sevilla 44
6098 df985b56 Real Madrid Getafe 41
6099 312c107a Real Sociedad Celta Vigo 46
6100 77a93c43 Real Sociedad Sevilla 45
6101 5e73ad1a Mallorca Barcelona 44
6102 daf1e1e7 Valencia Betis 44
6103 ee1f906d Real Sociedad Espanyol 43
6104 8d5bc7c7 Mallorca Almería 45
6105 8b08659c Getafe Athletic Club 46
6106 ca6228b4 Athletic Club Atlético Madrid 43
6107 2325006c Valladolid Girona 43
6108 849eee87 Celta Vigo Betis 44
6109 65182979 Girona Sevilla 45
6110 ad6d83f1 Betis Atlético Madrid 44
6111 70ec6175 Getafe Cádiz 44
6112 47a1d3f2 Rayo Vallecano Athletic Club 45
6113 a3257da8 Villarreal Valencia 46
6114 81393487 Getafe Girona 46
6115 7b4e5dae Girona Valencia 45
6116 897e2175 Celta Vigo Athletic Club 46
6117 477d4cdf Villarreal Real Madrid 42
6118 6b890537 Villarreal Valladolid 42
6119 deb5f8cf Real Madrid Valladolid 42
6120 87136a5b Sevilla Espanyol 43
6121 c5d94024 Real Madrid Sevilla 43
6122 2ce5c331 Mallorca Espanyol 45
6123 64f3e100 Rayo Vallecano Getafe 45
6124 bc5d03d2 Atlético Madrid Athletic Club 43
6125 bc23d0ab Cádiz Atlético Madrid 44
6126 274b9a9c Elche Osasuna 40
6127 e551bbc8 Celta Vigo Osasuna 44
6128 d5dc8a2c Getafe Espanyol 43
6129 a8b647af Sevilla Rayo Vallecano 46
6130 c2084c72 Elche Celta Vigo 42
6131 cc61d2ba Atlético Madrid Celta Vigo 42
6132 615ccfb0 Athletic Club Valencia 46
6133 bed213b9 Real Sociedad Rayo Vallecano 44
6134 a32c09d3 Barcelona Celta Vigo 42
6135 3e47416b Getafe Real Sociedad 45
6136 53243b91 Real Sociedad Athletic Club 46
6137 c5637fb1 Getafe Mallorca 46
6138 c6483087 Osasuna Getafe 44
6139 a94a07e1 Elche Espanyol 42
6140 1de90754 Betis Espanyol 45
6141 93e7ec48 Celta Vigo Barcelona 44
6142 4ad25809 Athletic Club Cádiz 44
6143 7493a41f Valencia Elche 44
6144 ffde27ac Real Madrid Girona 45
6145 dfc7863c Espanyol Elche 45
6146 da3b5ed5 Valencia Atlético Madrid 43
6147 6dd225f0 Girona Almería 45
6148 d7c28578 Osasuna Girona 45
6149 b944484e Valencia Almería 46
6150 bc5ec3c6 Sevilla Valladolid 23
6151 318144c8 Sevilla Cádiz 42
6152 1f998adf Betis Elche 39
6153 09f83bbc Barcelona Getafe 44
6154 95368d85 Valladolid Mallorca 43
6155 8ed0d2b7 Betis Osasuna 46
6156 aaab7ab9 Valencia Girona 23
6157 4ed9f64b Barcelona Valladolid 23
6158 67f4644f Athletic Club Osasuna 43
6159 67a548bd Girona Valladolid 45
6160 4760076d Villarreal Osasuna 40
6161 a9afb44e Valencia Mallorca 46
6162 b99f8e19 Cádiz Celta Vigo 46
6163 a3190587 Valladolid Atlético Madrid 42
6164 b1dca05d Sevilla Getafe 46
6165 c8355bdd Real Madrid Valencia 44
6166 aa527e49 Almería Atlético Madrid 43
6167 d530a139 Rayo Vallecano Atlético Madrid 43
6168 b5585ff8 Elche Sevilla 44
6169 af336b4a Cádiz Athletic Club 44
6170 dfda9563 Cádiz Girona 44
6171 dd7431ec Getafe Osasuna 43
6172 9ba59fd7 Rayo Vallecano Betis 46
6173 ce677ae3 Real Madrid Athletic Club 46
6174 1253bef2 Girona Getafe 23
6175 722dabd5 Valencia Sevilla 45
6176 ccb89898 Real Sociedad Atlético Madrid 43
6177 58ddf563 Almería Espanyol 44
6178 8fb6eaaa Atlético Madrid Elche 45
6179 44e57939 Villarreal Barcelona 41
6180 be7e4222 Valladolid Villarreal 20
6181 ad94dd60 Athletic Club Real Madrid 42
6182 39d72386 Osasuna Cádiz 45
6183 19bec97a Sevilla Osasuna 39
6184 85293f4f Girona Cádiz 46
6185 0792ae6b Sevilla Mallorca 43
6186 1e086908 Cádiz Rayo Vallecano 45
6187 c554c5ac Atlético Madrid Real Madrid 42
6188 3eac51cc Real Sociedad Valladolid 41
6189 6f633cb1 Elche Almería 22
6190 764f1270 Girona Osasuna 45
6191 15bdf085 Elche Barcelona 43
6192 f08a0268 Real Madrid Espanyol 45
6193 c9cc060c Real Madrid Villarreal 43
6194 21392431 Betis Celta Vigo 46
6195 1b9ec7de Girona Espanyol 44
6196 60cdc671 Cádiz Valladolid 45
6197 954c93c1 Betis Rayo Vallecano 46
6198 49ec6969 Valladolid Betis 44
6199 7b8f18a1 Elche Cádiz 46
6200 42eb1869 Atlético Madrid Betis 41
6201 06840a85 Rayo Vallecano Barcelona 44
6202 fd3ed02d Osasuna Athletic Club 43
6203 ab718d01 Athletic Club Sevilla 43
6204 3b56db84 Girona Real Sociedad 45
6205 6f312540 Espanyol Getafe 45
6206 7b270235 Celta Vigo Real Sociedad 44
6207 87d24f61 Real Sociedad Osasuna 46
6208 33b0a63b Valladolid Almería 46
6209 23d327b5 Mallorca Atlético Madrid 45
6210 7044faa9 Rayo Vallecano Elche 44
6211 e668a91a Betis Mallorca 44
6212 77173e8b Cádiz Espanyol 44
6213 77b8c292 Valencia Osasuna 44
6214 ad03c9e1 Osasuna Valencia 45
6215 f24fba48 Elche Rayo Vallecano 45
6216 ea93d7f3 Betis Cádiz 44
6217 4f0d05ab Elche Getafe 44
6218 dad5414f Real Sociedad Betis 43
6219 c0d557e1 Cádiz Villarreal 43
6220 c1e42359 Almería Real Madrid 23
6221 47134469 Almería Barcelona 43
6222 66ac20bd Celta Vigo Cádiz 45
6223 366a3ab1 Almería Villarreal 46
6224 4c562ec1 Athletic Club Real Sociedad 46
6225 2c36118e Valencia Valladolid 46
6226 e5cc8927 Celta Vigo Elche 46

In [48]:
new_attrs['Match_Id'] = atr_match_id
new_attrs['Home_Attack'] = atr_home_attack
new_attrs['Home_Midfield'] = atr_home_midfield
new_attrs['Home_Defense'] = atr_home_defense
new_attrs['Away_Attack'] = atr_away_attack
new_attrs['Away_Midfield'] = atr_away_midfield
new_attrs['Away_Defense'] = atr_away_defense

In [49]:
match_dataset_model_new = pd.merge(match_dataset_model, new_attrs, on='Match_Id', how='inner')
match_dataset_model_new

,Match_Id,Match_Date,Home_Team,Home_Manager,Home_Captain,Home_Formation,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,...,Away_Att_Take_Ons,Away_Succ_Take_Ons,Home_Score,Away_Score,Home_Attack,Home_Midfield,Home_Defense,Away_Attack,Away_Midfield,Away_Defense
0,4eccf13c,1/16/2019,Nîmes,Unknown,Unknown,4/4/2002,57,13,5,19,...,8,7,1,0,70.166667,70.583333,68.750000,74.333333,74.187500,73.571429
1,da4a3dd0,2/8/2019,Dijon,Unknown,Unknown,4/3/2003,41,11,3,17,...,15,10,1,2,73.800000,71.857143,70.333333,76.714286,77.916667,74.875000
2,6a8b98ba,4/14/2019,Saint-Étienne,Unknown,Unknown,3/4/2003,50,13,8,24,...,12,10,3,0,71.500000,76.000000,71.857143,72.600000,68.230769,70.333333
3,25268197,5/24/2019,Nantes,Unknown,Unknown,4/3/2003,51,7,4,20,...,13,10,0,1,69.625000,72.928571,70.333333,72.200000,71.769231,73.000000
4,2bfe33f3,1/11/2019,Caen,Unknown,Unknown,4-2-3-1,56,14,4,25,...,11,4,1,3,72.400000,73.285714,69.272727,75.600000,74.800000,71.700000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,9492fa68,5/25/2024,Milan,Unknown,Unknown,4-2-3-1,66,6,13,27,...,9,2,3,3,81.375000,79.285714,77.800000,70.500000,70.210526,69.625000
10679,d63c561d,5/18/2024,Lecce,Unknown,Unknown,4/4/2002,44,7,2,15,...,13,7,0,2,69.181818,67.307692,71.125000,78.250000,75.500000,73.307692
10680,dec7c7ae,5/11/2024,Milan,Unknown,Unknown,4-2-3-1,66,11,6,15,...,17,6,5,1,81.222222,77.428571,77.571429,69.888889,71.444444,70.600000
10681,ab8f65b4,5/19/2024,Monza,Unknown,Unknown,4-2-3-1,70,14,3,23,...,17,9,0,1,71.545455,73.125000,73.636364,68.727273,69.111111,68.416667
10682,f6279636,5/12/2024,Lazio,Unknown,Unknown,3/4/2003,59,18,7,17,...,20,8,2,0,77.285714,77.777778,77.700000,71.692308,71.470588,70.083333

In [50]:
match_dataset_model_new = match_dataset_model_new.loc[:,['Match_Id', 'Match_Date',
                                'Home_Team', 'Home_Manager', 'Home_Captain',
                                'Home_Formation', 'Home_Possession', 'Home_Fouls', 'Home_Corners', 'Home_Crosses',
                                'Home_Aerials_Won', 'Home_Clearances', 'Home_Offsides', 'Home_Goal_Kicks',
                                'Home_Throw_Ins', 'Home_Long_Balls', 'Home_Total_Players_Stats', 'Home_Minutes',
                                'Home_Gls', 'Home_Ast', 'Home_PK', 'Home_PK_Att',
                                'Home_Sh','Home_SoT', 'Home_CrdY', 'Home_CrdR',
                                'Home_Touches','Home_Tkl','Home_Int','Home_Blocks',
                                'Home_xG','Home_npxG', 'Home_xAG',
                                'Home_SCA', 'Home_GCA',
                                'Home_Cmp_Passes', 'Home_Att_Passes', 'Home_Cmp_percent_Passes', 'Home_PrgP_Passes',
                                'Home_Carries_Carries', 'Home_PrgC_Carries',
                                'Home_Att_Take_Ons', 'Home_Succ_Take_Ons',
                                'Away_Team', 'Away_Manager', 'Away_Captain',
                                'Away_Formation', 'Away_Possession', 'Away_Fouls', 'Away_Corners', 'Away_Crosses',
                                'Away_Aerials_Won', 'Away_Clearances', 'Away_Offsides', 'Away_Goal_Kicks',
                                'Away_Throw_Ins', 'Away_Long_Balls', 'Away_Total_Players_Stats', 'Away_Minutes',
                                'Away_Gls', 'Away_Ast', 'Away_PK', 'Away_PK_Att',
                                'Away_Sh','Away_SoT', 'Away_CrdY', 'Away_CrdR',
                                'Away_Touches','Away_Tkl','Away_Int','Away_Blocks',
                                'Away_xG','Away_npxG', 'Away_xAG',
                                'Away_SCA', 'Away_GCA',
                                'Away_Cmp_Passes', 'Away_Att_Passes', 'Away_Cmp_percent_Passes', 'Away_PrgP_Passes',
                                'Away_Carries_Carries', 'Away_PrgC_Carries',
                                'Away_Att_Take_Ons', 'Away_Succ_Take_Ons',
                                'Home_Attack', 'Home_Midfield', 'Home_Defense',
                                'Away_Attack', 'Away_Midfield', 'Away_Defense',
                                'Home_Score','Away_Score']]
match_dataset_model_new

,Match_Id,Match_Date,Home_Team,Home_Manager,Home_Captain,Home_Formation,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,...,Away_Att_Take_Ons,Away_Succ_Take_Ons,Home_Attack,Home_Midfield,Home_Defense,Away_Attack,Away_Midfield,Away_Defense,Home_Score,Away_Score
0,4eccf13c,1/16/2019,Nîmes,Unknown,Unknown,4/4/2002,57,13,5,19,...,8,7,70.166667,70.583333,68.750000,74.333333,74.187500,73.571429,1,0
1,da4a3dd0,2/8/2019,Dijon,Unknown,Unknown,4/3/2003,41,11,3,17,...,15,10,73.800000,71.857143,70.333333,76.714286,77.916667,74.875000,1,2
2,6a8b98ba,4/14/2019,Saint-Étienne,Unknown,Unknown,3/4/2003,50,13,8,24,...,12,10,71.500000,76.000000,71.857143,72.600000,68.230769,70.333333,3,0
3,25268197,5/24/2019,Nantes,Unknown,Unknown,4/3/2003,51,7,4,20,...,13,10,69.625000,72.928571,70.333333,72.200000,71.769231,73.000000,0,1
4,2bfe33f3,1/11/2019,Caen,Unknown,Unknown,4-2-3-1,56,14,4,25,...,11,4,72.400000,73.285714,69.272727,75.600000,74.800000,71.700000,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,9492fa68,5/25/2024,Milan,Unknown,Unknown,4-2-3-1,66,6,13,27,...,9,2,81.375000,79.285714,77.800000,70.500000,70.210526,69.625000,3,3
10679,d63c561d,5/18/2024,Lecce,Unknown,Unknown,4/4/2002,44,7,2,15,...,13,7,69.181818,67.307692,71.125000,78.250000,75.500000,73.307692,0,2
10680,dec7c7ae,5/11/2024,Milan,Unknown,Unknown,4-2-3-1,66,11,6,15,...,17,6,81.222222,77.428571,77.571429,69.888889,71.444444,70.600000,5,1
10681,ab8f65b4,5/19/2024,Monza,Unknown,Unknown,4-2-3-1,70,14,3,23,...,17,9,71.545455,73.125000,73.636364,68.727273,69.111111,68.416667,0,1
10682,f6279636,5/12/2024,Lazio,Unknown,Unknown,3/4/2003,59,18,7,17,...,20,8,77.285714,77.777778,77.700000,71.692308,71.470588,70.083333,2,0

Fact Match Statistics

In [ ]:
#existing files
#match_dataset_model = pd.read_csv("gs://football-data-etl/football-data-extracted/output-basic/match_dataset_model_new.csv")

In [51]:
match_dataset_model = match_dataset_model_new

In [52]:
unique_values1 = match_dataset_model.loc[~match_dataset_model['Home_Team'].isin(dim_team['Team_Name']), 'Home_Team'].unique()
unique_values1

array(['Gladbach'], dtype=object)

In [53]:
match_dataset_model.loc[match_dataset_model['Home_Team'] == 'Gladbach', 'Home_Team'] = "M'Gladbach"
match_dataset_model.loc[match_dataset_model['Away_Team'] == 'Gladbach', 'Away_Team'] = "M'Gladbach"

In [54]:
unique_values2 = match_dataset_model.loc[~match_dataset_model['Home_Team'].isin(dim_team['Team_Name']), 'Home_Team'].unique()
unique_values2

array([], dtype=object)

In [55]:
fact_match_statistics = pd.DataFrame({'Match': [],
                                'Home_Team': [],
                                'Home_Possession': [], 'Home_Fouls': [], 'Home_Corners': [],
                                'Home_Crosses': [], 'Home_Aerials_Won': [], 'Home_Clearances': [],
                                'Home_Offsides': [], 'Home_Goal_Kicks': [], 'Home_Throw_Ins': [],
                                'Home_Long_Balls': [], 'Home_Total_Players_Stats': [], 'Home_Minutes': [],
                                'Home_Gls': [], 'Home_Ast': [], 'Home_PK': [],
                                'Home_PK_Att': [], 'Home_Sh': [], 'Home_SoT': [],
                                'Home_CrdY': [], 'Home_CrdR': [], 'Home_Touches': [],
                                'Home_Tkl': [], 'Home_Int': [], 'Home_Blocks': [],
                                'Home_xG': [], 'Home_npxG': [], 'Home_xAG': [],
                                'Home_SCA': [], 'Home_GCA': [], 'Home_Cmp_Passes': [],
                                'Home_Att_Passes': [], 'Home_Cmp_percent_Passes': [], 'Home_PrgP_Passes': [],
                                'Home_Carries_Carries': [], 'Home_PrgC_Carries': [], 'Home_Att_Take_Ons': [],
                                'Home_Succ_Take_Ons': [],

                                'Away_Team': [],
                                'Away_Possession': [],'Away_Fouls': [],'Away_Corners': [],
                                'Away_Crosses': [],'Away_Aerials_Won': [],'Away_Clearances': [],
                                'Away_Offsides': [],'Away_Goal_Kicks': [],'Away_Throw_Ins': [],
                                'Away_Long_Balls': [],'Away_Total_Players_Stats': [],'Away_Minutes': [],
                                'Away_Gls': [],'Away_Ast': [],'Away_PK': [],
                                'Away_PK_Att': [],'Away_Sh': [],'Away_SoT': [],
                                'Away_CrdY': [],'Away_CrdR': [],'Away_Touches': [],
                                'Away_Tkl': [],'Away_Int': [],'Away_Blocks': [],
                                'Away_xG': [],'Away_npxG': [],'Away_xAG': [],
                                'Away_SCA': [],'Away_GCA': [],'Away_Cmp_Passes': [],
                                'Away_Att_Passes': [],'Away_Cmp_percent_Passes': [],'Away_PrgP_Passes': [],
                                'Away_Carries_Carries': [],'Away_PrgC_Carries': [],'Away_Att_Take_Ons': [],
                                'Away_Succ_Take_Ons': [],

                                'Home_Attack': [],'Home_Midfield': [],'Home_Defense': [],
                                'Away_Attack': [],'Away_Midfield': [],'Away_Defense': [],
                                'Home_Score': [],'Away_Score': []})

list_match = []
list_home_team = []
list_away_team = []

for i in range(0,len(match_dataset_model)):


    temp_df = dim_match[dim_match['Match_Id'] == match_dataset_model['Match_Id'].iloc[i]]
    if (len(temp_df) > 0):
        list_match.append(temp_df['Match_Key'].iloc[0])
    else:
        list_match.append(np.nan)

    temp_df = dim_team[dim_team['Team_Name'] == match_dataset_model['Home_Team'].iloc[i]]
    if (len(temp_df) > 0):

        print(i, match_dataset_model['Home_Team'].iloc[i])

        list_home_team.append(temp_df['Team_Key'].iloc[0])
    else:
        list_home_team.append(np.nan)



    temp_df = dim_team[dim_team['Team_Name'] == match_dataset_model_new['Away_Team'].iloc[i]]
    if (len(temp_df) > 0):
        list_away_team.append(temp_df['Team_Key'].iloc[0])
    else:
        list_away_team.append(np.nan)

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
5683 Alavés
5684 Villarreal
5685 Atlético Madrid
5686 Valencia
5687 Real Sociedad
5688 Granada
5689 Sevilla
5690 Athletic Club
5691 Valencia
5692 Valencia
5693 Elche
5694 Granada
5695 Elche
5696 Sevilla
5697 Celta Vigo
5698 Elche
5699 Espanyol
5700 Villarreal
5701 Athletic Club
5702 Osasuna
5703 Villarreal
5704 Villarreal
5705 Athletic Club
5706 Real Madrid
5707 Levante
5708 Atlético Madrid
5709 Real Sociedad
5710 Barcelona
5711 Barcelona
5712 Celta Vigo
5713 Rayo Vallecano
5714 Granada
5715 Granada
5716 Barcelona
5717 Real Madrid
5718 Betis
5719 Barcelona
5720 Athletic Club
5721 Real Madrid
5722 Mallorca
5723 Getafe
5724 Rayo Vallecano
5725 Real Madrid
5726 Villarreal
5727 Osasuna
5728 Levante
5729 Rayo Vallecano
5730 Rayo Vallecano
5731 Alavés
5732 Getafe
5733 Celta Vigo
5734 Villarreal
5735 Levante
5736 Granada
5737 Atlético Madrid
5738 Espanyol
5739 Espanyol
5740 Granada
5741 Levante
5742 Sevilla
5743 Real Sociedad
5744 Celta Vigo
5745 Betis
5746 Granada
5747 Valencia
5748 Mallorca
5749 Rayo Vallecano
5750 Real Sociedad
5751 Levante
5752 Sevilla
5753 Sevilla
5754 Getafe
5755 Osasuna
5756 Barcelona
5757 Real Sociedad
5758 Real Sociedad
5759 Osasuna
5760 Getafe
5761 Granada
5762 Cádiz
5763 Alavés
5764 Rayo Vallecano
5765 Villarreal
5766 Levante
5767 Espanyol
5768 Alavés
5769 Espanyol
5770 Espanyol
5771 Atlético Madrid
5772 Real Sociedad
5773 Real Sociedad
5774 Atlético Madrid
5775 Betis
5776 Atlético Madrid
5777 Villarreal
5778 Valencia
5779 Osasuna
5780 Real Madrid
5781 Betis
5782 Celta Vigo
5783 Valencia
5784 Real Sociedad
5785 Valencia
5786 Getafe
5787 Levante
5788 Cádiz
5789 Real Sociedad
5790 Atlético Madrid
5791 Barcelona
5792 Valencia
5793 Athletic Club
5794 Sevilla
5795 Real Sociedad
5796 Barcelona
5797 Villarreal
5798 Osasuna
5799 Mallorca
5800 Espanyol
5801 Espanyol
5802 Valencia
5803 Mallorca
5804 Sevilla
5805 Celta Vigo
5806 Real Sociedad
5807 Cádiz
5808 Real Sociedad
5809 Getafe
5810 Barcelona
5811 Elche
5812 Villarreal
5813 Getafe
5814 Valencia
5815 Getafe
5816 Villarreal
5817 Alavés
5818 Athletic Club
5819 Real Madrid
5820 Betis
5821 Barcelona
5822 Mallorca
5823 Elche
5824 Sevilla
5825 Villarreal
5826 Elche
5827 Betis
5828 Mallorca
5829 Mallorca
5830 Granada
5831 Espanyol
5832 Celta Vigo
5833 Alavés
5834 Granada
5835 Villarreal
5836 Rayo Vallecano
5837 Sevilla
5838 Real Madrid
5839 Mallorca
5840 Barcelona
5841 Osasuna
5842 Barcelona
5843 Atlético Madrid
5844 Osasuna
5845 Betis
5846 Real Madrid
5847 Athletic Club
5848 Real Madrid
5849 Sevilla
5850 Barcelona
5851 Granada
5852 Alavés
5853 Celta Vigo
5854 Levante
5855 Villarreal
5856 Getafe
5857 Getafe
5858 Barcelona
5859 Real Sociedad
5860 Celta Vigo
5861 Granada
5862 Mallorca
5863 Osasuna
5864 Mallorca
5865 Mallorca
5866 Valladolid
5867 Sevilla
5868 Elche
5869 Valladolid
5870 Atlético Madrid
5871 Barcelona
5872 Espanyol
5873 Athletic Club
5874 Getafe
5875 Sevilla
5876 Elche
5877 Almería
5878 Villarreal
5879 Athletic Club
5880 Getafe
5881 Rayo Vallecano
5882 Elche
5883 Mallorca
5884 Atlético Madrid
5885 Girona
5886 Rayo Vallecano
5887 Real Madrid
5888 Girona
5889 Real Sociedad
5890 Mallorca
5891 Espanyol
5892 Betis
5893 Getafe
5894 Real Sociedad
5895 Barcelona
5896 Real Madrid
5897 Real Madrid
5898 Valencia
5899 Villarreal
5900 Mallorca
5901 Athletic Club
5902 Osasuna
5903 Cádiz
5904 Valladolid
5905 Mallorca
5906 Almería
5907 Celta Vigo
5908 Almería
5909 Rayo Vallecano
5910 Atlético Madrid
5911 Cádiz
5912 Real Madrid
5913 Rayo Vallecano
5914 Barcelona
5915 Espanyol
5916 Celta Vigo
5917 Villarreal
5918 Real Sociedad
5919 Valladolid
5920 Cádiz
5921 Atlético Madrid
5922 Elche
5923 Sevilla
5924 Barcelona
5925 Betis
5926 Getafe
5927 Mallorca
5928 Atlético Madrid
5929 Espanyol
5930 Valladolid
5931 Mallorca
5932 Cádiz
5933 Cádiz
5934 Valladolid
5935 Cádiz
5936 Cádiz
5937 Getafe
5938 Sevilla
5939 Barcelona
5940 Espanyol
5941 Almería
5942 Elche
5943 Mallorca
5944 Villarreal
5945 Valladolid
5946 Valladolid
5947 Osasuna
5948 Betis
5949 Espanyol
5950 Osasuna
5951 Almería
5952 Osasuna
5953 Almería
5954 Betis
5955 Osasuna
5956 Almería
5957 Almería
5958 Celta Vigo
5959 Almería
5960 Betis
5961 Villarreal
5962 Athletic Club
5963 Espanyol
5964 Espanyol
5965 Sevilla
5966 Betis
5967 Valencia
5968 Barcelona
5969 Osasuna
5970 Real Madrid
5971 Osasuna
5972 Espanyol
5973 Real Madrid
5974 Sevilla
5975 Athletic Club
5976 Girona
5977 Valencia
5978 Celta Vigo
5979 Elche
5980 Valladolid
5981 Sevilla
5982 Osasuna
5983 Barcelona
5984 Atlético Madrid
5985 Rayo Vallecano
5986 Mallorca
5987 Osasuna
5988 Valladolid
5989 Villarreal
5990 Espanyol
5991 Espanyol
5992 Espanyol
5993 Girona
5994 Espanyol
5995 Valencia
5996 Real Sociedad
5997 Atlético Madrid
5998 Valladolid
5999 Girona
6000 Real Sociedad
6001 Elche
6002 Mallorca
6003 Osasuna
6004 Real Sociedad
6005 Osasuna
6006 Cádiz
6007 Barcelona
6008 Almería
6009 Atlético Madrid
6010 Cádiz
6011 Athletic Club
6012 Sevilla
6013 Atlético Madrid
6014 Villarreal
6015 Barcelona
6016 Girona
6017 Valencia
6018 Atlético Madrid
6019 Barcelona
6020 Real Madrid
6021 Villarreal
6022 Atlético Madrid
6023 Barcelona
6024 Getafe
6025 Atlético Madrid
6026 Celta Vigo
6027 Mallorca
6028 Valladolid
6029 Athletic Club
6030 Osasuna
6031 Mallorca
6032 Athletic Club
6033 Villarreal
6034 Valencia
6035 Betis
6036 Rayo Vallecano
6037 Valencia
6038 Espanyol
6039 Betis
6040 Mallorca
6041 Betis
6042 Mallorca
6043 Espanyol
6044 Valencia
6045 Real Sociedad
6046 Celta Vigo
6047 Real Madrid
6048 Rayo Vallecano
6049 Osasuna
6050 Getafe
6051 Getafe
6052 Almería
6053 Athletic Club
6054 Barcelona
6055 Celta Vigo
6056 Rayo Vallecano
6057 Villarreal
6058 Real Madrid
6059 Valencia
6060 Villarreal
6061 Rayo Vallecano
6062 Celta Vigo
6063 Barcelona
6064 Elche
6065 Osasuna
6066 Almería
6067 Sevilla
6068 Girona
6069 Almería
6070 Celta Vigo
6071 Rayo Vallecano
6072 Girona
6073 Elche
6074 Real Sociedad
6075 Barcelona
6076 Athletic Club
6077 Barcelona
6078 Atlético Madrid
6079 Real Madrid
6080 Espanyol
6081 Athletic Club
6082 Espanyol
6083 Sevilla
6084 Elche
6085 Rayo Vallecano
6086 Rayo Vallecano
6087 Barcelona
6088 Getafe
6089 Getafe
6090 Betis
6091 Girona
6092 Villarreal
6093 Rayo Vallecano
6094 Getafe
6095 Atlético Madrid
6096 Valladolid
6097 Cádiz
6098 Real Madrid
6099 Real Sociedad
6100 Real Sociedad
6101 Mallorca
6102 Valencia
6103 Real Sociedad
6104 Mallorca
6105 Getafe
6106 Athletic Club
6107 Valladolid
6108 Celta Vigo
6109 Girona
6110 Betis
6111 Getafe
6112 Rayo Vallecano
6113 Villarreal
6114 Getafe
6115 Girona
6116 Celta Vigo
6117 Villarreal
6118 Villarreal
6119 Real Madrid
6120 Sevilla
6121 Real Madrid
6122 Mallorca
6123 Rayo Vallecano
6124 Atlético Madrid
6125 Cádiz
6126 Elche
6127 Celta Vigo
6128 Getafe
6129 Sevilla
6130 Elche
6131 Atlético Madrid
6132 Athletic Club
6133 Real Sociedad
6134 Barcelona
6135 Getafe
6136 Real Sociedad
6137 Getafe
6138 Osasuna
6139 Elche
6140 Betis
6141 Celta Vigo
6142 Athletic Club
6143 Valencia
6144 Real Madrid
6145 Espanyol
6146 Valencia
6147 Girona
6148 Osasuna
6149 Valencia
6150 Sevilla
6151 Sevilla
6152 Betis
6153 Barcelona
6154 Valladolid
6155 Betis
6156 Valencia
6157 Barcelona
6158 Athletic Club
6159 Girona
6160 Villarreal
6161 Valencia
6162 Cádiz
6163 Valladolid
6164 Sevilla
6165 Real Madrid
6166 Almería
6167 Rayo Vallecano
6168 Elche
6169 Cádiz
6170 Cádiz
6171 Getafe
6172 Rayo Vallecano
6173 Real Madrid
6174 Girona
6175 Valencia
6176 Real Sociedad
6177 Almería
6178 Atlético Madrid
6179 Villarreal
6180 Valladolid
6181 Athletic Club
6182 Osasuna
6183 Sevilla
6184 Girona
6185 Sevilla
6186 Cádiz
6187 Atlético Madrid
6188 Real Sociedad
6189 Elche
6190 Girona
6191 Elche
6192 Real Madrid
6193 Real Madrid
6194 Betis
6195 Girona
6196 Cádiz
6197 Betis
6198 Valladolid
6199 Elche
6200 Atlético Madrid
6201 Rayo Vallecano
6202 Osasuna
6203 Athletic Club
6204 Girona
6205 Espanyol
6206 Celta Vigo
6207 Real Sociedad
6208 Valladolid
6209 Mallorca
6210 Rayo Vallecano
6211 Betis
6212 Cádiz
6213 Valencia
6214 Osasuna
6215 Elche
6216 Betis
6217 Elche
6218 Real Sociedad
6219 Cádiz
6220 Almería
6221 Almería
6222 Celta Vigo
6223 Almería
6224 Athletic Club
6225 Valencia
6226 Celta Vigo
6227 Real Madrid
6228 Cádiz
6229 Girona
6230 Betis
6231 Celta Vigo
6232 Villarreal
6233 Sevilla
6234 Almería
6235 Celta Vigo
6236 Valencia
6237 Real Sociedad
6238 Sevilla
6239 Getafe
6240 Villarreal
6241 Barcelona
6242 Real Sociedad
6243 Las Palmas
6244 Osasuna
6245 Real Madrid
6246 Mallorca
6247 Valencia
6248 Real Madrid
6249 Sevilla
6250 Las Palmas
6251 Osasuna
6252 Cádiz
6253 Real Madrid
6254 Real Sociedad
6255 Real Sociedad
6256 Atlético Madrid
6257 Mallorca
6258 Real Sociedad
6259 Athletic Club
6260 Celta Vigo
6261 Las Palmas
6262 Getafe
6263 Getafe
6264 Sevilla
6265 Mallorca
6266 Granada
6267 Osasuna
6268 Barcelona
6269 Las Palmas
6270 Sevilla
6271 Osasuna
6272 Alavés
6273 Villarreal
6274 Getafe
6275 Alavés
6276 Alavés
6277 Atlético Madrid
6278 Barcelona
6279 Real Madrid
6280 Real Sociedad
6281 Almería
6282 Girona
6283 Cádiz
6284 Villarreal
6285 Getafe
6286 Mallorca
6287 Villarreal
6288 Mallorca
6289 Granada
6290 Almería
6291 Granada
6292 Cádiz
6293 Real Sociedad
6294 Osasuna
6295 Barcelona
6296 Girona
6297 Rayo Vallecano
6298 Barcelona
6299 Granada
6300 Barcelona
6301 Celta Vigo
6302 Alavés
6303 Cádiz
6304 Cádiz
6305 Almería
6306 Sevilla
6307 Granada
6308 Valencia
6309 Atlético Madrid
6310 Cádiz
6311 Sevilla
6312 Sevilla
6313 Getafe
6314 Betis
6315 Betis
6316 Sevilla
6317 Athletic Club
6318 Barcelona
6319 Granada
6320 Rayo Vallecano
6321 Villarreal
6322 Athletic Club
6323 Valencia
6324 Betis
6325 Betis
6326 Las Palmas
6327 Alavés
6328 Betis
6329 Villarreal
6330 Alavés
6331 Celta Vigo
6332 Girona
6333 Celta Vigo
6334 Athletic Club
6335 Atlético Madrid
6336 Rayo Vallecano
6337 Valencia
6338 Rayo Vallecano
6339 Rayo Vallecano
6340 Almería
6341 Valencia
6342 Las Palmas
6343 Cádiz
6344 Real Madrid
6345 Betis
6346 Real Madrid
6347 Girona
6348 Mallorca
6349 Valencia
6350 Real Madrid
6351 Mallorca
6352 Atlético Madrid
6353 Valencia
6354 Atlético Madrid
6355 Betis
6356 Athletic Club
6357 Girona
6358 Villarreal
6359 Villarreal
6360 Almería
6361 Villarreal
6362 Rayo Vallecano
6363 Alavés
6364 Granada
6365 Valencia
6366 Atlético Madrid
6367 Getafe
6368 Almería
6369 Almería
6370 Real Sociedad
6371 Valencia
6372 Villarreal
6373 Osasuna
6374 Atlético Madrid
6375 Mallorca
6376 Betis
6377 Rayo Vallecano
6378 Rayo Vallecano
6379 Athletic Club
6380 Real Madrid
6381 Celta Vigo
6382 Celta Vigo
6383 Sevilla
6384 Barcelona
6385 Real Sociedad
6386 Atlético Madrid
6387 Las Palmas
6388 Granada
6389 Villarreal
6390 Atlético Madrid
6391 Girona
6392 Sevilla
6393 Alavés
6394 Mallorca
6395 Barcelona
6396 Atlético Madrid
6397 Almería
6398 Athletic Club
6399 Osasuna
6400 Celta Vigo
6401 Osasuna
6402 Betis
6403 Alavés
6404 Sevilla
6405 Betis
6406 Almería
6407 Real Madrid
6408 Las Palmas
6409 Mallorca
6410 Athletic Club
6411 Celta Vigo
6412 Rayo Vallecano
6413 Celta Vigo
6414 Granada
6415 Granada
6416 Athletic Club
6417 Athletic Club
6418 Villarreal
6419 Osasuna
6420 Granada
6421 Getafe
6422 Rayo Vallecano
6423 Rayo Vallecano
6424 Cádiz
6425 Betis
6426 Alavés
6427 Villarreal
6428 Celta Vigo
6429 Osasuna
6430 Real Madrid
6431 Cádiz
6432 Real Madrid
6433 Celta Vigo
6434 Las Palmas
6435 Mallorca
6436 Valencia
6437 Real Madrid
6438 Atlético Madrid
6439 Betis
6440 Alavés
6441 Atlético Madrid
6442 Getafe
6443 Granada
6444 Celta Vigo
6445 Alavés
6446 Real Madrid
6447 Las Palmas
6448 Athletic Club
6449 Barcelona
6450 Villarreal
6451 Las Palmas
6452 Real Sociedad
6453 Real Madrid
6454 Mallorca
6455 Cádiz
6456 Barcelona
6457 Valencia
6458 Villarreal
6459 Rayo Vallecano
6460 Valencia
6461 Cádiz
6462 Athletic Club
6463 Real Sociedad
6464 Las Palmas
6465 Las Palmas
6466 Granada
6467 Valencia
6468 Alavés
6469 Las Palmas
6470 Almería
6471 Granada
6472 Girona
6473 Cádiz
6474 Almería
6475 Las Palmas
6476 Almería
6477 Betis
6478 Celta Vigo
6479 Girona
6480 Cádiz
6481 Real Sociedad
6482 Sevilla
6483 Las Palmas
6484 Girona
6485 Girona
6486 Osasuna
6487 Almería
6488 Osasuna
6489 Sevilla
6490 Real Sociedad
6491 Athletic Club
6492 Osasuna
6493 Granada
6494 Girona
6495 Celta Vigo
6496 Osasuna
6497 Real Sociedad
6498 Betis
6499 Cádiz
6500 Mallorca
6501 Cádiz
6502 Valencia
6503 Rayo Vallecano
6504 Getafe
6505 Mallorca
6506 Alavés
6507 Valencia
6508 Girona
6509 Girona
6510 Rayo Vallecano
6511 Getafe
6512 Girona
6513 Girona
6514 Betis
6515 Almería
6516 Alavés
6517 Betis
6518 Getafe
6519 Betis
6520 Mallorca
6521 Sevilla
6522 Girona
6523 Atlético Madrid
6524 Villarreal
6525 Rayo Vallecano
6526 Osasuna
6527 Almería
6528 Cádiz
6529 Athletic Club
6530 Sevilla
6531 Real Madrid
6532 Getafe
6533 Alavés
6534 Atlético Madrid
6535 Getafe
6536 Barcelona
6537 Celta Vigo
6538 Atlético Madrid
6539 Athletic Club
6540 Getafe
6541 Alavés
6542 Villarreal
6543 Real Sociedad
6544 Athletic Club
6545 Almería
6546 Real Madrid
6547 Barcelona
6548 Cádiz
6549 Osasuna
6550 Real Sociedad
6551 Granada
6552 Sevilla
6553 Celta Vigo
6554 Getafe
6555 Sevilla
6556 Granada
6557 Athletic Club
6558 Rayo Vallecano
6559 Barcelona
6560 Atlético Madrid
6561 Real Sociedad
6562 Mallorca
6563 Girona
6564 Alavés
6565 Osasuna
6566 Betis
6567 Alavés
6568 Almería
6569 Almería
6570 Osasuna
6571 Atlético Madrid
6572 Valencia
6573 Real Sociedad
6574 Real Sociedad
6575 Las Palmas
6576 Rayo Vallecano
6577 Las Palmas
6578 Sevilla
6579 Villarreal
6580 Villarreal
6581 Athletic Club
6582 Sevilla
6583 Getafe
6584 Betis
6585 Real Sociedad
6586 Mallorca
6587 Real Madrid
6588 Mallorca
6589 Granada
6590 Osasuna
6591 Girona
6592 Celta Vigo
6593 Getafe
6594 Celta Vigo
6595 Granada
6596 Atlético Madrid
6597 Cádiz
6598 Athletic Club
6599 Real Madrid
6600 Rayo Vallecano
6601 Valencia
6602 Getafe
6603 Cádiz
6604 Mallorca
6605 Sevilla
6606 Rayo Vallecano
6607 Real Madrid
6608 Valencia
6609 Barcelona
6610 Celta Vigo
6611 Barcelona
6612 Girona
6613 M'Gladbach
6614 Hertha BSC
6615 M'Gladbach
6616 Wolfsburg
6617 Augsburg
6618 Dortmund
6619 Werder Bremen
6620 Freiburg
6621 Bayern Munich
6622 Düsseldorf
6623 Augsburg
6624 Eint Frankfurt
6625 Düsseldorf
6626 Nürnberg
6627 Schalke 04
6628 Dortmund
6629 Hannover 96
6630 Düsseldorf
6631 Nürnberg
6632 Dortmund
6633 Bayern Munich
6634 RB Leipzig
6635 RB Leipzig
6636 Hertha BSC
6637 Dortmund
6638 Nürnberg
6639 Eint Frankfurt
6640 Stuttgart
6641 Hertha BSC
6642 Leverkusen
6643 Leverkusen
6644 Wolfsburg
6645 Wolfsburg
6646 Freiburg
6647 Dortmund
6648 Bayern Munich
6649 Stuttgart
6650 Mainz 05
6651 Schalke 04
6652 Freiburg
6653 Hannover 96
6654 Augsburg
6655 Eint Frankfurt
6656 Nürnberg
6657 Stuttgart
6658 Düsseldorf
6659 Werder Bremen
6660 Eint Frankfurt
6661 M'Gladbach
6662 Mainz 05
6663 Hoffenheim
6664 Bayern Munich
6665 Düsseldorf
6666 Hoffenheim
6667 Wolfsburg
6668 Stuttgart
6669 Augsburg
6670 RB Leipzig
6671 Nürnberg
6672 Schalke 04
6673 Düsseldorf
6674 Dortmund
6675 Werder Bremen
6676 Hoffenheim
6677 Bayern Munich
6678 Augsburg
6679 Düsseldorf
6680 RB Leipzig
6681 Dortmund
6682 Stuttgart
6683 Augsburg
6684 Dortmund
6685 Eint Frankfurt
6686 Bayern Munich
6687 Freiburg
6688 Hertha BSC
6689 Eint Frankfurt
6690 Bayern Munich
6691 Leverkusen
6692 Freiburg
6693 Hannover 96
6694 Hannover 96
6695 Wolfsburg
6696 Augsburg
6697 Freiburg
6698 Stuttgart
6699 Augsburg
6700 Eint Frankfurt
6701 RB Leipzig
6702 Dortmund
6703 Werder Bremen
6704 Stuttgart
6705 Hannover 96
6706 Stuttgart
6707 Hertha BSC
6708 Hannover 96
6709 Schalke 04
6710 Hannover 96
6711 Freiburg
6712 Werder Bremen
6713 Freiburg
6714 Dortmund
6715 Dortmund
6716 Bayern Munich
6717 Wolfsburg
6718 Bayern Munich
6719 Schalke 04
6720 Mainz 05
6721 Augsburg
6722 Bayern Munich
6723 Nürnberg
6724 Schalke 04
6725 Werder Bremen
6726 Hertha BSC
6727 Dortmund
6728 Hertha BSC
6729 Nürnberg
6730 Werder Bremen
6731 Leverkusen
6732 Eint Frankfurt
6733 Schalke 04
6734 Hoffenheim
6735 M'Gladbach
6736 Hoffenheim
6737 Leverkusen
6738 Dortmund
6739 Nürnberg
6740 Augsburg
6741 Dortmund
6742 Schalke 04
6743 Eint Frankfurt
6744 Mainz 05
6745 Mainz 05
6746 Eint Frankfurt
6747 Hoffenheim
6748 Hoffenheim
6749 Freiburg
6750 Mainz 05
6751 Mainz 05
6752 Eint Frankfurt
6753 Augsburg
6754 Stuttgart
6755 RB Leipzig
6756 Freiburg
6757 Hertha BSC
6758 Wolfsburg
6759 Dortmund
6760 Hoffenheim
6761 Mainz 05
6762 Augsburg
6763 Dortmund
6764 Freiburg
6765 Wolfsburg
6766 RB Leipzig
6767 Augsburg
6768 Stuttgart
6769 Hertha BSC
6770 Schalke 04
6771 Hannover 96
6772 Leverkusen
6773 Schalke 04
6774 Nürnberg
6775 Stuttgart
6776 Hoffenheim
6777 Wolfsburg
6778 Eint Frankfurt
6779 Mainz 05
6780 Augsburg
6781 Augsburg
6782 Hannover 96
6783 Hoffenheim
6784 Mainz 05
6785 Düsseldorf
6786 Wolfsburg
6787 M'Gladbach
6788 M'Gladbach
6789 Schalke 04
6790 Bayern Munich
6791 Eint Frankfurt
6792 Düsseldorf
6793 RB Leipzig
6794 Wolfsburg
6795 Bayern Munich
6796 Leverkusen
6797 M'Gladbach
6798 Schalke 04
6799 RB Leipzig
6800 M'Gladbach
6801 M'Gladbach
6802 Hoffenheim
6803 Hertha BSC
6804 Eint Frankfurt
6805 Hannover 96
6806 Hertha BSC
6807 Düsseldorf
6808 Mainz 05
6809 Leverkusen
6810 Leverkusen
6811 Dortmund
6812 Düsseldorf
6813 Stuttgart
6814 Hertha BSC
6815 Leverkusen
6816 M'Gladbach
6817 Hoffenheim
6818 Schalke 04
6819 Freiburg
6820 Werder Bremen
6821 Mainz 05
6822 Freiburg
6823 Wolfsburg
6824 Freiburg
6825 Bayern Munich
6826 Stuttgart
6827 Leverkusen
6828 Düsseldorf
6829 Bayern Munich
6830 M'Gladbach
6831 Düsseldorf
6832 Nürnberg
6833 RB Leipzig
6834 Wolfsburg
6835 Stuttgart
6836 Eint Frankfurt
6837 Wolfsburg
6838 Hoffenheim
6839 Schalke 04
6840 Leverkusen
6841 M'Gladbach
6842 Werder Bremen
6843 Werder Bremen
6844 Leverkusen
6845 Nürnberg
6846 Hoffenheim
6847 Freiburg
6848 Schalke 04
6849 Hertha BSC
6850 Freiburg
6851 Nürnberg
6852 Stuttgart
6853 Leverkusen
6854 Schalke 04
6855 Werder Bremen
6856 Werder Bremen
6857 Stuttgart
6858 Wolfsburg
6859 Werder Bremen
6860 Eint Frankfurt
6861 Düsseldorf
6862 Hoffenheim
6863 Schalke 04
6864 M'Gladbach
6865 Leverkusen
6866 Nürnberg
6867 M'Gladbach
6868 RB Leipzig
6869 Wolfsburg
6870 RB Leipzig
6871 Hannover 96
6872 Werder Bremen
6873 Hertha BSC
6874 Hannover 96
6875 Nürnberg
6876 Mainz 05
6877 Düsseldorf
6878 RB Leipzig
6879 Wolfsburg
6880 Bayern Munich
6881 Hertha BSC
6882 Hoffenheim
6883 Mainz 05
6884 Bayern Munich
6885 Werder Bremen
6886 Hannover 96
6887 Düsseldorf
6888 RB Leipzig
6889 Leverkusen
6890 Eint Frankfurt
6891 Freiburg
6892 Hannover 96
6893 Hertha BSC
6894 Hertha BSC
6895 Werder Bremen
6896 Leverkusen
6897 RB Leipzig
6898 Werder Bremen
6899 Mainz 05
6900 M'Gladbach
6901 Mainz 05
6902 RB Leipzig
6903 Hoffenheim
6904 M'Gladbach
6905 Bayern Munich
6906 Hannover 96
6907 Hannover 96
6908 Augsburg
6909 Mainz 05
6910 Nürnberg
6911 Düsseldorf
6912 RB Leipzig
6913 Augsburg
6914 M'Gladbach
6915 Stuttgart
6916 Nürnberg
6917 Dortmund
6918 Freiburg
6919 M'Gladbach
6920 Union Berlin
6921 Eint Frankfurt
6922 Freiburg
6923 Hertha BSC
6924 Köln
6925 M'Gladbach
6926 Union Berlin
6927 RB Leipzig
6928 Hertha BSC
6929 Paderborn 07
6930 Freiburg
6931 Hoffenheim
6932 Köln
6933 Paderborn 07
6934 Werder Bremen
6935 Leverkusen
6936 Freiburg
6937 Schalke 04
6938 Bayern Munich
6939 Köln
6940 Wolfsburg
6941 RB Leipzig
6942 Eint Frankfurt
6943 Düsseldorf
6944 Köln
6945 Freiburg
6946 Dortmund
6947 Dortmund
6948 Dortmund
6949 Düsseldorf
6950 Eint Frankfurt
6951 RB Leipzig
6952 Wolfsburg
6953 Köln
6954 Schalke 04
6955 Düsseldorf
6956 Paderborn 07
6957 Bayern Munich
6958 Dortmund
6959 Paderborn 07
6960 Hoffenheim
6961 Dortmund
6962 Union Berlin
6963 Wolfsburg
6964 Düsseldorf
6965 RB Leipzig
6966 Paderborn 07
6967 M'Gladbach
6968 Köln
6969 M'Gladbach
6970 Eint Frankfurt
6971 Bayern Munich
6972 Eint Frankfurt
6973 Hoffenheim
6974 Hertha BSC
6975 Schalke 04
6976 Hertha BSC
6977 Düsseldorf
6978 Eint Frankfurt
6979 Augsburg
6980 M'Gladbach
6981 Hertha BSC
6982 Union Berlin
6983 Wolfsburg
6984 Dortmund
6985 Leverkusen
6986 Wolfsburg
6987 M'Gladbach
6988 Bayern Munich
6989 Bayern Munich
6990 Wolfsburg
6991 Wolfsburg
6992 Freiburg
6993 RB Leipzig
6994 Hertha BSC
6995 Hertha BSC
6996 Union Berlin

In [56]:
fact_match_statistics['Match'] = list_match
fact_match_statistics['Home_Team'] = list_home_team
fact_match_statistics['Home_Possession'] = match_dataset_model['Home_Possession'].to_list()
fact_match_statistics['Home_Fouls'] = match_dataset_model['Home_Fouls'].to_list()
fact_match_statistics['Home_Corners'] = match_dataset_model['Home_Corners'].to_list()
fact_match_statistics['Home_Crosses'] = match_dataset_model['Home_Crosses'].to_list()
fact_match_statistics['Home_Aerials_Won'] = match_dataset_model['Home_Aerials_Won'].to_list()
fact_match_statistics['Home_Clearances'] = match_dataset_model['Home_Clearances'].to_list()
fact_match_statistics['Home_Offsides'] = match_dataset_model['Home_Offsides'].to_list()
fact_match_statistics['Home_Goal_Kicks'] = match_dataset_model['Home_Goal_Kicks'].to_list()
fact_match_statistics['Home_Throw_Ins'] = match_dataset_model['Home_Throw_Ins'].to_list()
fact_match_statistics['Home_Long_Balls'] = match_dataset_model['Home_Long_Balls'].to_list()
fact_match_statistics['Home_Total_Players_Stats'] = match_dataset_model['Home_Total_Players_Stats'].to_list()
fact_match_statistics['Home_Minutes'] = match_dataset_model['Home_Minutes'].to_list()
fact_match_statistics['Home_Gls'] = match_dataset_model['Home_Gls'].to_list()
fact_match_statistics['Home_Ast'] = match_dataset_model['Home_Ast'].to_list()
fact_match_statistics['Home_PK'] = match_dataset_model['Home_PK'].to_list()
fact_match_statistics['Home_PK_Att'] = match_dataset_model['Home_PK_Att'].to_list()
fact_match_statistics['Home_Sh'] = match_dataset_model['Home_Sh'].to_list()
fact_match_statistics['Home_SoT'] = match_dataset_model['Home_SoT'].to_list()
fact_match_statistics['Home_CrdY'] = match_dataset_model['Home_CrdY'].to_list()
fact_match_statistics['Home_CrdR'] = match_dataset_model['Home_CrdR'].to_list()
fact_match_statistics['Home_Touches'] = match_dataset_model['Home_Touches'].to_list()
fact_match_statistics['Home_Tkl'] = match_dataset_model['Home_Tkl'].to_list()
fact_match_statistics['Home_Int'] = match_dataset_model['Home_Int'].to_list()
fact_match_statistics['Home_Blocks'] = match_dataset_model['Home_Blocks'].to_list()
fact_match_statistics['Home_Touches'] = match_dataset_model['Home_Touches'].to_list()
fact_match_statistics['Home_Tkl'] = match_dataset_model['Home_Tkl'].to_list()
fact_match_statistics['Home_Int'] = match_dataset_model['Home_Int'].to_list()
fact_match_statistics['Home_Blocks'] = match_dataset_model['Home_Blocks'].to_list()
fact_match_statistics['Home_xG'] = match_dataset_model['Home_xG'].to_list()
fact_match_statistics['Home_npxG'] = match_dataset_model['Home_npxG'].to_list()
fact_match_statistics['Home_xAG'] = match_dataset_model['Home_xAG'].to_list()
fact_match_statistics['Home_SCA'] = match_dataset_model['Home_SCA'].to_list()
fact_match_statistics['Home_GCA'] = match_dataset_model['Home_GCA'].to_list()
fact_match_statistics['Home_Cmp_Passes'] = match_dataset_model['Home_Cmp_Passes'].to_list()
fact_match_statistics['Home_Att_Passes'] = match_dataset_model['Home_Att_Passes'].to_list()
fact_match_statistics['Home_Cmp_percent_Passes'] = match_dataset_model['Home_Cmp_percent_Passes'].to_list()
fact_match_statistics['Home_PrgP_Passes'] = match_dataset_model['Home_PrgP_Passes'].to_list()
fact_match_statistics['Home_Carries_Carries'] = match_dataset_model['Home_Carries_Carries'].to_list()
fact_match_statistics['Home_PrgC_Carries'] = match_dataset_model['Home_PrgC_Carries'].to_list()
fact_match_statistics['Home_Att_Take_Ons'] = match_dataset_model['Home_Att_Take_Ons'].to_list()
fact_match_statistics['Home_Succ_Take_Ons'] = match_dataset_model['Home_Succ_Take_Ons'].to_list()

fact_match_statistics['Away_Team'] = list_away_team
fact_match_statistics['Away_Possession'] = match_dataset_model['Away_Possession'].to_list()
fact_match_statistics['Away_Fouls'] = match_dataset_model['Away_Fouls'].to_list()
fact_match_statistics['Away_Corners'] = match_dataset_model['Away_Corners'].to_list()
fact_match_statistics['Away_Crosses'] = match_dataset_model['Away_Crosses'].to_list()
fact_match_statistics['Away_Aerials_Won'] = match_dataset_model['Away_Aerials_Won'].to_list()
fact_match_statistics['Away_Clearances'] = match_dataset_model['Away_Clearances'].to_list()
fact_match_statistics['Away_Offsides'] = match_dataset_model['Away_Offsides'].to_list()
fact_match_statistics['Away_Goal_Kicks'] = match_dataset_model['Away_Goal_Kicks'].to_list()
fact_match_statistics['Away_Throw_Ins'] = match_dataset_model['Away_Throw_Ins'].to_list()
fact_match_statistics['Away_Long_Balls'] = match_dataset_model['Away_Long_Balls'].to_list()
fact_match_statistics['Away_Total_Players_Stats'] = match_dataset_model['Away_Total_Players_Stats'].to_list()
fact_match_statistics['Away_Minutes'] = match_dataset_model['Away_Minutes'].to_list()
fact_match_statistics['Away_Gls'] = match_dataset_model['Away_Gls'].to_list()
fact_match_statistics['Away_Ast'] = match_dataset_model['Away_Ast'].to_list()
fact_match_statistics['Away_PK'] = match_dataset_model['Away_PK'].to_list()
fact_match_statistics['Away_PK_Att'] = match_dataset_model['Away_PK_Att'].to_list()
fact_match_statistics['Away_Sh'] = match_dataset_model['Away_Sh'].to_list()
fact_match_statistics['Away_SoT'] = match_dataset_model['Away_SoT'].to_list()
fact_match_statistics['Away_CrdY'] = match_dataset_model['Away_CrdY'].to_list()
fact_match_statistics['Away_CrdR'] = match_dataset_model['Away_CrdR'].to_list()
fact_match_statistics['Away_Touches'] = match_dataset_model['Away_Touches'].to_list()
fact_match_statistics['Away_Tkl'] = match_dataset_model['Away_Tkl'].to_list()
fact_match_statistics['Away_Int'] = match_dataset_model['Away_Int'].to_list()
fact_match_statistics['Away_Blocks'] = match_dataset_model['Away_Blocks'].to_list()
fact_match_statistics['Away_Touches'] = match_dataset_model['Away_Touches'].to_list()
fact_match_statistics['Away_Tkl'] = match_dataset_model['Away_Tkl'].to_list()
fact_match_statistics['Away_Int'] = match_dataset_model['Away_Int'].to_list()
fact_match_statistics['Away_Blocks'] = match_dataset_model['Away_Blocks'].to_list()
fact_match_statistics['Away_xG'] = match_dataset_model['Away_xG'].to_list()
fact_match_statistics['Away_npxG'] = match_dataset_model['Away_npxG'].to_list()
fact_match_statistics['Away_xAG'] = match_dataset_model['Away_xAG'].to_list()
fact_match_statistics['Away_SCA'] = match_dataset_model['Away_SCA'].to_list()
fact_match_statistics['Away_GCA'] = match_dataset_model['Away_GCA'].to_list()
fact_match_statistics['Away_Cmp_Passes'] = match_dataset_model['Away_Cmp_Passes'].to_list()
fact_match_statistics['Away_Att_Passes'] = match_dataset_model['Away_Att_Passes'].to_list()
fact_match_statistics['Away_Cmp_percent_Passes'] = match_dataset_model['Away_Cmp_percent_Passes'].to_list()
fact_match_statistics['Away_PrgP_Passes'] = match_dataset_model['Away_PrgP_Passes'].to_list()
fact_match_statistics['Away_Carries_Carries'] = match_dataset_model['Away_Carries_Carries'].to_list()
fact_match_statistics['Away_PrgC_Carries'] = match_dataset_model['Away_PrgC_Carries'].to_list()
fact_match_statistics['Away_Att_Take_Ons'] = match_dataset_model['Away_Att_Take_Ons'].to_list()
fact_match_statistics['Away_Succ_Take_Ons'] = match_dataset_model['Away_Succ_Take_Ons'].to_list()

fact_match_statistics['Home_Attack'] = match_dataset_model['Home_Attack'].to_list()
fact_match_statistics['Home_Midfield'] = match_dataset_model['Home_Midfield'].to_list()
fact_match_statistics['Home_Defense'] = match_dataset_model['Home_Defense'].to_list()
fact_match_statistics['Away_Attack'] = match_dataset_model['Away_Attack'].to_list()
fact_match_statistics['Away_Midfield'] = match_dataset_model['Away_Midfield'].to_list()
fact_match_statistics['Away_Defense'] = match_dataset_model['Away_Defense'].to_list()

fact_match_statistics['Home_Score'] = match_dataset_model['Home_Score'].to_list()
fact_match_statistics['Away_Score'] = match_dataset_model['Away_Score'].to_list()

<h3>3. Fact Players Statistics</h3>

In [ ]:
fact_players_statistics = pd.DataFrame({'Match': [],
                                        'Team': [],
                                        'Player_Name': [], 'Player_Kitnum': [],
                                        'Nationality': [], 'Position': [],
                                        'Age': [], 'Minutes': [],
                                        'Gls': [], 'Ast': [], 'PK': [],
                                        'PK_Att': [], 'Sh': [], 'SoT': [],
                                        'CrdY': [], 'CrdR': [], 'Touches': [],
                                        'Tkl': [], 'Int': [], 'Blocks': [],
                                        'xG': [], 'npxG': [], 'xAG': [],
                                        'SCA': [], 'GCA': [], 'Cmp_Passes': [],
                                        'Att_Passes': [], 'Cmp_percent_Passes': [], 'PrgP_Passes': [],
                                        'Carries_Carries': [], 'PrgC_Carries': [], 'Att_Take_Ons': [],
                                        'Succ_Take_Ons': []})

list_match = []
list_team = []

for i in range(0,len(fbref_matchplayerstats)):
    print(i)

    temp_df = dim_match[dim_match['Match_Id'] == fbref_matchplayerstats['Match_Id'].iloc[i]]

    if (len(temp_df) > 0):
        list_match.append(temp_df['Match_Key'].iloc[0])
    else:
        list_match.append(np.nan)

    temp_df = dim_team[dim_team['Team_Name'] == fbref_matchplayerstats['Team'].iloc[i]]
    if (len(temp_df) > 0):
        list_team.append(temp_df['Team_Key'].iloc[0])
    else:
        list_team.append(np.nan)

#continue

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
364519
364520
364521
364522
364523
364524
364525
364526
364527
364528
364529
364530
364531
364532
364533
364534
364535
364536
364537
364538
364539
364540
364541
364542
364543
364544
364545
364546
364547
364548
364549
364550
364551
364552
364553
364554
364555
364556
364557
364558
364559
364560
364561
364562
364563
364564
364565
364566
364567
364568
364569
364570
364571
364572
364573
364574
364575
364576
364577
364578
364579
364580
364581
364582
364583
364584
364585
364586
364587
364588
364589
364590
364591
364592
364593
364594
364595
364596
364597
364598
364599
364600
364601
364602
364603
364604
364605
364606
364607
364608
364609
364610
364611
364612
364613
364614
364615
364616
364617
364618
364619
364620
364621
364622
364623
364624
364625
364626
364627
364628
364629
364630
364631
364632
364633
364634
364635
364636
364637
364638
364639
364640
364641
364642
364643
364644
364645
364646
364647
364648
364649
364650
364651
364652
364653
364654
364655
364656
364657
364658
364659
364660
364661
364662
364663
364664
364665
364666
364667
364668
364669
364670
364671
364672
364673
364674
364675
364676
364677
364678
364679
364680
364681
364682
364683
364684
364685
364686
364687
364688
364689
364690
364691
364692
364693
364694
364695
364696
364697
364698
364699
364700
364701
364702
364703
364704
364705
364706
364707
364708
364709
364710
364711
364712
364713
364714
364715
364716
364717
364718
364719
364720
364721
364722
364723
364724
364725
364726
364727
364728
364729
364730
364731
364732
364733
364734
364735
364736
364737
364738
364739
364740
364741
364742
364743
364744
364745
364746
364747
364748
364749
364750
364751
364752
364753
364754
364755
364756
364757
364758
364759
364760
364761
364762
364763
364764
364765
364766
364767
364768
364769
364770
364771
364772
364773
364774
364775
364776
364777
364778
364779
364780
364781
364782
364783
364784
364785
364786
364787
364788
364789
364790
364791
364792
364793
364794
364795
364796
364797
364798
364799
364800
364801
364802
364803
364804
364805
364806
364807
364808
364809
364810
364811
364812
364813
364814
364815
364816
364817
364818
364819
364820
364821
364822
364823
364824
364825
364826
364827
364828
364829
364830
364831
364832
364833
364834
364835
364836
364837
364838
364839
364840
364841
364842
364843
364844
364845
364846
364847
364848
364849
364850
364851
364852
364853
364854
364855
364856
364857
364858
364859
364860
364861
364862
364863
364864
364865
364866
364867
364868
364869
364870
364871
364872
364873
364874
364875
364876
364877
364878
364879
364880
364881
364882
364883
364884
364885
364886
364887
364888
364889
364890
364891
364892
364893
364894
364895
364896
364897
364898
364899
364900
364901
364902
364903
364904
364905
364906
364907
364908
364909
364910
364911
364912
364913
364914
364915
364916
364917
364918
364919
364920
364921
364922
364923
364924
364925
364926
364927
364928
364929
364930
364931
364932
364933
364934
364935
364936
364937
364938
364939
364940
364941
364942
364943
364944
364945
364946
364947
364948
364949
364950
364951
364952
364953
364954
364955
364956
364957
364958
364959
364960
364961
364962
364963
364964
364965
364966
364967
364968
364969
364970
364971
364972
364973
364974
364975
364976
364977
364978
364979
364980
364981
364982
364983
364984
364985
364986
364987
364988
364989
364990
364991
364992
364993
364994
364995
364996
364997
364998
364999
365000
365001
365002
365003
365004
365005
365006
365007
365008
365009
365010
365011
365012
365013
365014
365015
365016
365017
365018
365019
365020
365021
365022
365023
365024
365025
365026
365027
365028
365029
365030
365031
365032
365033
365034
365035
365036
365037
365038
365039
365040
365041
365042
365043
365044
365045
365046
365047
365048
365049
365050
365051
365052
365053
365054
365055
365056
365057
365058
365059
365060
365061
365062
365063
365064
365065
365066
365067
365068
365069
365070
365071
365072
365073
365074
365075
365076
365077
365078
365079
365080
365081
365082
365083
365084
365085
365086
365087
365088
365089
365090
365091
365092
365093
365094
365095
365096
365097
365098
365099
365100
365101
365102
365103
365104
365105
365106
365107
365108
365109
365110
365111
365112
365113
365114
365115
365116
365117
365118
365119
365120
365121
365122
365123
365124
365125
365126
365127
365128
365129
365130
365131
365132
365133
365134
365135
365136
365137
365138
365139
365140
365141
365142
365143
365144
365145
365146
365147
365148
365149
365150
365151
365152
365153
365154
365155
365156
365157
365158
365159
365160
365161
365162
365163
365164
365165
365166
365167
365168
365169
365170
365171
365172
365173
365174
365175
365176
365177
365178
365179
365180
365181
365182
365183
365184
365185
365186
365187
365188
365189
365190
365191
365192
365193
365194
365195
365196
365197
365198
365199
365200
365201
365202
365203
365204
365205
365206
365207
365208
365209
365210
365211
365212
365213
365214
365215
365216
365217
365218
365219
365220
365221
365222
365223
365224
365225
365226
365227
365228
365229
365230
365231
365232
365233
365234
365235
365236
365237
365238
365239
365240
365241
365242
365243
365244
365245
365246
365247
365248
365249
365250
365251
365252
365253
365254
365255
365256
365257
365258
365259
365260
365261
365262
365263
365264
365265
365266
365267
365268
365269
365270
365271
365272
365273
365274
365275
365276
365277
365278
365279
365280
365281
365282
365283
365284
365285
365286
365287
365288
365289
365290
365291
365292
365293
365294
365295
365296
365297
365298
365299
365300
365301
365302
365303
365304
365305
365306
365307
365308
365309
365310
365311
365312
365313
365314
365315
365316
365317
365318
365319
365320
365321
365322
365323
365324
365325
365326
365327
365328
365329
365330
365331
365332
365333
365334
365335
365336
365337
365338
365339
365340
365341
365342
365343
365344
365345
365346
365347
365348
365349
365350
365351
365352
365353
365354
365355
365356
365357
365358
365359
365360
365361
365362
365363
365364
365365
365366
365367
365368
365369
365370
365371
365372
365373
365374
365375
365376
365377
365378
365379
365380
365381
365382
365383
365384
365385
365386
365387
365388
365389
365390
365391
365392
365393
365394
365395
365396
365397
365398
365399
365400
365401
365402
365403
365404
365405
365406
365407
365408
365409
365410
365411
365412
365413
365414
365415
365416
365417
365418
365419
365420
365421
365422
365423
365424
365425
365426
365427
365428
365429
365430
365431
365432
365433
365434
365435
365436
365437
365438
365439
365440
365441
365442
365443
365444
365445
365446
365447
365448
365449
365450
365451
365452
365453
365454
365455
365456
365457
365458
365459
365460
365461
365462
365463
365464
365465
365466
365467
365468
365469
365470
365471
365472
365473
365474
365475
365476
365477
365478
365479
365480
365481
365482
365483
365484
365485
365486
365487
365488
365489
365490
365491
365492
365493
365494
365495
365496
365497
365498
365499
365500
365501
365502
365503
365504
365505
365506
365507
365508
365509
365510
365511
365512
365513
365514
365515
365516
365517
365518
365519
365520
365521
365522
365523
365524
365525
365526
365527
365528
365529
365530
365531
365532
365533
365534
365535
365536
365537
365538
365539
365540
365541
365542
365543
365544
365545
365546
365547
365548
365549
365550
365551
365552
365553
365554
365555
365556
365557
365558
365559
365560
365561
365562
365563
365564
365565
365566
365567
365568
365569
365570
365571
365572
365573
365574
365575
365576
365577
365578
365579
365580
365581
365582
365583
365584
365585
365586
365587
365588
365589
365590
365591
365592
365593
365594
365595
365596
365597
365598
365599
365600
365601
365602
365603
365604
365605
365606
365607
365608
365609
365610
365611
365612
365613
365614
365615
365616
365617
365618
365619
365620
365621
365622
365623
365624
365625
365626
365627
365628
365629
365630
365631
365632
365633
365634
365635
365636
365637
365638
365639
365640
365641
365642
365643
365644
365645
365646
365647
365648
365649
365650
365651
365652
365653
365654
365655
365656
365657
365658
365659
365660
365661
365662
365663
365664
365665
365666
365667
365668
365669
365670
365671
365672
365673
365674
365675
365676
365677
365678
365679
365680
365681
365682
365683
365684
365685
365686
365687
365688
365689
365690
365691
365692
365693
365694
365695
365696
365697
365698
365699
365700
365701
365702
365703
365704
365705
365706
365707
365708
365709
365710
365711
365712
365713
365714
365715
365716
365717
365718
365719
365720
365721
365722
365723
365724
365725
365726
365727
365728
365729
365730
365731
365732
365733
365734
365735
365736
365737
365738
365739
365740
365741
365742
365743
365744
365745
365746
365747
365748
365749
365750
365751
365752
365753
365754
365755
365756
365757
365758
365759
365760
365761
365762
365763
365764
365765
365766
365767
365768
365769
365770
365771
365772
365773
365774
365775
365776
365777
365778
365779
365780
365781
365782
365783
365784
365785
365786
365787
365788
365789
365790
365791
365792
365793
365794
365795
365796
365797
365798
365799
365800
365801
365802
365803
365804
365805
365806
365807
365808
365809
365810
365811
365812
365813
365814
365815
365816
365817
365818
365819
365820
365821
365822
365823
365824
365825
365826
365827
365828
365829
365830
365831
365832
365833
365834
365835
365836
365837
365838
365839
365840
365841
365842
365843
365844
365845
365846
365847
365848
365849
365850
365851
365852
365853
365854
365855
365856
365857
365858
365859
365860
365861
365862
365863
365864
365865
365866
365867
365868
365869
365870
365871
365872
365873
365874
365875
365876
365877
365878
365879
365880
365881
365882
365883
365884
365885
365886
365887
365888
365889
365890
365891
365892
365893
365894
365895
365896
365897
365898
365899
365900
365901
365902
365903
365904
365905
365906
365907
365908
365909
365910
365911
365912
365913
365914
365915
365916
365917
365918
365919
365920
365921
365922
365923
365924
365925
365926
365927
365928
365929
365930
365931
365932
365933
365934
365935
365936
365937
365938
365939
365940
365941
365942
365943
365944
365945
365946
365947
365948
365949
365950
365951
365952
365953
365954
365955
365956
365957
365958
365959
365960
365961
365962
365963
365964
365965
365966
365967
365968
365969
365970
365971
365972
365973
365974
365975
365976
365977
365978
365979
365980
365981
365982
365983
365984
365985
365986
365987
365988
365989
365990
365991
365992
365993
365994
365995
365996
365997
365998
365999
366000
366001
366002
366003
366004
366005
366006
366007
366008
366009
366010
366011
366012
366013
366014
366015
366016
366017
366018
366019
366020
366021
366022
366023
366024
366025
366026
366027
366028
366029
366030
366031
366032
366033
366034
366035
366036
366037
366038
366039
366040
366041
366042
366043
366044
366045
366046
366047
366048
366049
366050
366051
366052
366053
366054
366055
366056
366057
366058
366059
366060
366061
366062
366063
366064
366065
366066
366067
366068
366069
366070
366071
366072
366073
366074
366075
366076
366077
366078
366079
366080
366081
366082
366083
366084
366085
366086
366087
366088
366089
366090
366091
366092
366093
366094
366095
366096
366097
366098
366099
366100
366101
366102
366103
366104
366105
366106
366107
366108
366109
366110
366111
366112
366113
366114
366115
366116
366117
366118
366119
366120
366121
366122
366123
366124
366125
366126
366127
366128
366129
366130
366131
366132
366133
366134
366135
366136
366137
366138
366139
366140
366141
366142
366143
366144
366145
366146
366147
366148
366149
366150
366151
366152
366153
366154
366155
366156
366157
366158
366159
366160
366161
366162
366163
366164
366165
366166
366167
366168
366169
366170
366171
366172
366173
366174
366175
366176
366177
366178
366179
366180
366181
366182
366183
366184
366185
366186
366187
366188
366189
366190
366191
366192
366193
366194
366195
366196
366197
366198
366199
366200
366201
366202
366203
366204
366205
366206
366207
366208
366209
366210
366211
366212
366213
366214
366215
366216
366217
366218
366219
366220
366221
366222
366223
366224
366225
366226
366227
366228
366229
366230
366231
366232
366233
366234
366235
366236
366237
366238
366239
366240
366241
366242
366243
366244
366245
366246
366247
366248
366249
366250
366251
366252
366253
366254
366255
366256
366257
366258
366259
366260
366261
366262
366263
366264
366265
366266
366267
366268
366269
366270
366271
366272
366273
366274
366275
366276
366277
366278
366279
366280
366281
366282
366283
366284
366285
366286
366287
366288
366289
366290
366291
366292
366293
366294
366295
366296
366297
366298
366299
366300
366301
366302
366303
366304
366305
366306
366307
366308
366309
366310
366311
366312
366313
366314
366315
366316
366317
366318
366319
366320
366321
366322
366323
366324
366325
366326
366327
366328
366329
366330
366331
366332
366333
366334
366335
366336
366337
366338
366339
366340
366341
366342
366343
366344
366345
366346
366347
366348
366349
366350
366351
366352
366353
366354
366355
366356
366357
366358
366359
366360
366361
366362
366363
366364
366365
366366
366367
366368
366369
366370
366371
366372
366373
366374
366375
366376
366377
366378
366379
366380
366381
366382
366383
366384
366385
366386
366387
366388
366389
366390
366391
366392
366393
366394
366395
366396
366397
366398
366399
366400
366401
366402
366403
366404
366405
366406
366407
366408
366409
366410
366411
366412
366413
366414
366415
366416
366417
366418
366419
366420
366421
366422
366423
366424
366425
366426
366427
366428
366429
366430
366431
366432
366433
366434
366435
366436
366437
366438
366439
366440
366441
366442
366443
366444
366445
366446
366447
366448
366449
366450
366451
366452
366453
366454
366455
366456
366457
366458
366459
366460
366461
366462
366463
366464
366465
366466
366467
366468
366469
366470
366471
366472
366473
366474
366475
366476
366477
366478
366479
366480
366481
366482
366483
366484
366485
366486
366487
366488
366489
366490
366491
366492
366493
366494
366495
366496
366497
366498
366499
366500
366501
366502
366503
366504
366505
366506
366507
366508
366509
366510
366511
366512
366513
366514
366515
366516
366517
366518
366519
366520
366521
366522
366523
366524
366525
366526
366527
366528
366529
366530
366531
366532
366533
366534
366535
366536
366537
366538
366539
366540
366541
366542
366543
366544
366545
366546
366547
366548
366549
366550
366551
366552
366553
366554
366555
366556
366557
366558
366559
366560
366561
366562
366563
366564
366565
366566
366567
366568
366569
366570
366571
366572
366573
366574
366575
366576
366577
366578
366579
366580
366581
366582
366583
366584
366585
366586
366587
366588
366589
366590
366591
366592
366593
366594
366595
366596
366597
366598
366599
366600
366601
366602
366603
366604
366605
366606
366607
366608
366609
366610
366611
366612
366613
366614
366615
366616
366617
366618
366619
366620
366621
366622
366623
366624
366625
366626
366627
366628
366629
366630
366631
366632
366633
366634
366635
366636
366637
366638
366639
366640
366641
366642
366643
366644
366645
366646
366647
366648
366649
366650
366651
366652
366653
366654
366655
366656
366657
366658
366659
366660
366661
366662
366663
366664
366665
366666
366667
366668
366669
366670
366671
366672
366673
366674
366675
366676
366677
366678
366679
366680
366681
366682
366683
366684
366685
366686
366687
366688
366689
366690
366691
366692
366693
366694
366695
366696
366697
366698
366699
366700
366701
366702
366703
366704
366705
366706
366707
366708
366709
366710
366711
366712
366713
366714
366715
366716
366717
366718
366719
366720
366721
366722
366723
366724
366725
366726
366727
366728
366729
366730
366731
366732
366733
366734
366735
366736
366737
366738
366739
366740
366741
366742
366743
366744
366745
366746
366747
366748
366749
366750
366751
366752
366753
366754
366755
366756
366757
366758
366759
366760
366761
366762
366763
366764
366765
366766
366767
366768
366769
366770
366771
366772
366773
366774
366775
366776
366777
366778
366779
366780
366781
366782
366783
366784
366785
366786
366787
366788
366789
366790
366791
366792
366793
366794
366795
366796
366797
366798
366799
366800
366801
366802
366803
366804
366805
366806
366807
366808
366809
366810
366811
366812
366813
366814
366815
366816
366817
366818
366819
366820
366821
366822
366823
366824
366825
366826
366827
366828
366829
366830
366831
366832
366833
366834
366835
366836
366837
366838
366839
366840
366841
366842
366843
366844
366845
366846
366847
366848
366849
366850
366851
366852
366853
366854
366855
366856
366857
366858
366859
366860
366861
366862
366863
366864
366865
366866
366867
366868
366869
366870
366871
366872
366873
366874
366875
366876
366877
366878
366879
366880
366881
366882
366883
366884
366885
366886
366887
366888
366889
366890
366891
366892
366893
366894
366895
366896
366897
366898
366899
366900
366901
366902
366903
366904
366905
366906
366907
366908
366909
366910
366911
366912
366913
366914
366915
366916
366917
366918
366919
366920
366921
366922
366923
366924
366925
366926
366927
366928
366929
366930
366931
366932
366933
366934
366935
366936
366937
366938
366939
366940
366941
366942
366943
366944
366945
366946
366947
366948
366949
366950
366951
366952
366953
366954
366955
366956
366957
366958
366959
366960
366961
366962
366963
366964
366965
366966
366967
366968
366969
366970
366971
366972
366973
366974
366975
366976
366977
366978
366979
366980
366981
366982
366983
366984
366985
366986
366987
366988
366989
366990
366991
366992
366993
366994
366995
366996
366997
366998
366999
367000
367001
367002
367003
367004
367005
367006
367007
367008
367009
367010
367011
367012
367013
367014
367015
367016
367017
367018
367019
367020
367021
367022
367023
367024
367025
367026
367027
367028
367029
367030
367031
367032
367033
367034
367035
367036
367037
367038
367039
367040
367041
367042
367043
367044
367045
367046
367047
367048
367049
367050
367051
367052
367053
367054
367055
367056
367057
367058
367059
367060
367061
367062
367063
367064
367065
367066
367067
367068
367069
367070
367071
367072
367073
367074
367075
367076
367077
367078
367079
367080
367081
367082
367083
367084
367085
367086
367087
367088
367089
367090
367091
367092
367093
367094
367095
367096
367097
367098
367099
367100
367101
367102
367103
367104
367105
367106
367107
367108
367109
367110
367111
367112
367113
367114
367115
367116
367117
367118
367119
367120
367121
367122
367123
367124
367125
367126
367127
367128
367129
367130
367131
367132
367133
367134
367135
367136
367137
367138
367139
367140
367141
367142
367143
367144
367145
367146
367147
367148
367149
367150
367151
367152
367153
367154
367155
367156
367157
367158
367159
367160
367161
367162
367163
367164
367165
367166
367167
367168
367169
367170
367171
367172
367173
367174
367175
367176
367177
367178
367179
367180
367181
367182
367183
367184
367185
367186
367187
367188
367189
367190
367191
367192
367193
367194
367195
367196
367197
367198
367199
367200
367201
367202
367203
367204
367205
367206
367207
367208
367209
367210
367211
367212
367213
367214
367215
367216
367217
367218
367219
367220
367221
367222
367223
367224
367225
367226
367227
367228
367229
367230
367231
367232
367233
367234
367235
367236
367237
367238
367239
367240
367241
367242
367243
367244
367245
367246
367247
367248
367249
367250
367251
367252
367253
367254
367255
367256
367257
367258
367259
367260
367261
367262
367263
367264
367265
367266
367267
367268
367269
367270
367271
367272
367273
367274
367275
367276
367277
367278
367279
367280
367281
367282
367283
367284
367285
367286
367287
367288
367289
367290
367291
367292
367293
367294
367295
367296
367297
367298
367299
367300
367301
367302
367303
367304
367305
367306
367307
367308
367309
367310
367311
367312
367313
367314
367315
367316
367317
367318
367319
367320
367321
367322
367323
367324
367325
367326
367327
367328
367329
367330
367331
367332
367333
367334
367335
367336
367337
367338
367339
367340
367341
367342
367343
367344
367345
367346
367347
367348
367349
367350
367351
367352
367353
367354
367355
367356
367357
367358
367359
367360
367361
367362
367363
367364
367365
367366
367367

In [ ]:
fact_players_statistics['Match'] = list_match
fact_players_statistics['Team'] = list_team

fact_players_statistics['Player_Name'] = fbref_matchplayerstats['Player_Name'].to_list()
fact_players_statistics['Player_Kitnum'] = fbref_matchplayerstats['Player_Kitnum'].to_list()
fact_players_statistics['Nationality'] = fbref_matchplayerstats['Nationality'].to_list()
fact_players_statistics['Position'] = fbref_matchplayerstats['Position'].to_list()

fact_players_statistics['Age'] = fbref_matchplayerstats['Age'].to_list()
fact_players_statistics['Minutes'] = fbref_matchplayerstats['Minutes'].to_list()
fact_players_statistics['Gls'] = fbref_matchplayerstats['Gls'].to_list()
fact_players_statistics['Ast'] = fbref_matchplayerstats['Ast'].to_list()
fact_players_statistics['PK'] = fbref_matchplayerstats['PK'].to_list()
fact_players_statistics['PK_Att'] = fbref_matchplayerstats['PK_Att'].to_list()
fact_players_statistics['Sh'] = fbref_matchplayerstats['Sh'].to_list()
fact_players_statistics['SoT'] = fbref_matchplayerstats['SoT'].to_list()
fact_players_statistics['CrdY'] = fbref_matchplayerstats['CrdY'].to_list()
fact_players_statistics['CrdR'] = fbref_matchplayerstats['CrdR'].to_list()
fact_players_statistics['Touches'] = fbref_matchplayerstats['Touches'].to_list()
fact_players_statistics['Tkl'] = fbref_matchplayerstats['Tkl'].to_list()
fact_players_statistics['Int'] = fbref_matchplayerstats['Int'].to_list()
fact_players_statistics['Blocks'] = fbref_matchplayerstats['Blocks'].to_list()
fact_players_statistics['xG'] = fbref_matchplayerstats['xG'].to_list()
fact_players_statistics['npxG'] = fbref_matchplayerstats['npxG'].to_list()
fact_players_statistics['xAG'] = fbref_matchplayerstats['xAG'].to_list()
fact_players_statistics['SCA'] = fbref_matchplayerstats['SCA'].to_list()
fact_players_statistics['GCA'] = fbref_matchplayerstats['GCA'].to_list()
fact_players_statistics['Passes_Cmp'] = fbref_matchplayerstats['Passes_Cmp'].to_list()
fact_players_statistics['Passes_Att'] = fbref_matchplayerstats['Passes_Att'].to_list()
fact_players_statistics['Passes_Cmp_Percentage'] = fbref_matchplayerstats['Passes_Cmp_Percentage'].to_list()
fact_players_statistics['Passes_PrgP'] = fbref_matchplayerstats['Passes_PrgP'].to_list()
fact_players_statistics['Carries'] = fbref_matchplayerstats['Carries'].to_list()
fact_players_statistics['Carries_PrgC'] = fbref_matchplayerstats['Carries_PrgC'].to_list()
fact_players_statistics['Take_Ons_Att'] = fbref_matchplayerstats['Take_Ons_Att'].to_list()
fact_players_statistics['Take_Ons_Succ'] = fbref_matchplayerstats['Take_Ons_Succ'].to_list()

In [ ]:
#dim_match_squad.to_csv('gs://football-data-etl/football-data-staging/dim_match_squad.csv', index=False)'

In [ ]:
dim_league.to_csv('gs://football_data_etl/football_data_staging/dim_league.csv', index=False)
dim_team.to_csv('gs://football_data_etl/football-data-staging/dim_team.csv', index=False)
dim_date.to_csv('gs://football_data_etl/football-data-staging/dim_date.csv', index=False)
dim_match.to_csv('gs://football_data_etl/football-data-staging/dim_match.csv', index=False)
dim_player.to_csv('gs://football_data_etl/football-data-staging/dim_player.csv', index=False)
dim_player_version.to_csv('gs://football_data_etl/football-data-staging/dim_player_version.csv', index=False)
dim_match_squad.to_csv('gs://football_data_etl/football-data-staging/dim_match_squad.csv', index=False)
dim_match_goals.to_csv('gs://football_data_etl/football-data-staging/dim_match_goals.csv', index=False)

fact_player_attributes.to_csv('gs://football_data_etl/football-data-staging/fact_player_attributes.csv', index=False)
fact_match_statistics.to_csv('gs://football_data_etl/football-data-staging/fact_match_statistics.csv', index=False)
fact_players_statistics.to_csv('gs://football_data_etl/football-data-staging/fact_players_statistics.csv', index=False)