<h2>Xây dựng mô hình dự đoán kết quả các trận đấu</h2>

Phần này sẽ kết hợp các kỹ thuật và phương pháp trong Machine Learning để xây dựng một mô hình dự đoán kết quả của các trận đấu trong tương lai, sử dụng Spark Machine Learning

<h2>I. Các thư viện và model được sử dụng</h2>

In [66]:
!pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.10/dist-packages (3.5.1)
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)

In [67]:
import pandas as pd
import matplotlib.pyplot as plt

#import findspark
#import pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import monotonically_increasing_id, lit, when

from pyspark.ml.classification import LogisticRegression, DecisionTreeClassifier, NaiveBayes, RandomForestClassifier
from pyspark.ml.feature import OneHotEncoder,StringIndexer,VectorAssembler
#from pyspark.ml.regression import LinearRegression, DecisionTreeRegressor
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

from pyspark.ml.stat import ChiSquareTest
from pyspark.sql.types import *

from google.cloud import bigquery
from google.cloud import storage
#from google.colab import auth

import os

Sử dụng Authentication nếu chạy ở local.

In [68]:
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "./keys/key.json"

<h2>II. Dataset Model</h2>

Chọn tên project

In [69]:
project_id = 'second-chariot-420108'
bigQuery_client = bigquery.Client(project=project_id)
storage_client = storage.Client()

In [70]:
query_factMatchStatistics = """
SELECT * FROM `second-chariot-420108.Football_DataWarehouse_1.Fact_Match_Statistics`
"""
query_dimMatch = """
SELECT * FROM `second-chariot-420108.Football_DataWarehouse_1.Dim_Match`
"""

query_dimTeam = """
SELECT * FROM `second-chariot-420108.Football_DataWarehouse_1.Dim_Team`
"""

In [71]:
match_dataset_model = pd.read_gbq(query_factMatchStatistics, project_id=project_id, dialect='standard')
dim_match = pd.read_gbq(query_dimMatch, project_id=project_id, dialect='standard')
dim_team = pd.read_gbq(query_dimTeam, project_id=project_id, dialect='standard')

In [72]:
match_dataset_model = match_dataset_model.rename(columns={'Match': 'Match_Key'})

In [73]:
match_dataset_model = match_dataset_model.drop(['Home_Total_Players_Stats', 'Home_Minutes',
                                                'Away_Total_Players_Stats', 'Away_Minutes'], axis=1)

In [74]:
match_dataset_model
match_dataset_model.to_csv('./match_dataset_model.csv', index=False)

In [75]:
match_dataset_model_desc = pd.merge(match_dataset_model, dim_match[['Match_Key','Match_Date']], on='Match_Key', how='inner')

In [76]:
match_dataset_model_desc = match_dataset_model_desc.sort_values(by='Match_Date', ascending=False).reset_index(drop=True)
match_dataset_model_desc

,Match_Key,Home_Team,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,Home_Aerials_Won,Home_Clearances,Home_Offsides,Home_Goal_Kicks,...,Away_Succ_Take_Ons,Home_Attack,Home_Midfield,Home_Defense,Away_Attack,Away_Midfield,Away_Defense,Home_Score,Away_Score,Match_Date
0,12646,136,33,18,4,17,5,15,3,9,...,9,72.000000,71.533333,70.083333,77.100000,74.900000,77.266667,2,1,20240526
1,7846,64,39,11,6,24,4,16,1,7,...,8,77.153846,77.812500,74.363636,78.142857,76.800000,77.785714,1,2,20240526
2,7845,62,54,18,2,14,5,14,2,12,...,13,76.200000,74.750000,73.846154,69.600000,73.000000,71.636364,2,2,20240526
3,12643,118,40,18,2,11,11,22,1,7,...,8,78.250000,76.411765,72.692308,73.181818,73.866667,73.285714,3,0,20240526
4,12648,117,35,17,9,21,6,3,2,5,...,6,71.000000,69.650000,71.500000,81.600000,79.350000,80.615385,2,2,20240526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,2592,35,38,9,2,23,21,13,2,5,...,17,75.500000,68.727273,72.625000,84.857143,84.000000,81.625000,0,3,20180811
10679,387,9,57,20,5,16,21,16,1,6,...,8,71.545455,72.000000,73.000000,0.000000,0.000000,0.000000,3,4,20180811
10680,2590,33,63,11,7,11,32,40,0,7,...,9,77.500000,75.000000,74.700000,0.000000,0.000000,0.000000,2,0,20180811
10681,381,10,60,7,5,20,19,14,1,7,...,11,78.285714,77.800000,75.333333,73.000000,71.833333,72.571429,4,0,20180810
10682,2587,30,47,11,2,12,9,36,4,5,...,9,85.600000,80.700000,79.454545,77.333333,78.083333,75.500000,2,1,20180810

In [77]:
match_dataset_model_desc.dtypes

Match_Key            Int64
Home_Team            Int64
Home_Possession      Int64
Home_Fouls           Int64
Home_Corners         Int64
                    ...
Away_Midfield      float64
Away_Defense       float64
Home_Score           Int64
Away_Score           Int64
Match_Date           Int64
Length: 82, dtype: object

In [78]:
df_without_nan_all = match_dataset_model_desc
df_without_nan_all = df_without_nan_all.dropna()
df_without_nan_all

,Match_Key,Home_Team,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,Home_Aerials_Won,Home_Clearances,Home_Offsides,Home_Goal_Kicks,...,Away_Succ_Take_Ons,Home_Attack,Home_Midfield,Home_Defense,Away_Attack,Away_Midfield,Away_Defense,Home_Score,Away_Score,Match_Date
0,12646,136,33,18,4,17,5,15,3,9,...,9,72.000000,71.533333,70.083333,77.100000,74.900000,77.266667,2,1,20240526
1,7846,64,39,11,6,24,4,16,1,7,...,8,77.153846,77.812500,74.363636,78.142857,76.800000,77.785714,1,2,20240526
2,7845,62,54,18,2,14,5,14,2,12,...,13,76.200000,74.750000,73.846154,69.600000,73.000000,71.636364,2,2,20240526
3,12643,118,40,18,2,11,11,22,1,7,...,8,78.250000,76.411765,72.692308,73.181818,73.866667,73.285714,3,0,20240526
4,12648,117,35,17,9,21,6,3,2,5,...,6,71.000000,69.650000,71.500000,81.600000,79.350000,80.615385,2,2,20240526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,2592,35,38,9,2,23,21,13,2,5,...,17,75.500000,68.727273,72.625000,84.857143,84.000000,81.625000,0,3,20180811
10679,387,9,57,20,5,16,21,16,1,6,...,8,71.545455,72.000000,73.000000,0.000000,0.000000,0.000000,3,4,20180811
10680,2590,33,63,11,7,11,32,40,0,7,...,9,77.500000,75.000000,74.700000,0.000000,0.000000,0.000000,2,0,20180811
10681,381,10,60,7,5,20,19,14,1,7,...,11,78.285714,77.800000,75.333333,73.000000,71.833333,72.571429,4,0,20180810
10682,2587,30,47,11,2,12,9,36,4,5,...,9,85.600000,80.700000,79.454545,77.333333,78.083333,75.500000,2,1,20180810

In [79]:
match_dataset_model_desc[~match_dataset_model_desc['Match_Key'].isin(df_without_nan_all['Match_Key'])]['Match_Key'].tolist()

[]

In [80]:
df_without_nan = match_dataset_model_desc[['Home_Score', 'Away_Score']]
df_without_nan = df_without_nan.dropna()
df_without_nan

       Home_Score  Away_Score
0               2           1
1               1           2
2               2           2
3               3           0
4               2           2
...           ...         ...
10678           0           3
10679           3           4
10680           2           0
10681           4           0
10682           2           1

[10683 rows x 2 columns]

In [81]:
len(match_dataset_model_desc) - len(df_without_nan)

0

Với mỗi cột, nếu kiểu dữ liệu là Int64 thì ép kiểu thành Float

Home_Team và Away_Team ép kiểu thành str.

In [82]:

for col in match_dataset_model_desc.columns:
    if col != 'Match_Key' and col != 'Home_Team' and col != 'Away_Team' and match_dataset_model_desc[col].dtype == 'Int64':
        match_dataset_model_desc[col] = match_dataset_model_desc[col].astype(float)

match_dataset_model_desc['Home_Team'] = match_dataset_model_desc['Home_Team'].astype(int)
match_dataset_model_desc['Home_Team'] = match_dataset_model_desc['Home_Team'].astype(str)

match_dataset_model_desc['Away_Team'] = match_dataset_model_desc['Away_Team'].astype(int)
match_dataset_model_desc['Away_Team'] = match_dataset_model_desc['Away_Team'].astype(str)

In [83]:
match_dataset_model_desc.dtypes

Match_Key            Int64
Home_Team           object
Home_Possession    float64
Home_Fouls         float64
Home_Corners       float64
                    ...
Away_Midfield      float64
Away_Defense       float64
Home_Score         float64
Away_Score         float64
Match_Date         float64
Length: 82, dtype: object

Danh sách các đội:

In [84]:
list_all_teams = match_dataset_model_desc['Home_Team'].unique()
list_all_teams

array(['136', '64', '62', '118', '117', '134', '138', '74', '72', '124',
       '116', '85', '88', '131', '80', '77', '79', '130', '63', '126',
       '121', '143', '119', '21', '144', '8', '20', '3', '57', '65',
       '128', '76', '83', '29', '86', '39', '125', '25', '5', '55', '48',
       '71', '120', '49', '40', '66', '61', '42', '78', '24', '1', '38',
       '43', '84', '51', '115', '135', '70', '109', '140', '92', '101',
       '105', '102', '93', '100', '99', '129', '14', '30', '44', '52',
       '6', '114', '89', '19', '10', '112', '26', '12', '11', '2', '104',
       '97', '36', '33', '56', '31', '47', '32', '96', '46', '106', '91',
       '23', '103', '87', '75', '81', '145', '7', '28', '27', '41', '54',
       '37', '9', '141', '122', '95', '90', '50', '142', '68', '34', '4',
       '111', '15', '113', '123', '73', '82', '53', '137', '22', '132',
       '16', '133', '139', '60', '107', '110', '13', '18', '127', '17',
       '98', '35', '45', '108'], dtype=object)

Thay đổi các statistic

In [85]:
# For each team, get all the matches that the team played
# Then calculate the average of the last 2 matches for each feature
# Then update the match_dataset_model_desc with the new values
for team in list_all_teams:
    print(team)

    this_team = match_dataset_model_desc[(match_dataset_model_desc['Home_Team'] == team) |
                (match_dataset_model_desc['Away_Team'] == team)]
    for i in range(0, len(this_team)-2):

        if(this_team.iloc[i,this_team.columns.get_loc('Home_Team')] == team):

            for j in range(2, 37):

                list_2_elements = []

                for k in range(i+1, i+3):
                    if(this_team.iloc[k,this_team.columns.get_loc('Home_Team')] == team):

                        list_2_elements.append(this_team.iloc[k, j])

                    if(this_team.iloc[k,this_team.columns.get_loc('Away_Team')] == team):

                        list_2_elements.append(this_team.iloc[k, j+36])

                match_key = this_team.iloc[i,this_team.columns.get_loc('Match_Key')]


                match_dataset_model_desc.loc[match_dataset_model_desc['Match_Key'] == match_key,
                                             match_dataset_model_desc.columns[j]] = sum(list_2_elements) / 2

        if(this_team.iloc[i,this_team.columns.get_loc('Away_Team')] == team):

            for j in range(38, 73):

                list_2_elements = []

                for k in range(i+1, i+3):
                    if(this_team.iloc[k,this_team.columns.get_loc('Home_Team')] == team):

                        list_2_elements.append(this_team.iloc[k, j-36])

                    if(this_team.iloc[k,this_team.columns.get_loc('Away_Team')] == team):

                        list_2_elements.append(this_team.iloc[k, j])

                match_key = this_team.iloc[i,this_team.columns.get_loc('Match_Key')]

                match_dataset_model_desc.loc[match_dataset_model_desc['Match_Key'] == match_key,
                                             match_dataset_model_desc.columns[j]] = sum(list_2_elements) / 2

136
64
62
118
117
134
138
74
72
124
116
85
88
131
80
77
79
130
63
126
121
143
119
21
144
8
20
3
57
65
128
76
83
29
86
39
125
25
5
55
48
71
120
49
40
66
61
42
78
24
1
38
43
84
51
115
135
70
109
140
92
101
105
102
93
100
99
129
14
30
44
52
6
114
89
19
10
112
26
12
11
2
104
97
36
33
56
31
47
32
96
46
106
91
23
103
87
75
81
145
7
28
27
41
54
37
9
141
122
95
90
50
142
68
34
4
111
15
113
123
73
82
53
137
22
132
16
133
139
60
107
110
13
18
127
17
98
35
45
108

In [86]:
match_dataset_model_desc

,Match_Key,Home_Team,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,Home_Aerials_Won,Home_Clearances,Home_Offsides,Home_Goal_Kicks,...,Away_Succ_Take_Ons,Home_Attack,Home_Midfield,Home_Defense,Away_Attack,Away_Midfield,Away_Defense,Home_Score,Away_Score,Match_Date
0,12646,136,47.0,16.5,6.0,20.0,19.0,20.0,3.0,8.0,...,6.5,72.000000,71.533333,70.083333,77.100000,74.900000,77.266667,2.0,1.0,20240526.0
1,7846,64,51.5,9.0,2.0,20.0,12.0,23.0,0.0,10.0,...,11.5,77.153846,77.812500,74.363636,78.142857,76.800000,77.785714,1.0,2.0,20240526.0
2,7845,62,52.0,13.5,2.0,8.5,14.5,20.0,2.5,8.5,...,4.0,76.200000,74.750000,73.846154,69.600000,73.000000,71.636364,2.0,2.0,20240526.0
3,12643,118,57.0,15.5,5.5,15.5,14.0,13.0,1.0,6.0,...,5.5,78.250000,76.411765,72.692308,73.181818,73.866667,73.285714,3.0,0.0,20240526.0
4,12648,117,45.0,19.0,6.5,24.0,24.5,13.0,1.5,4.5,...,4.0,71.000000,69.650000,71.500000,81.600000,79.350000,80.615385,2.0,2.0,20240526.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,2592,35,38.0,9.0,2.0,23.0,21.0,13.0,2.0,5.0,...,17.0,75.500000,68.727273,72.625000,84.857143,84.000000,81.625000,0.0,3.0,20180811.0
10679,387,9,57.0,20.0,5.0,16.0,21.0,16.0,1.0,6.0,...,8.0,71.545455,72.000000,73.000000,0.000000,0.000000,0.000000,3.0,4.0,20180811.0
10680,2590,33,63.0,11.0,7.0,11.0,32.0,40.0,0.0,7.0,...,9.0,77.500000,75.000000,74.700000,0.000000,0.000000,0.000000,2.0,0.0,20180811.0
10681,381,10,60.0,7.0,5.0,20.0,19.0,14.0,1.0,7.0,...,11.0,78.285714,77.800000,75.333333,73.000000,71.833333,72.571429,4.0,0.0,20180810.0
10682,2587,30,47.0,11.0,2.0,12.0,9.0,36.0,4.0,5.0,...,9.0,85.600000,80.700000,79.454545,77.333333,78.083333,75.500000,2.0,1.0,20180810.0

<h2>III. Xây dựng mô hình dự đoán kết quả trận đấu</h2>

Phần này sẽ kết hợp các kỹ thuật và phương pháp trong Machine Learning để xây dựng một mô hình dự đoán kết quả của các trận đấu trong tương lai, sử dụng Spark Machine Learning

<h3>1. Phân tích dữ liệu</h3>

In [87]:
dataset_model = match_dataset_model_desc.copy()

Thêm attribute Result thể hiện kết quả trận đấu cho đội sân nhà với 3 trường hợp: Win, Draw, Lose

In [88]:
list_result = ['Win' if home_score > away_score
               else 'Draw' if home_score == away_score
               else 'Lose' for home_score, away_score
               in zip(dataset_model['Home_Score'], dataset_model['Away_Score'])]

In [89]:
dataset_model['Result'] = list_result
dataset_model

,Match_Key,Home_Team,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,Home_Aerials_Won,Home_Clearances,Home_Offsides,Home_Goal_Kicks,...,Home_Attack,Home_Midfield,Home_Defense,Away_Attack,Away_Midfield,Away_Defense,Home_Score,Away_Score,Match_Date,Result
0,12646,136,47.0,16.5,6.0,20.0,19.0,20.0,3.0,8.0,...,72.000000,71.533333,70.083333,77.100000,74.900000,77.266667,2.0,1.0,20240526.0,Win
1,7846,64,51.5,9.0,2.0,20.0,12.0,23.0,0.0,10.0,...,77.153846,77.812500,74.363636,78.142857,76.800000,77.785714,1.0,2.0,20240526.0,Lose
2,7845,62,52.0,13.5,2.0,8.5,14.5,20.0,2.5,8.5,...,76.200000,74.750000,73.846154,69.600000,73.000000,71.636364,2.0,2.0,20240526.0,Draw
3,12643,118,57.0,15.5,5.5,15.5,14.0,13.0,1.0,6.0,...,78.250000,76.411765,72.692308,73.181818,73.866667,73.285714,3.0,0.0,20240526.0,Win
4,12648,117,45.0,19.0,6.5,24.0,24.5,13.0,1.5,4.5,...,71.000000,69.650000,71.500000,81.600000,79.350000,80.615385,2.0,2.0,20240526.0,Draw
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,2592,35,38.0,9.0,2.0,23.0,21.0,13.0,2.0,5.0,...,75.500000,68.727273,72.625000,84.857143,84.000000,81.625000,0.0,3.0,20180811.0,Lose
10679,387,9,57.0,20.0,5.0,16.0,21.0,16.0,1.0,6.0,...,71.545455,72.000000,73.000000,0.000000,0.000000,0.000000,3.0,4.0,20180811.0,Lose
10680,2590,33,63.0,11.0,7.0,11.0,32.0,40.0,0.0,7.0,...,77.500000,75.000000,74.700000,0.000000,0.000000,0.000000,2.0,0.0,20180811.0,Win
10681,381,10,60.0,7.0,5.0,20.0,19.0,14.0,1.0,7.0,...,78.285714,77.800000,75.333333,73.000000,71.833333,72.571429,4.0,0.0,20180810.0,Win
10682,2587,30,47.0,11.0,2.0,12.0,9.0,36.0,4.0,5.0,...,85.600000,80.700000,79.454545,77.333333,78.083333,75.500000,2.0,1.0,20180810.0,Win

Kiểm tra số row thiếu dữ liệu, số thuộc tính input từ Home_Team đến Away_Defense

In [90]:
nan_rows = dataset_model.isna().sum(axis=1)
num_nan_rows = len(nan_rows[nan_rows > 0])
print("Tổng số trận:", len(dataset_model))
print("Số trận bị thiếu dữ liệu:", num_nan_rows)
print("Số thuộc tính input:", (dataset_model.columns.get_loc("Away_Defense")
                               - dataset_model.columns.get_loc("Home_Team")) + 1)

Tổng số trận: 10683
Số trận bị thiếu dữ liệu: 0
Số thuộc tính input: 78

In [91]:
dataset_model[dataset_model.isna().any(axis=1)]

Empty DataFrame
Columns: [Match_Key, Home_Team, Home_Possession, Home_Fouls, Home_Corners, Home_Crosses, Home_Aerials_Won, Home_Clearances, Home_Offsides, Home_Goal_Kicks, Home_Throw_Ins, Home_Long_Balls, Home_Gls, Home_Ast, Home_PK, Home_PK_Att, Home_Sh, Home_SoT, Home_CrdY, Home_CrdR, Home_Touches, Home_Tkl, Home_Int, Home_Blocks, Home_xG, Home_npxG, Home_xAG, Home_SCA, Home_GCA, Home_Cmp_Passes, Home_Att_Passes, Home_Cmp_percent_Passes, Home_PrgP_Passes, Home_Carries_Carries, Home_PrgC_Carries, Home_Att_Take_Ons, Home_Succ_Take_Ons, Away_Team, Away_Possession, Away_Fouls, Away_Corners, Away_Crosses, Away_Aerials_Won, Away_Clearances, Away_Offsides, Away_Goal_Kicks, Away_Throw_Ins, Away_Long_Balls, Away_Gls, Away_Ast, Away_PK, Away_PK_Att, Away_Sh, Away_SoT, Away_CrdY, Away_CrdR, Away_Touches, Away_Tkl, Away_Int, Away_Blocks, Away_xG, Away_npxG, Away_xAG, Away_SCA, Away_GCA, Away_Cmp_Passes, Away_Att_Passes, Away_Cmp_percent_Passes, Away_PrgP_Passes, Away_Carries_Carries, Away_PrgC_Carries, Away_Att_Take_Ons, Away_Succ_Take_Ons, Home_Attack, Home_Midfield, Home_Defense, Away_Attack, Away_Midfield, Away_Defense, Home_Score, Away_Score, Match_Date, Result]
Index: []

[0 rows x 83 columns]

Xoá NaN

In [92]:
#dataset_model = dataset_model[dataset_model['Match_Key'] != 10768]
#dataset_model = dataset_model[dataset_model['Match_Key'] != 10753]

#attack_mid_defense = 0
dataset_model = dataset_model[(dataset_model['Home_Attack'] != 0) &
                              (dataset_model['Home_Midfield'] != 0) &
                              (dataset_model['Home_Defense'] != 0)]
dataset_model = dataset_model[(dataset_model['Away_Attack'] != 0) &
                              (dataset_model['Away_Midfield'] != 0) &
                              (dataset_model['Away_Defense'] != 0)]

In [93]:
print("Số trận bị thiếu dữ liệu:", len(dataset_model.isna().sum(axis=1)[dataset_model.isna().sum(axis=1) > 0]))

Số trận bị thiếu dữ liệu: 0

In [94]:
dataset_model

,Match_Key,Home_Team,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,Home_Aerials_Won,Home_Clearances,Home_Offsides,Home_Goal_Kicks,...,Home_Attack,Home_Midfield,Home_Defense,Away_Attack,Away_Midfield,Away_Defense,Home_Score,Away_Score,Match_Date,Result
0,12646,136,47.0,16.5,6.0,20.0,19.0,20.0,3.0,8.0,...,72.000000,71.533333,70.083333,77.100000,74.900000,77.266667,2.0,1.0,20240526.0,Win
1,7846,64,51.5,9.0,2.0,20.0,12.0,23.0,0.0,10.0,...,77.153846,77.812500,74.363636,78.142857,76.800000,77.785714,1.0,2.0,20240526.0,Lose
2,7845,62,52.0,13.5,2.0,8.5,14.5,20.0,2.5,8.5,...,76.200000,74.750000,73.846154,69.600000,73.000000,71.636364,2.0,2.0,20240526.0,Draw
3,12643,118,57.0,15.5,5.5,15.5,14.0,13.0,1.0,6.0,...,78.250000,76.411765,72.692308,73.181818,73.866667,73.285714,3.0,0.0,20240526.0,Win
4,12648,117,45.0,19.0,6.5,24.0,24.5,13.0,1.5,4.5,...,71.000000,69.650000,71.500000,81.600000,79.350000,80.615385,2.0,2.0,20240526.0,Draw
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10674,385,4,43.0,14.0,6.0,22.0,21.0,32.0,2.0,10.0,...,74.000000,74.200000,75.750000,76.500000,73.250000,72.500000,2.0,1.0,20180811.0,Win
10677,386,8,56.0,12.0,2.0,10.0,10.0,19.0,1.0,7.0,...,69.500000,71.133333,69.166667,75.166667,72.588235,74.166667,3.0,1.0,20180811.0,Win
10678,2592,35,38.0,9.0,2.0,23.0,21.0,13.0,2.0,5.0,...,75.500000,68.727273,72.625000,84.857143,84.000000,81.625000,0.0,3.0,20180811.0,Lose
10681,381,10,60.0,7.0,5.0,20.0,19.0,14.0,1.0,7.0,...,78.285714,77.800000,75.333333,73.000000,71.833333,72.571429,4.0,0.0,20180810.0,Win
10682,2587,30,47.0,11.0,2.0,12.0,9.0,36.0,4.0,5.0,...,85.600000,80.700000,79.454545,77.333333,78.083333,75.500000,2.0,1.0,20180810.0,Win

<h3>2. Kiểm tra mối tương quan, biến đổi thuộc tính</h3>

Khởi chạy một phiên làm việc với SparkSession

In [95]:
spark = (SparkSession
         .builder
         .appName("Classifications Technique")
         .getOrCreate())

Chuyển đổi Dataframe pandas sang Dataframe Spark

In [96]:
matches = spark.createDataFrame(dataset_model)
display(matches.limit(5).toPandas())

,Match_Key,Home_Team,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,Home_Aerials_Won,Home_Clearances,Home_Offsides,Home_Goal_Kicks,...,Home_Attack,Home_Midfield,Home_Defense,Away_Attack,Away_Midfield,Away_Defense,Home_Score,Away_Score,Match_Date,Result
0,12646,136,47.0,16.5,6.0,20.0,19.0,20.0,3.0,8.0,...,72.000000,71.533333,70.083333,77.100000,74.900000,77.266667,2.0,1.0,20240526.0,Win
1,7846,64,51.5,9.0,2.0,20.0,12.0,23.0,0.0,10.0,...,77.153846,77.812500,74.363636,78.142857,76.800000,77.785714,1.0,2.0,20240526.0,Lose
2,7845,62,52.0,13.5,2.0,8.5,14.5,20.0,2.5,8.5,...,76.200000,74.750000,73.846154,69.600000,73.000000,71.636364,2.0,2.0,20240526.0,Draw
3,12643,118,57.0,15.5,5.5,15.5,14.0,13.0,1.0,6.0,...,78.250000,76.411765,72.692308,73.181818,73.866667,73.285714,3.0,0.0,20240526.0,Win
4,12648,117,45.0,19.0,6.5,24.0,24.5,13.0,1.5,4.5,...,71.000000,69.650000,71.500000,81.600000,79.350000,80.615385,2.0,2.0,20240526.0,Draw

Sử dụng phương pháp One-hot Encoding để biến đổi một số thuộc tính sang numeric

In [97]:
#Attributes không dùng tới
unused_cols = ['Match_Key', 'Match_Date', 'Home_Score', 'Away_Score']
#Output
output_cols = ['Result']

- Chọn các input và các input cần được One-hot Encoding

In [98]:
input_cols = [column for column in matches.columns
              if column not in output_cols and column not in unused_cols]
encode_cols = ['Home_Team','Away_Team']

In [99]:
def EncodedData(matches, unused_cols, output_cols, encode_cols):
    #String Indexer
    indexer = StringIndexer(inputCols=encode_cols, outputCols = [encode_col+ "_Index" for encode_col in encode_cols])
    encoded_df = indexer.fit(matches).transform(matches)

    #OneHot Encoder
    encodeer = OneHotEncoder(inputCols=[encode_col+"_Index" for encode_col in encode_cols],
                             outputCols=[encode_col+"_Onehot" for encode_col in encode_cols])
    encoded_df = encodeer.fit(encoded_df).transform(encoded_df)

    #Lấy ra những cột bị Index
    indexed_cols = [encode_col +"_Index" for encode_col in encode_cols]

    #Những cột được assembled là những cột không nằm trong unused_cols và indexed_cols và encode_cols và output_cols
    vector_assembled_input_cols = [col for col in encoded_df.columns
                                            if col not in unused_cols
                                            and col not in indexed_cols
                                            and col not in encode_cols
                                            and col not in output_cols
                                            ]
    assembler = VectorAssembler(inputCols=vector_assembled_input_cols,outputCol="Features")
    encoded_df = assembler.transform(encoded_df.select('*'))
    return encoded_df

- Tập data sau quá trình One-hot Encoding

In [100]:
encoded_matches = EncodedData(matches,unused_cols,output_cols,encode_cols)
display(encoded_matches.limit(5).toPandas())

,Match_Key,Home_Team,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,Home_Aerials_Won,Home_Clearances,Home_Offsides,Home_Goal_Kicks,...,Away_Defense,Home_Score,Away_Score,Match_Date,Result,Home_Team_Index,Away_Team_Index,Home_Team_Onehot,Away_Team_Onehot,Features
0,12646,136,47.0,16.5,6.0,20.0,19.0,20.0,3.0,8.0,...,77.266667,2.0,1.0,20240526.0,Win,76.0,37.0,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(47.0, 16.5, 6.0, 20.0, 19.0, 20.0, 3.0, 8.0, ..."
1,7846,64,51.5,9.0,2.0,20.0,12.0,23.0,0.0,10.0,...,77.785714,1.0,2.0,20240526.0,Lose,15.0,7.0,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...","(51.5, 9.0, 2.0, 20.0, 12.0, 23.0, 0.0, 10.0, ..."
2,7845,62,52.0,13.5,2.0,8.5,14.5,20.0,2.5,8.5,...,71.636364,2.0,2.0,20240526.0,Draw,4.0,8.0,"(0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...","(52.0, 13.5, 2.0, 8.5, 14.5, 20.0, 2.5, 8.5, 2..."
3,12643,118,57.0,15.5,5.5,15.5,14.0,13.0,1.0,6.0,...,73.285714,3.0,0.0,20240526.0,Win,23.0,39.0,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(57.0, 15.5, 5.5, 15.5, 14.0, 13.0, 1.0, 6.0, ..."
4,12648,117,45.0,19.0,6.5,24.0,24.5,13.0,1.5,4.5,...,80.615385,2.0,2.0,20240526.0,Draw,54.0,19.0,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(45.0, 19.0, 6.5, 24.0, 24.5, 13.0, 1.5, 4.5, ..."

Thêm attribute Label ứng với 3 nhãn Result: Win (0.0), Lose (1.0), Draw (2.0)

In [101]:
class_indexer = StringIndexer(inputCol = 'Result', outputCol = 'Label')

encoded_matches_label = class_indexer.fit(encoded_matches).transform(encoded_matches)

display(encoded_matches_label.limit(5).toPandas())

,Match_Key,Home_Team,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,Home_Aerials_Won,Home_Clearances,Home_Offsides,Home_Goal_Kicks,...,Home_Score,Away_Score,Match_Date,Result,Home_Team_Index,Away_Team_Index,Home_Team_Onehot,Away_Team_Onehot,Features,Label
0,12646,136,47.0,16.5,6.0,20.0,19.0,20.0,3.0,8.0,...,2.0,1.0,20240526.0,Win,76.0,37.0,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(47.0, 16.5, 6.0, 20.0, 19.0, 20.0, 3.0, 8.0, ...",0.0
1,7846,64,51.5,9.0,2.0,20.0,12.0,23.0,0.0,10.0,...,1.0,2.0,20240526.0,Lose,15.0,7.0,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...","(51.5, 9.0, 2.0, 20.0, 12.0, 23.0, 0.0, 10.0, ...",1.0
2,7845,62,52.0,13.5,2.0,8.5,14.5,20.0,2.5,8.5,...,2.0,2.0,20240526.0,Draw,4.0,8.0,"(0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...","(52.0, 13.5, 2.0, 8.5, 14.5, 20.0, 2.5, 8.5, 2...",2.0
3,12643,118,57.0,15.5,5.5,15.5,14.0,13.0,1.0,6.0,...,3.0,0.0,20240526.0,Win,23.0,39.0,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(57.0, 15.5, 5.5, 15.5, 14.0, 13.0, 1.0, 6.0, ...",0.0
4,12648,117,45.0,19.0,6.5,24.0,24.5,13.0,1.5,4.5,...,2.0,2.0,20240526.0,Draw,54.0,19.0,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(45.0, 19.0, 6.5, 24.0, 24.5, 13.0, 1.5, 4.5, ...",2.0

<h3>4. Xây dựng mô hình dự đoán với phương pháp Logistic Regression</h3>

Tập dữ liệu có *n* cột, với mỗi lần

Các function hỗ trợ cho việc xây dựng tập train, test

- Function Reduce_Matches() loại bỏ 20 trận đầu cho tập dữ liệu với mỗi lần gọi

In [102]:
def Reduce_Matches(matches_df):

    matches_df = matches_df.withColumn("id", monotonically_increasing_id())

    filtered_data = matches_df.filter(matches_df.id >= 20)
    filtered_data = filtered_data.drop("id")

    return filtered_data

- Function Train_Dataset() trả về tập train
- Funtion Test_Dataset() trả về tập test với 10 trận mới nhất (20 row đầu tiên)

In [103]:
def Train_Dataset(matches_df):

    test_count = 20

    encoded_test_matches = matches_df.limit(test_count)
    encoded_train_matches = matches_df.subtract(encoded_test_matches)

    return encoded_train_matches

def Test_Dataset(matches_df):

    test_count = 20

    encoded_test_matches = matches_df.limit(test_count)

    return encoded_test_matches

Funtion hỗ trợ các phương pháp đánh giá cho model

In [104]:
def Measure_Function(predictions, measure):

    evaluator = MulticlassClassificationEvaluator(labelCol="Label")

    measure_method = evaluator.evaluate(predictions, {evaluator.metricName: measure})

    return measure_method

    #print("Accuracy = %g" % accuracy)
    #print("Test Error = %g" % (1.0 - accuracy))

<h4>Logistic Regression</h4>

In [105]:
#Xây dựng model dựa vào tập train
def LogisticRegression_Func(X_train):
    logit = LogisticRegression(featuresCol = "Features", labelCol = "Label", elasticNetParam=0.1, regParam=0.1)
    logitModel = logit.fit(X_train)

    return logitModel

In [106]:
#Áp dụng model trên tập test
def LogitRegres_Predictions(logitModel, X_test):

    predictions = logitModel.transform(X_test)

    return predictions

In [107]:
#
matches_df = encoded_matches_label
X_test = matches_df.filter((matches_df["Match_Key"] == 4805) | (matches_df["Match_Key"] == 4800)
| (matches_df["Match_Key"] == 4801) | (matches_df["Match_Key"] == 4806) | (matches_df["Match_Key"] == 4804)
| (matches_df["Match_Key"] == 4799) | (matches_df["Match_Key"] == 4803) | (matches_df["Match_Key"] == 4798)
| (matches_df["Match_Key"] == 4802) | (matches_df["Match_Key"] == 4797) |
(matches_df["Match_Key"] == 7841) | (matches_df["Match_Key"] == 7840)
| (matches_df["Match_Key"] == 7837) | (matches_df["Match_Key"] == 7846) | (matches_df["Match_Key"] == 7842)
| (matches_df["Match_Key"] == 7844) | (matches_df["Match_Key"] == 7843) | (matches_df["Match_Key"] == 7838)
| (matches_df["Match_Key"] == 7845) | (matches_df["Match_Key"] == 7839)|
(matches_df["Match_Key"] == 12641) | (matches_df["Match_Key"] == 12643)
| (matches_df["Match_Key"] == 12644) | (matches_df["Match_Key"] == 12648) | (matches_df["Match_Key"] == 12645)
| (matches_df["Match_Key"] == 12639) | (matches_df["Match_Key"] == 12640) | (matches_df["Match_Key"] == 12642)
| (matches_df["Match_Key"] == 12646) | (matches_df["Match_Key"] == 12647) |
(matches_df["Match_Key"] == 2531) | (matches_df["Match_Key"] == 2528)
| (matches_df["Match_Key"] == 2526) | (matches_df["Match_Key"] == 2532) | (matches_df["Match_Key"] == 2524)
| (matches_df["Match_Key"] == 2527) | (matches_df["Match_Key"] == 2530) | (matches_df["Match_Key"] == 2529)
| (matches_df["Match_Key"] == 2525) |
(matches_df["Match_Key"] == 9991) | (matches_df["Match_Key"] == 9990)
| (matches_df["Match_Key"] == 9992) | (matches_df["Match_Key"] == 9987) | (matches_df["Match_Key"] == 9989)
| (matches_df["Match_Key"] == 9994) | (matches_df["Match_Key"] == 9988) | (matches_df["Match_Key"] == 9986)
| (matches_df["Match_Key"] == 9993))

In [108]:
X_test.count()

48

In [109]:
X_test.show()

+---------+---------+---------------+----------+------------+------------+----------------+---------------+-------------+---------------+--------------+---------------+--------+--------+-------+-----------+-------+--------+---------+---------+------------+--------+--------+-----------+-------------------+-------------------+--------+--------+--------+---------------+---------------+-----------------------+----------------+--------------------+-----------------+-----------------+------------------+---------+---------------+----------+------------+------------+----------------+---------------+-------------+---------------+--------------+---------------+--------+--------+-------+-----------+-------+--------+---------+---------+------------+--------+--------+-----------+------------------+------------------+-------------------+--------+--------+---------------+---------------+-----------------------+----------------+--------------------+-----------------+-----------------+------------------+-----------+-------------+------------+-----------+-------------+------------+----------+----------+-----------+------+---------------+---------------+-----------------+-----------------+--------------------+-----+
|Match_Key|Home_Team|Home_Possession|Home_Fouls|Home_Corners|Home_Crosses|Home_Aerials_Won|Home_Clearances|Home_Offsides|Home_Goal_Kicks|Home_Throw_Ins|Home_Long_Balls|Home_Gls|Home_Ast|Home_PK|Home_PK_Att|Home_Sh|Home_SoT|Home_CrdY|Home_CrdR|Home_Touches|Home_Tkl|Home_Int|Home_Blocks|            Home_xG|          Home_npxG|Home_xAG|Home_SCA|Home_GCA|Home_Cmp_Passes|Home_Att_Passes|Home_Cmp_percent_Passes|Home_PrgP_Passes|Home_Carries_Carries|Home_PrgC_Carries|Home_Att_Take_Ons|Home_Succ_Take_Ons|Away_Team|Away_Possession|Away_Fouls|Away_Corners|Away_Crosses|Away_Aerials_Won|Away_Clearances|Away_Offsides|Away_Goal_Kicks|Away_Throw_Ins|Away_Long_Balls|Away_Gls|Away_Ast|Away_PK|Away_PK_Att|Away_Sh|Away_SoT|Away_CrdY|Away_CrdR|Away_Touches|Away_Tkl|Away_Int|Away_Blocks|           Away_xG|         Away_npxG|           Away_xAG|Away_SCA|Away_GCA|Away_Cmp_Passes|Away_Att_Passes|Away_Cmp_percent_Passes|Away_PrgP_Passes|Away_Carries_Carries|Away_PrgC_Carries|Away_Att_Take_Ons|Away_Succ_Take_Ons|Home_Attack|Home_Midfield|Home_Defense|Away_Attack|Away_Midfield|Away_Defense|Home_Score|Away_Score| Match_Date|Result|Home_Team_Index|Away_Team_Index| Home_Team_Onehot| Away_Team_Onehot|            Features|Label|
+---------+---------+---------------+----------+------------+------------+----------------+---------------+-------------+---------------+--------------+---------------+--------+--------+-------+-----------+-------+--------+---------+---------+------------+--------+--------+-----------+-------------------+-------------------+--------+--------+--------+---------------+---------------+-----------------------+----------------+--------------------+-----------------+-----------------+------------------+---------+---------------+----------+------------+------------+----------------+---------------+-------------+---------------+--------------+---------------+--------+--------+-------+-----------+-------+--------+---------+---------+------------+--------+--------+-----------+------------------+------------------+-------------------+--------+--------+---------------+---------------+-----------------------+----------------+--------------------+-----------------+-----------------+------------------+-----------+-------------+------------+-----------+-------------+------------+----------+----------+-----------+------+---------------+---------------+-----------------+-----------------+--------------------+-----+
|    12646|      136|           47.0|      16.5|         6.0|        20.0|            19.0|           20.0|          3.0|            8.0|          23.0|           66.5|     0.5|     0.0|    0.5|        0.5|    9.5|     1.5|      4.0|      0.5|       486.0|    13.5|     7.0|       10.0|               1.05| 0.7000000000000001|    0.55|    16.0|     1.0|          274.5|          382.0|                  71.95|            23.5|               237.0|             12.5|             16.5|               5.0|      128|           48.0|      10.5|         3.5|        14.5|            11.5|           21.5|          0.5|           10.0|          17.5|           65.0|     1.0|     0.5|    0.5|        0.5|   14.5|     5.5|      1.5|      0.5|       564.0|    15.5|     6.5|       11.5|               1.0|0.6000000000000001|               0.55|    29.0|     2.0|          379.0|          465.0|                  81.25|            35.5|               297.0|             19.5|             14.5|               6.5|       72.0|  71.53333333| 70.08333333|       77.1|         74.9| 77.26666667|       2.0|       1.0|2.0240526E7|   Win|           76.0|           37.0| (135,[76],[1.0])| (135,[37],[1.0])|(346,[0,1,2,3,4,5...|  0.0|
|     7846|       64|           51.5|       9.0|         2.0|        20.0|            12.0|           23.0|          0.0|           10.0|          19.0|           70.5|     0.0|     0.0|    0.0|        0.0|   11.5|     3.5|      3.5|      0.0|       603.0|    21.5|     6.0|        7.0|                1.1|                1.1|    1.05|    19.5|     0.0|          395.5|          489.0|                   80.8|            38.0|               357.5|             19.0|             19.0|               9.5|       66|           68.0|      10.5|         7.0|        16.0|            11.0|            9.5|          0.5|           10.0|          20.5|           58.5|     2.5|     2.0|    0.0|        0.0|   15.0|     6.5|      2.5|      0.0|       791.5|    11.0|     4.5|        6.5|1.4500000000000002|1.4500000000000002|               1.15|    29.0|     4.5|          626.5|          703.5|      89.05000000000001|            59.0|               605.5|             21.5|             25.0|              11.5|77.15384615|      77.8125| 74.36363636|78.14285714|         76.8| 77.78571429|       1.0|       2.0|2.0240526E7|  Lose|           15.0|            7.0| (135,[15],[1.0])|  (135,[7],[1.0])|(346,[0,1,2,3,4,5...|  1.0|
|     7845|       62|           52.0|      13.5|         2.0|         8.5|            14.5|           20.0|          2.5|            8.5|          23.0|           69.0|     2.0|     2.0|    0.0|        0.0|    9.0|     4.5|      1.5|      0.0|       631.5|    21.0|     4.0|       10.5|                1.2|                1.2|     1.2|    18.0|     4.0|          416.0|          525.0|                  79.15|            32.5|               349.5|             17.0|             22.5|               8.5|       61|           40.0|      11.5|         4.0|        14.5|             7.0|           14.5|          2.5|            8.0|          19.0|           58.0|     0.5|     0.0|    0.5|        0.5|   13.0|     4.0|      2.0|      0.0|       508.5|    11.0|     8.0|       11.0|2.0500000000000003|              1.65|                1.1|    23.0|     1.0|          323.0|          412.0|                  78.75|            29.0|               224.5|             15.0|             15.0|               4.0|       76.2|        74.75| 73.84615385|       69.6|         73.0| 71.63636364|       2.0|       2.0|2.0240526E7|  Draw|            4.0|            8.0|  (135,[4],[1.0])|  (135,[8],[1.0])|(346,[0,1,2,3,4,5...|  2.0|
|    12643|      118|           57.0|      15.5|         5.5|        15.5|            14.0|           13.0|          1.0|            6.0|          19.5|           55.0|     2.0|     2.0|    0.0|        0.0|   21.5|     8.0|      2.5|      0.0|       684.5|    13.0|    10.5|        6.0| 2.1500000000000004| 2.1500000000000004|    1.95|    38.0|     3.0|          504.0|          588.5|                   85.6|            51.5|               372.5|             19.5|             14.0|               6.0|      135|           48.5|      15.0|         3.5|        12.0|            16.5|           22.5|          1.0|            8.0|          18.0|           70.0|     2.5|     2.5|    0.0|        0.0|    8.5|     3.5|      1.5|      0.0|       514.5|    13.0|     8.5|        9.0|               0.7|               0.7|               0.65|    15.5|     5.0|          321.5|          408.0|                  78.65|            24.0|               259.5|              9.0|             15.0|               5.5|      78.25|  76.41176471| 72.69230769|73.18181818|  73.86666667| 73.28571429|       3.0|       0.0|2.0240526E7|   Win|           23.0|           39.0| (135,[23],[1.0])| (135,[39],[1.0])|(346,[0,1,2,3,4,5...|  0.0|
|    12648|      117|           45.0|      19.0|         6.5|        24.0|            24.5|           13.0|          1.5|            4.5|          20.5|           84.5|     1.5|     1.5|    0.0|        0.0|   15.0|     5.0|      2.5|      0.5|       497.0|    20.5|     8.5|       11.0|               1.65|               1.65|    1.65|    28.0|     3.0|          259.0|          387.5|                  66.85|            30.5|               227.0|             14.5|             16.0|               7.0|      120|           57.5|       9.0|         6.0|        18.5|            13.0|           12.0|          0.5|            9.0|          11.0|           60.0|     3.0|     2.0|    0.0|        0.0|   16.5|     6.0|      0.0|      0.0|       703.5|    14.5|    10.0|        9.5|              1.65|              1.65| 1.2999999999999998|    30.0|     5.0|          534.5|          608.5|                  87.85|            43.5|               413.0|             22.0|              8.0|               4.0|       71.0|        69.65|        71.5|       81.6|        79.35| 80.61538462|       2.0|       2.0|2.0240526E7|  Draw|           54.0|           19.0| (135,[54],[1.0])| (135,[19],[1.0])|(346,[0,1,2,3,4,5...|  2.0|
|    12644|      134|           48.5|      14.5|         6.0|        19.0|            14.0|           14.0|          1.5|            3.5|          21.0|           53.0|     1.0|     0.5|    0.0|        0.5|   15.0|     4.0|      2.0|      0.0|       557.0|    19.5|     5.5|       12.5|                1.4|               0.95|     0.8|    26.5|     1.5|          371.0|          456.5|      79.30000000000001|            39.0|               289.0|             16.5|             20.5|               9.5|      140|           54.5|       9.5|         5.0|        17.5|            12.0|           11.5|          1.0|           10.5|          20.5|           72.5|     0.0|     0.0|    0.0|        0.0|   10.0|     2.5|      1.0|      0.0|       615.5|    14.5|     7.0|        8.5|0.8500000000000001|0.8500000000000001|                0.7|    18.5|     0.0|          424.0|          525.0|                   80.8|            45.5|               349.0|             18.0|             24.0|              10.0|79.16666667|  76.53846154| 76.71428571|69.18181818|  67.30769231|      71.125|       0.0|       0.0|2.0240526E7|  Draw|           37.0|           96.0| (135,[37],[1.0])| (135,[96],[1.0])|(346,[0,1,2,3,4,5...|  2.0|
|    12647|      138|           36.0|       8.5|         6.0|        17.0|             9.0|           17.5|          0.0|            9.0|          17.0|           47.5|     0.5|     0.5|    0.0|        0.0|   16.5|     5.5|      1.0|      0.0|       457.0|     8.5|     6.0|       14.5| 1.7000000000000002| 1.7000000000000002|    1.25|    29.0|     1.0|          281.0|          357.5|                   77.2|            31.5|               223.5|             22.5|             18.5|               9.0|      119|           41.0|      12.5|         3.5|        15.5|            21.5|           23.5|          0.5|            9.0|          22.5|           80.0|     1.5|     0.5|    0.5|        0.5|   11.5|     2.0|      1.0|      0.0|       462.0|    21.0|     7.5|       12.0|               1.6|              1.25|               1.05|    20.5|     2.5|          237.0|          338.5|      70.19999999999999|            25.5|               194.5|             12.5|             21.5|              11.0|68.18181818|  69.11111111| 68.41666667|73.83333333|  73.33333333| 69.10526316|       0.0|       1.0|2.0240526E7|  Lose|          110.0|           47.0|(135,[110],[1.0])| (135,[47],[1.0])|(346,[0,1,2,3,4,5...|  1.0|
|     7844|       74|           54.0|      10.5|         3.5|        14.0|            12.5|           23.0|          5.0|            7.5|          24.5|           67.5|     1.0|     0.5|    0.0|        0.0|   12.5|     5.0|      1.5|      0.0|       653.5|    20.0|     7.0|       12.5|               1.45|               1.45|    1.05|    22.0|     1.5|          412.5|          527.0|                   78.2|            43.0|               301.0|             17.5|             23.5|              11.5|       70|           38.5|      12.5|         1.5|        16.0|            19.0|           18.5|          2.5|            7.0|          23.0|           69.5|     0.5|     0.5|    0.0|        0.0|   13.5|     6.0|      3.0|      0.0|       419.0|    14.5|     5.5|        8.0|              1.25|              1.25|               1.15|    24.5|     1.0|          220.0|          317.5|                  68.65|            31.5|               184.0|             10.5|             13.0|               7.5|71.33333333|        73.44|        73.4|       79.0|         75.2|        73.2|       1.0|       1.0|2.0240526E7|  Draw|          130.0|           51.0|(135,[130],[1.0])| (135,[51],[1.0])|(346,[0,1,2,3,4,5...|  2.0|
|     7843|       72|           48.5|      22.0|         3.5|        14.5|             9.5|           18.0|          0.5|           11.5|          21.5|           72.5|     0.0|     0.0|    0.0|        0.0|    9.0|     3.5|      5.5|      0.5|       500.5|    13.0|     7.5|        8.0|0.44999999999999996|0.44999999999999996|    0.35|    16.5|     0.0|          309.0|          406.0|      74.05000000000001|            31.5|               255.5|              9.0|             17.5|               9.5|       83|           50.0|      10.0|         8.0|        27.5|            19.0|           24.5|          2.5|            7.5|          24.0|           76.0|     1.5|     1.0|    0.0|        0.0|   19.5|     6.0|      1.5|      0.0|       591.5|    16.0|    12.0|        7.0|               2.0|               2.0|               1.45|    35.5|     2.5|          362.0|          474.5|      76.19999999999999|            46.5|               334.0|             18.0|             16.0|               6.5|74.33333333|  75.11764706|        74.7|      75.75|  75.47368421|     74.9375|       1.0|       2.0|2.0240526E7|  Lose|            2.0|           63.0|  (135,[2],[1.0])| (135,[63],[1.0])|(346,[0,1,2,3,4,5...|  1.0|
|    12645|      124|           51.0|      16.5|         3.5|        12.0|            10.0|           19.0|          1.5|           13.0|          22.0|           67.0|     1.5|     1.5|    0.0|        0.0|    9.5|     4.0|      2.0|      0.0|       587.5|    15.0|     7.5|       11.5|               1.15|               1.15|     1.1|    16.0|     3.0|          401.5|          491.0|                   81.7|            31.5|               299.5|             10.5|             13.0|               5.5|      125|           45.5|      12.0|         6.0|        22.5|            21.0|           28.0|          0.5|            9.5|          15.0|           79.0|     0.5|     0.0|    0.5|        0.5|    9.0|     1.5|      3.0|      0.5|       485.5|    17.0|     3.5|        8.0|               1.0|               0.6|               0.55|    19.0|     1.0|          273.5|          383.5|                  71.25|            35.5|               251.0|             13.5|             12.0|               6.5|77.28571429|         78.4| 76.44444444|71.33333333|  71.21428571|      71.375|       1.0|       1.0|2.0240526E7|  Draw|           34.0|           43.0| (135,[34],[1.0])| (135,[43],[1.0])|(346,[0,1,2,3,4,5...|  2.0|
|    12641|      116|           52.5|      18.0|         5.5|        21.5|            11.5|            9.5|          2.0|            5.0|          20.0|           46.0|     2.0|     0.5|    0.0|        0.0|   18.0|     5.0|      3.5|      0.0|       580.0|    14.5|     4.0|       12.5|                1.5|                1.5|    1.25|    32.5|     2.5|          401.0|          479.5|                   83.8|            56.0|               373.5|             18.5|             17.0|               6.0|      144|           60.5|      14.0|         2.0|        17.5|            19.0|           21.5|          0.0|            9.5|          19.5|           71.5|     0.5|     0.5|    0.0|        0.0|   10.0|     2.0|      1.0|      0.0|       646.0|    14.5|     4.5|        7.0|              0.85|              0.85|               0.65|    17.5|     1.0|          465.0|          550.0|                   84.3|            37.5|               376.0|             15.5|             15.0|               5.0|77.71428571|  76.47058824| 77.84615385|71.54545455|       73.125| 73.07692308|       2.0|       0.0|2.0240525E7|   Win|           33.0|          107.0| (135,[33],[1.0])|(135,[107],[1.0])|(346,[0,1,2,3,4,5...|  0.0|
|     7838|       85|           48.0|      10.5|         3.5|        16.5|            23.0|           21.0|          2.0|           10.5|          26.5|           84.5|     2.5|     1.5|    0.0|        0.0|   12.5|     5.0|      1.0|      0.0|       554.0|    11.0|     6.5|        5.5|               1.25|               1.25|     0.6|    19.5|     4.0|          342.5|          457.5|                  75.05|            27.5|               304.5|             14.0|             13.5|               6.0|       78|           38.0|      14.5|         2.0|        16.5|             7.0|           18.5|          0.0|           11.0|          11.5|           46.5|     2.5|     1.5|    0.0|        0.0|   16.0|     5.0|      3.5|      0.5|       582.0|    20.0|     9.5|        8.5|              1.15|              1.15|               0.65|    29.0|     3.5|          407.0|          476.5|                  85.05|            43.5|               331.0|             16.0|             20.5|               9.5|       73.8|  75.64285714| 75.16666667|83.83333333|  80.36363636|       80.25|       1.0|       1.0|2.0240525E7|  Draw|           51.0|           18.0| (135,[51],[1.0])| (135,[18],[1.0])|(346,[0,1,2,3,4,5...|  2.0|
|     7840|       88|           42.0|       9.5|         3.0|        10.5|            10.5|           30.5|          3.0|           11.5|          15.0|           56.5|     1.0|     0.5|    0.0|        0.0|    9.5|     3.0|      1.5|      0.0|       546.5|    16.5|     7.0|       12.5|               0.65|               0.65|    0.35|    18.0|     2.0|          350.5|          429.5|                  81.65|            21.0|               280.0|             11.0|             16.5|               6.5|       86|           46.5|      12.0|         7.0|        27.5|            20.5|           13.5|          2.0|           12.5|          19.0|           88.0|     0.5|     0.5|    0.0|        0.0|   14.5|     5.0|      2.5|      0.5|       549.5|    19.5|     6.5|        9.5|               1.7|               1.7|                1.2|    26.0|     1.0|          326.0|          446.0|                  73.25|            35.5|               314.5|             15.5|             19.0|              11.0|       72.0|         75.5| 71.36363636|       74.0|  74.65384615| 72.88888889|       6.0|       1.0|2.0240525E7|   Win|          112.0|           70.0|(135,[112],[1.0])| (135,[70],[1.0])|(346,[0,1,2,3,4,5...|  0.0|

In [110]:
X_train = matches_df.subtract(X_test)
X_train = X_train.select('Features', 'Label')
X_test = X_test.select('Features', 'Label')
X_train.count()

9061

In [111]:
logitModel = LogisticRegression_Func(X_train)
predictions = LogitRegres_Predictions(logitModel, X_test)

In [112]:
predictions.show()

+--------------------+-----+--------------------+--------------------+----------+
|            Features|Label|       rawPrediction|         probability|prediction|
+--------------------+-----+--------------------+--------------------+----------+
|(346,[0,1,2,3,4,5...|  0.0|[1.39906848223745...|[0.27514716791886...|       1.0|
|(346,[0,1,2,3,4,5...|  1.0|[1.80742129401867...|[0.34094513894952...|       1.0|
|(346,[0,1,2,3,4,5...|  2.0|[2.08540435878205...|[0.51331050907541...|       0.0|
|(346,[0,1,2,3,4,5...|  0.0|[2.37943376514898...|[0.58119036479050...|       0.0|
|(346,[0,1,2,3,4,5...|  2.0|[1.19269089099121...|[0.16993194538473...|       1.0|
|(346,[0,1,2,3,4,5...|  2.0|[2.55497443173884...|[0.64726460781802...|       0.0|
|(346,[0,1,2,3,4,5...|  1.0|[1.57135682143536...|[0.35088749938836...|       0.0|
|(346,[0,1,2,3,4,5...|  2.0|[1.84558070778811...|[0.41583078301967...|       0.0|
|(346,[0,1,2,3,4,5...|  1.0|[1.66919385234539...|[0.35370932270187...|       1.0|
|(346,[0,1,2,3,4,5...|  2.0|[2.36268754871522...|[0.60372192339579...|       0.0|
|(346,[0,1,2,3,4,5...|  0.0|[2.46762245618277...|[0.60510091663917...|       0.0|
|(346,[0,1,2,3,4,5...|  2.0|[1.60455920255616...|[0.29917552722858...|       1.0|
|(346,[0,1,2,3,4,5...|  0.0|[1.70274942892298...|[0.37556763162736...|       0.0|
|(346,[0,1,2,3,4,5...|  2.0|[3.04119300730885...|[0.76958828845403...|       0.0|
|(346,[0,1,2,3,4,5...|  1.0|[1.67992949634887...|[0.33571607567646...|       1.0|
|(346,[0,1,2,3,4,5...|  1.0|[1.50890385640079...|[0.27141797692861...|       1.0|
|(346,[0,1,2,3,4,5...|  2.0|[2.88625348677974...|[0.71064815829386...|       0.0|
|(346,[0,1,2,3,4,5...|  0.0|[1.77061311861741...|[0.38764106493727...|       0.0|
|(346,[0,1,2,3,4,5...|  0.0|[2.63548701582195...|[0.64447890758739...|       0.0|
|(346,[0,1,2,3,4,5...|  1.0|[1.42289539395637...|[0.27909868215663...|       1.0|
+--------------------+-----+--------------------+--------------------+----------+
only showing top 20 rows

In [113]:
#
future_match = matches_df.filter((matches_df["Match_Key"] == 4805) | (matches_df["Match_Key"] == 4800)
| (matches_df["Match_Key"] == 4801) | (matches_df["Match_Key"] == 4806) | (matches_df["Match_Key"] == 4804)
| (matches_df["Match_Key"] == 4799) | (matches_df["Match_Key"] == 4803) | (matches_df["Match_Key"] == 4798)
| (matches_df["Match_Key"] == 4802) | (matches_df["Match_Key"] == 4797) |
(matches_df["Match_Key"] == 7841) | (matches_df["Match_Key"] == 7840)
| (matches_df["Match_Key"] == 7837) | (matches_df["Match_Key"] == 7846) | (matches_df["Match_Key"] == 7842)
| (matches_df["Match_Key"] == 7844) | (matches_df["Match_Key"] == 7843) | (matches_df["Match_Key"] == 7838)
| (matches_df["Match_Key"] == 7845) | (matches_df["Match_Key"] == 7839)|
(matches_df["Match_Key"] == 12641) | (matches_df["Match_Key"] == 12643)
| (matches_df["Match_Key"] == 12644) | (matches_df["Match_Key"] == 12648) | (matches_df["Match_Key"] == 12645)
| (matches_df["Match_Key"] == 12639) | (matches_df["Match_Key"] == 12640) | (matches_df["Match_Key"] == 12642)
| (matches_df["Match_Key"] == 12646) | (matches_df["Match_Key"] == 12647) |
(matches_df["Match_Key"] == 2531) | (matches_df["Match_Key"] == 2528)
| (matches_df["Match_Key"] == 2526) | (matches_df["Match_Key"] == 2532) | (matches_df["Match_Key"] == 2524)
| (matches_df["Match_Key"] == 2527) | (matches_df["Match_Key"] == 2530) | (matches_df["Match_Key"] == 2529)
| (matches_df["Match_Key"] == 2525) |
(matches_df["Match_Key"] == 9991) | (matches_df["Match_Key"] == 9990)
| (matches_df["Match_Key"] == 9992) | (matches_df["Match_Key"] == 9987) | (matches_df["Match_Key"] == 9989)
| (matches_df["Match_Key"] == 9994) | (matches_df["Match_Key"] == 9988) | (matches_df["Match_Key"] == 9986)
| (matches_df["Match_Key"] == 9993))

In [114]:
future_match = future_match.withColumn("id", monotonically_increasing_id())
predictions = predictions.withColumn("id", monotonically_increasing_id())

In [115]:
future_match.show()

+---------+---------+---------------+----------+------------+------------+----------------+---------------+-------------+---------------+--------------+---------------+--------+--------+-------+-----------+-------+--------+---------+---------+------------+--------+--------+-----------+-------------------+-------------------+--------+--------+--------+---------------+---------------+-----------------------+----------------+--------------------+-----------------+-----------------+------------------+---------+---------------+----------+------------+------------+----------------+---------------+-------------+---------------+--------------+---------------+--------+--------+-------+-----------+-------+--------+---------+---------+------------+--------+--------+-----------+------------------+------------------+-------------------+--------+--------+---------------+---------------+-----------------------+----------------+--------------------+-----------------+-----------------+------------------+-----------+-------------+------------+-----------+-------------+------------+----------+----------+-----------+------+---------------+---------------+-----------------+-----------------+--------------------+-----+---+
|Match_Key|Home_Team|Home_Possession|Home_Fouls|Home_Corners|Home_Crosses|Home_Aerials_Won|Home_Clearances|Home_Offsides|Home_Goal_Kicks|Home_Throw_Ins|Home_Long_Balls|Home_Gls|Home_Ast|Home_PK|Home_PK_Att|Home_Sh|Home_SoT|Home_CrdY|Home_CrdR|Home_Touches|Home_Tkl|Home_Int|Home_Blocks|            Home_xG|          Home_npxG|Home_xAG|Home_SCA|Home_GCA|Home_Cmp_Passes|Home_Att_Passes|Home_Cmp_percent_Passes|Home_PrgP_Passes|Home_Carries_Carries|Home_PrgC_Carries|Home_Att_Take_Ons|Home_Succ_Take_Ons|Away_Team|Away_Possession|Away_Fouls|Away_Corners|Away_Crosses|Away_Aerials_Won|Away_Clearances|Away_Offsides|Away_Goal_Kicks|Away_Throw_Ins|Away_Long_Balls|Away_Gls|Away_Ast|Away_PK|Away_PK_Att|Away_Sh|Away_SoT|Away_CrdY|Away_CrdR|Away_Touches|Away_Tkl|Away_Int|Away_Blocks|           Away_xG|         Away_npxG|           Away_xAG|Away_SCA|Away_GCA|Away_Cmp_Passes|Away_Att_Passes|Away_Cmp_percent_Passes|Away_PrgP_Passes|Away_Carries_Carries|Away_PrgC_Carries|Away_Att_Take_Ons|Away_Succ_Take_Ons|Home_Attack|Home_Midfield|Home_Defense|Away_Attack|Away_Midfield|Away_Defense|Home_Score|Away_Score| Match_Date|Result|Home_Team_Index|Away_Team_Index| Home_Team_Onehot| Away_Team_Onehot|            Features|Label| id|
+---------+---------+---------------+----------+------------+------------+----------------+---------------+-------------+---------------+--------------+---------------+--------+--------+-------+-----------+-------+--------+---------+---------+------------+--------+--------+-----------+-------------------+-------------------+--------+--------+--------+---------------+---------------+-----------------------+----------------+--------------------+-----------------+-----------------+------------------+---------+---------------+----------+------------+------------+----------------+---------------+-------------+---------------+--------------+---------------+--------+--------+-------+-----------+-------+--------+---------+---------+------------+--------+--------+-----------+------------------+------------------+-------------------+--------+--------+---------------+---------------+-----------------------+----------------+--------------------+-----------------+-----------------+------------------+-----------+-------------+------------+-----------+-------------+------------+----------+----------+-----------+------+---------------+---------------+-----------------+-----------------+--------------------+-----+---+
|    12646|      136|           47.0|      16.5|         6.0|        20.0|            19.0|           20.0|          3.0|            8.0|          23.0|           66.5|     0.5|     0.0|    0.5|        0.5|    9.5|     1.5|      4.0|      0.5|       486.0|    13.5|     7.0|       10.0|               1.05| 0.7000000000000001|    0.55|    16.0|     1.0|          274.5|          382.0|                  71.95|            23.5|               237.0|             12.5|             16.5|               5.0|      128|           48.0|      10.5|         3.5|        14.5|            11.5|           21.5|          0.5|           10.0|          17.5|           65.0|     1.0|     0.5|    0.5|        0.5|   14.5|     5.5|      1.5|      0.5|       564.0|    15.5|     6.5|       11.5|               1.0|0.6000000000000001|               0.55|    29.0|     2.0|          379.0|          465.0|                  81.25|            35.5|               297.0|             19.5|             14.5|               6.5|       72.0|  71.53333333| 70.08333333|       77.1|         74.9| 77.26666667|       2.0|       1.0|2.0240526E7|   Win|           76.0|           37.0| (135,[76],[1.0])| (135,[37],[1.0])|(346,[0,1,2,3,4,5...|  0.0|  0|
|     7846|       64|           51.5|       9.0|         2.0|        20.0|            12.0|           23.0|          0.0|           10.0|          19.0|           70.5|     0.0|     0.0|    0.0|        0.0|   11.5|     3.5|      3.5|      0.0|       603.0|    21.5|     6.0|        7.0|                1.1|                1.1|    1.05|    19.5|     0.0|          395.5|          489.0|                   80.8|            38.0|               357.5|             19.0|             19.0|               9.5|       66|           68.0|      10.5|         7.0|        16.0|            11.0|            9.5|          0.5|           10.0|          20.5|           58.5|     2.5|     2.0|    0.0|        0.0|   15.0|     6.5|      2.5|      0.0|       791.5|    11.0|     4.5|        6.5|1.4500000000000002|1.4500000000000002|               1.15|    29.0|     4.5|          626.5|          703.5|      89.05000000000001|            59.0|               605.5|             21.5|             25.0|              11.5|77.15384615|      77.8125| 74.36363636|78.14285714|         76.8| 77.78571429|       1.0|       2.0|2.0240526E7|  Lose|           15.0|            7.0| (135,[15],[1.0])|  (135,[7],[1.0])|(346,[0,1,2,3,4,5...|  1.0|  1|
|     7845|       62|           52.0|      13.5|         2.0|         8.5|            14.5|           20.0|          2.5|            8.5|          23.0|           69.0|     2.0|     2.0|    0.0|        0.0|    9.0|     4.5|      1.5|      0.0|       631.5|    21.0|     4.0|       10.5|                1.2|                1.2|     1.2|    18.0|     4.0|          416.0|          525.0|                  79.15|            32.5|               349.5|             17.0|             22.5|               8.5|       61|           40.0|      11.5|         4.0|        14.5|             7.0|           14.5|          2.5|            8.0|          19.0|           58.0|     0.5|     0.0|    0.5|        0.5|   13.0|     4.0|      2.0|      0.0|       508.5|    11.0|     8.0|       11.0|2.0500000000000003|              1.65|                1.1|    23.0|     1.0|          323.0|          412.0|                  78.75|            29.0|               224.5|             15.0|             15.0|               4.0|       76.2|        74.75| 73.84615385|       69.6|         73.0| 71.63636364|       2.0|       2.0|2.0240526E7|  Draw|            4.0|            8.0|  (135,[4],[1.0])|  (135,[8],[1.0])|(346,[0,1,2,3,4,5...|  2.0|  2|
|    12643|      118|           57.0|      15.5|         5.5|        15.5|            14.0|           13.0|          1.0|            6.0|          19.5|           55.0|     2.0|     2.0|    0.0|        0.0|   21.5|     8.0|      2.5|      0.0|       684.5|    13.0|    10.5|        6.0| 2.1500000000000004| 2.1500000000000004|    1.95|    38.0|     3.0|          504.0|          588.5|                   85.6|            51.5|               372.5|             19.5|             14.0|               6.0|      135|           48.5|      15.0|         3.5|        12.0|            16.5|           22.5|          1.0|            8.0|          18.0|           70.0|     2.5|     2.5|    0.0|        0.0|    8.5|     3.5|      1.5|      0.0|       514.5|    13.0|     8.5|        9.0|               0.7|               0.7|               0.65|    15.5|     5.0|          321.5|          408.0|                  78.65|            24.0|               259.5|              9.0|             15.0|               5.5|      78.25|  76.41176471| 72.69230769|73.18181818|  73.86666667| 73.28571429|       3.0|       0.0|2.0240526E7|   Win|           23.0|           39.0| (135,[23],[1.0])| (135,[39],[1.0])|(346,[0,1,2,3,4,5...|  0.0|  3|
|    12648|      117|           45.0|      19.0|         6.5|        24.0|            24.5|           13.0|          1.5|            4.5|          20.5|           84.5|     1.5|     1.5|    0.0|        0.0|   15.0|     5.0|      2.5|      0.5|       497.0|    20.5|     8.5|       11.0|               1.65|               1.65|    1.65|    28.0|     3.0|          259.0|          387.5|                  66.85|            30.5|               227.0|             14.5|             16.0|               7.0|      120|           57.5|       9.0|         6.0|        18.5|            13.0|           12.0|          0.5|            9.0|          11.0|           60.0|     3.0|     2.0|    0.0|        0.0|   16.5|     6.0|      0.0|      0.0|       703.5|    14.5|    10.0|        9.5|              1.65|              1.65| 1.2999999999999998|    30.0|     5.0|          534.5|          608.5|                  87.85|            43.5|               413.0|             22.0|              8.0|               4.0|       71.0|        69.65|        71.5|       81.6|        79.35| 80.61538462|       2.0|       2.0|2.0240526E7|  Draw|           54.0|           19.0| (135,[54],[1.0])| (135,[19],[1.0])|(346,[0,1,2,3,4,5...|  2.0|  4|
|    12644|      134|           48.5|      14.5|         6.0|        19.0|            14.0|           14.0|          1.5|            3.5|          21.0|           53.0|     1.0|     0.5|    0.0|        0.5|   15.0|     4.0|      2.0|      0.0|       557.0|    19.5|     5.5|       12.5|                1.4|               0.95|     0.8|    26.5|     1.5|          371.0|          456.5|      79.30000000000001|            39.0|               289.0|             16.5|             20.5|               9.5|      140|           54.5|       9.5|         5.0|        17.5|            12.0|           11.5|          1.0|           10.5|          20.5|           72.5|     0.0|     0.0|    0.0|        0.0|   10.0|     2.5|      1.0|      0.0|       615.5|    14.5|     7.0|        8.5|0.8500000000000001|0.8500000000000001|                0.7|    18.5|     0.0|          424.0|          525.0|                   80.8|            45.5|               349.0|             18.0|             24.0|              10.0|79.16666667|  76.53846154| 76.71428571|69.18181818|  67.30769231|      71.125|       0.0|       0.0|2.0240526E7|  Draw|           37.0|           96.0| (135,[37],[1.0])| (135,[96],[1.0])|(346,[0,1,2,3,4,5...|  2.0|  5|
|    12647|      138|           36.0|       8.5|         6.0|        17.0|             9.0|           17.5|          0.0|            9.0|          17.0|           47.5|     0.5|     0.5|    0.0|        0.0|   16.5|     5.5|      1.0|      0.0|       457.0|     8.5|     6.0|       14.5| 1.7000000000000002| 1.7000000000000002|    1.25|    29.0|     1.0|          281.0|          357.5|                   77.2|            31.5|               223.5|             22.5|             18.5|               9.0|      119|           41.0|      12.5|         3.5|        15.5|            21.5|           23.5|          0.5|            9.0|          22.5|           80.0|     1.5|     0.5|    0.5|        0.5|   11.5|     2.0|      1.0|      0.0|       462.0|    21.0|     7.5|       12.0|               1.6|              1.25|               1.05|    20.5|     2.5|          237.0|          338.5|      70.19999999999999|            25.5|               194.5|             12.5|             21.5|              11.0|68.18181818|  69.11111111| 68.41666667|73.83333333|  73.33333333| 69.10526316|       0.0|       1.0|2.0240526E7|  Lose|          110.0|           47.0|(135,[110],[1.0])| (135,[47],[1.0])|(346,[0,1,2,3,4,5...|  1.0|  6|
|     7844|       74|           54.0|      10.5|         3.5|        14.0|            12.5|           23.0|          5.0|            7.5|          24.5|           67.5|     1.0|     0.5|    0.0|        0.0|   12.5|     5.0|      1.5|      0.0|       653.5|    20.0|     7.0|       12.5|               1.45|               1.45|    1.05|    22.0|     1.5|          412.5|          527.0|                   78.2|            43.0|               301.0|             17.5|             23.5|              11.5|       70|           38.5|      12.5|         1.5|        16.0|            19.0|           18.5|          2.5|            7.0|          23.0|           69.5|     0.5|     0.5|    0.0|        0.0|   13.5|     6.0|      3.0|      0.0|       419.0|    14.5|     5.5|        8.0|              1.25|              1.25|               1.15|    24.5|     1.0|          220.0|          317.5|                  68.65|            31.5|               184.0|             10.5|             13.0|               7.5|71.33333333|        73.44|        73.4|       79.0|         75.2|        73.2|       1.0|       1.0|2.0240526E7|  Draw|          130.0|           51.0|(135,[130],[1.0])| (135,[51],[1.0])|(346,[0,1,2,3,4,5...|  2.0|  7|
|     7843|       72|           48.5|      22.0|         3.5|        14.5|             9.5|           18.0|          0.5|           11.5|          21.5|           72.5|     0.0|     0.0|    0.0|        0.0|    9.0|     3.5|      5.5|      0.5|       500.5|    13.0|     7.5|        8.0|0.44999999999999996|0.44999999999999996|    0.35|    16.5|     0.0|          309.0|          406.0|      74.05000000000001|            31.5|               255.5|              9.0|             17.5|               9.5|       83|           50.0|      10.0|         8.0|        27.5|            19.0|           24.5|          2.5|            7.5|          24.0|           76.0|     1.5|     1.0|    0.0|        0.0|   19.5|     6.0|      1.5|      0.0|       591.5|    16.0|    12.0|        7.0|               2.0|               2.0|               1.45|    35.5|     2.5|          362.0|          474.5|      76.19999999999999|            46.5|               334.0|             18.0|             16.0|               6.5|74.33333333|  75.11764706|        74.7|      75.75|  75.47368421|     74.9375|       1.0|       2.0|2.0240526E7|  Lose|            2.0|           63.0|  (135,[2],[1.0])| (135,[63],[1.0])|(346,[0,1,2,3,4,5...|  1.0|  8|
|    12645|      124|           51.0|      16.5|         3.5|        12.0|            10.0|           19.0|          1.5|           13.0|          22.0|           67.0|     1.5|     1.5|    0.0|        0.0|    9.5|     4.0|      2.0|      0.0|       587.5|    15.0|     7.5|       11.5|               1.15|               1.15|     1.1|    16.0|     3.0|          401.5|          491.0|                   81.7|            31.5|               299.5|             10.5|             13.0|               5.5|      125|           45.5|      12.0|         6.0|        22.5|            21.0|           28.0|          0.5|            9.5|          15.0|           79.0|     0.5|     0.0|    0.5|        0.5|    9.0|     1.5|      3.0|      0.5|       485.5|    17.0|     3.5|        8.0|               1.0|               0.6|               0.55|    19.0|     1.0|          273.5|          383.5|                  71.25|            35.5|               251.0|             13.5|             12.0|               6.5|77.28571429|         78.4| 76.44444444|71.33333333|  71.21428571|      71.375|       1.0|       1.0|2.0240526E7|  Draw|           34.0|           43.0| (135,[34],[1.0])| (135,[43],[1.0])|(346,[0,1,2,3,4,5...|  2.0|  9|
|    12641|      116|           52.5|      18.0|         5.5|        21.5|            11.5|            9.5|          2.0|            5.0|          20.0|           46.0|     2.0|     0.5|    0.0|        0.0|   18.0|     5.0|      3.5|      0.0|       580.0|    14.5|     4.0|       12.5|                1.5|                1.5|    1.25|    32.5|     2.5|          401.0|          479.5|                   83.8|            56.0|               373.5|             18.5|             17.0|               6.0|      144|           60.5|      14.0|         2.0|        17.5|            19.0|           21.5|          0.0|            9.5|          19.5|           71.5|     0.5|     0.5|    0.0|        0.0|   10.0|     2.0|      1.0|      0.0|       646.0|    14.5|     4.5|        7.0|              0.85|              0.85|               0.65|    17.5|     1.0|          465.0|          550.0|                   84.3|            37.5|               376.0|             15.5|             15.0|               5.0|77.71428571|  76.47058824| 77.84615385|71.54545455|       73.125| 73.07692308|       2.0|       0.0|2.0240525E7|   Win|           33.0|          107.0| (135,[33],[1.0])|(135,[107],[1.0])|(346,[0,1,2,3,4,5...|  0.0| 10|
|     7838|       85|           48.0|      10.5|         3.5|        16.5|            23.0|           21.0|          2.0|           10.5|          26.5|           84.5|     2.5|     1.5|    0.0|        0.0|   12.5|     5.0|      1.0|      0.0|       554.0|    11.0|     6.5|        5.5|               1.25|               1.25|     0.6|    19.5|     4.0|          342.5|          457.5|                  75.05|            27.5|               304.5|             14.0|             13.5|               6.0|       78|           38.0|      14.5|         2.0|        16.5|             7.0|           18.5|          0.0|           11.0|          11.5|           46.5|     2.5|     1.5|    0.0|        0.0|   16.0|     5.0|      3.5|      0.5|       582.0|    20.0|     9.5|        8.5|              1.15|              1.15|               0.65|    29.0|     3.5|          407.0|          476.5|                  85.05|            43.5|               331.0|             16.0|             20.5|               9.5|       73.8|  75.64285714| 75.16666667|83.83333333|  80.36363636|       80.25|       1.0|       1.0|2.0240525E7|  Draw|           51.0|           18.0| (135,[51],[1.0])| (135,[18],[1.0])|(346,[0,1,2,3,4,5...|  2.0| 11|
|     7840|       88|           42.0|       9.5|         3.0|        10.5|            10.5|           30.5|          3.0|           11.5|          15.0|           56.5|     1.0|     0.5|    0.0|        0.0|    9.5|     3.0|      1.5|      0.0|       546.5|    16.5|     7.0|       12.5|               0.65|               0.65|    0.35|    18.0|     2.0|          350.5|          429.5|                  81.65|            21.0|               280.0|             11.0|             16.5|               6.5|       86|           46.5|      12.0|         7.0|        27.5|            20.5|           13.5|          2.0|           12.5|          19.0|           88.0|     0.5|     0.5|    0.0|        0.0|   14.5|     5.0|      2.5|      0.5|       549.5|    19.5|     6.5|        9.5|               1.7|               1.7|                1.2|    26.0|     1.0|          326.0|          446.0|                  73.25|            35.5|               314.5|             15.5|             19.0|              11.0|       72.0|         75.5| 71.36363636|       74.0|  74.65384615| 72.88888889|       6.0|       1.0|2.0240525E7|   Win|          112.0|           70.0|(135,[112],[1.0])| (135,[70],[1.0])|(346,[0,1,2,3,4,5...|  0.0| 12|

In [116]:
predictions_completed = future_match.join(predictions, "id", "inner").drop("id")

In [117]:
predictions_completed = predictions_completed.withColumn("Result_Predict", when(predictions_completed["prediction"] == 0.0, "Win")
                                        .when(predictions_completed["prediction"] == 1.0, "Lose")
                                        .when(predictions_completed["prediction"] == 2.0, "Draw"))

In [118]:
display(predictions_completed.toPandas().head(5))

,Match_Key,Home_Team,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,Home_Aerials_Won,Home_Clearances,Home_Offsides,Home_Goal_Kicks,...,Home_Team_Onehot,Away_Team_Onehot,Features,Label,Features,Label,rawPrediction,probability,prediction,Result_Predict
0,4800,39,50.5,11.0,6.5,11.5,12.5,14.5,2.5,6.5,...,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(50.5, 11.0, 6.5, 11.5, 12.5, 14.5, 2.5, 6.5, ...",0.0,"(50.5, 11.0, 6.5, 11.5, 12.5, 14.5, 2.5, 6.5, ...",0.0,"[2.7534308354999824, 1.0801213164214905, 1.449...","[0.6853134808323204, 0.12858200226826433, 0.18...",0.0,Win
1,4802,55,53.0,7.5,7.5,22.5,18.5,20.5,0.5,10.5,...,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(53.0, 7.5, 7.5, 22.5, 18.5, 20.5, 0.5, 10.5, ...",1.0,"(53.0, 7.5, 7.5, 22.5, 18.5, 20.5, 0.5, 10.5, ...",1.0,"[1.6198549907937405, 1.8141156354068022, 1.449...","[0.3270021080137222, 0.3971155363956653, 0.275...",1.0,Lose
2,12639,126,42.5,9.0,4.5,22.0,17.5,20.5,3.0,4.5,...,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(42.5, 9.0, 4.5, 22.0, 17.5, 20.5, 3.0, 4.5, 1...",1.0,"(42.5, 9.0, 4.5, 22.0, 17.5, 20.5, 3.0, 4.5, 1...",1.0,"[1.422895393956375, 1.864774509831114, 1.44986...","[0.279098682156636, 0.43417363496122524, 0.286...",1.0,Lose
3,12646,136,47.0,16.5,6.0,20.0,19.0,20.0,3.0,8.0,...,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(47.0, 16.5, 6.0, 20.0, 19.0, 20.0, 3.0, 8.0, ...",0.0,"(47.0, 16.5, 6.0, 20.0, 19.0, 20.0, 3.0, 8.0, ...",0.0,"[1.3990684822374537, 1.8579556002320683, 1.449...","[0.27514716791886956, 0.435368687064164, 0.289...",1.0,Lose
4,2524,20,49.5,12.5,7.0,24.0,11.5,7.5,1.5,5.0,...,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(49.5, 12.5, 7.0, 24.0, 11.5, 7.5, 1.5, 5.0, 1...",1.0,"(49.5, 12.5, 7.0, 24.0, 11.5, 7.5, 1.5, 5.0, 1...",1.0,"[1.7853937190013363, 1.7139486826087138, 1.449...","[0.37792810348235095, 0.3518689969984658, 0.27...",0.0,Win

In [119]:
predictions_completed = predictions_completed.drop(
    *["Features", "Label", "Home_Team_Onehot", "Away_Team_Onehot",
      "probability", "rawPrediction", "Away_Team_Index", "Home_Team_Index"]
    )

In [120]:
display(predictions_completed.toPandas().head(5))

,Match_Key,Home_Team,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,Home_Aerials_Won,Home_Clearances,Home_Offsides,Home_Goal_Kicks,...,Home_Defense,Away_Attack,Away_Midfield,Away_Defense,Home_Score,Away_Score,Match_Date,Result,prediction,Result_Predict
0,4800,39,50.5,11.0,6.5,11.5,12.5,14.5,2.5,6.5,...,79.444444,75.666667,72.000000,74.769231,2.0,1.0,20240519.0,Win,0.0,Win
1,4802,55,53.0,7.5,7.5,22.5,18.5,20.5,0.5,10.5,...,73.615385,78.625000,76.444444,70.555556,2.0,4.0,20240519.0,Lose,1.0,Lose
2,12639,126,42.5,9.0,4.5,22.0,17.5,20.5,3.0,4.5,...,70.625000,77.000000,76.166667,73.000000,2.0,3.0,20240523.0,Lose,1.0,Lose
3,12646,136,47.0,16.5,6.0,20.0,19.0,20.0,3.0,8.0,...,70.083333,77.100000,74.900000,77.266667,2.0,1.0,20240526.0,Win,1.0,Lose
4,2524,20,49.5,12.5,7.0,24.0,11.5,7.5,1.5,5.0,...,69.900000,71.500000,73.100000,72.857143,0.0,3.0,20240519.0,Lose,0.0,Win

In [121]:
# predictions_completed.write.csv("gs://football-data-etl/football-data-predicting/predictions_matches.csv", header=True)
predictions_completed.toPandas().to_csv('./predictions_matches.csv', index=False)

In [122]:
X_test.toPandas().to_csv('/content/drive/MyDrive/Colab Notebooks/football-data-predicting/X_test.csv', index=False)

OSError: Cannot save file into a non-existent directory: '/content/drive/MyDrive/Colab Notebooks/football-data-predicting'

In [ ]:
predictions.toPandas().to_csv('/content/drive/MyDrive/Colab Notebooks/football-data-predicting/predictions.csv', index=False)

In [ ]:
predictions_completed.toPandas().to_csv('/content/drive/MyDrive/Colab Notebooks/football-data-predicting/predictions_completed.csv', index=False)